

Insert into TIPO_GRUPPO
   (DES_TIPO_GRUPPO, DES_DESCRIZIONE, DES_TABELLA_TARGET, COD_USERAGG, DTT_TMST)
 Values
   ('LAVORATORE', 'LAVORATORE', 'LAVORATORE', 'SYSTEM', NOW());
Insert into TIPO_GRUPPO
   (DES_TIPO_GRUPPO, DES_DESCRIZIONE, COD_USERAGG, DTT_TMST)
 Values
   ('SIL_CONTEXT', 'SILCONTEXT', 'SYSTEM', NOW());

