

Insert into TAB_TIPO_INTERMEDIARIO
   (COD_TIPO_INTERMEDIARIO, DES_TIPO_INTERMEDIARIO, FLG_PUBBLICO, DAT_INIZIO, DTT_TMST)
 Values
   ('SP', 'Ente Promotore', 'N', TO_DATE('06/07/2011 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_TIPO_INTERMEDIARIO
   (COD_TIPO_INTERMEDIARIO, DES_TIPO_INTERMEDIARIO, FLG_PUBBLICO, DAT_INIZIO, DTT_TMST)
 Values
   ('APL', 'Agenzia per il lavoro', 'N', TO_DATE('10/13/2010 11:53:11', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_TIPO_INTERMEDIARIO
   (COD_TIPO_INTERMEDIARIO, DES_TIPO_INTERMEDIARIO, FLG_PUBBLICO, DAT_INIZIO, DTT_TMST)
 Values
   ('A', 'Agenzie di somministrazione di tipo generalista', 'N', TO_DATE('07/14/2006 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_TIPO_INTERMEDIARIO
   (COD_TIPO_INTERMEDIARIO, DES_TIPO_INTERMEDIARIO, FLG_PUBBLICO, DAT_INIZIO, DTT_TMST)
 Values
   ('B', 'Agenzie di somministrazione di tipo specialista', 'N', TO_DATE('07/14/2006 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_TIPO_INTERMEDIARIO
   (COD_TIPO_INTERMEDIARIO, DES_TIPO_INTERMEDIARIO, FLG_PUBBLICO, DAT_INIZIO, DTT_TMST)
 Values
   ('C', 'Agenzie di intermediazione', 'N', TO_DATE('07/14/2006 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_TIPO_INTERMEDIARIO
   (COD_TIPO_INTERMEDIARIO, DES_TIPO_INTERMEDIARIO, FLG_PUBBLICO, DAT_INIZIO, DTT_TMST)
 Values
   ('D', 'Agenzie di ricerca e selezione del personale', 'N', TO_DATE('07/14/2006 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_TIPO_INTERMEDIARIO
   (COD_TIPO_INTERMEDIARIO, DES_TIPO_INTERMEDIARIO, FLG_PUBBLICO, DAT_INIZIO, DTT_TMST)
 Values
   ('E', 'Agenzie di supporto alla ricollocazione professionale', 'N', TO_DATE('07/14/2006 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_TIPO_INTERMEDIARIO
   (COD_TIPO_INTERMEDIARIO, DES_TIPO_INTERMEDIARIO, FLG_PUBBLICO, DAT_INIZIO, DTT_TMST)
 Values
   ('H', 'Università', 'N', TO_DATE('07/14/2006 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_TIPO_INTERMEDIARIO
   (COD_TIPO_INTERMEDIARIO, DES_TIPO_INTERMEDIARIO, FLG_PUBBLICO, DAT_INIZIO, DTT_TMST)
 Values
   ('L', 'Regioni', 'N', TO_DATE('07/14/2006 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_TIPO_INTERMEDIARIO
   (COD_TIPO_INTERMEDIARIO, DES_TIPO_INTERMEDIARIO, FLG_PUBBLICO, DAT_INIZIO, DTT_TMST)
 Values
   ('M', 'CPI per ricollocazione', 'N', TO_DATE('07/14/2006 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_TIPO_INTERMEDIARIO
   (COD_TIPO_INTERMEDIARIO, DES_TIPO_INTERMEDIARIO, FLG_PUBBLICO, DAT_INIZIO, DTT_TMST)
 Values
   ('N', 'Province', 'N', TO_DATE('07/14/2006 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_TIPO_INTERMEDIARIO
   (COD_TIPO_INTERMEDIARIO, DES_TIPO_INTERMEDIARIO, FLG_PUBBLICO, DAT_INIZIO, DTT_TMST)
 Values
   ('S', 'SCUOLE', 'S', TO_DATE('09/18/2012 16:12:13', 'MM/DD/YYYY HH24:MI:SS'), now());   
Insert into TAB_TIPO_INTERMEDIARIO
   (COD_TIPO_INTERMEDIARIO, DES_TIPO_INTERMEDIARIO, FLG_PUBBLICO, DAT_INIZIO, DTT_TMST)
 Values
   ('CPI', 'CENTRO PER L''IMPIEGO', 'S', TO_DATE('01/01/2001 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_TIPO_INTERMEDIARIO
   (COD_TIPO_INTERMEDIARIO, DES_TIPO_INTERMEDIARIO, FLG_PUBBLICO, DAT_INIZIO, DTT_TMST)
 Values
   ('Autorizzato', 'ENTE AUTORIZZATO', 'S', TO_DATE('04/13/2005 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_TIPO_INTERMEDIARIO
   (COD_TIPO_INTERMEDIARIO, DES_TIPO_INTERMEDIARIO, FLG_PUBBLICO, DAT_INIZIO, DTT_TMST)
 Values
   ('Accreditato', 'ENTE ACCREDITATO', 'S', TO_DATE('04/13/2005 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
   
INSERT INTO TAB_TIPO_INTERMEDIARIO  
   (COD_TIPO_INTERMEDIARIO, DES_TIPO_INTERMEDIARIO, FLG_PUBBLICO, DAT_INIZIO, DTT_TMST)
 VALUES 
   ('IL', 'ANPAL Servizi S.p.A.', 'N', TO_DATE('01-01-2017','DD-MM-YYYY'), NOW());

   
/*   
Insert into TAB_TIPO_INTERMEDIARIO
   (COD_TIPO_INTERMEDIARIO, DES_TIPO_INTERMEDIARIO, FLG_PUBBLICO, DAT_INIZIO, DTT_TMST)
 Values
   ('MSNA', 'ATS - AVVISO MSNA', 'S', TO_DATE('09/18/2012 16:12:13', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('09/18/2012 16:12:13', 'MM/DD/YYYY HH24:MI:SS'));

Insert into TAB_TIPO_INTERMEDIARIO
   (COD_TIPO_INTERMEDIARIO, DES_TIPO_INTERMEDIARIO, FLG_PUBBLICO, DAT_INIZIO, DTT_TMST)
 Values
   ('BTG', 'Botteghe di mestiere', 'N', TO_DATE('01/01/2012 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('09/03/2012 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into TAB_TIPO_INTERMEDIARIO
   (COD_TIPO_INTERMEDIARIO, DES_TIPO_INTERMEDIARIO, FLG_PUBBLICO, DAT_INIZIO, DTT_TMST)
 Values
   ('INTG', 'ATS - AVVISO INTEGRAZIONE MSNA', 'S', TO_DATE('09/18/2012 16:12:13', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('09/18/2012 16:12:13', 'MM/DD/YYYY HH24:MI:SS'));


Insert into TAB_TIPO_INTERMEDIARIO
   (COD_TIPO_INTERMEDIARIO, DES_TIPO_INTERMEDIARIO, FLG_PUBBLICO, DAT_INIZIO, DTT_TMST)
 Values
   ('ABTG', 'Botteghe di mestiere regione Abruzzo', 'N', TO_DATE('01/07/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('07/30/2013 12:38:59', 'MM/DD/YYYY HH24:MI:SS'));

*/