
INSERT INTO TAB_PROVINCE
   (cod_provincia, cod_regione, des_provincia, dat_inizio, dat_fine, dtt_tmst, des_targa, cod_ml_reg)
 VALUES 
   ('111', '20', 'SUD SARDEGNA', TO_DATE('04/02/2016', 'MM/DD/YYYY'), NULL, NOW(), 'SU', '15');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DTT_TMST, DES_TARGA, COD_ML_REG)
 Values
   ('110', '16', 'BARLETTA-ANDRIA-TRANI', TO_DATE('09/15/2009 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), 'BT', '14');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DTT_TMST, DES_TARGA, COD_ML_REG)
 Values
   ('109', '11', 'FERMO', TO_DATE('09/15/2009 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), 'FM', '11');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DTT_TMST, DES_TARGA, COD_ML_REG)
 Values
   ('108', '03', 'MONZA E BRIANZA', TO_DATE('09/15/2009 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), 'MB', '10');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DTT_TMST, DES_TARGA, COD_ML_REG)
 Values
   ('084', '19', 'AGRIGENTO', TO_DATE('01/01/1999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), 'AG', '16');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DTT_TMST, DES_TARGA, COD_ML_REG)
 Values
   ('006', '01', 'ALESSANDRIA', TO_DATE('01/01/1999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), 'AL', '13');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DTT_TMST, DES_TARGA, COD_ML_REG)
 Values
   ('042', '11', 'ANCONA', TO_DATE('01/01/1999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), 'AN', '11');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DTT_TMST, DES_TARGA, COD_ML_REG)
 Values
   ('007', '02', 'AOSTA', TO_DATE('01/01/1999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), 'AO', '20');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DTT_TMST, DES_TARGA, COD_ML_REG)
 Values
   ('044', '11', 'ASCOLI PICENO', TO_DATE('01/01/1999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), 'AP', '11');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DTT_TMST, DES_TARGA, COD_ML_REG)
 Values
   ('066', '13', 'L''AQUILA', TO_DATE('01/01/1999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), 'AQ', '01');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DTT_TMST, DES_TARGA, COD_ML_REG)
 Values
   ('051', '09', 'AREZZO', TO_DATE('01/01/1999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), 'AR', '17');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DTT_TMST, DES_TARGA, COD_ML_REG)
 Values
   ('005', '01', 'ASTI', TO_DATE('01/01/1999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), 'AT', '13');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DTT_TMST, DES_TARGA, COD_ML_REG)
 Values
   ('064', '15', 'AVELLINO', TO_DATE('01/01/1999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), 'AV', '05');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DTT_TMST, DES_TARGA, COD_ML_REG)
 Values
   ('072', '16', 'BARI', TO_DATE('01/01/1999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), 'BA', '14');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DTT_TMST, DES_TARGA, COD_ML_REG)
 Values
   ('016', '03', 'BERGAMO', TO_DATE('01/01/1999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), 'BG', '10');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DTT_TMST, DES_TARGA, COD_ML_REG)
 Values
   ('096', '01', 'BIELLA', TO_DATE('01/01/1999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), 'BI', '13');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DTT_TMST, DES_TARGA, COD_ML_REG)
 Values
   ('025', '05', 'BELLUNO', TO_DATE('01/01/1999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), 'BL', '21');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DTT_TMST, DES_TARGA, COD_ML_REG)
 Values
   ('062', '15', 'BENEVENTO', TO_DATE('01/01/1999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), 'BN', '05');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DTT_TMST, DES_TARGA, COD_ML_REG)
 Values
   ('037', '08', 'BOLOGNA', TO_DATE('01/01/1999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), 'BO', '06');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DTT_TMST, DES_TARGA, COD_ML_REG)
 Values
   ('074', '16', 'BRINDISI', TO_DATE('01/01/1999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), 'BR', '14');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DTT_TMST, DES_TARGA, COD_ML_REG)
 Values
   ('017', '03', 'BRESCIA', TO_DATE('01/01/1999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), 'BS', '10');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DTT_TMST, DES_TARGA, COD_ML_REG)
 Values
   ('021', '04', 'BOLZANO-BOZEN', TO_DATE('01/01/1999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), 'BZ', '03');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DTT_TMST, DES_TARGA, COD_ML_REG)
 Values
   ('092', '20', 'CAGLIARI', TO_DATE('01/01/1999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), 'CA', '15');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DTT_TMST, DES_TARGA, COD_ML_REG)
 Values
   ('070', '14', 'CAMPOBASSO', TO_DATE('01/01/1999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), 'CB', '12');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DTT_TMST, DES_TARGA, COD_ML_REG)
 Values
   ('061', '15', 'CASERTA', TO_DATE('01/01/1999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), 'CE', '05');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DTT_TMST, DES_TARGA, COD_ML_REG)
 Values
   ('069', '13', 'CHIETI', TO_DATE('01/01/1999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), 'CH', '01');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DTT_TMST, DES_TARGA, COD_ML_REG)
 Values
   ('085', '19', 'CALTANISSETTA', TO_DATE('01/01/1999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), 'CL', '16');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DTT_TMST, DES_TARGA, COD_ML_REG)
 Values
   ('004', '01', 'CUNEO', TO_DATE('01/01/1999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), 'CN', '13');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DTT_TMST, DES_TARGA, COD_ML_REG)
 Values
   ('013', '03', 'COMO', TO_DATE('01/01/1999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), 'CO', '10');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DTT_TMST, DES_TARGA, COD_ML_REG)
 Values
   ('019', '03', 'CREMONA', TO_DATE('01/01/1999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), 'CR', '10');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DTT_TMST, DES_TARGA, COD_ML_REG)
 Values
   ('078', '18', 'COSENZA', TO_DATE('01/01/1999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), 'CS', '04');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DTT_TMST, DES_TARGA, COD_ML_REG)
 Values
   ('087', '19', 'CATANIA', TO_DATE('01/01/1999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), 'CT', '16');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DTT_TMST, DES_TARGA, COD_ML_REG)
 Values
   ('079', '18', 'CATANZARO', TO_DATE('01/01/1999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), 'CZ', '04');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DTT_TMST, DES_TARGA, COD_ML_REG)
 Values
   ('086', '19', 'ENNA', TO_DATE('01/01/1999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), 'EN', '16');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DTT_TMST, DES_TARGA, COD_ML_REG)
 Values
   ('040', '08', 'FORLÌ E CESENA', TO_DATE('01/01/1999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), 'FC', '06');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DTT_TMST, DES_TARGA, COD_ML_REG)
 Values
   ('038', '08', 'FERRARA', TO_DATE('01/01/1999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), 'FE', '06');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DTT_TMST, DES_TARGA, COD_ML_REG)
 Values
   ('071', '16', 'FOGGIA', TO_DATE('01/01/1999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), 'FG', '14');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DTT_TMST, DES_TARGA, COD_ML_REG)
 Values
   ('048', '09', 'FIRENZE', TO_DATE('01/01/1999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), 'FI', '17');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DTT_TMST, DES_TARGA, COD_ML_REG)
 Values
   ('060', '12', 'FROSINONE', TO_DATE('01/01/1999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), 'FR', '08');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DTT_TMST, DES_TARGA, COD_ML_REG)
 Values
   ('010', '07', 'GENOVA', TO_DATE('01/01/1999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), 'GE', '09');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DTT_TMST, DES_TARGA, COD_ML_REG)
 Values
   ('031', '06', 'GORIZIA', TO_DATE('01/01/1999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), 'GO', '07');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DTT_TMST, DES_TARGA, COD_ML_REG)
 Values
   ('053', '09', 'GROSSETO', TO_DATE('01/01/1999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), 'GR', '17');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DTT_TMST, DES_TARGA, COD_ML_REG)
 Values
   ('008', '07', 'IMPERIA', TO_DATE('01/01/1999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), 'IM', '09');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DTT_TMST, DES_TARGA, COD_ML_REG)
 Values
   ('094', '14', 'ISERNIA', TO_DATE('01/01/1999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), 'IS', '12');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DTT_TMST, DES_TARGA, COD_ML_REG)
 Values
   ('101', '18', 'CROTONE', TO_DATE('01/01/1999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), 'KR', '04');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DTT_TMST, DES_TARGA, COD_ML_REG)
 Values
   ('097', '03', 'LECCO', TO_DATE('01/01/1999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), 'LC', '10');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DTT_TMST, DES_TARGA, COD_ML_REG)
 Values
   ('075', '16', 'LECCE', TO_DATE('01/01/1999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), 'LE', '14');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DTT_TMST, DES_TARGA, COD_ML_REG)
 Values
   ('049', '09', 'LIVORNO', TO_DATE('01/01/1999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), 'LI', '17');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DTT_TMST, DES_TARGA, COD_ML_REG)
 Values
   ('098', '03', 'LODI', TO_DATE('01/01/1999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), 'LO', '10');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DTT_TMST, DES_TARGA, COD_ML_REG)
 Values
   ('059', '12', 'LATINA', TO_DATE('01/01/1999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), 'LT', '08');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DTT_TMST, DES_TARGA, COD_ML_REG)
 Values
   ('046', '09', 'LUCCA', TO_DATE('01/01/1999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), 'LU', '17');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DTT_TMST, DES_TARGA, COD_ML_REG)
 Values
   ('043', '11', 'MACERATA', TO_DATE('01/01/1999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), 'MC', '11');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DTT_TMST, DES_TARGA, COD_ML_REG)
 Values
   ('083', '19', 'MESSINA', TO_DATE('01/01/1999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), 'ME', '16');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DTT_TMST, DES_TARGA, COD_ML_REG)
 Values
   ('015', '03', 'MILANO', TO_DATE('01/01/1999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), 'MI', '10');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DTT_TMST, DES_TARGA, COD_ML_REG)
 Values
   ('020', '03', 'MANTOVA', TO_DATE('01/01/1999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), 'MN', '10');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DTT_TMST, DES_TARGA, COD_ML_REG)
 Values
   ('036', '08', 'MODENA', TO_DATE('01/01/1999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), 'MO', '06');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DTT_TMST, DES_TARGA, COD_ML_REG)
 Values
   ('045', '09', 'MASSA CARRARA', TO_DATE('01/01/1999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), 'MS', '17');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DTT_TMST, DES_TARGA, COD_ML_REG)
 Values
   ('077', '17', 'MATERA', TO_DATE('01/01/1999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), 'MT', '02');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DTT_TMST, DES_TARGA, COD_ML_REG)
 Values
   ('063', '15', 'NAPOLI', TO_DATE('01/01/1999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), 'NA', '05');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DTT_TMST, DES_TARGA, COD_ML_REG)
 Values
   ('003', '01', 'NOVARA', TO_DATE('01/01/1999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), 'NO', '13');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DTT_TMST, DES_TARGA, COD_ML_REG)
 Values
   ('091', '20', 'NUORO', TO_DATE('01/01/1999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), 'NU', '15');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DTT_TMST, DES_TARGA, COD_ML_REG)
 Values
   ('095', '20', 'ORISTANO', TO_DATE('01/01/1999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), 'OR', '15');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DTT_TMST, DES_TARGA, COD_ML_REG)
 Values
   ('082', '19', 'PALERMO', TO_DATE('01/01/1999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), 'PA', '16');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DTT_TMST, DES_TARGA, COD_ML_REG)
 Values
   ('033', '08', 'PIACENZA', TO_DATE('01/01/1999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), 'PC', '06');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DTT_TMST, DES_TARGA, COD_ML_REG)
 Values
   ('028', '05', 'PADOVA', TO_DATE('01/01/1999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), 'PD', '21');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DTT_TMST, DES_TARGA, COD_ML_REG)
 Values
   ('068', '13', 'PESCARA', TO_DATE('01/01/1999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), 'PE', '01');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DTT_TMST, DES_TARGA, COD_ML_REG)
 Values
   ('054', '10', 'PERUGIA', TO_DATE('01/01/1999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), 'PG', '19');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DTT_TMST, DES_TARGA, COD_ML_REG)
 Values
   ('050', '09', 'PISA', TO_DATE('01/01/1999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), 'PI', '17');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DTT_TMST, DES_TARGA, COD_ML_REG)
 Values
   ('093', '06', 'PORDENONE', TO_DATE('01/01/1999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), 'PN', '07');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DTT_TMST, DES_TARGA, COD_ML_REG)
 Values
   ('100', '09', 'PRATO', TO_DATE('01/01/1999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), 'PO', '17');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DTT_TMST, DES_TARGA, COD_ML_REG)
 Values
   ('034', '08', 'PARMA', TO_DATE('01/01/1999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), 'PR', '06');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DTT_TMST, DES_TARGA, COD_ML_REG)
 Values
   ('047', '09', 'PISTOIA', TO_DATE('01/01/1999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), 'PT', '17');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DTT_TMST, DES_TARGA, COD_ML_REG)
 Values
   ('041', '11', 'PESARO E URBINO', TO_DATE('01/01/1999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), 'PU', '11');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DTT_TMST, DES_TARGA, COD_ML_REG)
 Values
   ('018', '03', 'PAVIA', TO_DATE('01/01/1999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), 'PV', '10');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DTT_TMST, DES_TARGA, COD_ML_REG)
 Values
   ('076', '17', 'POTENZA', TO_DATE('01/01/1999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), 'PZ', '02');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DTT_TMST, DES_TARGA, COD_ML_REG)
 Values
   ('039', '08', 'RAVENNA', TO_DATE('01/01/1999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), 'RA', '06');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DTT_TMST, DES_TARGA, COD_ML_REG)
 Values
   ('080', '18', 'REGGIO CALABRIA', TO_DATE('01/01/1999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), 'RC', '04');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DTT_TMST, DES_TARGA, COD_ML_REG)
 Values
   ('035', '08', 'REGGIO EMILIA', TO_DATE('01/01/1999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), 'RE', '06');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DTT_TMST, DES_TARGA, COD_ML_REG)
 Values
   ('088', '19', 'RAGUSA', TO_DATE('01/01/1999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), 'RG', '16');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DTT_TMST, DES_TARGA, COD_ML_REG)
 Values
   ('057', '12', 'RIETI', TO_DATE('01/01/1999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), 'RI', '08');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DTT_TMST, DES_TARGA, COD_ML_REG)
 Values
   ('058', '12', 'ROMA', TO_DATE('01/01/1999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), 'RM', '08');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DTT_TMST, DES_TARGA, COD_ML_REG)
 Values
   ('099', '08', 'RIMINI', TO_DATE('01/01/1999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), 'RN', '06');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DTT_TMST, DES_TARGA, COD_ML_REG)
 Values
   ('029', '05', 'ROVIGO', TO_DATE('01/01/1999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), 'RO', '21');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DTT_TMST, DES_TARGA, COD_ML_REG)
 Values
   ('065', '15', 'SALERNO', TO_DATE('01/01/1999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), 'SA', '05');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DTT_TMST, DES_TARGA, COD_ML_REG)
 Values
   ('052', '09', 'SIENA', TO_DATE('01/01/1999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), 'SI', '17');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DTT_TMST, DES_TARGA, COD_ML_REG)
 Values
   ('014', '03', 'SONDRIO', TO_DATE('01/01/1999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), 'SO', '10');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DTT_TMST, DES_TARGA, COD_ML_REG)
 Values
   ('011', '07', 'LA SPEZIA', TO_DATE('01/01/1999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), 'SP', '09');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DTT_TMST, DES_TARGA, COD_ML_REG)
 Values
   ('089', '19', 'SIRACUSA', TO_DATE('01/01/1999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), 'SR', '16');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DTT_TMST, DES_TARGA, COD_ML_REG)
 Values
   ('090', '20', 'SASSARI', TO_DATE('01/01/1999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), 'SS', '15');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DTT_TMST, DES_TARGA, COD_ML_REG)
 Values
   ('009', '07', 'SAVONA', TO_DATE('01/01/1999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), 'SV', '09');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DTT_TMST, DES_TARGA, COD_ML_REG)
 Values
   ('073', '16', 'TARANTO', TO_DATE('01/01/1999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), 'TA', '14');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DTT_TMST, DES_TARGA, COD_ML_REG)
 Values
   ('067', '13', 'TERAMO', TO_DATE('01/01/1999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), 'TE', '01');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DTT_TMST, DES_TARGA, COD_ML_REG)
 Values
   ('022', '04', 'TRENTO', TO_DATE('01/01/1999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), 'TN', '18');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DTT_TMST, DES_TARGA, COD_ML_REG)
 Values
   ('001', '01', 'TORINO', TO_DATE('01/01/1999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), 'TO', '13');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DTT_TMST, DES_TARGA, COD_ML_REG)
 Values
   ('081', '19', 'TRAPANI', TO_DATE('01/01/1999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), 'TP', '16');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DTT_TMST, DES_TARGA, COD_ML_REG)
 Values
   ('055', '10', 'TERNI', TO_DATE('01/01/1999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), 'TR', '19');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DTT_TMST, DES_TARGA, COD_ML_REG)
 Values
   ('032', '06', 'TRIESTE', TO_DATE('01/01/1999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), 'TS', '07');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DTT_TMST, DES_TARGA, COD_ML_REG)
 Values
   ('026', '05', 'TREVISO', TO_DATE('01/01/1999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), 'TV', '21');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DTT_TMST, DES_TARGA, COD_ML_REG)
 Values
   ('030', '06', 'UDINE', TO_DATE('01/01/1999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), 'UD', '07');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DTT_TMST, DES_TARGA, COD_ML_REG)
 Values
   ('012', '03', 'VARESE', TO_DATE('01/01/1999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), 'VA', '10');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DTT_TMST, DES_TARGA, COD_ML_REG)
 Values
   ('103', '01', 'VERBANO CUSIO OSSOLA', TO_DATE('01/01/1999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), 'VB', '13');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DTT_TMST, DES_TARGA, COD_ML_REG)
 Values
   ('002', '01', 'VERCELLI', TO_DATE('01/01/1999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), 'VC', '13');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DTT_TMST, DES_TARGA, COD_ML_REG)
 Values
   ('027', '05', 'VENEZIA', TO_DATE('01/01/1999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), 'VE', '21');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DTT_TMST, DES_TARGA, COD_ML_REG)
 Values
   ('024', '05', 'VICENZA', TO_DATE('01/01/1999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), 'VI', '21');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DTT_TMST, DES_TARGA, COD_ML_REG)
 Values
   ('023', '05', 'VERONA', TO_DATE('01/01/1999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), 'VR', '21');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DTT_TMST, DES_TARGA, COD_ML_REG)
 Values
   ('056', '12', 'VITERBO', TO_DATE('01/01/1999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), 'VT', '08');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DTT_TMST, DES_TARGA, COD_ML_REG)
 Values
   ('102', '18', 'VIBO VALENTIA', TO_DATE('01/01/1999 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), 'VV', '04');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DTT_TMST, DES_TARGA, COD_ML_REG)
 Values
   ('104', '20', 'OLBIA-TEMPIO', TO_DATE('02/01/2006 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), 'OT', '15');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DTT_TMST, DES_TARGA, COD_ML_REG)
 Values
   ('105', '20', 'OGLIASTRA', TO_DATE('02/01/2006 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), 'OG', '15');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DTT_TMST, DES_TARGA, COD_ML_REG)
 Values
   ('106', '20', 'MEDIO CAMPIDANO', TO_DATE('02/01/2006 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), 'VS', '15');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DTT_TMST, DES_TARGA, COD_ML_REG)
 Values
   ('107', '20', 'CARBONIA-IGLESIAS', TO_DATE('02/01/2006 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), 'CI', '15');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DAT_FINE, DTT_TMST, COD_ML_REG)
 Values
   ('701', '00', 'FIUME', TO_DATE('01/01/1900 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), NOW(), '00');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DAT_FINE, DTT_TMST, COD_ML_REG)
 Values
   ('702', '00', 'POLA', TO_DATE('01/01/1900 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), NOW(), '00');
Insert into TAB_PROVINCE
   (COD_PROVINCIA, COD_REGIONE, DES_PROVINCIA, DAT_INIZIO, DAT_FINE, DTT_TMST, COD_ML_REG)
 Values
   ('703', '00', 'ZARA', TO_DATE('01/01/1900 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW(), NOW(), '00');

