
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('432', 'Z327', 'MADAGASCAR', 'N', TO_DATE('01/01/1965 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('434', 'Z328', 'MALAWI', 'N', TO_DATE('01/01/1965 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('435', 'Z329', 'MALI', 'N', TO_DATE('01/01/1965 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('436', 'Z330', 'MAROCCO', 'MAROCCHINA', 'N', TO_DATE('01/01/1965 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('437', 'Z331', 'MAURITANIA', 'N', TO_DATE('01/01/1965 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('440', 'Z333', 'MOZAMBICO', 'N', TO_DATE('12/31/1975 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('442', 'Z334', 'NIGER', 'N', TO_DATE('01/01/1965 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('443', 'Z335', 'NIGERIA', 'NIGERIANA', 'N', TO_DATE('01/01/1965 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('419', 'Z336', 'EGITTO', 'EGIZIANA', 'N', TO_DATE('01/01/1965 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('465', 'Z337', 'ZIMBABWE', 'N', TO_DATE('12/31/1980 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('446', 'Z338', 'RUANDA', 'N', TO_DATE('01/01/1965 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('450', 'Z343', 'SENEGAL', 'SENEGALESE', 'N', TO_DATE('01/01/1965 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('451', 'Z344', 'SIERRA LEONE', 'N', TO_DATE('01/01/1965 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('453', 'Z345', 'SOMALIA', 'SOMALA', 'N', TO_DATE('01/01/1965 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('455', 'Z348', 'SUDAN', 'SUDANESE', 'N', TO_DATE('01/01/1965 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('456', 'Z349', 'SWAZILAND', 'N', TO_DATE('12/31/1975 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('458', 'Z351', 'TOGO', 'TOGOLESE', 'N', TO_DATE('01/01/1965 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('460', 'Z352', 'TUNISIA', 'TUNISINA', 'N', TO_DATE('01/01/1965 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('461', 'Z353', 'UGANDA', 'UGANDESE', 'N', TO_DATE('01/01/1965 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('464', 'Z355', 'ZAMBIA', 'ZAMBESE', 'N', TO_DATE('01/01/1965 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('457', 'Z357', 'TANZANIA', 'TANZANIANA', 'N', TO_DATE('10/01/1966 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('408', 'Z358', 'BOTSWANA', 'N', TO_DATE('10/01/1966 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('429', 'Z359', 'LESOTHO', 'N', TO_DATE('10/01/1966 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('424', 'Z361', 'GIBUTI', 'N', TO_DATE('12/31/1977 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('466', 'Z368', 'ERITREA', 'ERITREA', 'N', TO_DATE('05/24/1993 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('509', 'Z401', 'CANADA', 'CANADESE', 'N', TO_DATE('01/01/1965 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('536', 'Z404', 'STATI UNITI D''AMERICA', 'STATUNITENSE', 'N', TO_DATE('01/01/1965 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('513', 'Z503', 'COSTA RICA', 'COSTATICANA', 'N', TO_DATE('01/01/1965 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('514', 'Z504', 'CUBA', 'CUBANA', 'N', TO_DATE('01/01/1965 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('517', 'Z506', 'EL SALVADOR', 'SALVADOREGNA', 'N', TO_DATE('01/01/1965 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('518', 'Z507', 'GIAMAICA', 'GIAMAICANA', 'N', TO_DATE('01/01/1965 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('523', 'Z509', 'GUATEMALA', 'GUATEMALTECA', 'N', TO_DATE('01/01/1965 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('524', 'Z510', 'HAITI', 'HAITIANA', 'N', TO_DATE('01/01/1965 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('525', 'Z511', 'HONDURAS', 'HONDUREGNA', 'N', TO_DATE('01/01/1965 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('507', 'Z512', 'BELIZE', 'N', TO_DATE('12/31/1984 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('527', 'Z514', 'MESSICO', 'MESSICANA', 'N', TO_DATE('01/01/1965 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('529', 'Z515', 'NICARAGUA', 'NICARACUENSE', 'N', TO_DATE('01/01/1965 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('506', 'Z522', 'BARBADOS', 'N', TO_DATE('12/31/1975 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('519', 'Z524', 'GRENADA', 'N', TO_DATE('12/31/1977 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('515', 'Z526', 'DOMINICA', 'N', TO_DATE('12/31/1980 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('532', 'Z527', 'SAINT LUCIA', 'N', TO_DATE('12/31/1980 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('503', 'Z532', 'ANTIGUA E BARBUDA', 'N', TO_DATE('12/31/1984 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('602', 'Z600', 'ARGENTINA', 'ARGENTINA', 'N', TO_DATE('01/01/1965 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('604', 'Z601', 'BOLIVIA', 'BOLIVIANA', 'N', TO_DATE('01/01/1965 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('605', 'Z602', 'BRASILE', 'BRASILIANA', 'N', TO_DATE('01/01/1965 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('606', 'Z603', 'CILE', 'CILENA', 'N', TO_DATE('01/01/1965 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('608', 'Z604', 'COLOMBIA', 'COLOMBIANA', 'N', TO_DATE('01/01/1965 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('609', 'Z605', 'ECUADOR', 'ECUADOREGNA', 'N', TO_DATE('01/01/1965 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('612', 'Z606', 'GUYANA', 'N', TO_DATE('12/31/1975 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('616', 'Z608', 'SURINAME', 'N', TO_DATE('12/31/1975 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('614', 'Z610', 'PARAGUAY', 'PARAGUAIANA', 'N', TO_DATE('01/01/1965 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('617', 'Z612', 'TRINIDAD E TOBAGO', 'N', TO_DATE('01/01/1965 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('618', 'Z613', 'URUGUAY', 'URUGUAIANA', 'N', TO_DATE('01/01/1965 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('619', 'Z614', 'VENEZUELA', 'VENEZUELANA', 'N', TO_DATE('01/01/1965 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('701', 'Z700', 'AUSTRALIA', 'AUSTRALIANA', 'N', TO_DATE('01/01/1965 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('735', 'Z161', 'TERRITORI PALESTINESI', 'PALESTINESE', 'N', TO_DATE('07/21/2008 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('272', 'Z160', 'KOSOVO', 'KOSOVARA', 'N', TO_DATE('02/17/2008 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('715', 'Z713', 'NAURU', 'N', TO_DATE('12/31/1975 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('719', 'Z719', 'NUOVA ZELANDA', 'NEOZELANDESE', 'N', TO_DATE('01/01/1965 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('727', 'Z726', 'SAMOA', 'N', TO_DATE('01/01/1965 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('721', 'Z730', 'PAPUA NUOVA GUINEA', 'N', TO_DATE('12/31/1975 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('708', 'Z731', 'KIRIBATI', 'N', TO_DATE('12/31/1980 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('731', 'Z732', 'TUVALU', 'N', TO_DATE('12/31/1980 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('732', 'Z733', 'VANUATU', 'N', TO_DATE('12/31/1980 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('720', 'Z734', 'PALAU', 'N', TO_DATE('01/01/1997 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('219', 'Z114', 'REGNO UNITO', 'BRITANNICA', 'S', TO_DATE('01/02/1997 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('221', 'Z116', 'IRLANDA', 'IRLANDESE', 'S', TO_DATE('01/03/1997 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('233', 'Z127', 'POLONIA', 'POLACCA', 'S', TO_DATE('01/04/1997 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('245', 'Z154', 'RUSSA, FEDERAZIONE', 'RUSSA', 'N', TO_DATE('01/05/1997 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('246', 'Z106', 'SANTA SEDE', 'N', TO_DATE('01/06/1997 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('252', 'Z153', 'BOSNIA-ERZEGOVINA', 'BOSNIACA', 'N', TO_DATE('01/07/1997 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('253', 'Z148', 'MACEDONIA, EX REP. JUGOSLAVIA', 'MACEDONE', 'N', TO_DATE('01/08/1997 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('254', 'Z140', 'MOLDOVA', 'N', TO_DATE('01/09/1997 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('256', 'Z139', 'BIELORUSSIA', 'BIELORUSSA', 'N', TO_DATE('01/10/1997 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('257', 'Z156', 'CECA, REPUBBLICA', 'CECA', 'S', TO_DATE('01/11/1997 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('307', 'Z206', 'MYANMAR', 'BIRMANA', 'N', TO_DATE('01/12/1997 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('314', 'Z210', 'CINESE, REPUBBLICA POPOLARE', 'CINESE', 'N', TO_DATE('01/13/1997 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('319', 'Z214', 'COREA, REPUBBLICA POPOLARE', 'NORDCOREANA', 'N', TO_DATE('01/14/1997 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('320', 'Z213', 'COREA, REPUBBLICA', 'SUDCOREANA', 'N', TO_DATE('01/15/1997 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('324', 'Z218', 'TERRITORI AUTONOMIA PALESTINESE', 'PALESTINESE', 'N', TO_DATE('01/16/1997 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('338', 'Z242', 'TIMOR ORIENTALE', 'N', TO_DATE('01/17/1997 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('356', 'Z255', 'KAZAKHSTAN', 'KAZAKA', 'N', TO_DATE('01/18/1997 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('363', 'Z217', 'TAIWAN', 'N', TO_DATE('01/19/1997 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('364', 'Z258', 'TURKMENISTAN', 'TURKMENA', 'N', TO_DATE('01/20/1997 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('409', 'Z354', 'BURKINA FASO', 'N', TO_DATE('01/21/1997 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('414', 'Z308', 'CENTRAFRICANA, REPUBBLICA', 'N', TO_DATE('01/22/1997 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('418', 'Z311', 'CONGO ', 'CONGOLESE', 'N', TO_DATE('01/23/1997 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('438', 'Z332', 'MAURITIUS', 'N', TO_DATE('01/24/1997 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('448', 'Z341', 'SAO TOMÈ E PRINCIPE', 'N', TO_DATE('01/25/1997 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('449', 'Z342', 'SEYCELLES', 'N', TO_DATE('01/26/1997 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('454', 'Z347', 'SUD AFRICA', 'SUDAFRICANA', 'N', TO_DATE('01/27/1997 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('463', 'Z312', 'CONGO, REP.DEMOCRATICA', 'N', TO_DATE('01/28/1997 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('505', 'Z502', 'BAHAMAS', 'N', TO_DATE('01/29/1997 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('516', 'Z505', 'DOMINICANA, REPUBBLICA', 'N', TO_DATE('01/30/1997 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('530', 'Z516', 'PANAMA', 'PANAMENSE', 'N', TO_DATE('01/31/1997 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('533', 'Z528', 'SAINT VINCENT E GRENADIN', 'N', TO_DATE('02/01/1997 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('534', 'Z533', 'SAINT KITTS E NEVIS', 'N', TO_DATE('02/02/1997 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('615', 'Z611', 'PERU''', 'PERUVIANA', 'N', TO_DATE('02/03/1997 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('703', 'Z704', 'FIGI', 'N', TO_DATE('02/04/1997 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('712', 'Z711', 'MARSHALL, ISOLE', 'N', TO_DATE('02/05/1997 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('713', 'Z735', 'MICRONESIA, STATI FEDERATI', 'N', TO_DATE('02/06/1997 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('725', 'Z724', 'SALOMONE, ISOLE', 'N', TO_DATE('02/07/1997 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('730', 'Z728', 'TONGA', 'N', TO_DATE('02/08/1997 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, DES_CITTADINANZA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('999', 'APOLIDE', 'N', TO_DATE('02/09/1997 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('201', 'Z100', 'ALBANIA', 'ALBANESE', 'N', TO_DATE('01/01/1965 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('202', 'Z101', 'ANDORRA', 'ANDORRANA', 'N', TO_DATE('01/01/1965 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('203', 'Z102', 'AUSTRIA', 'AUSTRIACA', 'S', TO_DATE('01/01/1965 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('206', 'Z103', 'BELGIO', 'BELGA', 'S', TO_DATE('01/01/1965 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('209', 'Z104', 'BULGARIA', 'BULGARA', 'S', TO_DATE('01/01/1965 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('212', 'Z107', 'DANIMARCA', 'DANESE', 'S', TO_DATE('01/01/1965 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('214', 'Z109', 'FINLANDIA', 'FINLANDESE', 'S', TO_DATE('01/01/1965 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('215', 'Z110', 'FRANCIA', 'FRANCESE', 'S', TO_DATE('01/01/1965 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('216', 'Z112', 'GERMANIA', 'TEDESCA', 'S', TO_DATE('10/03/1990 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('220', 'Z115', 'GRECIA', 'GRECA', 'S', TO_DATE('01/01/1965 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('223', 'Z117', 'ISLANDA', 'ISLANDESE', 'N', TO_DATE('01/01/1965 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('225', 'Z119', 'LIECHTENSTEIN', 'N', TO_DATE('01/01/1965 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('000', '0000', 'ITALIA', 'ITALIANA', 'S', TO_DATE('01/01/1965 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('226', 'Z120', 'LUSSEMBURGO', 'LUSSEMBURGHESE', 'S', TO_DATE('01/01/1965 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('227', 'Z121', 'MALTA', 'MALTESE', 'S', TO_DATE('01/01/1965 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('229', 'Z123', 'MONACO', 'MONEGASCA', 'N', TO_DATE('01/01/1965 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('231', 'Z125', 'NORVEGIA', 'NORVEGESE', 'N', TO_DATE('01/01/1965 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('232', 'Z126', 'PAESI BASSI', 'OLANDESE', 'S', TO_DATE('01/01/1965 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('234', 'Z128', 'PORTOGALLO', 'PORTOGHESE', 'S', TO_DATE('01/01/1965 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('235', 'Z129', 'ROMANIA', 'ROMENA', 'S', TO_DATE('01/01/1965 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('236', 'Z130', 'SAN MARINO', 'SANMARINESE', 'N', TO_DATE('01/01/1965 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('239', 'Z131', 'SPAGNA', 'SPAGNOLA', 'S', TO_DATE('01/01/1965 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('240', 'Z132', 'SVEZIA', 'SVEDESE', 'S', TO_DATE('01/01/1965 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('241', 'Z133', 'SVIZZERA', 'SVIZZERA', 'N', TO_DATE('01/01/1965 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('244', 'Z134', 'UNGHERIA', 'UNGHERESE', 'S', TO_DATE('01/01/1965 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('243', 'Z138', 'UCRAINA', 'UCRAINA', 'N', TO_DATE('08/24/1991 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('247', 'Z144', 'ESTONIA', 'ESTONE', 'S', TO_DATE('09/06/1991 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('248', 'Z145', 'LETTONIA', 'LETTONE', 'S', TO_DATE('09/06/1991 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('249', 'Z146', 'LITUANIA', 'LITUANA', 'S', TO_DATE('09/06/1991 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('250', 'Z149', 'CROAZIA', 'CROATA', 'S', TO_DATE('01/07/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('251', 'Z150', 'SLOVENIA', 'SLOVENA', 'S', TO_DATE('10/08/1991 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('255', 'Z155', 'SLOVACCHIA', 'SLOVACCA', 'S', TO_DATE('01/01/1993 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DAT_FINE, DTT_TMST)
 Values
   ('224', 'Z157', 'SERBIA E MONTENEGRO', 'SERBA / MONTENEGRINA', 'N', TO_DATE('02/04/2003 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('06/02/2006 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('271', 'Z158', 'SERBIA', 'SERBA', 'N', TO_DATE('06/03/2006 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('270', 'Z159', 'MONTENEGRO', 'MONTENEGRINA', 'N', TO_DATE('06/03/2006 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('301', 'Z200', 'AFGHANISTAN', 'AFGHANA', 'N', TO_DATE('01/01/1965 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('302', 'Z203', 'ARABIA SAUDITA', 'SAUDITA', 'N', TO_DATE('01/01/1965 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('304', 'Z204', 'BAHREIN', 'N', TO_DATE('12/31/1975 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('306', 'Z205', 'BHUTAN', 'BHUTANESE ', 'N', TO_DATE('12/31/1975 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('309', 'Z207', 'BRUNEI', 'N', TO_DATE('12/31/1984 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('310', 'Z208', 'CAMBOGIA', 'CAMBOGIANA', 'N', TO_DATE('01/01/1965 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('311', 'Z209', 'SRI LANKA', 'CINGALESE', 'N', TO_DATE('12/31/1975 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('315', 'Z211', 'CIPRO', 'CIPRIOTA', 'S', TO_DATE('01/01/1965 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('322', 'Z215', 'EMIRATI ARABI UNITI', 'N', TO_DATE('12/31/1975 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('323', 'Z216', 'FILIPPINE', 'FILIPPINA', 'N', TO_DATE('01/01/1965 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('326', 'Z219', 'GIAPPONE', 'GIAPPONESE', 'N', TO_DATE('01/01/1965 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('327', 'Z220', 'GIORDANIA', 'GIORDANA', 'N', TO_DATE('01/01/1965 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('330', 'Z222', 'INDIA', 'INDIANA', 'N', TO_DATE('01/01/1965 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('331', 'Z223', 'INDONESIA', 'INDONESIANA', 'N', TO_DATE('01/01/1965 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('332', 'Z224', 'IRAN', 'IRANIANA', 'N', TO_DATE('01/01/1965 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('333', 'Z225', 'IRAQ', 'IRACHENA', 'N', TO_DATE('01/01/1965 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('334', 'Z226', 'ISRAELE', 'ISRAELIANA', 'N', TO_DATE('01/01/1965 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('335', 'Z227', 'KUWAIT', 'KUATIANA', 'N', TO_DATE('01/01/1965 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('336', 'Z228', 'LAOS', 'LAOTIANA', 'N', TO_DATE('01/01/1965 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('337', 'Z229', 'LIBANO', 'LIBANESE', 'N', TO_DATE('01/01/1965 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('339', 'Z232', 'MALDIVE', 'N', TO_DATE('01/01/1965 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('341', 'Z233', 'MONGOLIA', 'MONGOLA', 'N', TO_DATE('01/01/1965 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('342', 'Z234', 'NEPAL', 'NEPALESE', 'N', TO_DATE('01/01/1965 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('343', 'Z235', 'OMAN', 'N', TO_DATE('01/01/1965 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('344', 'Z236', 'PAKISTAN', 'PACHISTANA', 'N', TO_DATE('01/01/1965 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('345', 'Z237', 'QATAR', 'N', TO_DATE('12/31/1975 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('348', 'Z240', 'SIRIA', 'SIRIANA', 'N', TO_DATE('01/01/1965 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('349', 'Z241', 'THAILANDIA', 'TAILANDESE', 'N', TO_DATE('01/01/1965 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('351', 'Z243', 'TURCHIA', 'TURCA', 'N', TO_DATE('01/01/1965 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('354', 'Z246', 'YEMEN', 'YEMENITA', 'N', TO_DATE('01/01/1965 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('340', 'Z247', 'MALAYSIA', 'MALESIANA', 'N', TO_DATE('10/01/1966 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('346', 'Z248', 'SINGAPORE', 'N', TO_DATE('10/01/1966 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('305', 'Z249', 'BANGLADESH', 'N', TO_DATE('12/31/1975 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('353', 'Z251', 'VIETNAM', 'VIETNAMITA', 'N', TO_DATE('12/31/1977 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('358', 'Z252', 'ARMENIA', 'ARMENA', 'N', TO_DATE('01/01/1994 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('359', 'Z253', 'AZERBAIGIAN', 'N', TO_DATE('01/01/1994 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('360', 'Z254', 'GEORGIA', 'GEORGIANA', 'N', TO_DATE('01/01/1994 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('361', 'Z256', 'KIRGHIZISTAN', 'KIRGISA', 'N', TO_DATE('01/01/1994 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('362', 'Z257', 'TAGIKISTAN', 'TAGIKA', 'N', TO_DATE('01/01/1994 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('357', 'Z259', 'UZBEKISTAN', 'UZBEKA', 'N', TO_DATE('01/01/1994 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('441', 'Z300', 'NAMIBIA', 'N', TO_DATE('12/31/1978 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('401', 'Z301', 'ALGERIA', 'ALGERINA', 'N', TO_DATE('01/01/1965 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('402', 'Z302', 'ANGOLA', 'ANGOLANA', 'N', TO_DATE('12/31/1977 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('410', 'Z305', 'BURUNDI', 'N', TO_DATE('01/01/1965 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('411', 'Z306', 'CAMERUN', 'CAMERUNENSE', 'N', TO_DATE('01/01/1965 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('413', 'Z307', 'CAPO VERDE', 'CAPOVERDIANA', 'N', TO_DATE('12/31/1975 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('415', 'Z309', 'CIAD', 'N', TO_DATE('01/01/1965 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('417', 'Z310', 'COMORE', 'N', TO_DATE('12/31/1977 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('404', 'Z313', 'COSTA D''AVORIO', 'IVORIANA', 'N', TO_DATE('01/01/1965 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('406', 'Z314', 'BENIN', 'N', TO_DATE('12/31/1975 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('420', 'Z315', 'ETIOPIA', 'ETIOPE', 'N', TO_DATE('05/24/1993 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('421', 'Z316', 'GABON', 'N', TO_DATE('01/01/1965 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('422', 'Z317', 'GAMBIA', 'N', TO_DATE('01/01/1965 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('423', 'Z318', 'GHANA', 'GHANESE', 'N', TO_DATE('01/01/1965 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('425', 'Z319', 'GUINEA', 'N', TO_DATE('01/01/1965 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('426', 'Z320', 'GUINEA BISSAU', 'N', TO_DATE('12/31/1975 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('427', 'Z321', 'GUINEA EQUATORIALE', 'N', TO_DATE('12/31/1975 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('428', 'Z322', 'KENYA', 'KENIANA', 'N', TO_DATE('01/01/1965 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('430', 'Z325', 'LIBERIA', 'LIBERIANA', 'N', TO_DATE('01/01/1965 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into TAB_CITTADINANZE
   (COD_CITTADINANZA, COD_MF, DES_CITTADINANZA, DES_NAZIONALITA, FLG_UE, DAT_INIZIO, DTT_TMST)
 Values
   ('431', 'Z326', 'LIBIA', 'LIBICA', 'N', TO_DATE('01/01/1965 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());

