/* Data for the 'spc_regola' table  (Records 1 - 16) */

INSERT INTO spc_regola ("ide_regola", "cod_gruppo_regola", "des_nome", "des_descrizione", "cod_tipo_codifica_regola", "txt_codifica_regola_sql", "txt_codifica_regola_xml", "cod_userins", "dtt_tmstins")
VALUES 
  (1, E'IP', E'RicercaIscrizione', E'Ricerca Semplice Iscrizioni', E'SQL', E'select i.ide_iscrizione_persona from\x0D\x0AIscrizione_Persona I, Iscrizione_Persona_AltreInfo AI\x0D\x0Awhere  ai.ide_iscrizione_persona = i.ide_iscrizione_persona and\x0D\x0ATRIM(ai.Cod_Istituto) = TRIM(''${appctx_utente_unitaorgrif}'')', E'SQL', E'SYSTEM', NOW() ),
  (2, E'P', E'RicercaSemplice', E'Ricerca Semplice Lavoratore', E'SQL', E'select L.ide_lavoratore\x0D\x0Afrom   Iscrizione_Persona I, Iscrizione_Persona_AltreInfo AI,\x0D\x0A       Lavoratore L, Persona P, stato_lavoratore S\x0D\x0Awhere  ai.ide_iscrizione_persona = i.ide_iscrizione_persona\x0D\x0Aand    p.ide_iscrizione_persona = i.ide_iscrizione_persona\x0D\x0Aand    l.ide_lavoratore = p.ide_lavoratore\x0D\x0Aand    s.ide_lavoratore = L.ide_lavoratore\x0D\x0Aand    TRIM(ai.Cod_Istituto) = TRIM(''${appctx_utente_unitaorgrif}'')\x0D\x0Aand    s.cod_stato = ''V''', E'SQL', E'SYSTEM', NOW() ),
  (3, E'SP', E'RicercaSelezioni', E'Ricerca Semplice Selezioni', E'SQL', E'select s.ide_selezione\x0D\x0Afrom   Selezione S, Utente U\x0D\x0Awhere  upper(u.cod_userid) = upper(s.cod_userins)\x0D\x0Aand    TRIM(u.Cod_Unita_Organizzativa) = TRIM(''${appctx_utente_unitaorgrif}'')', E'SQL', E'SYSTEM', NOW() ),
  (6, E'UO', E'ListaAnagraficaUniversita', E'Lista Anagrafica Istituto Universita', E'SQL', E'select ti.COD_INTERMEDIARIO\x0D\x0A   from tab_intermediari ti, utente u\x0D\x0A  where TRIM(ti.COD_INTERMEDIARIO) = TRIM(u.cod_unita_organizzativa)\x0D\x0A    and upper(u.cod_userid) = upper(''${appctx_utente_userid}'')', E'SQL', E'SYSTEM', NOW() ),
  (7, E'UO', E'LISTA ENTE tutti INTERMEDIARI', E'LISTA ENTE tutti INTERMEDIARI (TABELLA INTERMEDIARI)', E'SQL', E'SELECT DISTINCT T.COD_INTERMEDIARIO  FROM TAB_INTERMEDIARI T, APPL_INT AI\x0D\x0A\x09\x09\x09WHERE T.COD_TIPO_INTERMEDIARIO=''PUOI2.SP''  AND T.COD_INTERMEDIARIO=AI.COD_INTERMEDIARIO', E'SQL', E'SYSTEM', NOW() ),
  (11, E'UO', E'FiltroRichPagamento per Servizio Competente', E'Filtro richieste di pagamento per Servizio Competente', E'SQL', E'select mia.ide_modulo_pagamento\x0D\x0A                                from modulo_intervento_attore mia, intervento_attore ia, lav_ente lave, lavoratore lav, appl_int ai\x0D\x0A                                 where ai.cod_applicazione = SUBSTR(''${appctx_codapplicazione}'',2)\x0D\x0A                                   and mia.PRG_INTERVENTO_ATTORE = ia.PRG_INTERVENTO_ATTORE\x0D\x0A                                   and CAST(IA.COD_ATTORE AS INTEGER)= lav.IDE_LAVORATORE\x0D\x0A                                   and ai.ide_appl_int = lave.ide_appl_int\x0D\x0A                                   and lave.IDE_LAVORATORE   = lav.IDE_LAVORATORE\x0D\x0A                                   and lav.FLG_CANCELLAZIONE = ''N''\x0D\x0A                                   and ai.COD_INTERMEDIARIO like ''${appctx_utente_unitaorgrif}''||''%''\x0D\x0A                                   and (lave.DTT_FIN>=NOW() or lave.DTT_FIN is null)\x0D\x0A                                   and lave.DTT_INI<=NOW()', E'SQL', E'SYSTEM', NOW() ),
  (13, E'P', E'FiltroLavoratori per Servizio Competente', E'FiltroLavoratori per Servizio Competente', E'SQL', E'select distinct(lave.ide_lavoratore) from lav_ente lave, lavoratore lav, appl_int ai\x0D\x0A                                 where ai.cod_applicazione = SUBSTR(''${appctx_codapplicazione}'',2)\x0D\x0A                                   and ai.ide_appl_int = lave.ide_appl_int\x0D\x0A                                   and lave.IDE_LAVORATORE   = lav.IDE_LAVORATORE\x0D\x0A                                   and lav.FLG_CANCELLAZIONE = ''N''\x0D\x0A                                   and ai.COD_INTERMEDIARIO like ''${appctx_utente_unitaorgrif}''||''%''\x0D\x0A                                   and (lave.DTT_FIN>=NOW() or lave.DTT_FIN is null)\x0D\x0A                                   and lave.DTT_INI<=NOW()\x0D\x0A', E'SQL', E'SYSTEM', NOW() ),
  (15, E'P', E'Lavoratore', E'Lavoratore', E'SQL', E'SELECT l.ide_lavoratore\x0D\x0AFROM lavoratore l,\x0D\x0A  persona p,\x0D\x0A  iscrizione_persona i\x0D\x0AWHERE l.ide_lavoratore = p.ide_lavoratore\x0D\x0A AND p.ide_iscrizione_persona = i.ide_iscrizione_persona\x0D\x0A AND upper(i.cod_userid) = upper(''${appctx_utente_userid}'')', E'SQL', E'SYSTEM', NOW() ),
  (18, E'UO', E'LISTA tipologia servizio', E'LISTA tipologia servizio', E'SQL', E'SELECT DISTINCT COD_TIPOLOGIA_SERVIZIO\x0D\x0A   FROM DEC_TIPOLOGIA_SERVIZIO\x0D\x0A  WHERE COD_TIPOLOGIA_SERVIZIO LIKE TRIM(''${appctx_utente_unitaorgrif}'')||''%''', E'SQL', E'SYSTEM', NOW() ),
  (19, E'IP', E'LISTA Livelli studio', E'LISTA Livelli studio', E'SQL', E'(''7'',''8'',''12'')', E'SQL', E'SYSTEM', NOW() ),
  (20, E'P', E'Filtro Interventi per Servizio Competente', E'Filtro Interventi per Servizio Competente del lavoratore', E'SQL', E'select ia.IDE_INTERVENTO from intervento_attore ia\x0D\x0Awhere CAST(IA.COD_ATTORE AS INTEGER) in(\x0D\x0Aselect distinct(lave.ide_lavoratore) from lav_ente lave, lavoratore lav, appl_int ai\x0D\x0A                                 where ai.cod_applicazione = SUBSTR(''${appctx_codapplicazione}'',2)\x0D\x0A                                   and ai.ide_appl_int = lave.ide_appl_int\x0D\x0A                                   and lave.IDE_LAVORATORE   = lav.IDE_LAVORATORE\x0D\x0A                                   and lav.FLG_CANCELLAZIONE = ''N''\x0D\x0A                                   and ai.COD_INTERMEDIARIO like ''${appctx_utente_unitaorgrif}''||''%''\x0D\x0A                                   and (lave.DTT_FIN>=NOW() or lave.DTT_FIN is null)\x0D\x0A                                   and lave.DTT_INI<=NOW()\x0D\x0A                       )', E'SQL', E'SYSTEM', NOW() ),
  (21, E'UO', E'FiltroElenchiPagamento per Servizio Competente', E'Filtro elenchi di pagamento per Servizio Competente', E'SQL', E'select ed.IDE_ELENCO\x0D\x0Afrom elenco_destinatario ed, elenco el\x0D\x0Awhere ed.ide_elenco=el.ide_elenco and el.cod_tipo_incentivo=''TUT''\x0D\x0A and el.cod_intermediario = ''${appctx_utente_unitaorgrif}''\x0D\x0A\x09\x09', E'SQL', E'SYSTEM', NOW() ),
  (23, E'IP', E'Tipologia incentivo', E'Tipologia incentivo', E'SQL', E'''PAI'',''TUT''', E'SQL', E'SYSTEM', NOW() ),
  (42, E'UO', E'FiltroNewRichPagamento PAI per Servizio Competente', E'Filtro new richieste di pagamento per Servizio Competente', E'SQL', E'select rp.IDE_RICHIESTA_PAGAMENTO from RICHIESTA_PAGAMENTO rp where rp.COD_INTERMEDIARIO = ''${appctx_utente_unitaorgrif}''', E'SQL', E'SYSTEM', NOW() ),
  (43, E'UO', E'Filtro New Elenchi PAI per Servizio Competente', E'Filtro new Elenchi per Servizio Competente', E'SQL', E'select e.IDE_ELENCO from elenco e\x0D\x0Awhere e.COD_INTERMEDIARIO = ''${appctx_utente_unitaorgrif}''\x0D\x0A  and e.cod_tipo_incentivo=''PAI''', E'SQL', E'SYSTEM', NOW() ),
  (44, E'UO', E'Servizio Competente', E'Servizio Competente', E'SQL', E'''${appctx_utente_unitaorgrif}''', E'SQL', E'SYSTEM', NOW());