
\echo 'executing script 43_Pk_Diz.sql';

ALTER TABLE DEC_TIPO_REDDITO   ADD  CONSTRAINT PK_DEC_TIPO_REDDITO   PRIMARY KEY (COD_TIPO_REDDITO) ;
 

 ALTER TABLE PRG_SIGMA
	ADD CONSTRAINT  PK_PRG_SIGMA PRIMARY KEY (IDE_PRG_SIGMA) ;


ALTER TABLE DEC_TIPO_REPORT ADD
  CONSTRAINT PK_DEC_TIPO_REPORT
 PRIMARY KEY
 (COD_TIPO_REPORT) ;


ALTER TABLE DEC_TIPO_PARAM_REPORT ADD
  CONSTRAINT PK_DEC_TIPO_PARAM_REPORT
 PRIMARY KEY
 (COD_TIPO_PARAM_REPORT) ;
	

 
ALTER TABLE TAB_AMBITO_TERRITORIALE ADD
  CONSTRAINT PK_AMBITO_TERRITORIALE
 PRIMARY KEY
 (COD_AMBITO_TERRITORIALE) ;

  
ALTER TABLE TAB_NATURAGIURIDICA ADD
 CONSTRAINT PK_NATURAGIURIDICA
 PRIMARY KEY
 (COD_NATURAGIURIDICA) ;
 
  
 ALTER TABLE TAB_TRASFERTE 
 ADD CONSTRAINT PK_TRASFERTE
 PRIMARY KEY
 (COD_TRASFERTE) ;
 
  
 ALTER TABLE DEC_MOTIVO_RIFIUTO_PATTO 
 ADD CONSTRAINT PK_RIFIUTO_PATTO
 PRIMARY KEY
 (COD_MOTIVO_RIFIUTO_PATTO) ;
 
 

ALTER TABLE DEC_STATI_FILE_PROFILO 
 ADD CONSTRAINT PK_STATI_FILE_PROFILO
 PRIMARY KEY
 (COD_STATO_FILE_PROFILO) ;
 
  
ALTER TABLE TAB_QUESTURE 
 ADD CONSTRAINT PK_QUESTURE
 PRIMARY KEY
 (COD_QUESTURA) ;

  
 ALTER TABLE DEC_TARGET 
 ADD CONSTRAINT PK_DEC_TARGET
 PRIMARY KEY
 (COD_APPLICAZIONE, COD_TARGET) ;
 
  
ALTER TABLE DEC_TIPO_PROCESSO_ATTIVITA 
 ADD CONSTRAINT PK_TIPO_PROCESSO_ATT
 PRIMARY KEY
 (COD_PROCESSO_ATTIVITA)  ;
 
 

ALTER TABLE DEC_SOGG_ASSICURA ADD
  CONSTRAINT PKC_SOGG_ASSICURA
 PRIMARY KEY
 (COD_SOGG_ASSICURA) ;



ALTER TABLE TAB_AMBITI_DISCIPLINARI ADD
  CONSTRAINT PK_AMBITI_DISCIPLINARI
 PRIMARY KEY
 (COD_AMBITO_DISCIPLINARE) ;




ALTER TABLE DEC_AREA_RIFERIMENTO ADD
  CONSTRAINT PK_AREA_RIFERIMENTO
 PRIMARY KEY
 (COD_AREA_RIF) ;



ALTER TABLE DEC_ATTIVITA ADD
  CONSTRAINT PK_ATTIVITA
 PRIMARY KEY
 (COD_ATTIVITA) ;



ALTER TABLE DEC_CAUSA_EVENTO_MOBILITA ADD
  CONSTRAINT PK_CAUSA_EVENTO_MOBILITA
 PRIMARY KEY
 (COD_CAUSA_EVENTO) ;




ALTER TABLE TAB_INTERVENTI ADD
  CONSTRAINT PK_INTERVENTI
 PRIMARY KEY
 (COD_INTERVENTO) ;



ALTER TABLE DEC_MOTIVO_CESSAZIONE_TIROCINI ADD
  CONSTRAINT PK_MCESSAZIONE_TIROCINI
 PRIMARY KEY
 (COD_MOTIVO_CESSAZIONE) ;



ALTER TABLE TAB_MEZZITRASP ADD
  CONSTRAINT PK_MEZZITRASP
 PRIMARY KEY
 (COD_MEZZITRASP) ;



ALTER TABLE TAB_MOBILITAGEOG ADD
  CONSTRAINT PK_MOBILITAGEOG
 PRIMARY KEY
 (COD_MOBILITAGEOG) ;



ALTER TABLE DEC_MODALITA_CONVOCAZIONE ADD
  CONSTRAINT PK_MODALITA_CONVOCAZIONE
 PRIMARY KEY
 (COD_MODALITA_CONVOCAZIONE) ;




ALTER TABLE TAB_OBBLIGOFORMATIVO ADD
  CONSTRAINT PK_OBBLIGOFORMATIVO
 PRIMARY KEY
 (COD_OBBLIGOFORMATIVO) ;



ALTER TABLE DEC_ORIGINE_INFO ADD
  CONSTRAINT PK_ORIGINE_INFO
 PRIMARY KEY
 (COD_ORIGINE_INFO) ;



ALTER TABLE DEC_PERIODO_PAGAMENTO ADD
  CONSTRAINT PK_PERIODO_PAGAMENTO
 PRIMARY KEY
 (COD_APPLICAZIONE, COD_PERIODO_PAGAMENTO) ;



ALTER TABLE TIPO_EVENTO_CAUSA_MOBILITA ADD
  PRIMARY KEY
 (COD_CAUSA_EVENTO, COD_EVENTO_MOBILITA) ;




ALTER TABLE DEC_TIPO_PAGAMENTO ADD
  CONSTRAINT PK_TIPO_PAGAMENTO
 PRIMARY KEY
 (COD_APPLICAZIONE, COD_TIPO_PAGAMENTO) ;



ALTER TABLE DEC_TIPO_PATTO ADD
  CONSTRAINT PK_TIPO_PATTO
 PRIMARY KEY
 (COD_TIPO_PATTO, COD_APPLICAZIONE) ;



ALTER TABLE DEC_TIPO_TIROCINIO ADD
  CONSTRAINT PK_TIPO_TIROCINIO
 PRIMARY KEY
 (COD_TIPO_TIROCINIO) ;



ALTER TABLE TAB_UNITA_TEMPO ADD
  CONSTRAINT PK_UNITA_TEMPO
 PRIMARY KEY
 (COD_UNITA_TEMPO) ;



ALTER TABLE DEC_VERBI ADD
  CONSTRAINT PK_VERBI
 PRIMARY KEY
 (COD_VERBO) ;



ALTER TABLE DEC_CERTIFICATORI ADD
  PRIMARY KEY
 (COD_CERTIFICATORI) ;



ALTER TABLE DEC_DETTAGLIOISTITUTO ADD
  PRIMARY KEY
 (COD_DETTAGLIOISTITUTO, COD_TIPOISTITUTO) ;



ALTER TABLE DEC_ALLEGATI ADD
  CONSTRAINT PK_DEC_ALLEGATI
 PRIMARY KEY
 (COD_APPLICAZIONE, COD_ALLEGATO) ;



ALTER TABLE DEC_AREA_COMPETENZA ADD
  CONSTRAINT PK_DEC_AREA_COMPETENZA
 PRIMARY KEY
 (COD_AREA_COMPETENZA) ;



ALTER TABLE DEC_DESTINATARIO ADD
  CONSTRAINT PK_DEC_DESTINATARIO
 PRIMARY KEY
 (COD_DESTINATARIO) ;


ALTER TABLE DEC_ESITO_PROPOSTA ADD
  CONSTRAINT PK_DEC_ESITO_PROPOSTA
 PRIMARY KEY
 (COD_ESITO_PROPOSTA) ;



ALTER TABLE DEC_LINGUECONOSCENZACEF ADD
  CONSTRAINT PK_DEC_LINGUECONOSCENZACEF
 PRIMARY KEY
 (COD_CONOSCENZA_CEF) ;



ALTER TABLE DEC_MOTIVO_CONVOCAZIONE ADD
  CONSTRAINT PK_DEC_MOTIVO_CONVOCAZIONE
 PRIMARY KEY
 (COD_APPLICAZIONE, COD_MOTIVO_CONVOCAZIONE) ;



ALTER TABLE DEC_STATO_DOCUMENTO ADD
  CONSTRAINT PK_DEC_STATO_DOCUMENTO
 PRIMARY KEY
 (COD_STATO_DOCUMENTO) ;



ALTER TABLE DEC_STATO_PROCEDURA ADD
  CONSTRAINT PK_DEC_STATO_PROCEDURA
 PRIMARY KEY
 (COD_STATO_PROCEDURA) ;



ALTER TABLE DEC_TIPOLOGIA_COMPETENZA ADD
  CONSTRAINT PK_DEC_TIP_COMPETENZA
 PRIMARY KEY
 (COD_TIPOLOGIA_COMPETENZA) ;



ALTER TABLE DEC_VOCE_COSTO ADD
  CONSTRAINT PK_DEC_VOCE_COSTO
 PRIMARY KEY
 (COD_VOCE_COSTO) ;



ALTER TABLE DEC_WSC ADD
  CONSTRAINT PK_DEC_WSC
 PRIMARY KEY
 (COD_APPLICAZIONE, COD_WSC) ;




ALTER TABLE DEC_ELEMENTI ADD
  CONSTRAINT PK_ELEMENTI
 PRIMARY KEY
 (COD_ELEMENTO) ;



ALTER TABLE TAB_ENTE_RILASCIO_DOC ADD
  CONSTRAINT PK_ENTE_RILASCIO_DOC
 PRIMARY KEY
 (COD_ENTE_RILASCIO_DOC) ;



ALTER TABLE DEC_ESITO_CONVOCAZIONE ADD
  CONSTRAINT PK_ESITO_CONVOCAZIONE
 PRIMARY KEY
 (COD_ESITO_CONVOCAZIONE) ;



ALTER TABLE TAB_FORMAGIURIDICA ADD
  CONSTRAINT PK_FORMAGIURIDICA
 PRIMARY KEY
 (COD_FORMAGIURIDICA) ;



ALTER TABLE DEC_GRADO_ELEMENTO_COMPETENZA ADD
  CONSTRAINT PK_GRADO_ELEMENTO_COMP
 PRIMARY KEY
 (COD_GRADO_ELEMENTO_COMPETENZA) ;




ALTER TABLE DEC_TIPOLOGIA_AZIONE ADD
  CONSTRAINT PK_DEC_TIPOLOGIA_AZIONE
 PRIMARY KEY
 (COD_APPLICAZIONE, COD_TIPOLOGIA_AZIONE) ;



ALTER TABLE DEC_TIPOLOGIA_FONDO ADD
  CONSTRAINT PK_DEC_TIPOLOGIA_FONDO
 PRIMARY KEY
 (COD_TIPOLOGIA_FONDO) ;



ALTER TABLE DEC_TIPOPAG_PAI ADD
  CONSTRAINT PK_DEC_TIPOPAG_PAI
 PRIMARY KEY
 (COD_TIPOPAG_PAI) ;



ALTER TABLE DEC_TIPO_CONVENZIONE ADD
  CONSTRAINT PK_DEC_TIPO_CONVENZIONE
 PRIMARY KEY
 (COD_APPLICAZIONE, COD_TIPO_CONVENZIONE) ;



ALTER TABLE DEC_TIPO_COSTO ADD
  CONSTRAINT PK_DEC_TIPO_COSTO
 PRIMARY KEY
 (COD_TIPO_COSTO) ;



ALTER TABLE DEC_TIPO_INCENTIVO ADD
  CONSTRAINT PK_DEC_TIPO_INCENTIVO
 PRIMARY KEY
 (COD_TIPO_INCENTIVO) ;



ALTER TABLE DEC_TIPO_COSTO_PIANO ADD
  CONSTRAINT PK_DEC_TIPO_PIANO
 PRIMARY KEY
 (COD_TIPO_COSTO_PIANO) ;



ALTER TABLE TAB_DOCUMENTI ADD
  CONSTRAINT PK_DOCUMENTI
 PRIMARY KEY
 (COD_DOCUMENTO) ;



ALTER TABLE COMPETENZA_ELEMENTI ADD
  CONSTRAINT PK_COMPETENZA_ELEMENTI
 PRIMARY KEY
 (COD_COMPETENZA, COD_ELEMENTO, COD_GRADO_ELEMENTO_COMPETENZA) ;



ALTER TABLE DEC_COMPETENZE ADD
  CONSTRAINT PK_COMPETENZE
 PRIMARY KEY
 (COD_COMPETENZA) ;



ALTER TABLE COMPETENZE_AREA_COMP ADD
  CONSTRAINT PK_COMPETENZE_AREA_COMP
 PRIMARY KEY
 (COD_COMPETENZA, COD_AREA_COMPETENZA) ;



ALTER TABLE COMPETENZE_TIPOLOGIA_COMP ADD
  CONSTRAINT PK_COMPETENZE_TIP_COMP
 PRIMARY KEY
 (COD_COMPETENZA, COD_TIPOLOGIA_COMPETENZA) ;



ALTER TABLE TAB_COMUNI_CAP ADD
  CONSTRAINT PK_COMUNI_CAP
 PRIMARY KEY
 (COD_COMUNE, COD_CAP) ;



ALTER TABLE DEC_CONDIZIONE_TIROCINIO ADD
  CONSTRAINT PK_CONDIZIONE_TIROCINIO
 PRIMARY KEY
 (COD_CONDIZIONE_TIROCINIO) ;



ALTER TABLE TAB_CORSOTIPO ADD
  CONSTRAINT PK_CORSOTIPO
 PRIMARY KEY
 (COD_CORSOTIPO) ;



ALTER TABLE DEC_CRITERIO_SOSP_CONS ADD
  CONSTRAINT PK_CRITERIO_SOSP_CONS
 PRIMARY KEY
 (COD_CRITERIO_SC) ;

 


ALTER TABLE DEC_TERRITORIO ADD
  CONSTRAINT PK_TERRITORIO
 PRIMARY KEY
 (COD_COMUNE, COD_INTERMEDIARIO, COD_TIPO_INTERMEDIARIO) ;



ALTER TABLE TAB_TIPODISABILITA ADD
  CONSTRAINT PK_TIPODISABILITA
 PRIMARY KEY
 (COD_TIPODISABILITA) ;



ALTER TABLE DEC_TIPOLOGIA_SERVIZIO ADD
  CONSTRAINT PK_TIPOLOGIA_SERVIZIO
 PRIMARY KEY
 (COD_TIPOLOGIA_SERVIZIO) ;



ALTER TABLE TAB_TIPORECAPITO ADD
  CONSTRAINT PK_TIPORECAPITO
 PRIMARY KEY
 (COD_TIPORECAPITO) ;



ALTER TABLE DEC_TIPO_AMBITO_CRITERIO ADD
  CONSTRAINT PK_TIPO_AMBITO_CRITERIO
 PRIMARY KEY
 (COD_TIPO_AMBITO_CRITERIO) ;



ALTER TABLE DEC_TIPO_COMPETENZA ADD
  CONSTRAINT PK_TIPO_COMPETENZA
 PRIMARY KEY
 (COD_TIPO_COMPETENZA) ;



ALTER TABLE DEC_TIPO_ELEMENTO ADD
  CONSTRAINT PK_TIPO_ELEMENTO
 PRIMARY KEY
 (COD_TIPO_ELEMENTO) ;



ALTER TABLE DEC_TIPO_EVENTO_MOBILITA ADD
  CONSTRAINT PK_TIPO_EVENTO_MOBILITA
 PRIMARY KEY
 (COD_TIPO_EVENTO_MOBILITA) ;


ALTER TABLE DEC_CAUSA_FINE_DID ADD
  CONSTRAINT PK_CAUSA_FINE_DID
 PRIMARY KEY
 (COD_CAUSA_FINE_DID) ;



ALTER TABLE DEC_PROFILI ADD
  CONSTRAINT PK_PROFILI
 PRIMARY KEY
 (COD_PROFILO) ;



ALTER TABLE PROFILO_COMPETENZE ADD
  CONSTRAINT PK_PROFILO_COMPETENZE
 PRIMARY KEY
 (COD_PROFILO, COD_COMPETENZA) ;



ALTER TABLE PROFILO_COMPORTAMENTI ADD
  CONSTRAINT PK_PROFILO_COMPORTAMENTI
 PRIMARY KEY
 (COD_PROFILO, COD_ELEMENTO) ;

/*

ALTER TABLE TAB_QUESTURE ADD
  CONSTRAINT PK_QUESTURE
 PRIMARY KEY
 (COD_QUESTURA) ;
*/



ALTER TABLE TAB_RIPTERRITORIALE ADD
  CONSTRAINT PK_RIPTERRITORIALE
 PRIMARY KEY
 (COD_RIPTERRITORIALE) ;



ALTER TABLE TAB_STATOCIVILE ADD
  CONSTRAINT PK_STATOCIVILE
 PRIMARY KEY
 (COD_STATOCIVILE) ;



ALTER TABLE TAB_STATOESPERIENZA ADD
  CONSTRAINT PK_STATOESPERIENZA
 PRIMARY KEY
 (COD_STATOESPERIENZA) ;



ALTER TABLE DEC_ENTE_EROGATORE ADD
  PRIMARY KEY
 (COD_ENTE_EROGATORE) ;



ALTER TABLE DEC_EVENTI_INTERVENTO ADD
  PRIMARY KEY
 (COD_EVENTO) ;



ALTER TABLE DEC_STRINT_AREA ADD
  PRIMARY KEY
 (COD_AREA_INTERVENTO) ;



ALTER TABLE DEC_STRINT_MACROSTRUMENTO ADD
  PRIMARY KEY
 (COD_MACROSTRUMENTO) ;



ALTER TABLE DEC_SUSSIDI_ENTE_EROGATORE ADD
  PRIMARY KEY
 (COD_TIPO_SUSSIDIO, COD_ENTE_EROGATORE) ;



ALTER TABLE DEC_SUSSIDIO ADD
  PRIMARY KEY
 (COD_TIPO_SUSSIDIO) ;



ALTER TABLE DEC_TIPO_ATTRIBUTO ADD
  PRIMARY KEY
 (COD_TIPO_ATTRIBUTO) ;



ALTER TABLE DEC_TIPOISTITUTO ADD
  PRIMARY KEY
 (COD_TIPOISTITUTO) ;

 -- TABELLE PORTATE DA J
 

ALTER TABLE DEC_STATO_ISCRIZIONE ADD
  CONSTRAINT PK_STATO_ISCRIZIONE
 PRIMARY KEY
 (COD_STATO) ;

 
ALTER TABLE DEC_STATO_ISCRIZIONE_PERSONA ADD
  CONSTRAINT PK_STATO_ISCRIZIONE_PERS
 PRIMARY KEY
 (COD_STATO) ;




ALTER TABLE DEC_FORMATO_FILE ADD
  CONSTRAINT PK_FORMATO_FILE
 PRIMARY KEY
 (COD_FORMATO) ;


ALTER TABLE DEC_LIV_TIPO_AMMORTIZZATORE ADD
  CONSTRAINT PK_DEC_LIV_TIPO_AMMORTIZZATORE
 PRIMARY KEY
 (COD_TIPO_AMMORTIZZATORE) ;




ALTER TABLE DEC_MESI ADD
  CONSTRAINT PK_DEC_MESI
 PRIMARY KEY
 (COD_MESE) ;



ALTER TABLE DEC_STATO_SELEZIONE_DETTAGLIO ADD
  CONSTRAINT PK_DEC_STATO_SELEZIONE_DETTAGL
 PRIMARY KEY
 (COD_STATO) ;



ALTER TABLE DEC_TIPO_SOGGETTO ADD
  CONSTRAINT PK_TIPOSOGGETTO
 PRIMARY KEY
 (COD_TIPO_SOGGETTO) ;


ALTER TABLE DEC_FASCIA_ETA ADD
  CONSTRAINT PK_DEC_FASCIA_ETA
 PRIMARY KEY
 (COD_TIPO_FASCIA, COD_FASCIA_ETA) ;

 
ALTER TABLE DEC_TIPO_DOCENZA ADD
  CONSTRAINT PK_DEC_TIPO_DOCENZA
 PRIMARY KEY
 (COD_TIPO_DOCENZA) ;

 ALTER TABLE DEC_CALCOLO_ORE
	ADD CONSTRAINT  PK_DEC_CALCOLO_ORE PRIMARY KEY (COD_CALCOLO_ORE) ;
	
--20160621
ALTER TABLE DEC_TIPO_RAGGRUPPAMENTO
	ADD CONSTRAINT  PK_DEC_TIPO_RAGGRUPPAMENTO PRIMARY KEY (COD_TIPO_RAGGRUPPAMENTO);

ALTER TABLE RAGGRUPPAMENTO_INTERMEDIARI
	ADD CONSTRAINT  PK_RAGGRUPPAMENTO_INTERMEDIARI PRIMARY KEY (COD_INTERM_PRINCIPALE,COD_INTERM_AGGREGATO,COD_TIPO_RAGGRUPPAMENTO,DAT_INIZIO);	
	
-- 20170213
ALTER TABLE DEC_ATTRIBUTI_COSTO
	ADD CONSTRAINT  PK_DEC_ATTRIBUTI_COSTO PRIMARY KEY (COD_ATTRIBUTO);
		
ALTER TABLE DEC_MISURE
	ADD CONSTRAINT  PK_DEC_MISURE PRIMARY KEY (COD_MISURA,COD_APPLICAZIONE)	;	
	
--20170831
ALTER TABLE PROGETTI_SIGMA
	ADD CONSTRAINT  PK_PROGETTI_SIGMA PRIMARY KEY (IDE_PROGETTO_SIGMA);
	
-- 20190517
ALTER TABLE DEC_STATO_ELENCO
	ADD CONSTRAINT PK_STATO_ELENCO PRIMARY KEY (COD_STATO_ELENCO);
	
-- 20190905
ALTER TABLE DEC_NATURA_CUP
	ADD CONSTRAINT PK_NATURA_CUP PRIMARY KEY (COD_NATURA_CUP);	