
\echo 'executing script 50_Fk_Cla.sql';

\c :dbName plus_classificazione;

ALTER TABLE TAB_PROVINCE ADD FOREIGN KEY (COD_REGIONE) REFERENCES TAB_REGIONI (COD_REGIONE);
ALTER TABLE TAB_ATECOLIV3 ADD CONSTRAINT FK_ATECOLIV3_LIV2 FOREIGN KEY (COD_ATECOLIV2) REFERENCES TAB_ATECOLIV2 (COD_ATECOLIV2);
ALTER TABLE TAB_REGIONI ADD FOREIGN KEY (COD_MOBILITAGEOG) REFERENCES TAB_MOBILITAGEOG (COD_MOBILITAGEOG);
ALTER TABLE TAB_QUALPROFLIV4 ADD FOREIGN KEY (COD_QUALPROFLIV3) REFERENCES TAB_QUALPROFLIV3 (COD_QUALPROFLIV3);
ALTER TABLE TAB_FIGURAPROFESS ADD FOREIGN KEY (COD_AREAPROFESS) REFERENCES TAB_AREAPROFESS (COD_AREAPROFESS);
ALTER TABLE TAB_ATECOLIV1 ADD CONSTRAINT FK_ATECOLIV1_LIV0 FOREIGN KEY (COD_ATECOLIV0) REFERENCES TAB_ATECOLIV0 (COD_ATECOLIV0);
ALTER TABLE TAB_ALBO_INTERMEDIARI ADD CONSTRAINT FK_ALBO_INTERMEDIARI FOREIGN KEY (COD_INTERMEDIARIO) REFERENCES TAB_INTERMEDIARI (COD_INTERMEDIARIO);
ALTER TABLE TAB_COMUNI ADD FOREIGN KEY (COD_PROVINCIA) REFERENCES TAB_PROVINCE (COD_PROVINCIA);
ALTER TABLE TAB_QUALPROFLIV2 ADD FOREIGN KEY (COD_QUALPROFLIV1) REFERENCES TAB_QUALPROFLIV1 (COD_QUALPROFLIV1);
ALTER TABLE TAB_ALBO_SEDI ADD CONSTRAINT FK_TAB_ALBO_SEDI_INTERMEDIARI FOREIGN KEY (COD_ALBO_INTERMEDIARI) REFERENCES TAB_ALBO_INTERMEDIARI (COD_ALBO_INTERMEDIARI) ON DELETE SET NULL;
ALTER TABLE TAB_ATECOLIV2 ADD CONSTRAINT FK_ATECOLIV2_LIV1 FOREIGN KEY (COD_ATECOLIV1) REFERENCES TAB_ATECOLIV1 (COD_ATECOLIV1);
ALTER TABLE TAB_STUDIOTITOLO ADD FOREIGN KEY (COD_LIVELLOSTUDIO) REFERENCES TAB_STUDIOLIVELLO (COD_LIVELLOSTUDIO);
ALTER TABLE TAB_REGIONI ADD FOREIGN KEY (COD_RIPTERRITORIALE) REFERENCES TAB_RIPTERRITORIALE (COD_RIPTERRITORIALE);
ALTER TABLE TAB_INTERMEDIARI ADD CONSTRAINT FK_INTERMED_COMUNE FOREIGN KEY (COD_COMUNE_RECAPITO) REFERENCES TAB_COMUNI (COD_COMUNE);
ALTER TABLE TAB_INTERMEDIARI_FILIALI ADD CONSTRAINT FK_INTERMEDIARI_FILIALI FOREIGN KEY (COD_INTERMEDIARIO) REFERENCES TAB_INTERMEDIARI (COD_INTERMEDIARIO);
ALTER TABLE TAB_QUALPROFLIV3 ADD FOREIGN KEY (COD_QUALPROFLIV2) REFERENCES TAB_QUALPROFLIV2 (COD_QUALPROFLIV2);
ALTER TABLE TAB_ATECOLIV4 ADD CONSTRAINT FK_ATECOLIV4_LIV3 FOREIGN KEY (COD_ATECOLIV3) REFERENCES TAB_ATECOLIV3 (COD_ATECOLIV3);
ALTER TABLE TAB_ALBO_INTERMEDIARI ADD CONSTRAINT FK_TAB_ALBO_INTERMEDIARI_ATECO FOREIGN KEY (COD_SETTORE) REFERENCES TAB_ATECOLIV4 (COD_ATECOLIV4) ON DELETE SET NULL;
ALTER TABLE TAB_ALBO_SEDI ADD CONSTRAINT FK_TAB_ALBO_SEDI_NAZ FOREIGN KEY (COD_NAZIONE_ESTERA) REFERENCES TAB_NAZIONI (COD_NAZIONE) ON DELETE SET NULL;
ALTER TABLE TAB_INTERMEDIARI ADD CONSTRAINT FK_INTERMEDIARI_COMUNI_CAP FOREIGN KEY (COD_COMUNE_RECAPITO, COD_CAP_RECAPITO) REFERENCES TAB_COMUNI_CAP (COD_COMUNE,COD_CAP);
ALTER TABLE TAB_ALBO_INTERMEDIARI ADD CONSTRAINT FK_TAB_ALBO_INTERMEDIARI_CCNL FOREIGN KEY (COD_CCNL_PREVALENTE) REFERENCES TAB_CCNL (COD_CCNL) ON DELETE SET NULL;
ALTER TABLE TAB_COMUNE_INTERMEDIARI ADD FOREIGN KEY (COD_INTERMEDIARIO) REFERENCES TAB_INTERMEDIARI (COD_INTERMEDIARIO) ON DELETE CASCADE;
ALTER TABLE TAB_ALBO_SEDI ADD CONSTRAINT FK_TAB_ALBO_SEDI_COMUNE FOREIGN KEY (COD_COMUNE) REFERENCES TAB_COMUNI (COD_COMUNE) ON DELETE SET NULL;
ALTER TABLE TAB_ALBO_SEDI ADD CONSTRAINT FK_ALBO_SEDI_FILIALI FOREIGN KEY (COD_INTERMEDIARIO, COD_FILIALE) REFERENCES TAB_INTERMEDIARI_FILIALI (COD_INTERMEDIARIO,COD_FILIALE);
ALTER TABLE TAB_INTERMEDIARI ADD FOREIGN KEY (COD_TIPO_INTERMEDIARIO) REFERENCES TAB_TIPO_INTERMEDIARIO (COD_TIPO_INTERMEDIARIO);
alter table TAB_INTERMEDIARI add constraint FX_INTERMEDIARIO_PADRE foreign key (COD_PADRE) references TAB_INTERMEDIARI (COD_INTERMEDIARIO);
ALTER TABLE TAB_QUALPROFLIV1 ADD FOREIGN KEY (COD_QUALPROFLIV0) REFERENCES TAB_QUALPROFLIV0 (COD_QUALPROFLIV0);
ALTER TABLE TAB_INTERMEDIARI_FILIALI ADD CONSTRAINT FK_COMUNI_INTERMFILIALI FOREIGN KEY (COD_COMUNE) REFERENCES TAB_COMUNI (COD_COMUNE) ON DELETE SET NULL;
ALTER TABLE TAB_INTERMEDIARI_FILIALI ADD CONSTRAINT FK_INTERM_FILIALI_COMUNI_CAP FOREIGN KEY (COD_COMUNE, COD_CAP) REFERENCES TAB_COMUNI_CAP (COD_COMUNE,COD_CAP);
ALTER TABLE TAB_INTERMEDIARI	ADD CONSTRAINT FK_INTERMEDIARIO_RAGG FOREIGN KEY (COD_RAGGRUPPAMENTO) REFERENCES TAB_INTERMEDIARI (COD_INTERMEDIARIO);
 ALTER TABLE TAB_INTERMEDIARI	ADD CONSTRAINT FK_TAB_FORMAGIURIDICA FOREIGN KEY (COD_FORMAGIURIDICA) REFERENCES PLUS_DIZIONARI.TAB_FORMAGIURIDICA (COD_FORMAGIURIDICA) ON DELETE SET NULL;
 ALTER TABLE TAB_INTERMEDIARI   ADD CONSTRAINT FK_DEC_ENTE_EROGATORE FOREIGN KEY (COD_ENTE_EROGATORE) REFERENCES PLUS_DIZIONARI.DEC_ENTE_EROGATORE (COD_ENTE_EROGATORE);

-- 20190920
 ALTER TABLE tab_intermediari  ADD CONSTRAINT fk_intermediario_ateco FOREIGN KEY (cod_ateco)  REFERENCES plus_classificazione.tab_atecoliv4(cod_atecoliv4); 