
\echo 'executing script 60_Fk_Diz.sql';

\c :dbName plus_dizionari;
--set search_path to plus_dizionari;



ALTER TABLE DEC_ELEMENTI ADD 
  FOREIGN KEY (COD_TIPO_ELEMENTO) 
 REFERENCES DEC_TIPO_ELEMENTO (COD_TIPO_ELEMENTO);



ALTER TABLE DEC_ELEMENTI ADD 
  FOREIGN KEY (COD_AREA_RIF) 
 REFERENCES DEC_AREA_RIFERIMENTO (COD_AREA_RIF);



ALTER TABLE DEC_SUSSIDI_ENTE_EROGATORE ADD 
  FOREIGN KEY (COD_ENTE_EROGATORE) 
 REFERENCES DEC_ENTE_EROGATORE (COD_ENTE_EROGATORE);



ALTER TABLE DEC_SUSSIDI_ENTE_EROGATORE ADD 
  FOREIGN KEY (COD_TIPO_SUSSIDIO) 
 REFERENCES DEC_SUSSIDIO (COD_TIPO_SUSSIDIO);



ALTER TABLE PROFILO_COMPETENZE ADD 
  FOREIGN KEY (COD_PROFILO) 
 REFERENCES DEC_PROFILI (COD_PROFILO);



ALTER TABLE PROFILO_COMPETENZE ADD 
  FOREIGN KEY (COD_COMPETENZA) 
 REFERENCES DEC_COMPETENZE (COD_COMPETENZA);



ALTER TABLE PROFILO_COMPETENZE ADD 
  FOREIGN KEY (COD_TIPO_COMPETENZA) 
 REFERENCES DEC_TIPO_COMPETENZA (COD_TIPO_COMPETENZA);



ALTER TABLE PROFILO_COMPORTAMENTI ADD 
  FOREIGN KEY (COD_ELEMENTO) 
 REFERENCES DEC_ELEMENTI (COD_ELEMENTO);



ALTER TABLE PROFILO_COMPORTAMENTI ADD 
  FOREIGN KEY (COD_PROFILO) 
 REFERENCES DEC_PROFILI (COD_PROFILO);




ALTER TABLE TAB_COMUNI_CAP ADD 
  CONSTRAINT FK_COMCAP_COMUNI 
 FOREIGN KEY (COD_COMUNE) 
 REFERENCES TAB_COMUNI (COD_COMUNE)
    ON DELETE CASCADE;



ALTER TABLE COMPETENZE_AREA_COMP ADD 
  CONSTRAINT FK_COMPETENZE_AREA_COMP_1 
 FOREIGN KEY (COD_AREA_COMPETENZA) 
 REFERENCES DEC_AREA_COMPETENZA (COD_AREA_COMPETENZA);



ALTER TABLE COMPETENZE_AREA_COMP ADD 
  CONSTRAINT FK_COMPETENZE_AREA_COMP_2 
 FOREIGN KEY (COD_COMPETENZA) 
 REFERENCES DEC_COMPETENZE (COD_COMPETENZA);




ALTER TABLE TIPO_EVENTO_CAUSA_MOBILITA ADD 
  FOREIGN KEY (COD_EVENTO_MOBILITA) 
 REFERENCES DEC_TIPO_EVENTO_MOBILITA (COD_TIPO_EVENTO_MOBILITA);



ALTER TABLE TIPO_EVENTO_CAUSA_MOBILITA ADD 
  FOREIGN KEY (COD_CAUSA_EVENTO) 
 REFERENCES DEC_CAUSA_EVENTO_MOBILITA (COD_CAUSA_EVENTO);



ALTER TABLE COMPETENZE_TIPOLOGIA_COMP ADD 
  CONSTRAINT FK_COMPETENZE_TIP_COMP_1 
 FOREIGN KEY (COD_TIPOLOGIA_COMPETENZA) 
 REFERENCES DEC_TIPOLOGIA_COMPETENZA (COD_TIPOLOGIA_COMPETENZA);



ALTER TABLE COMPETENZE_TIPOLOGIA_COMP ADD 
  CONSTRAINT FK_COMPETENZE_TIP_COMP_2 
 FOREIGN KEY (COD_COMPETENZA) 
 REFERENCES DEC_COMPETENZE (COD_COMPETENZA);



ALTER TABLE TAB_FORMAGIURIDICA ADD 
  CONSTRAINT FK_TAB_FORMAGIURIDICA_PARENT 
 FOREIGN KEY (PARENT) 
 REFERENCES TAB_FORMAGIURIDICA (COD_FORMAGIURIDICA);



ALTER TABLE COMPETENZA_ELEMENTI ADD 
  FOREIGN KEY (COD_COMPETENZA) 
 REFERENCES DEC_COMPETENZE (COD_COMPETENZA);



ALTER TABLE COMPETENZA_ELEMENTI ADD 
  FOREIGN KEY (COD_GRADO_ELEMENTO_COMPETENZA) 
 REFERENCES DEC_GRADO_ELEMENTO_COMPETENZA (COD_GRADO_ELEMENTO_COMPETENZA);



ALTER TABLE DEC_ATTIVITA ADD 
  FOREIGN KEY (COD_COMPETENZA) 
 REFERENCES DEC_COMPETENZE (COD_COMPETENZA);



ALTER TABLE DEC_COMPETENZE ADD 
  FOREIGN KEY (COD_VERBO) 
 REFERENCES DEC_VERBI (COD_VERBO);



 ALTER TABLE DEC_DETTAGLIOISTITUTO ADD 
  FOREIGN KEY (COD_TIPOISTITUTO) 
 REFERENCES DEC_TIPOISTITUTO (COD_TIPOISTITUTO)
    ON DELETE CASCADE;
 
 ALTER TABLE DEC_DETTAGLIOISTITUTO ADD 
  FOREIGN KEY (COD_TIPO_SUSSIDIO) 
 REFERENCES DEC_SUSSIDIO (COD_TIPO_SUSSIDIO)
    ON DELETE SET NULL;
	
-- 20160621

ALTER TABLE RAGGRUPPAMENTO_INTERMEDIARI
	ADD CONSTRAINT FK_INTER_PRINC FOREIGN KEY (COD_INTERM_PRINCIPALE) REFERENCES plus_classificazione.TAB_INTERMEDIARI (COD_INTERMEDIARIO) ON DELETE CASCADE;

ALTER TABLE RAGGRUPPAMENTO_INTERMEDIARI
	ADD CONSTRAINT FK_INTERM_AGGR FOREIGN KEY (COD_INTERM_AGGREGATO) REFERENCES plus_classificazione.TAB_INTERMEDIARI (COD_INTERMEDIARIO) ON DELETE CASCADE;

ALTER TABLE RAGGRUPPAMENTO_INTERMEDIARI
	ADD CONSTRAINT FK_DEC_RAGG_RAGGR_INTERM FOREIGN KEY (COD_TIPO_RAGGRUPPAMENTO) REFERENCES DEC_TIPO_RAGGRUPPAMENTO (COD_TIPO_RAGGRUPPAMENTO);

	
/*
-- 20160920	
ALTER TABLE RAGGRUPPAMENTO_INTERMEDIARI
	ADD (CONSTRAINT FK_APPLICAZIONE_RAGGR FOREIGN KEY (COD_APPLICAZIONE) REFERENCES APPLICAZIONE (COD_APPLICAZIONE));
*/	
	
--20170831
 ALTER TABLE PROGETTI_SIGMA
	ADD CONSTRAINT FK_DEC_MISURE FOREIGN KEY (COD_MISURA, COD_APPLICAZIONE) REFERENCES DEC_MISURE (COD_MISURA, COD_APPLICAZIONE); 

		