
\echo 'executing script 61_Idx_Diz.sql';

CREATE INDEX IDX_COMP_AREA_COMP_01 ON COMPETENZE_AREA_COMP
(COD_AREA_COMPETENZA) ;



CREATE INDEX IDX_COMP_AREA_COMP_02 ON COMPETENZE_AREA_COMP
(COD_COMPETENZA) ;



CREATE INDEX IDX_COMP_TIP_COMP_01 ON COMPETENZE_TIPOLOGIA_COMP
(COD_TIPOLOGIA_COMPETENZA) ;



CREATE INDEX IDX_COMP_TIP_COMP_02 ON COMPETENZE_TIPOLOGIA_COMP
(COD_COMPETENZA) ;

