/* Data for the 'inside_profiler.tab_servizio' table  (Records 1 - 363) */

INSERT INTO inside_profiler.tab_servizio ("cod_codiceservizio", "des_descrizione", "des_nome", "cod_codicestrumento", "img_logo", "des_nome_logo", "des_tipo_logo", "cod_useragg", "dtt_tmst", "des_url")
VALUES 
  (E'provaServizio', E'Descrizione Prova Servizio', E'Prova Servizio', E'ST.FAD.LOA', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.AMM.PAGAMENTI', E'Gestione Pagamenti', E'Gestione Pagamenti', E'ST.AMM.PAGAMENTI', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.AREADOCUM.MENU', E'voce area documentale nel Menu', E'voce area documentale nel Menu', E'ST.AREADOCUM.MENU', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.AZI.ANNULLACANC', E'Annulla cancellazione logica  Datore Lavoro', E'Annulla cancellazione logica  Datore Lavoro', E'ST.AZI.ANNULLACANC', NULL, NULL, NULL, E'MANUALE', NOW(), NULL),
  (E'SV.AZI.CTXAZI', E'Datore lavoro contesto', E'Datore lavoro contesto', E'ST.AZI.CTXAZI', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.AZI.DELAZI', E'Elimina dati relativi all''Azienda', E'Elimina dati relativi all''Azienda', E'ST.AZI.DELAZI', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.AZI.DELAZI.SEDE', E'Elimina dati relativi alla sede di lavoro', E'Elimina dati relativi alla sede di lavoro', E'ST.AZI.DELAZI', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.AZI.DELAZI.UTENTEDATORE', E'Elimina dati relativi all''utente Azienda', E'Elimina dati relativi all''utente Azienda', E'ST.AZI.DELAZI.UTENTEDATORE', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.AZI.DELAZI.UTENTESEDE', E'Elimina dati relativi all''utente sede Azienda', E'Elimina dati relativi all''utente sede Azienda', E'ST.AZI.DELAZI.UTENTESEDE', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.AZI.DIS.INFOAGG', E'Informazioni Aggiuntive Disabili', E'Informazioni Aggiuntive Disabili', E'ST.AZI.DIS.INFOAGG', NULL, NULL, NULL, E'ICF', NOW(), NULL),
  (E'SV.AZI.DISPOINTERVENTI.DATORE', E'Disponibilita interventi relativi all''Azienda', E'Disponibilita interventi relativi all''Azienda', E'ST.AZI.DISPOINTERVENTI.DATORE', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.AZI.DISPOINTERVENTI.SEDE', E'Disponibilita interventi relativi alla sede Azienda', E'Disponibilita interventi relativi alla sede Azienda', E'ST.AZI.DISPOINTERVENTI.SEDE', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.AZI.DISPOINTERVENTI.UTENTEDATORE', E'Disponibilita interventi relativi all''utente Azienda', E'Disponibilita interventi relativi all''utente Azienda', E'ST.PA.DISPINT', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.AZI.DISPOINTERVENTI.UTENTESEDE', E'Disponibilita interventi relativi all''utente sede Azienda', E'Disponibilita interventi relativi all''utente sede Azienda', E'ST.AZI.DISPOINTERVENTI.UTENTESEDE', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.AZI.ELIMINA.VISAZI', E'Visualizzazione datore lavoro in elimina scheda', E'Visualizzazione datore lavoro in elimina scheda', E'ST.AZI.VISAZI', NULL, NULL, NULL, E'MANUALE', NOW(), NULL),
  (E'SV.AZI.ENTEVIS', E'Visualizza dati relativi al serivo competente dell''Azienda', E'Visualizza dati relativi al serivo competente dell''Azienda', E'ST.AZI.ENTEVIS', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.AZI.FABBOCC.DATORE', E'Fabbisogni occupazionali relativi all''Azienda', E'Fabbisogni occupazionali relativi all''Azienda', E'ST.AZI.FABBOCC.DATORE', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.AZI.FABBOCC.SEDE', E'Fabbisogni occupazionali relativi alla sede Azienda', E'Fabbisogni occupazionali relativi alla sede Azienda', E'ST.AZI.FABBOCC.SEDE', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.AZI.FABBOCC.UTENTEDATORE', E'Fabbisogni occupazionali relativi all''utente Azienda', E'Fabbisogni occupazionali relativi all''utente Azienda', E'ST.AZI.FABBOCC.UTENTEDATORE', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.AZI.FABBOCC.UTENTESEDE', E'Fabbisogni occupazionali relativi all''utente sede Azienda', E'Fabbisogni occupazionali relativi all''utente sede Azienda', E'ST.AZI.FABBOCC.UTENTESEDE', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.AZI.GESTENTECOMP', E'Gestione Ente di Competenza - Azienda', E'Gestione Ente di Competenza - Azienda', E'ST.AZI.GESTENTECOMP', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.AZI.GESTENTECOMP.LSTENTI', E'Lista Enti di Competenza', E'Lista Enti di Competenza', E'ST.AZI.GESTENTECOMP.LSTENTI', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.AZI.INSAZI', E'Inserimento Azienda', E'Inserimento Azienda', E'ST.AZI.INSAZI', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.AZI.MENU', E'Strumento che rappresenta il nodo di primo livello per GESTIONE IMPRESA', E'Menu GESTIONE IMPRESA', E'ST.AZI.MENU', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.AZI.MODAZI', E'Modifica dati relativi all''Azienda', E'Modifica dati relativi all''Azienda', E'ST.AZI.MODAZI', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.AZI.MODAZI.SEDE', E'Modifica dati relativi alla sede di lavoro', E'Modifica dati relativi alla sede di lavoro', E'ST.AZI.MODAZI', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.AZI.MODAZI.UTENTEDATORE', E'Modifica dati relativi all''utente Azienda', E'Modifica dati relativi all''utente Azienda', E'ST.IMP.RICIMP', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.AZI.MODAZI.UTENTESEDE', E'Modifica dati relativi all''utente sede Azienda', E'Modifica dati relativi all''utente sede Azienda', E'ST.AZI.MODAZI.UTENTESEDE', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.AZIREG.MENU', E'menu'' dell''azienda ospite', E'menu'' dell''azienda ospite', E'ST.AZIREG.MENU', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.AZI.RICAZI', E'Ricerca Azienda', E'Ricerca Azienda', E'ST.AZI.RICAZI', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.AZI.RICSEDLAV', E'Ricerca Sedi di Lavoro di Aziende', E'Ricerca Sedi di Lavoro di Aziende', E'ST.AZI.RICSEDLAV', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.AZI.SCHEDA', E'SCHEDA AZIENDA', E'SCHEDA AZIENDA', E'ST.AZI.SCHEDA', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.AZI.SERVIZI', E'Servizi relativi all''Azienda', E'Servizi relativi all''Azienda', E'ST.AZI.SERVIZI', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.AZI.SERVIZI.SEDE', E'Servizi relativi alla sede Azienda', E'Servizi relativi alla sede Azienda', E'ST.AZI.SERVIZI.SEDE', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.AZI.SERVIZI.UTENTEDATORE', E'Servizi relativi all''utente Azienda', E'Servizi relativi all''utente Azienda', E'ST.AZI.SERVIZI.UTENTEDATORE', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.AZI.SERVIZI.UTENTESEDE', E'Servizi relativi all''utente Azienda', E'Servizi relativi all''utente Azienda', E'ST.AZI.SERVIZI.UTENTESEDE', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.AZI.VISAZI', E'Visualizza dati relativi all''Azienda', E'Visualizza dati relativi all''Azienda', E'ST.AZI.VISAZI', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.AZI.VISAZI.SEDE', E'Visualizza dati relativi alla sede di lavoro', E'Visualizza dati relativi alla sede di lavoro', E'ST.AZI.VISAZI', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.AZI.VISAZI.UTENTEDATORE', E'Visualizza dati relativi all''utente Azienda', E'Visualizza dati relativi all''utente Azienda', E'ST.AZI.VISAZI.UTENTEDATORE', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.AZI.VISAZI.UTENTESEDE', E'Visualizza dati relativi all''utente sede Azienda', E'Visualizza dati relativi all''utente sede Azienda', E'ST.AZI.VISAZI.UTENTESEDE', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.A16.GENRICH', E'Genera Richiesta', E'Genera Richiesta', E'ST.A16.GENRICH', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.A16.GSTCAND', E'Gestisci Candidato', E'Gestisci Candidato', E'ST.A16.GSTCAND', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.A16.MENU', E'Strumento che rappresenta il nodo di primo livello per ARTICOLO16', E'Menu ARTICOLO16', E'ST.A16.MENU', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.A16.RICRICH', E'Ricerca Richiesta', E'Ricerca Richiesta', E'ST.A16.RICRICH', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.A16.VISESCL', E'Visualizza Esclusi', E'Visualizza Esclusi', E'ST.A16.VISESCL', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.A16.VISGRAD', E'Visualizza Graduatoria', E'Visualizza Graduatoria', E'ST.A16.VISGRAD', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.A16.VISMODTRASM', E'Visualizza Modulo Trasmissione', E'Visualizza Modulo Trasmissione', E'ST.A16.VISMODTRASM', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.COB.COMOBB.MENU', E'Strumento che rappresenta il nodo di secondo livello COMUNICAZIONI OBBLIGATORIE', E'SottoMenu COMUNICAZIONI OBBLIGATORIE', E'ST.COB.COMOBB.MENU', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.FAD.SGRDOCS', E'Documenti di Segreteria', E'Documenti di Segreteria', E'ST.FAD.SGRDOCS', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.COB.COMUFF.DROP', E'Servizio per l''eliminazione fisica delle comunicazioni d''ufficio', E'Elimina Com Ufficio', E'ST.COB.COMUFF.DROP', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.COB.COMUFF.MENU', E'Strumento che rappresenta il nodo di secondo livello COMUNICAZIONI D''UFFICIO', E'SottoMenu COMUNICAZIONI D''UFFICIO', E'ST.COB.COMUFF.MENU', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.COB.COMUFF.RICCOB', E'Strumento per la ricerca delle comunicazioni d''ufficio già gestite', E'Ricerca Com Ufficio', E'ST.COB.COMUFF.RICCOB', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.LAV.TRALAV', E'Trasferimento Lavoratore tra CPI nell''ambito della stessa Regione', E'Trasferimento Lavoratore tra CPI nell''ambito della stessa Regione', E'ST.LAV.TRALAV', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.LAV.UNI', E'CRITERIO RICERCA UNIVERSITA', E'CRITERIO RICERCA UNIVERSITA', E'ST.LAV.UNI', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.LAV.VISCERTCOMP', E'Visualizzazione Certificato Competenze', E'Visualizzazione Certificato Competenze', E'ST.LAV.VISCERTCOMP', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.LAV.VISCV', E'Visualizzazione Curriculum Vitae del Lavoratore', E'Visualizzazione Curriculum Vitae del Lavoratore', E'ST.LAV.VISCV', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.LAV.VISCV.OPEAMMIN', E'Visualizzazione curriculum per utente plus.amministratore', E'Visualizzazione curriculum per utente plus.amministratore', E'ST.LAV.VISCV.OPEAMMIN', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.LAV.VISCV.USER', E'Visualizzazione curriculum per utente plus.user', E'Visualizzazione curriculum per utente plus.user', E'ST.LAV.VISCV', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.LAV.VISFAS', E'Visualizzazione Fascicolo Personale del Lavoratore', E'Visualizzazione Fascicolo Personale del Lavoratore', E'ST.LAV.VISFAS', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.LAV.VISFAS.OPEAMMIN', E'Visualizzazione fascicolo personale per utente plus.amministratore', E'Visualizzazione fascicolo personale per utente plus.amministratore', E'ST.LAV.VISFAS.OPEAMMIN', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.LAV.VISFAS.USER', E'Visualizzazione fascicolo personale per utente plus.user', E'Visualizzazione fascicolo personale per utente plus.user', E'ST.LAV.VISFAS', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.LAV.VISLIBFORM', E'Viene visualizzato il dettaglio del libretto formativo del lavoratore', E'Viene visualizzato il dettaglio del libretto formativo del lavoratore', E'ST.LAV.VISLIBFORM', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.LAV.VISLISTAMOBILITA', E'visualizza lista mobilita del lavoratore', E'visualizza lista mobilita del lavoratore', E'ST.LAV.VISLISTAMOBILITA', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.LAV.VISSAP', E'Visualizzazione della Scheda Anagrafico-Professionale di un lavoratore', E'Visualizzazione della Scheda Anagrafico-Professionale di un lavoratore', E'ST.LAV.VISSAP', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.LAV.VISSAP.USER', E'SERVIZIO DI PROVA PER LA VISUALIZZAZIONE DELLA SCHEDA UTENTE', E'SERVIZIO DI PROVA PER LA VISUALIZZAZIONE DELLA SCHEDA UTENTE', E'ST.LAV.VISSAP', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.LAV.VISSTAMPELIBFORM', E'Elenco stampe del libretto formativo', E'Elenco stampe del libretto formativo', E'ST.LAV.VISSTAMPELIBFORM', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.LINKUTILI.MENU', E'Collegamento a Banche dati utili all''operatore', E'Collegamento a Banche dati utili all''operatore', E'ST.LINKUTILI.MENU', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.MACROSTRUM.GESREN', E'Gestione Rendicontazione', E'Gestione Rendicontazione', E'ST.MACROSTRUM.GESREN', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.MIS.GESCON', E'Gestione convocazioni', E'Gestione convocazioni', E'ST.MIS.GESCON', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.MIS.GESPAI', E'Gestione PAI (Piano di Azione Individuale)', E'Gestione PAI (Piano di Azione Individuale)', E'ST.MIS.GESPAI', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.MIS.GESPAI.LSTAZIONI', E'Lista Azioni PAI', E'Lista Azioni PAI', E'ST.MIS.GESPAI.LSTAZIONI', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.MIS.GESTEMPLATE', E'Gestione Template PAI', E'Gestione Template PAI', E'ST.MIS.GESTEMPLATE', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.MIS.MENU', E'Strumento che rappresenta il nodo per MISURE', E'Menu MISURE', E'ST.MIS.MENU', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.MIS.STAMPACON', E'stampa convocazione', E'stampa convocazione', E'ST.MIS.STAMPACON', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.ORI.ALIPCM', E'Alimentazione Portafoglio Competenze', E'Alimentazione Portafoglio Competenze', E'ST.ORI.ALIPCM', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.ORI.BILPSS.MENU', E'Strumento che rappresenta il nodo per BILANCIO PROSSIMITA', E'Menu BILANCIO PROSSIMITA', E'ST.ORI.BILPSS.MENU', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.ORI.CANBILPSS', E'Cancelllazione di un Bilancio di Prossimità', E'Cancelllazione di un Bilancio di Prossimità', E'ST.ORI.CANBILPSS', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.ORI.ELABILPSS', E'Elaborazione del Bilancio di Prossimità', E'Elaborazione del Bilancio di Prossimità', E'ST.ORI.ELABILPSS', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.ORI.MENU', E'Strumento che rappresenta il nodo per ORIENTAMENTO', E'Menu ORIENTAMENTO', E'ST.ORI.MENU', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.ORI.PCM.MENU', E'Strumento che rappresenta il nodo per PORTAFOGLIO COMPETENZE', E'Menu PORTAFOGLIO COMPETENZE', E'ST.ORI.PCM.MENU', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.ORI.VISBILPSS', E'Visualizzazione e stampa del Bilancio di Prossimità', E'Visualizzazione e stampa del Bilancio di Prossimità', E'ST.ORI.VISBILPSS', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.ORI.VISBILPSS.USER', E'Bilancio Prossimita Studente', E'Bilancio Prossimita Studente-User', E'ST.ORI.VISBILPSS', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.ORI.VISPCM', E'Visualizzazione e stampa Portafoglio Competenze', E'Visualizzazione e stampa Portafoglio Competenze', E'ST.ORI.VISPCM', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.ORI.VISPCM.USER', E'Bilancio Prossimità Studente-User', E'Bilancio Prossimità Studente-User', E'ST.ORI.VISPCM', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.OSPITE.REGUTENTE', E'registrazione dell''utente ospite', E'registrazione dell''utente ospite', E'ST.OSPITE.REGUTENTE', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.OSPITE.REGUTENTE.MENU', E'menu'' di registrazione dell''ospite', E'menu'' di registrazione dell''ospite', E'ST.OSPITE.REGUTENTE', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.PA.ACCERTAMENTODPCM', E'Accertamento disabilita'' d.p.c.m.', E'Accertamento disabilita'' d.p.c.m.', E'ST.PA.ACCERTAMENTODPCM', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.PA.ACCOGL', E'Accoglienza', E'Accoglienza', E'ST.PA.ACCOGL', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.PA.ATTORESTRINT', E'Inserimento e modifica di un attore di Strutture Interventi', E'Inserimento e modifica di un attore di Strutture Interventi', E'ST.PA.ATTORESTRINT', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.PA.CCO.STAMPA', E'Stampa del Certificato di Competenze', E'Stampa del Certificato di Competenze', E'ST.PA.CCO.STAMPA', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.PA.COLLOBBL', E'Collocamento Obbligatorio', E'Collocamento Obbligatorio', E'ST.PA.COLLOBBL', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.PA.COLLPA', E'Collocamento PA', E'Collocamento PA', E'ST.PA.COLLPA', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.PA.DISPASSIST', E'Disponibilita'' tipo assistenza', E'Disponibilita'' tipo assistenza', E'ST.PA.DISPASSIST', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.PA.DISPASSTEMP', E'Gestione disponibilita'' al tipo di assistenza e disponibilita'' temporale', E'Gestione disponibilita'' al tipo di assistenza e disponibilita'' temporale', E'ST.PA.DISPASSTEMP', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.PA.DISPINT', E'Disponibilita interventi', E'Disponibilita interventi', E'ST.PA.DISPINT', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.PA.DISPTEMP', E'Gestione disponibilita'' temporale', E'Gestione disponibilita'' temporale', E'ST.PA.DISPTEMP', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.PA.DLFABBOCC', E'Fabbisogni occupazionali', E'Fabbisogni occupazionali', E'ST.PA.DLFABBOCC', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.IMP.RICSEDI', E'Ricerca Sedi Impresa', E'Ricerca Sedi Impresa', E'ST.IMP.RICSEDI', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.IMP.RICTRASMESSI', E'Ricerca elenchi lavoratori trasmessi', E'Ricerca trasmessi', E'ST.IMP.RICTRASMESSI', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.INT.IST.AUP.MENU', E'Strumento che rappresenta il nodo di secondo livello GESTIONE AULE IN PRESENZA', E'SottoMenu GESTIONE AULE IN PRESENZA', E'ST.INT.IST.AUP.MENU', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.INT.IST.NEWAUP', E'Strumento per la creazione di aule in presenza nel modulo interventi', E'Nuova aula in presenza (modulo interventi)', E'ST.INT.IST', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.INT.IST.NEWSEM', E'Strumento per la creazione di un nuovo seminario nel modulo interventi', E'Nuovo seminario (modulo interventi)', E'ST.INT.IST', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.INT.IST.NEWTIR', E'Strumento per la creazione di un nuovo tirocinio nel modulo interventi', E'Nuovo tirocinio (modulo interventi)', E'ST.INT.IST', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.INT.IST.NEWTIR.DOMANDA', E'Strumento per la creazione nuovo tirocinio nel modulo interventi con azienda selezionata', E'Nuovo tirocinio (modulo interventi, azienda selezionata)', E'ST.INT.IST', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.INT.IST.NEWTIR.DOMANDA.SEDE', E'Strumento per la creazione nuovo tirocinio nel modulo interventi con sede selezionata', E'Nuovo tirocinio (modulo interventi, sede selezionata)', E'ST.INT.IST', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.INT.IST.RICAUP', E'Strumento per la ricerca  di aule in presenza nel modulo interventi', E'Ricerca aule in presenza (modulo interventi)', E'ST.INT.IST', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.INT.IST.RICAUP.OFFERTA', E'Strumento per la ricerca di aule in presenza nel modulo interventi con lavoratore selezionato', E'Ricerca aule in presenza (modulo interventi, lavoratore selezionato)', E'ST.INT.IST', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.INT.IST.RICSEM', E'Strumento per la ricerca dei seminari nel modulo interventi', E'Ricerca seminari (modulo interventi)', E'ST.INT.IST', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.INT.IST.RICSEM.OFFERTA', E'Strumento per la ricerca dei seminari nel modulo interventi con lavoratore selezionato', E'Ricerca seminari (modulo interventi, lavoratore selezionato)', E'ST.INT.IST', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.INT.IST.RICTIR', E'Strumento per la ricerca dei tirocini nel modulo interventi', E'Ricerca tirocini (modulo interventi)', E'ST.INT.IST', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.INT.IST.RICTIR.DOMANDA', E'Strumento per la ricerca dei tirocini nel modulo interventi con azienda selezionata', E'Ricerca tirocini (modulo interventi, azienda selezionata)', E'ST.INT.IST', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.INT.IST.RICTIR.DOMANDA.SEDE', E'Strumento per la ricerca dei tirocini nel modulo interventi con sede selezionata', E'Ricerca tirocini (modulo interventi, sede selezionata)', E'ST.INT.IST', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.INT.IST.RICTIR.OFFERTA', E'Strumento per la ricerca dei tirocini nel modulo interventi con lavoratore selezionato', E'Ricerca tirocini (modulo interventi, lavoratore selezionato)', E'ST.INT.IST', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.INT.IST.RICTIR.USER.AZIENDA', E'Strumento per la ricerca dei tirocini nel modulo interventi con utente azienda', E'Ricerca tirocini (modulo interventi, utente azienda)', E'ST.INT.IST', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.INT.IST.RICTIR.USER.SEDE', E'Strumento per la ricerca dei tirocini nel modulo interventi con utente sede', E'Ricerca tirocini (modulo interventi, utente sede)', E'ST.INT.IST', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.INT.IST.SEM.MENU', E'Menu gestione seminari', E'Menu gestione seminari', E'ST.INT.IST.SEM.MENU', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.INT.IST.TIR.MENU', E'Strumento che rappresenta il nodo di secondo livello GESTIONE TIROCINI', E'SottoMenu GESTIONE TIROCINI', E'ST.INT.IST.TIR.MENU', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.INT.IST.VISRICAUP', E'Strumento per la ricerca (sola visualizzazione) di aule in presenza nel modulo interventi', E'Ricerca aule in presenza (visualizzazione, modulo interventi)', E'ST.INT.IST', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.INT.IST.VISRICAUP.OFFERTA', E'Strumento per la ricerca (sola visualizzazione) di aule in presenza nel modulo interventi con lavoratore selezionato', E'Ricerca aule in presenza (visualizzazione, modulo interventi, lavoratore selezionato)', E'ST.INT.IST', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.INT.IST.VISRICSEM', E'Strumento per la ricerca (sola visualizzazione) dei seminari nel modulo interventi', E'Ricerca seminari (visualizzazione, modulo interventi)', E'ST.INT.IST', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.INT.IST.VISRICSEM.OFFERTA', E'Strumento per la ricerca (sola visualizzazione) dei seminari nel modulo interventi con lavoratore selezionato', E'Ricerca seminari (visualizzazione, modulo interventi, lavoratore selezionato)', E'ST.INT.IST', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.INT.IST.VISRICTIR', E'Strumento per la ricerca (sola visualizzazione) dei tirocini nel modulo interventi', E'Ricerca tirocini (visualizzazione, modulo interventi)', E'ST.INT.IST', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.INT.IST.VISRICTIR.DOMANDA', E'Strumento per la ricerca (sola visualizzazione) dei tirocini nel modulo interventi con azienda selezionata', E'Ricerca tirocini (visualizzazione, modulo interventi, azienda selezionata)', E'ST.INT.IST', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.INT.IST.VISRICTIR.DOMANDA.SEDE', E'Strumento per la ricerca (sola visualizzazione) dei tirocini nel modulo interventi con sede selezionata', E'Ricerca tirocini (visualizzazione, modulo interventi, sede selezionata)', E'ST.INT.IST', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.INT.IST.VISRICTIR.OFFERTA', E'Strumento per la ricerca (sola visualizzazione) dei tirocini nel modulo interventi con lavoratore selezionato', E'Ricerca tirocini (visualizzazione, modulo interventi, lavoratore selezionato)', E'ST.INT.IST', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.INT.IST.VISRICTIR.USER.AZIENDA', E'Strumento per la ricerca (sola visualizzazione) dei tirocini nel modulo interventi con utente azienda', E'Ricerca tirocini (visualizzazione, modulo interventi, utente azienda)', E'ST.INT.IST', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.INT.IST.VISRICTIR.USER.SEDE', E'Strumento per la ricerca (sola visualizzazione) dei tirocini nel modulo interventi con utente sede', E'Ricerca tirocini (visualizzazione, modulo interventi, utente sede)', E'ST.INT.IST', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.INT.IST.VISRICTIR.USER.USER', E'Strumento per la ricerca (sola visualizzazione) dei tirocini nel modulo interventi con utente user', E'Ricerca tirocini (visualizzazione, modulo interventi, utente user)', E'ST.INT.IST', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.INT.ISTVISRICTIR.USER.USER', E'Ricerca Tirocinio', E'Ricerca Tirocinio', E'ST.INT.ISTVISRICTIR.USER.USER', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.INT.MENU', E'Strumento che rappresenta il nodo INTERVENTI', E'SottoMenu INTERVENTI', E'ST.INT.MENU', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.INT.STRINT.GSTSTRINT', E'Strumento per la gestione strutture intervento', E'Gestione strutture intervento', E'ST.INT.STRINT.GSTSTRINT', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.INT.STRINT.MENU', E'Strumento che rappresenta il nodo di secondo livello GESTIONE STRUTTURA INTERVENTI', E'SottoMenu GESTIONE STRUTTURA INTERVENTI', E'ST.INT.STRINT.MENU', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.INT.STRINT.VISSTRINT', E'Servzio per la visualizzazione delle strutture intervento', E'Visualizzazione strutture intervento', E'ST.INT.STRINT.VISSTRINT', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.JPLUS.INCR', E'Collegamento all''incrocio JPLUS', E'Collegamento all''incrocio JPLUS', E'ST.JPLUS.INCR', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.JPLUS.ISCR', E'Collegamento Gestione Iscrizione JPLUS', E'Collegamento Gestione Iscrizione JPLUS', E'ST.JPLUS.ISCR', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.JPLUS.PAGAMENTI', E'Collegamento Gestione Dati Pagamenti JPLUS', E'Collegamento Gestione Dati Pagamenti JPLUS', E'ST.JPLUS.PAGAMENTI', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.JPLUS.STAT', E'Collegamento alle statistiche JPLUS', E'Collegamento alle statistiche JPLUS', E'ST.JPLUS.STAT', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.LAV.ANNULLACANCLAV', E'Annulla cancellazione logica lavoratore', E'Annulla cancellazione logica lavoratore', E'ST.LAV.ANNULLACANCLAV', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.LAV.CPI', E'CRITERIO RICERCA CPI', E'CRITERIO RICERCA CPI', E'ST.LAV.CPI', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.LAV.CTXSAP', E'Lavoratore contesto', E'Lavoratore contesto', E'ST.LAV.CTXSAP', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.LAV.DID', E'Gestione Dichiarazione di Immediata Disponibilità', E'Gestione Dichiarazione di Immediata Disponibilità', E'ST.LAV.DID', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.LAV.DIS.COLLMIR', E'Collocamento Mirato', E'Collocamento Mirato', E'ST.LAV.DIS.COLLMIR', NULL, NULL, NULL, E'ICF', NOW(), NULL),
  (E'SV.LAV.DIS.SEZC', E'Disabili Sezione C', E'Disabili Sezione C', E'ST.LAV.DIS.SEZC', NULL, NULL, NULL, E'ICF', NOW(), NULL),
  (E'SV.LAV.DIS.SEZD', E'Disabili Sezione D', E'Disabili Sezione D', E'ST.LAV.DIS.SEZD', NULL, NULL, NULL, E'ICF', NOW(), NULL),
  (E'SV.LAV.DIS.SEZE', E'Disabili Sezione E', E'Disabili Sezione E', E'ST.LAV.DIS.SEZE', NULL, NULL, NULL, E'ICF', NOW(), NULL),
  (E'SV.LAV.DIS.SEZF', E'Disabili Sezione F', E'Disabili Sezione F', E'ST.LAV.DIS.SEZF', NULL, NULL, NULL, E'ICF', NOW(), NULL),
  (E'SV.LAV.DIS.SEZG', E'Disabili Sezione G', E'Disabili Sezione G', E'ST.LAV.DIS.SEZG', NULL, NULL, NULL, E'ICF', NOW(), NULL),
  (E'SV.LAV.DIS.SEZH', E'Disabili Sezione H', E'Disabili Sezione H', E'ST.LAV.DIS.SEZH', NULL, NULL, NULL, E'ICF', NOW(), NULL),
  (E'SV.LAV.DIS.SEZH1', E'Disabili Sezione H1', E'Disabili Sezione H1', E'ST.LAV.DIS.SEZH1', NULL, NULL, NULL, E'ICF', NOW(), NULL),
  (E'SV.LAV.DIS.SEZH2', E'Disabili Sezione H2', E'Disabili Sezione H2', E'ST.LAV.DIS.SEZH2', NULL, NULL, NULL, E'ICF', NOW(), NULL),
  (E'SV.LAV.DIS.SEZI', E'Disabili Sezione I', E'Disabili Sezione I', E'ST.LAV.DIS.SEZI', NULL, NULL, NULL, E'ICF', NOW(), NULL),
  (E'SV.LAV.DIS.SEZL', E'Disabili Sezione L', E'Disabili Sezione L', E'ST.LAV.DIS.SEZL', NULL, NULL, NULL, E'ICF', NOW(), NULL),
  (E'SV.LAV.DIS.SEZM', E'Disabili Sezione M', E'Disabili Sezione M', E'ST.LAV.DIS.SEZM', NULL, NULL, NULL, E'ICF', NOW(), NULL),
  (E'SV.LAV.DIS.SINTPROT', E'Sintesi Protocollo Lavoratore', E'Sintesi Protocollo Lavoratore', E'ST.LAV.DIS.SINTPROT', NULL, NULL, NULL, E'ICF', NOW(), NULL),
  (E'SV.LAV.ELILAV', E'Cancellazione fisica delle informazioni di un lavoratore (uso amministratore)', E'Cancellazione fisica delle informazioni di un lavoratore (uso amministratore)', E'ST.LAV.ELILAV', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.LAV.ELIMINA.VISSAP', E'Visualizzazione SAP in elimina persona', E'Visualizzazione SAP in elimina persona', E'ST.LAV.VISSAP', NULL, NULL, NULL, E'MANUALE', NOW(), NULL),
  (E'SV.LAV.ESPSTUDIO', E'Esperienze di studio del lavoratore', E'Esperienze di studio del lavoratore', E'ST.LAV.ESPSTUDIO', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.LAV.FASCICOLO', E'Ricerca lavoratore x visualizzare fascicolo', E'Ricerca lavoratore x visualizzare fascicolo', E'ST.LAV.VISFAS', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.LAV.GESPIANO', E'Servizio Gestione Piano', E'Servizio Gestione Piano', E'ST.LAV.GESPIANO', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.LAV.GESTENTECOMP', E'Gestione Ente di Competenza', E'Gestione Ente di Competenza', E'ST.LAV.GESTENTECOMP', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.LAV.GESTENTECOMP.LSTENTI', E'Lista Enti di Competenza', E'Lista Enti di Competenza', E'ST.LAV.GESTENTECOMP.LSTENTI', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.LAV.GESTLAV', E'Ricerca Lavoratore', E'Ricerca Lavoratore', E'ST.LAV.GESTLAV', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.LAV.INSLAV', E'Inserimento Lavoratore', E'Inserimento Lavoratore', E'ST.LAV.INSLAV', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.LAV.INSLAV.MENU', E'Menu Inserisci Lavoratore', E'Menu Inserisci Lavoratore', E'ST.LAV.INSLAV', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.LAV.MENU', E'Strumento che rappresenta il nodo di primo livello per GESTIONE LAVORATORE', E'Menu GESTIONE LAVORATORE', E'ST.LAV.MENU', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.LAV.MOBILITA', E'mobilita', E'mobilita', E'ST.LAV.MOBILITA', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.LAV.MODSAP', E'Modifica della Scheda Anagrafico-Professionale di un lavoratore', E'Modifica della Scheda Anagrafico-Professionale di un lavoratore', E'ST.LAV.MODSAP', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.LAV.MODSAP.USER', E'SERVIZIO DI PROVA PER LA MODIFICA DELLA SCHEDA UTENTE', E'SERVIZIO DI PROVA PER LA MODIFICA DELLA SCHEDA UTENTE', E'ST.LAV.MODSAP', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.LAV.NAZ', E'CRITERIO RICERCA NAZIONE', E'CRITERIO RICERCA NAZIONE', E'ST.LAV.NAZ', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.LAV.OFFERTA.MENU', E'Menu offerta per il lavoratore', E'Menu offerta per il lavoratore', E'ST.LAV.OFFERTA.MENU', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.LAV.OFFERTA.RICLAV', E'Ricerca lavoratore', E'Ricerca lavoratore', E'ST.LAV.OFFERTA.RICLAV', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.LAV.OFFERTA.RICLAVEXTRAREG', E'Ricerca extra regionali', E'Ricerca extra regionali', E'ST.LAV.OFFERTA.RICLAVEXTRAREG', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.LAV.PATTOSERV', E'Lista Patti di Servizio', E'Lista Patti di Servizio', E'ST.LAV.PATTOSERV', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.LAV.PATTOSERV.LSTPATTI', E'Lista Patti di Servizio', E'Lista Patti di Servizio', E'ST.LAV.PATTOSERV.LSTPATTI', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.LAV.PATTOSERV.PATTO', E'Gestione Patti di Servizio', E'Gestione Patti di Servizio', E'ST.LAV.PATTOSERV.PATTO', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.LAV.PATTOSERV.RIFIUTO', E'Gestione Rifiuti Patto di Servizio', E'Gestione Rifiuti Patto di Servizio', E'ST.LAV.PATTOSERV.RIFIUTO', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.LAV.PERS', E'CRITERIO RICERCA PERSONALI', E'CRITERIO RICERCA PERSONALI', E'ST.LAV.PERS', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.LAV.PROFILOSINTESI', E'profilo di sintesi', E'profilo di sintesi', E'ST.LAV.PROFILOSINTESI', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.LAV.PROV', E'CRITERIO RICERCA PROVINCIA', E'CRITERIO RICERCA PROVINCIA', E'ST.LAV.PROV', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.LAV.REG', E'CRITERIO RICERCA REGIONE', E'CRITERIO RICERCA REGIONE', E'ST.LAV.REG', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.LAV.REGUTENTE', E'Inserimento Lavoratore (Registrazione)', E'Inserimento Lavoratore (Registrazione)', E'ST.LAV.INSLAV', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.LAV.RICAVA.RDBAMBITI', E'CRITERIO RICERCA RadioButton', E'CRITERIO RICERCA RadioButton', E'ST.LAV.RICAVA.RDBAMBITI', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.LAV.RICFASCICOLOLAV', E'Ricerca fascicolo personale di un iscritto al progetto. Comprende anche i fuoriusciti dal bacino', E'Ricerca fascicolo personale di un iscritto al progetto. Comprende anche i fuoriusciti dal bacino', E'ST.LAV.RICFASCICOLOLAV', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.LAV.RICLAV', E'Ricerca Lavoratore', E'Ricerca Lavoratore', E'ST.LAV.RICLAV', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.LAV.RICLAVA', E'Ricerca Avanzata Lavoratore', E'Ricerca Avanzata Lavoratore', E'ST.LAV.RICLAVA', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.LAV.RICLAVDIS', E'Comunica a Pegaso', E'Comunica a Pegaso', E'ST.LAV.RICLAVDIS', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.LAV.RICLAVEXTRAREG', E'Ricerca Lavoratori Extra-Regionali', E'Ricerca Lavoratori Extra-Regionali', E'ST.LAV.RICLAVEXTRAREG', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.LAV.SCHEDA', E'SCHEDA AP', E'SCHEDA AP', E'ST.LAV.SCHEDA', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.LAV.SOSP', E'Servizio che rappresenta il nodo di secondo livello GESTIONE SOSPENSIONI', E'SottoMenu GESTIONE SOSPENSIONI', E'ST.LAV.SOSP', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.LAV.SOSP.GEST', E'Servizio per la gestione sospensione rapporto di lavoro attivo a TI', E'Gestisci sospensione', E'ST.LAV.SOSP.GEST', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.LAV.SOSP.INS', E'Servizio per l''inserimento sospensione rapporto di lavoro attivo a TI', E'Inserisci sospensione', E'ST.LAV.SOSP.INS', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.COB.COMUFF.VISNEW', E'Strumento per la visualizzazione delle comunicazioni d''ufficio non ancora gestite', E'Nuove Com Ufficio', E'ST.COB.COMUFF.VISNEW', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.COB.DELCOMOBB', E'Elimina Comunicazione Obbligatoria', E'Elimina Comunicazione Obbligatoria', E'ST.COB.DELCOMOBB', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.COB.INSCOMOBB', E'Inserimento Comunicazione Obbligatoria', E'Inserimento Comunicazione Obbligatoria', E'ST.COB.INSCOMOBB', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.COB.MENU', E'Strumento che rappresenta il nodo di primo livello per COMUNICAZIONI OBBLIGATORIE', E'Menu COMUNICAZIONI OBBLIGATORIE', E'ST.COB.MENU', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.COB.RICCOB', E'Ricerca di comunicazioni obbligatorie elaborate', E'Ricerca di comunicazioni obbligatorie elaborate', E'ST.COB.RICCOB', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.COB.VISNEW', E'Visualizzazione nuove comunicazioni obbligatorie', E'Visualizzazione nuove comunicazioni obbligatorie', E'ST.COB.VISNEW', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.CONTESTO.FAD.BIBL', E'Analisi Contesto', E'Analisi Contesto', E'ST.FAD.BIBL', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.CONV.INSSOGPROM', E'Inserimento soggetto promotore', E'Inserimento soggetto promotore', E'ST.CONV.GESSOGPROM', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.CONV.MODSOGPROM', E'Modifica soggetto promotore', E'Modifica soggetto promotore', E'ST.CONV.GESSOGPROM', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.CONV.RICSOGPROM', E'Ricerca soggetto promotore', E'Ricerca soggetto promotore', E'ST.CONV.GESSOGPROM', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.CPL.RICARCHIVIATI', E'Ricerca elenchi lavoratori archiviati', E'Ricerca archiviati', E'ST.CPL.RICARCHIVIATI', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.CPL.RICELENCO', E'Ricerca elenco lavoratori eccedenti', E'Ricerca elenco', E'ST.CPL.RICELENCO', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.CRIT.MENU', E'Strumento che rappresenta il nodo di CRITERI RICERCA', E'Menu CRITERI RICERCA', E'ST.CRIT.MENU', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.DOCS.FAD.BIBL', E'Documentazione', E'Documentazione', E'ST.FAD.BIBL', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.DOCS.FAD.GESDOC', E'Gestione Documentale', E'Gestione Documentale', E'ST.FAD.BIBL', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.EXT.LINK.ATECO', E'Classificazione Ateco 2007', E'Classificazione Ateco 2007', E'ST.EXT.LINK.ATECO', NULL, NULL, NULL, E'PROFILER', NOW(), NULL),
  (E'SV.EXT.LINK.BANCHEDATI', E'Linka alle banche dati', E'Linka alle banche dati', E'ST.EXT.LINK', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.EXT.LINK.CHECKCF', E'Link a sito Agenzia delle Entrate per Verifica Codice Fiscale', E'Link a sito Agenzia delle Entrate per Verifica Codice Fiscale', E'ST.EXT.LINK.CHECKCF', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.EXT.LINK.FAD', E'Link a FAD', E'Link a FAD', E'ST.EXT.LINK.FAD', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.EXT.LINK.FIGPROF', E'Classificazione Fig. Profess.', E'Classificazione Fig. Profess.', E'ST.EXT.LINK.FIGPROF', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.EXT.LINK.FORMGIU', E'Classificazione forma giuridica', E'Classificazione forma giuridica', E'ST.EXT.LINK.FORMGIU', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.EXT.LINK.ICD', E'Classificazione ICD', E'Classificazione ICD', E'ST.EXT.LINK.ICD', NULL, NULL, NULL, E'PROFILER', NOW(), NULL),
  (E'SV.EXT.LINK.ICF', E'Classificazione ICF', E'Classificazione ICF', E'ST.EXT.LINK.ICF', NULL, NULL, NULL, E'PROFILER', NOW(), NULL),
  (E'SV.FAD.ARCH', E'Archivio', E'Archivio', E'ST.FAD.ARCH', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.FAD.ARCH.SGRDOCS', E'Documenti di Segreteria archivio', E'Documenti di Segreteria archivio', E'ST.FAD.SGRDOCS', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.FAD.BIBL', E'Biblioteca', E'Biblioteca', E'ST.FAD.BIBL', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.FAD.BIBL.AREADOCUM', E'documenti area documentale', E'documenti area documentale', E'ST.FAD.BIBL.AREADOCUM', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.FAD.CALEFAD', E'Calendario FAD', E'Calendario FAD', E'ST.FAD.CALEFAD', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.FAD.COMMAREA', E'Area Comune', E'Area Comune', E'ST.FAD.COMMAREA', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.FAD.FAQADMIN', E'FAQ ADMIN', E'FAQ ADMIN FAD', E'ST.FAD.FAQADMIN', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.FAD.FAQSGR', E'F.A.Q. Segreteria', E'F.A.Q. Segreteria FAD', E'ST.FAD.FAQSGR', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.FAD.FORUMFAD', E'Forum FAD', E'Forum FAD', E'ST.FAD.FORUMFAD', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.FAD.IMPUTE', E'Importazione Utenti', E'Importazione Utenti FAD', E'ST.FAD.IMPUTE', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.FAD.ISCRUTE', E'Iscrizione Utente', E'Iscrizione Utente FAD', E'ST.FAD.ISCRUTE', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.FAD.LAV.PERC', E'Percorsi', E'Percorsi', E'ST.FAD.PERC', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.FAD.LOA', E'Authoring', E'Authoring', E'ST.FAD.LOA', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.FAD.LSTAULE', E'Lista aule FAD', E'Lista aule FAD', E'ST.FAD.LSTAULE', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.FAD.LSTCORSI', E'Lista Corsi FAD', E'Lista Corsi FAD', E'ST.FAD.LSTCORSI', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.FAD.LSTUTENTI', E'Lista Utenti', E'Lista Utenti FAD', E'ST.FAD.LSTUTENTI', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.FAD.MONITORING', E'Report di statistiche', E'Report di statistiche', E'ST.FAD.MONITORING', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.FAD.NEWS', E'Notizie', E'Notizie FAD', E'ST.FAD.NEWS', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.FAD.PERC', E'Percorsi', E'Percorsi FAD', E'ST.FAD.PERC', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.FAD.PERCCAT', E'Catalogo Percorsi', E'Catalogo Percorsi FAD', E'ST.FAD.PERCCAT', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.FAD.PERCFOR', E'Percorsi Formativi', E'Percorsi Formativi FAD', E'ST.FAD.PERCFOR', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.FAD.PERCTMPL', E'Template Percorsi', E'Template Percorsi FAD', E'ST.FAD.PERCTMPL', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.FAD.POSTAFAD', E'Posta FAD', E'Posta FAD', E'ST.FAD.POSTAFAD', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.FAD.REMUTE', E'Rimozione Utenti', E'Rimozione Utenti', E'ST.FAD.REMUTE', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.FAD.SCHPERS', E'Scheda Personale', E'Scheda Personale FAD', E'ST.FAD.SCHPERS', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.FAD.STRCORSI', E'Struttura Corsi', E'Struttura Corsi FAD', E'ST.FAD.STRCORSI', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.FAD.STRPERC', E'Struttura Percorsi', E'Struttura Percorsi FAD', E'ST.FAD.STRPERC', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.FAD.TEST', E'Test', E'Test', E'ST.FAD.TEST', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.FONDO.INS', E'Servizio inserimento nuovo fondo', E'Servizio inserimento nuovo fondo', E'ST.FONDO.INS', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.FONDO.RIC', E'Servizio ricerca fondi', E'Servizio ricerca fondi', E'ST.FONDO.RIC', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.GESTRU.FAD.POSTAFAD', E'Posta FAD per Area Gestione RU', E'Posta FAD per Area Gestione RU', E'ST.FAD.VIRTCOMM', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.GESTRU.FAD.VIRTCOMM', E'Servizio Comunità virtuale per Area Gestione RU', E'Servizio Comunità virtuale per Area Gestione RU', E'ST.FAD.PERC', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.IMP.DOMANDA.RICIMP', E'Voce di menu Ricerca Datori Lavoro', E'Voce di menu Ricerca Datori Lavoro', E'ST.IMP.DOMANDA.RICIMP', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.IMP.DOMANDA.RICSEDI', E'Voce di menu Ricerca Sedi', E'Voce di menu Ricerca Sedi', E'ST.IMP.DOMANDA.RICSEDI', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.IMP.DROP', E'Servizio per l''eliminazione fisica del Datore Lavoro', E'Elimina Datore Lavoro', E'ST.IMP.DROP', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.IMP.FASCICOLO', E'Fascicolo Azienda', E'Fascicolo Azienda', E'ST.IMP.FASCICOLO', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.IMP.FASCICOLO.UTENTEDATORE', E'Fascicolo Azienda per l''utente di tipo Azienda Registrata', E'Fascicolo Azienda per l''utente di tipo Azienda Registrata', E'ST.IMP.FASCICOLO.UTENTEDATORE', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.IMP.INSERISCI', E'Inserisci Impresa', E'Inserisci Sedi Impresa', E'ST.IMP.INSERISCI', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.IMP.RICDELIBERATI', E'Ricerca elenchi lavoratori deliberati', E'Ricerca deliberati', E'ST.IMP.RICDELIBERATI', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.IMP.RICIMP', E'Ricerca Impresa', E'Ricerca Impresa', E'ST.IMP.RICIMP', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.PA.GESTAMMSOC', E'GestioneAmmortizzatoriSociali', E'GestioneAmmortizzatoriSociali', E'ST.PA.GESTAMMSOC', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.PA.GESTINFODESTR', E'Gestione Informazioni Destrutturate', E'Gestione Informazioni Destrutturate', E'ST.PA.GESTINFODESTR', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.PA.GESTISTINTNEWIST', E'Lista strutture intervento nuovo tirocinio', E'Lista strutture intervento', E'ST.PA.GESTISTINTNEWIST', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.PA.GESTISTINTRICIST', E'Lista strutture intervento ricerca tirocinio', E'Lista strutture intervento', E'ST.PA.GESTISTINTRICIST', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.PA.GSTAMMTZ', E'Gestione Ammortizzatori', E'Gestione Ammortizzatori', E'ST.PA.GSTAMMTZ', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.PA.GSTDOM', E'Gestione Domanda', E'Gestione Domanda', E'ST.PA.GSTDOM', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.PA.GSTMOB', E'Gestione Mobilità', E'Gestione Mobilità', E'ST.PA.GSTMOB', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.PA.INFODESTR', E'Informazioni destrutturate', E'Informazioni destrutturate', E'ST.PA.INFODESTR', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.PA.INSSTG', E'Inserisci Stage e Tirocini PA', E'Inserisci Stage e Tirocini PA', E'ST.PA.INSSTG', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.PA.INSTIRCONV', E'Strumento per l''inserimento di Convenzioni in Stage e Tirocini', E'Strumento per l''inserimento di Convenzioni in Stage e Tirocini', E'ST.PA.INSTIRCONV', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.PA.INSTIRPRG', E'Strumento per l''inserimento di Progetti in Stage e Tirocini', E'Strumento per l''inserimento di Progetti in Stage e Tirocini', E'ST.PA.INSTIRPRG', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.PA.LFO.STAMPA', E'Stampa libretto formativo', E'Stampa libretto formativo', E'ST.PA.LFO.STAMPA', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.PA.MENU', E'Strumento che rappresenta il nodo di primo livello per GESTIONE POLITICHE', E'Menu GESTIONE POLITICHE', E'ST.PA.MENU', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.PA.MODTIRCONV', E'Strumento per la modifica di Convenzioni in Stage e Tirocini', E'Strumento per la modifica di Convenzioni in Stage e Tirocini', E'ST.PA.MODTIRCONV', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.PA.MODTIRPRG', E'Strumento per la modifica di Progetti in Stage e Tirocini', E'Strumento per la modifica di Progetti in Stage e Tirocini', E'ST.PA.MODTIRPRG', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.PA.MONAMMSOC', E'Monitoraggio Ammortizzatori Sociali', E'Monitoraggio Ammortizzatori Sociali', E'ST.PA.MONAMMSOC', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.PA.NUCLEOFAM', E'Nucleo familiare', E'Nucleo familiare', E'ST.PA.NUCLEOFAM', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.PA.OBBLFORM', E'Obbligo Formativo', E'Obbligo Formativo', E'ST.PA.OBBLFORM', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.PA.ORIENTAM', E'Orientamento', E'Orientamento', E'ST.PA.ORIENTAM', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.PA.PROFILOCCUP', E'Profilo Occupabilita', E'Profilo Occupabilita', E'ST.PA.PROFILOCCUP', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.PA.PROSPINFORM', E'Prospetto informativo', E'Prospetto informativo', E'ST.PA.PROSPINFORM', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.PA.REDDSUSS', E'Redditi e Sussidi', E'Redditi e Sussidi', E'ST.PA.REDDSUSS', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.PA.RICSTG', E'Ricerca Stage e Tirocini PA', E'Ricerca Stage e Tirocini PA', E'ST.PA.RICSTG', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.PA.RICSTG.OPEAMMIN', E'Ricerca stage per utente plus.amministratore', E'Ricerca stage per utente plus.amministratore', E'ST.PA.RICSTG.OPEAMMIN', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.PA.RICSTG.UTENTEDATORE', E'Ricerca stage per utente plus.azienda', E'Ricerca stage per utente plus.azienda', E'ST.PA.RICSTG', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.PA.RICSTG.UTENTESEDE', E'ricerca stage per sede di lavoro', E'ricerca stage per sede di lavoro', E'ST.PA.RICSTG.UTENTESEDE', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.PA.RICTIR', E'Ricerca progetto (Stage e Tirocini)', E'Ricerca progetto (Stage e Tirocini)', E'ST.PA.RICTIR', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.PA.RICTIR.OPEAMMIN', E'Ricerca progetti per utente plus.amministratore', E'Ricerca progetti per utente plus.amministratore', E'ST.PA.RICTIR.OPEAMMIN', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.PA.RICTIR.UTENTEDATORE', E'Ricerca progetti per utente plus.azienda', E'Ricerca progetti per utente plus.azienda', E'ST.PA.RICTIR', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.PA.RICTIR.UTENTESEDE', E'ricerca tirocini per sede di lavoro', E'ricerca tirocini per sede di lavoro', E'ST.PA.RICTIR', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.PA.RICTIR.UTENTEUSER', E'Ricerca progetti per utente plus.user', E'Ricerca progetti per utente plus.user', E'ST.PA.RICTIR', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.PA.SCHEDA.USER', E'scheda utente del profilo USER', E'scheda utente del profilo user', E'ST.PA.SCHEDA.USER', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.PA.SCHEDA.UTENTEDATORE', E'Scheda utente', E'Scheda utente', E'ST.PA.SCHEDA.UTENTE', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.PA.SCHEDA.UTENTESEDE', E'Scheda utente', E'Scheda utente', E'ST.PA.SCHEDA.UTENTE', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.PA.SCHEDEORI', E'Schede di orientamento individuale', E'Schede di orientamento individuale', E'ST.PA.SCHEDEORI', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.PA.SERVIZIOGENERICO', E'Servizio generico di PA', E'Servizio generico di PA', E'ST.PA.SERVIZIOGENERICO', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.PA.STG.MENU', E'Strumento che rappresenta il nodo STAGE E TIROCINI', E'Menu STAGE E TIROCINI', E'ST.PA.STG.MENU', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.PA.STG.MENU.UTENTEDATORE', E'Strumento che rappresenta il nodo STAGE E TIROCINI per l''utente di tipo Azienda Registrata', E'Strumento che rappresenta il nodo STAGE E TIROCINI per l''utente di tipo Azienda Registrata', E'ST.PA.STG.MENU.UTENTEDATORE', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.PA.STG.MENU.UTENTESEDE', E'stage per sede di lavoro', E'stage per sede di lavoro', E'ST.PA.STG.MENU.UTENTESEDE', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.PA.STGTIRC', E'Stage e Tirocini', E'Stage e Tirocini', E'ST.PA.STGTIRC', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.PA.STORIAMIG', E'Storia migratoria', E'Storia migratoria', E'ST.PA.STORIAMIG', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.PA.VINCOLIAMBIENTALI', E'Vincoli Ambientali', E'Vincoli Ambientali', E'ST.PA.VINCOLIAMBIENTALI', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.PA.VISTIRCONV', E'Strumento per la visualizzazione di Convenzioni in Stage e Tirocini', E'Strumento per la visualizzazione di Convenzioni in Stage e Tirocini', E'ST.PA.VISTIRCONV', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.PA.VISTIRPRG', E'Strumento per la visualizzazione di Progetti in Stage e Tirocini', E'Strumento per la visualizzazione di Progetti in Stage e Tirocini', E'ST.PA.VISTIRPRG', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.PLUS.CRUSCOTTO', E'Cruscotto PLUS', E'Cruscotto PLUS', E'ST.PLUS.CRUSCOTTO', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.PLUS.MODPWD', E'Modifica Password', E'Modifica Password', E'ST.PLUS.MODPWD', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.POLATT.BACHECA', E'Bacheca Annunci', E'Bacheca Annunci', E'ST.POLATT.BACHECA', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.POLATT.GESTIONE', E'Gestione Annunci', E'Gestione Annunci', E'ST.POLATT.GESTIONE', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.POLATT.MENU', E'Strumento che rappresenta il nodo di primo livello per BORSA LAVORO', E'Menu BORSA LAVORO', E'ST.POLATT.MENU', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.POLATT.RICERCA', E'Ricerca Personale', E'Ricerca Personale', E'ST.POLATT.RICERCA', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.POL.STAGE', E'Stage e tirocini', E'Stage e tirocini', E'ST.POL.STAGE', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.POL.STAGE.INSCONV', E'Inserimento di una convenzione', E'Inserimento di una convenzione', E'ST.POL.STAGE.INSCONV', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.POL.STAGE.RICCONV', E'Ricerca di convenzioni', E'Ricerca di convenzioni', E'ST.POL.STAGE.RICCONV', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.REG.MENU', E'Voce Registrazione del menu orizzontale', E'Voce Registrazione del menu orizzontale', E'ST.REG.MENU', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.REG.MODPASSWORD', E'Modifica password', E'Modifica password', E'ST.REG.MODPASSWORD', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.REG.REGAZIREG', E'registrazione dell''azienda ospite', E'registrazione dell''azienda ospite', E'ST.REG.REGAZIREG', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.REG.REGDATLAV', E'Registrazione del datore di lavoro', E'Registrazione del datore di lavoro', E'ST.REG.REGDATLAV', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.REG.REGSEDEAZIREG', E'Registrazione delle sedi di lavoro per l''utente di tipo Azienda Registrata', E'Registrazione delle sedi di lavoro per l''utente di tipo Azienda Registrata', E'ST.REG.REGSEDEAZIREG', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.REG.REGSEDEDATLAV', E'Registrazione sede del datore di lavoro', E'Registrazione sede del datore di lavoro', E'ST.REG.REGSEDEDATLAV', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.RICLAV.CPI', E'Criteri di Ricerca salvati-CPI', E'Criteri di Ricerca salvati-CPI', E'ST.RICLAV.CPI', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.RICLAV.PERS', E'Criteri di Ricerca salvati-personali', E'Criteri di Ricerca salvati-personali', E'ST.RICLAV.PERS', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.RICLAV.PROV', E'Criteri di Ricerca salvati-provincia', E'Criteri di Ricerca salvati-provincia', E'ST.RICLAV.PROV', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.RICLAV.REG', E'Criteri di Ricerca salvati-regione', E'Criteri di Ricerca salvati-regione', E'ST.RICLAV.REG', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.SPC', E'Strumenti Profilazione e Configurazione', E'Strumenti Profilazione e Configurazione', E'ST.SPC.SPC', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.SPC.CREPROG', E'Crea Progetto', E'Crea Progetto', E'ST.SPC.CREPROG', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.SPC.CRESTRUTT', E'Crea Struttura Progetto', E'Crea Struttura Progetto', E'ST.SPC.CRESTRUTT', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.SPC.ELISTAT', E'ELIMINA STATITISTICHE MONITORAGGIO', E'ELIMINA STATITISTICHE MONITORAGGIO', E'ST.SPC.ELISTAT', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.SPC.EROPROG', E'Erogazione Progetto', E'Erogazione Progetto', E'ST.SPC.EROPROG', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.SPC.GSTAPPL', E'Gestione Applicazione', E'Gestione Applicazione', E'ST.SPC.GSTAPPL', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.SPC.GSTPRF', E'Gestione Profilazione', E'Gestione Profilazione', E'ST.SPC.GSTPRF', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.SPC.GSTPROFILO', E'Gestione Profilo', E'Gestione Profilo', E'ST.SPC.GSTPROFILO', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.SPC.GSTPROG', E'Gestione Progetto', E'Gestione Progetto', E'ST.SPC.GSTPROG', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.SPC.GSTSRV', E'Gestione Servizio', E'Gestione Servizio', E'ST.SPC.GSTSRV', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.SPC.GSTSTR', E'Gestione Strumento', E'Gestione Strumento', E'ST.SPC.GSTSTR', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.SPC.GSTTRG', E'Gestione Target', E'Gestione Target', E'ST.SPC.GSTTRG', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.SPC.INSREGOLA', E'Inserisci Regola', E'Inserisci Regola', E'ST.SPC.INSREGOLA', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.SPC.MONIT', E'MONITORAGGIO DEI SERVIZI', E'MONITORAGGIO DEI SERVIZI', E'ST.SPC.MONIT', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.SPC.RICPROG', E'Ricerca Progetto', E'Ricerca Progetto', E'ST.SPC.RICPROG', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.SPC.RICREGOLA', E'Ricerca Regola', E'Ricerca Regola', E'ST.SPC.RICREGOLA', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.SPC.RICSTRUTT', E'Ricerca Struttura Progetto', E'Ricerca Struttura Progetto', E'ST.SPC.RICSTRUTT', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.SPC.SPC', E'Strumenti Profilazione e Configurazione', E'Strumenti Profilazione e Configurazione', E'ST.SPC.SPC', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.SPC.STRUTTPROG', E'Struttura Progetto', E'Struttura Progetto', E'ST.SPC.STRUTTPROG', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.SPC.VISSTAT', E'VIS STATITISTICHE MONITORAGGIO', E'VIS STATITISTICHE MONITORAGGIO', E'ST.SPC.VISSTAT', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.SPI.FAD.CALEFAD', E'Calendario FAD', E'Calendario FAD', E'ST.FAD.CALEFAD', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.SPI.FAD.FAQSGR', E'F.A.Q. Segreteria', E'F.A.Q. Segreteria FAD', E'ST.FAD.FAQSGR', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.SPI.FAD.NEWS', E'Notizie', E'Notizie FAD', E'ST.FAD.NEWS', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.SPI.FAD.PERC', E'Percorsi', E'Percorsi FAD', E'ST.FAD.VIRTCOMM', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.SPI.FAD.PERCFOR', E'Percorsi Formativi', E'Percorsi Formativi FAD', E'ST.FAD.PERCFOR', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.SPI.FAD.POSTAFAD', E'Posta FAD', E'Posta FAD', E'ST.FAD.POSTAFAD', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.SPI.FAD.SCHPERS', E'Scheda Personale', E'Scheda Personale FAD', E'ST.FAD.SCHPERS', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.SPI.FAD.VIRTCOMM', E'Servizio Comunità virtuale per Area direttori SPI', E'Servizio Comunità virtuale per Area direttori SPI', E'ST.FAD.POSTAFAD', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.SPI.RICELENCO', E'Ricerca Elenchi', E'Ricerca Elenchi', E'ST.SPI.RICELENCO', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.STA.MENU', E'Strumento che rappresenta il nodo di primo livello per MONITORAGGIO', E'Menu MONITORAGGIO', E'ST.STA.MENU', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.STA.REPORT', E'Report statistici', E'Report statistici', E'ST.STA.REPORT', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.STA.REPORT.MENU', E'Strumento che rappresenta il nodo per STATISTICHE', E'Menu STATISTICHE', E'ST.STA.REPORT.MENU', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.STA.REPORT.01', E'Flusso di ingresso nel Cpi: Lavoratori distinti per livello del Titolo di Studio e classe di Età', E'Flusso di ingresso nel Cpi: Lavoratori distinti per livello del Titolo di Studio e classe di Età', E'ST.STA.REPORT.01', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.STA.REPORT.02', E'Servizi richiesti al Centro per l''Impiego distinti per tipologia di Servizio e livello del Titolo di Studio ', E'Servizi richiesti al Centro per l''Impiego distinti per tipologia di Servizio e livello del Titolo di Studio ', E'ST.STA.REPORT.02', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.STA.REPORT.03', E'Candidature espresse dai Lavoratori distinte per Settore ed Area Professionale ', E'Candidature espresse dai Lavoratori distinte per Settore ed Area Professionale ', E'ST.STA.REPORT.03', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.STA.REPORT.04', E'Durata media di Disoccupazione dei Lavoratori distinta per livello del Titolo di Studio  ', E'Durata media di Disoccupazione dei Lavoratori distinta per livello del Titolo di Studio  ', E'ST.STA.REPORT.04', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.STA.REPORT.05', E'Numero di Lavoratori per durata di Disoccupazione, classi di Età e Sesso', E'Numero di Lavoratori per durata di Disoccupazione, classi di Età e Sesso', E'ST.STA.REPORT.05', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.TOOLS.RICCONV', E'Tool di ricerca convocazioni', E'Tool di ricerca convocazioni', E'ST.TOOLS.RICCONV', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.TOOLS.RICENTE', E'Tool di ricerca enti', E'Tool di ricerca enti', E'ST.TOOLS.RICENTE', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.TOOLS.RICPROMOTORE', E'Tool di ricerca promotori', E'Tool di ricerca promotori', E'ST.TOOLS.RICPROMOTORE', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.TOOLS.RICSERVCOMP', E'Ricerca dati relativi al servizio competente', E'Ricerca dati relativi al servizio competente', E'ST.TOOLS.RICSERVCOMP', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.VALUT.FAD.POSTAFAD', E'Posta FAD per Area Valutazione', E'Posta FAD per Area Valutazione', E'ST.FAD.VIRTCOMM', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.VALUT.FAD.VIRTCOMM', E'Servizio Comunità virtuale per Area Valutazione', E'Servizio Comunità virtuale per Valutazione', E'ST.FAD.POSTAFAD', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.AZI.SERVCOMP', E'Visualizza dati relativi al serivo competente dell''Azienda', E'Visualizza dati relativi al serivo competente dell''Azienda', E'ST.AZI.SERVCOMP', NULL, NULL, NULL, E'SYSTEM', NOW(), NULL),
  (E'SV.LAV.DIS.SEZB', E'Disabili Sezione B', E'Disabili Sezione B', E'ST.LAV.DIS.SEZB', NULL, NULL, NULL, E'ICF', NOW(), NULL),
  (E'SV.LAV.DIS.SEZVC', E'Disabili Verbale Conclusivo', E'Disabili Verbale Conclusivo', E'ST.LAV.DIS.SEZVC', NULL, NULL, NULL, E'ICF', NOW(), NULL);