/* Data for the 'inside_profiler.tab_strumento' table  (Records 1 - 307) */

INSERT INTO inside_profiler.tab_strumento ("cod_codicestrumento", "des_descrizione", "des_nome", "img_logo", "des_nome_logo", "des_tipo_logo", "des_url", "cod_useragg", "dtt_tmst")
VALUES 
  (E'ST.AMM.PAGAMENTI', E'Gestione Pagamenti', E'Gestione Pagamenti', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.AREADOCUM.MENU', E'voce area documentale nel Menu', E'voce area documentale nel Menu', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.AZI.ANNULLACANC', E'Annulla cancellazione logica Datore Lavoro', E'Annulla cancellazione logica  Datore Lavoro', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.AZI.CTXAZI', E'Datore lavoro contesto', E'Datore lavoro contesto', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.AZI.DELAZI', E'Eliminazione dati relativi all''Azienda', E'Eliminazione dati relativi all''Azienda', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.AZI.DELAZI.UTENTEDATORE', E'Elimina dati relativi all''utente Azienda', E'Elimina dati relativi all''utente Azienda', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.AZI.DELAZI.UTENTESEDE', E'Visualizza dati relativi all''utente sede Azienda', E'Visualizza dati relativi all''utente sede Azienda', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.AZI.DIS.INFOAGG', E'Informazioni Aggiuntive Disabili', E'Informazioni Aggiuntive Disabili', NULL, NULL, NULL, NULL, E'ICF', NOW()),
  (E'ST.AZI.DISPOINTERVENTI.DATORE', E'Disponibilita interventi azienda', E'Disponibilita interventi azienda', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.AZI.DISPOINTERVENTI.SEDE', E'Disponibilita interventi sede azienda', E'Disponibilita interventi sede azienda', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.AZI.DISPOINTERVENTI.UTENTEDATORE', E'Disponibilita interventi utente azienda', E'Disponibilita interventi utente azienda', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.AZI.DISPOINTERVENTI.UTENTESEDE', E'Disponibilita interventi utente sede azienda', E'Disponibilita interventi utente sede azienda', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.AZI.ENTEVIS', E'Visualizzazione dati relativi al servizio competente dell''Azienda', E'Visualizzazione dati relativi al servizio competente dell''Azienda', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.AZI.FABBOCC.DATORE', E'Fabbisogni occupazionali azienda', E'Fabbisogni occupazionali azienda', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.AZI.FABBOCC.SEDE', E'Fabbisogni occupazionali sede azienda', E'Fabbisogni occupazionali sede azienda', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.AZI.FABBOCC.UTENTEDATORE', E'Fabbisogni occupazionali utente azienda', E'Fabbisogni occupazionali utente azienda', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.AZI.FABBOCC.UTENTESEDE', E'Fabbisogni occupazionali utente sede azienda', E'Fabbisogni occupazionali utente sede azienda', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.AZI.GESTENTECOMP', E'Gestione Ente di Competenza - Azienda', E'Gestione Ente di Competenza - Azienda', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.AZI.GESTENTECOMP.LSTENTI', E'Lista Enti di Competenza', E'Lista Enti di Competenza', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.AZI.INSAZI', E'Inserimento Azienda', E'Inserimento Azienda', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.AZI.MENU', E'Strumento che rappresenta il nodo di primo livello per GESTIONE IMPRESA', E'Menu GESTIONE IMPRESA', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.AZI.MODAZI', E'Modifica dati relativi all''Azienda', E'Modifica dati relativi all''Azienda', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.AZI.MODAZI.UTENTEDATORE', E'Modifica dati relativi all''utente Azienda', E'Modifica dati relativi all''utente Azienda', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.AZI.MODAZI.UTENTESEDE', E'Modifica dati relativi all''utente sede Azienda', E'Modifica dati relativi all''utente sede Azienda', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.AZIREG.MENU', E'menu dell''azienda ospite', E'menu'' dell''azienda ospite', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.AZI.RICAZI', E'Ricerca Azienda', E'Ricerca Azienda', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.AZI.RICSEDLAV', E'Ricerca Sedi di Lavoro di Aziende', E'Ricerca Sedi di Lavoro di Aziende', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.AZI.SCHEDA', E'SCHEDA AZIENDA', E'SCHEDA AZIENDA', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.AZI.SERVIZI', E'Servizi relativi all''Azienda', E'Servizi relativi all''Azienda', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.AZI.SERVIZI.SEDE', E'Servizi relativi alla sede Azienda', E'Servizi relativi alla sede Azienda', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.AZI.SERVIZI.UTENTEDATORE', E'Servizi relativi all''utente Azienda', E'Servizi relativi all''utente Azienda', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.AZI.SERVIZI.UTENTESEDE', E'Servizi relativi all''utente sede Azienda', E'Servizi relativi all''utente sede Azienda', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.AZI.VISAZI', E'Visualizzazione dati relativi all''Azienda', E'Visualizzazione dati relativi all''Azienda', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.AZI.VISAZI.UTENTEDATORE', E'Visualizza dati relativi all''utente Azienda', E'Visualizza dati relativi all''utente Azienda', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.AZI.VISAZI.UTENTESEDE', E'Visualizza dati relativi all''utente sede Azienda', E'Visualizza dati relativi all''utente sede Azienda', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.A16.GENRICH', E'Genera Richiesta', E'Genera Richiesta', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.A16.GSTCAND', E'Gestisci Candidato', E'Gestisci Candidato', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.A16.MENU', E'Strumento che rappresenta il nodo di primo livello per ARTICOLO16', E'Menu ARTICOLO16', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.A16.RICRICH', E'Ricerca Richiesta', E'Ricerca Richiesta', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.A16.VISESCL', E'Visualizza Esclusi', E'Visualizza Esclusi', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.A16.VISGRAD', E'Visualizza Graduatoria', E'Visualizza Graduatoria', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.A16.VISMODTRASM', E'Visualizza Modulo Trasmissione', E'Visualizza Modulo Trasmissione', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.COB.COMOBB.MENU', E'Strumento che rappresenta il nodo di secondo livello COMUNICAZIONI OBBLIGATORIE', E'SottoMenu COMUNICAZIONI OBBLIGATORIE', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.COB.COMUFF.DROP', E'Strumento per l''eliminazione fisica delle comunicazioni d''ufficio', E'Elimina Com Ufficio', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.COB.COMUFF.MENU', E'Strumento che rappresenta il nodo di secondo livello COMUNICAZIONI D''UFFICIO', E'SottoMenu COMUNICAZIONI D''UFFICIO', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.COB.COMUFF.RICCOB', E'Strumento per la ricerca delle comunicazioni d''ufficio già gestite', E'Ricerca Com Ufficio', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.COB.COMUFF.VISNEW', E'Strumento per la visualizzazione delle comunicazioni d''ufficio non ancora gestite', E'Nuove Com Ufficio', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.COB.DELCOMOBB', E'Elimina Comunicazione Obbligatoria', E'Elimina Comunicazione Obbligatoria', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.COB.INSCOMOBB', E'Inserimento Comunicazione Obbligatoria', E'Inserimento Comunicazione Obbligatoria', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.COB.MENU', E'Strumento che rappresenta il nodo di primo livello per COMUNICAZIONI OBBLIGATORIE', E'Menu COMUNICAZIONI OBBLIGATORIE', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.COB.RICCOB', E'Ricerca di comunicazioni obbligatorie elaborate', E'Ricerca di comunicazioni obbligatorie elaborate', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.COB.VISNEW', E'Visualizzazione nuove comunicazioni obbligatorie', E'Visualizzazione nuove comunicazioni obbligatorie', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.CONV.GESSOGPROM', E'Gestione soggetto promotore', E'Gestione soggetto promotore', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.CPL.RICARCHIVIATI', E'Ricerca elenchi lavoratori archiviati', E'Ricerca archiviati', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.CPL.RICELENCO', E'Ricerca elenco lavoratori eccedenti', E'Ricerca elenco', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.CRIT.MENU', E'Strumento che rappresenta il nodo di CRITERI RICERCA', E'Menu CRITERI RICERCA', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.EXT.LINK', E'Collegamento ad altra applicazione', E'Collegamento ad altra applicazione', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.EXT.LINK.ATECO', E'Classificazione Ateco 2007', E'Classificazione Ateco 2007', NULL, NULL, NULL, NULL, E'PROFILER', NOW()),
  (E'ST.EXT.LINK.CHECKCF', E'Link a sito Agenzia delle Entrate per Verifica Codice Fiscale', E'Link a sito Agenzia delle Entrate per Verifica Codice Fiscale', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.EXT.LINK.FAD', E'Link a FAD', E'Link a FAD', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.EXT.LINK.FIGPROF', E'Classificazione Fig. Profess.', E'Classificazione Fig. Profess.', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.EXT.LINK.FORMGIU', E'Classificazione forma giuridica', E'Classificazione forma giuridica', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.EXT.LINK.ICD', E'Classificazione ICD', E'Classificazione ICD', NULL, NULL, NULL, NULL, E'PROFILER', NOW()),
  (E'ST.RICLAV.CPI', E'Criteri di Ricerca salvati-CPI', E'Criteri di Ricerca salvati-CPI', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.RICLAV.PERS', E'Criteri di Ricerca salvati-personali', E'Criteri di Ricerca salvati-personali', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.RICLAV.PROV', E'Criteri di Ricerca salvati-provincia', E'Criteri di Ricerca salvati-provincia', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.RICLAV.REG', E'Criteri di Ricerca salvati-regione', E'Criteri di Ricerca salvati-regione', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.SPC.CREPROG', E'Crea Progetto', E'Crea Progetto', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.SPC.CRESTRUTT', E'Crea Struttura Progetto', E'Crea Struttura Progetto', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.SPC.ELISTAT', E'ELIMINA STATISTICHE MONITORAGGIO', E'ELIMINA STATISTICHE MONITORAGGIO', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.SPC.EROPROG', E'Erogazione Progetto', E'Erogazione Progetto', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.SPC.GSTAPPL', E'Gestione Applicazione', E'Gestione Applicazione', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.SPC.GSTPRF', E'Gestione Profilazione', E'Gestione Profilazione', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.SPC.GSTPROFILO', E'Gestione Profilo', E'Gestione Profilo', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.SPC.GSTPROG', E'Gestione Progetto', E'Gestione Progetto', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.SPC.GSTSRV', E'Gestione Servizio', E'Gestione Servizio', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.SPC.GSTSTR', E'Gestione Strumento', E'Gestione Strumento', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.SPC.GSTTRG', E'Gestione Target', E'Gestione Target', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.SPC.INSREGOLA', E'Inserisci Regola', E'Inserisci Regola', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.SPC.MONIT', E'MONITORAGGIO DEI SERVIZI', E'MONITORAGGIO DEI SERVIZI', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.SPC.RICPROG', E'Ricerca Progetto', E'Ricerca Progetto', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.SPC.RICREGOLA', E'Ricerca Regola', E'Ricerca Regola', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.SPC.RICSTRUTT', E'Ricerca Struttura Progetto', E'Ricerca Struttura Progetto', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.SPC.SPC', E'Strumenti Profilazione e Configurazione', E'Strumenti Profilazione e Configurazione', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.SPC.STRUTTPROG', E'Struttura Progetto', E'Struttura Progetto', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.SPC.VISSTAT', E'VISUALIZZA STATISTICHE MONITORAGGIO', E'VISUALIZZA STATISTICHE MONITORAGGIO', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.SPI.RICELENCO', E'Ricerca Elenchi', E'Ricerca Elenchi', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.STA.MENU', E'Strumento che rappresenta il nodo di primo livello per MONITORAGGIO', E'Menu MONITORAGGIO', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.STA.REPORT', E'Report statistici', E'Report statistici', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.STA.REPORT.MENU', E'Strumento che rappresenta il nodo per STATISTICHE', E'Menu STATISTICHE', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.STA.REPORT.01', E'Flusso di ingresso nel Cpi: Lavoratori distinti per livello del Titolo di Studio e classe di Età', E'Flusso di ingresso nel Cpi: Lavoratori distinti per livello del Titolo di Studio e classe di Età', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.STA.REPORT.02', E'Servizi richiesti al Centro per l''Impiego distinti per tipologia di Servizio e livello del Titolo di Studio ', E'Servizi richiesti al Centro per l''Impiego distinti per tipologia di Servizio e livello del Titolo di Studio ', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.STA.REPORT.03', E'Candidature espresse dai Lavoratori distinte per Settore ed Area Professionale ', E'Candidature espresse dai Lavoratori distinte per Settore ed Area Professionale ', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.STA.REPORT.04', E'Durata media di Disoccupazione dei Lavoratori distinta per livello del Titolo di Studio  ', E'Durata media di Disoccupazione dei Lavoratori distinta per livello del Titolo di Studio  ', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.STA.REPORT.05', E'Numero di Lavoratori per durata di Disoccupazione, classi di Età e Sesso', E'Numero di Lavoratori per durata di Disoccupazione, classi di Età e Sesso', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.TOOLS.RICCONV', E'Tool di ricerca convocazioni', E'Tool di ricerca convocazioni', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.TOOLS.RICENTE', E'Tool di ricerca enti', E'Tool di ricerca enti', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.TOOLS.RICPROMOTORE', E'Tool di ricerca promotori', E'Tool di ricerca promotori', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.TOOLS.RICSERVCOMP', E'Ricerca dati relativi al servizio competente dell''Azienda', E'Ricerca dati relativi al servizio competente dell''Azienda', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.EXT.LINK.ICF', E'Classificazione ICF', E'Classificazione ICF', NULL, NULL, NULL, NULL, E'PROFILER', NOW()),
  (E'ST.FAD.ARCH', E'Archivio', E'Archivio', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.FAD.BIBL', E'Biblioteca', E'Biblioteca', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.FAD.BIBL.AREADOCUM', E'documenti area documentale', E'documenti area documentale', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.FAD.CALEFAD', E'Calendario FAD', E'Calendario FAD', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.FAD.COMMAREA', E'Area Comune', E'Area Comune', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.FAD.FAQADMIN', E'FAQ ADMIN', E'FAQ ADMIN FAD', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.FAD.FAQSGR', E'F.A.Q. Segreteria', E'F.A.Q. Segreteria FAD', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.FAD.FORUMFAD', E'Forum FAD', E'Forum FAD', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.FAD.IMPUTE', E'Importazione Utenti', E'Importazione Utenti FAD', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.FAD.ISCRUTE', E'Iscrizione Utente', E'Iscrizione Utente FAD', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.FAD.LOA', E'Authoring', E'Authoring', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.FAD.LSTAULE', E'Lista aule FAD', E'Lista aule FAD', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.FAD.LSTCORSI', E'Lista Corsi FAD', E'Lista Corsi FAD', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.FAD.LSTUTENTI', E'Lista Utenti', E'Lista Utenti FAD', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.FAD.MONITORING', E'Report di statistiche', E'Report di statistiche', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.FAD.NEWS', E'Notizie', E'Notizie FAD', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.FAD.PERC', E'Percorsi', E'Percorsi FAD', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.FAD.PERCCAT', E'Catalogo Percorsi', E'Catalogo Percorsi FAD', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.FAD.PERCFOR', E'Percorsi Formativi', E'Percorsi Formativi FAD', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.FAD.PERCTMPL', E'Template Percorsi', E'Template Percorsi FAD', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.FAD.POSTAFAD', E'Posta FAD', E'Posta FAD', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.FAD.REMUTE', E'Rimozione Utenti', E'Rimozione Utenti', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.FAD.SCHPERS', E'Scheda Personale', E'Scheda Personale FAD', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.FAD.SGRDOCS', E'Documenti di Segreteria', E'Documenti di Segreteria', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.FAD.STRCORSI', E'Struttura Corsi', E'Struttura Corsi FAD', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.FAD.STRPERC', E'Struttura Percorsi', E'Struttura Percorsi FAD', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.FAD.TEST', E'Test', E'Test', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.FAD.VIRTCOMM', E'Strumento Comunità virtuale', E'Strumento Comunità virtuale', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.FONDO.INS', E'Inserimento nuovo FONDO', E'Inserimento nuovo FONDO', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.FONDO.RIC', E'Ricerca fondi', E'Ricerca fondi', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.IMP.DOMANDA.RICIMP', E'Voce di menu Ricerca Datore di Lavoro', E'Voce di menu Ricerca Datore di Lavoro', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.IMP.DOMANDA.RICSEDI', E'Voce di menu Ricerca sedi', E'Voce di menu Ricerca sedi', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.IMP.DROP', E'Strumento per l''eliminazione fisica del Datore Lavoro', E'Elimina Datore Lavoro', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.IMP.FASCICOLO', E'Fascicolo Azienda', E'Fascicolo Azienda', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.IMP.FASCICOLO.UTENTEDATORE', E'Fascicolo Azienda per l''utente di tipo Azienda Registrata', E'Fascicolo Azienda per l''utente di tipo Azienda Registrata', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.IMP.INSERISCI', E'Inserisci Impresa', E'Inserisci Impresa', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.IMP.RICDELIBERATI', E'Ricerca elenchi lavoratori deliberati', E'Ricerca deliberati', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.IMP.RICIMP', E'Ricerca Impresa', E'Ricerca Impresa', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.IMP.RICSEDI', E'Ricerca Sedi Impresa', E'Ricerca Sedi Impresa', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.IMP.RICTRASMESSI', E'Ricerca elenchi lavoratori trasmessi', E'Ricerca trasmessi', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.LAV.VISCERTCOMP', E'Visualizzazione Certificato Competenze del lavoratore', E'Visualizzazione Certificato Competenze del lavoratore', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.LAV.VISCV', E'Visualizzazione Curriculum Vitae del Lavoratore', E'Visualizzazione Curriculum Vitae del Lavoratore', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.LAV.VISCV.OPEAMMIN', E'Visualizzazione curriculum per utente plus.amministratore', E'Visualizzazione curriculum per utente plus.amministratore', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.LAV.VISCV.USER', E'Visualizzazione curriculum per utente plus.user', E'Visualizzazione curriculum per utente plus.user', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.LAV.VISFAS', E'Visualizzazione Fascicolo Personale del Lavoratore', E'Visualizzazione Fascicolo Personale del Lavoratore', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.LAV.VISFAS.OPEAMMIN', E'Visualizzazione fascicolo personale per utente plus.amministratore', E'Visualizzazione fascicolo personale per utente plus.amministratore', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.LAV.VISFAS.USER', E'Visualizzazione fascicolo personale per utente plus.user', E'Visualizzazione fascicolo personale per utente plus.user', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.LAV.VISLIBFORM', E'Viene visualizzato il dettaglio del libretto formativo del lavoratore', E'Viene visualizzato il dettaglio del libretto formativo del lavoratore', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.LAV.VISLISTAMOBILITA', E'visualizza lista mobilita del lavoratore', E'visualizza lista mobilita del lavoratore', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.LAV.VISSAP', E'Visualizzazione della Scheda Anagrafico-Professionale di un lavoratore', E'Visualizzazione della Scheda Anagrafico-Professionale di un lavoratore', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.LAV.VISSAP.USER', E'STRUMENTO DI PROVA PER LA VISUALIZZAZIONE DELLA SCHEDA UTENTE', E'STRUMENTO DI PROVA PER LA VISUALIZZAZIONE DELLA SCHEDA UTENTE', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.LAV.VISSTAMPELIBFORM', E'Elenco stampe del libretto formativo', E'Elenco stampe del libretto formativo', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.LINKUTILI.MENU', E'Collegamento a Banche dati utili all''operatore', E'Collegamento a Banche dati utili all''operatore', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.MACROSTRUM.GESREN', E'Gestione Rendicontazione', E'Gestione Rendicontazione', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.MIS.GESCON', E'Gestione convocazioni', E'Gestione convocazioni', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.MIS.GESPAI', E'Gestione PAI (Piano di Azione Individuale)', E'Gestione PAI (Piano di Azione Individuale)', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.MIS.GESPAI.LSTAZIONI', E'Lista Azioni PAI', E'Lista Azioni PAI', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.MIS.GESTEMPLATE', E'Gestione Template PAI', E'Gestione Template PAI', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.MIS.MENU', E'Strumento che rappresenta il nodo per MISURE', E'Menu MISURE', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.MIS.STAMPACON', E'stampa convocazione', E'stampa convocazione', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.ORI.ALIPCM', E'Alimentazione Portafoglio Competenze', E'Alimentazione Portafoglio Competenze', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.ORI.BILPSS.MENU', E'Strumento che rappresenta il nodo per BILANCIO PROSSIMITA', E'Menu BILANCIO PROSSIMITA', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.ORI.CANBILPSS', E'Cancelllazione di un Bilancio di Prossimità', E'Cancelllazione di un Bilancio di Prossimità', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.ORI.ELABILPSS', E'Elaborazione del Bilancio di Prossimità', E'Elaborazione del Bilancio di Prossimità', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.ORI.MENU', E'Strumento che rappresenta il nodo per ORIENTAMENTO', E'Menu ORIENTAMENTO', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.ORI.PCM.MENU', E'Strumento che rappresenta il nodo per PORTAFOGLIO COMPETENZE', E'Menu PORTAFOGLIO COMPETENZE', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.ORI.VISBILPSS', E'Visualizzazione e stampa del Bilancio di Prossimità', E'Visualizzazione e stampa del Bilancio di Prossimità', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.ORI.VISPCM', E'Visualizzazione e stampa Portafoglio Competenze', E'Visualizzazione e stampa Portafoglio Competenze', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.OSPITE.REGUTENTE', E'Registrazione dell''utente ospite', E'Registrazione dell''utente ospite', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.PA.ACCERTAMENTODPCM', E'Accertamento disabilita'' d.p.c.m.', E'Accertamento disabilita'' d.p.c.m.', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.PA.ACCOGL', E'Accoglienza', E'Accoglienza', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.PA.ATTORESTRINT', E'Inserimento e modifica di un attore di Strutture Interventi', E'Inserimento e modifica di un attore di Strutture Interventi', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.PA.CCO.STAMPA', E'Stampa del certificato di competenze', E'Stampa del certificato di competenze', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.PA.COLLOBBL', E'Collocamento Obbligatorio', E'Collocamento Obbligatorio', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.PA.COLLPA', E'Collocamento PA', E'Collocamento PA', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.PA.DISPASSIST', E'Disponibilita'' tipo assistenza', E'Disponibilita'' tipo assistenza', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.PA.DISPASSTEMP', E'Gestione disponibilita'' al tipo di assistenza e disponibilita'' temporale', E'Gestione disponibilita'' al tipo di assistenza e disponibilita'' temporale', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.PA.DISPINT', E'Disponibilita interventi', E'Disponibilita interventi', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.PA.DISPTEMP', E'Gestione disponibilita'' temporale', E'Gestione disponibilita'' temporale', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.PA.DLFABBOCC', E'Fabbisogni Occupazionali', E'Fabbisogni Occupazionali', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.PA.GESTAMMSOC', E'Gestione Ammortizzatori Sociali', E'Gestione Ammortizzatori Sociali', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.PA.GESTINFODESTR', E'Gestione Informazioni Destrutturate', E'Gestione Informazioni Destrutturate', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.PA.GESTISTINTNEWIST', E'Lista strutture intervento nuovo tirocinio', E'Lista strutture intervento', NULL, NULL, NULL, NULL, E'PROFILER', NOW()),
  (E'ST.PA.GESTISTINTRICIST', E'Lista strutture intervento ricerca tirocinio', E'Lista strutture intervento', NULL, NULL, NULL, NULL, E'PROFILER', NOW()),
  (E'ST.PA.GSTAMMTZ', E'Gestione Ammortizzatori', E'Gestione Ammortizzatori', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.PA.GSTDOM', E'Gestione Domanda', E'Gestione Domanda', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.PA.GSTMOB', E'Gestione Mobilità', E'Gestione Mobilità', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.PA.INFODESTR', E'Informazioni destrutturate', E'Informazioni destrutturate', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.PA.INSSTG', E'Inserisci Stage e Tirocini PA', E'Inserisci', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.PA.INSTIRCONV', E'Strumento per l''inserimento di Convenzioni in Stage e Tirocini', E'Strumento per l''inserimento di Convenzioni in Stage e Tirocini', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.PA.INSTIRPRG', E'Strumento per l''inserimento di Progetti in Stage e Tirocini', E'Strumento per l''inserimento di Progetti in Stage e Tirocini', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.PA.LFO.STAMPA', E'Stampa del libretto formativo', E'Stampa del libretto formativo', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.PA.MENU', E'Strumento che rappresenta il nodo di primo livello per GESTIONE POLITICHE', E'Menu GESTIONE POLITICHE', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.PA.MODTIRCONV', E'Strumento per la modifica di Convenzioni in Stage e Tirocini', E'Strumento per la modifica di Convenzioni in Stage e Tirocini', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.PA.MODTIRPRG', E'Strumento per la modifica di Progetti in Stage e Tirocini', E'Strumento per la modifica di Progetti in Stage e Tirocini', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.PA.MONAMMSOC', E'Monitoraggio Ammortizzatori Sociali', E'Monitoraggio Ammortizzatori Sociali', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.PA.NUCLEOFAM', E'Nucleo familiare', E'Nucleo familiare', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.PA.OBBLFORM', E'Obbligo Formativo', E'Obbligo Formativo', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.PA.ORIENTAM', E'Orientamento', E'Orientamento', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.PA.PROFILOCCUP', E'Profilo Occupabilita', E'Profilo Occupabilita', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.PA.PROSPINFORM', E'Prospetto informativo aziendale', E'Prospetto informativo aziendale', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.PA.REDDSUSS', E'Redditi e Sussidi', E'Redditi e Sussidi', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.PA.RICSTG', E'Ricerca Stage e Tirocini PA', E'Ricerca', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.PA.RICSTG.OPEAMMIN', E'Ricerca stage per utente plus.amministratore', E'Ricerca stage per utente plus.amministratore', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.PA.RICSTG.UTENTEDATORE', E'Ricerca stage per utente plus.azienda', E'Ricerca stage per utente plus.azienda', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.PA.RICSTG.UTENTESEDE', E'ricerca stage per sede di lavoro', E'ricerca stage per sede di lavoro', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.PA.RICTIR', E'Ricerca progetto (Stage e Tirocini)', E'Ricerca progetto (Stage e Tirocini)', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.PA.RICTIR.OPEAMMIN', E'Ricerca progetti per utente plus.amministratore', E'Ricerca progetti per utente plus.amministratore', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.PA.RICTIR.UTENTEDATORE', E'Ricerca progetti per utente plus.azienda', E'Ricerca progetti per utente plus.azienda', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.PA.RICTIR.UTENTESEDE', E'ricerca tirocini per sede di lavoro', E'ricerca tirocini per sede di lavoro', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.PA.RICTIR.UTENTEUSER', E'Ricerca progetti per utente plus.user', E'Ricerca progetti per utente plus.user', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.PA.SCHEDA.USER', E'prova scheda user', E'prova scheda user', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.PA.SCHEDA.UTENTE', E'Scheda utente (attivazione menu contestuale dell''utente)', E'Scheda utente', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.PA.SCHEDEORI', E'Schede di orientamento individuale', E'Schede di orientamento individuale', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.PA.SERVIZIOGENERICO', E'Servizio generico di PA', E'Servizio generico di PA', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.PA.STG.MENU', E'Strumento che rappresenta il nodo STAGE E TIROCINI', E'Menu STAGE E TIROCINI', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.PA.STG.MENU.UTENTEDATORE', E'Strumento che rappresenta il nodo STAGE E TIROCINI per l''utente di tipo Azienda Registrata', E'Strumento che rappresenta il nodo STAGE E TIROCINI per l''utente di tipo Azienda Registrata', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.PA.STG.MENU.UTENTESEDE', E'stage per sede di lavoro', E'stage per sede di lavoro', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.PA.STGTIRC', E'Stage e Tirocini', E'Stage e Tirocini', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.PA.STORIAMIG', E'Storia migratoria', E'Storia migratoria', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.PA.VINCOLIAMBIENTALI', E'Vincoli Ambientali', E'Vincoli Ambientali', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.PA.VISTIRCONV', E'Strumento per la visualizzazione di Convenzioni in Stage e Tirocini', E'Strumento per la visualizzazione di Convenzioni in Stage e Tirocini', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.PA.VISTIRPRG', E'Strumento per la visualizzazione di Progetti in Stage e Tirocini', E'Strumento per la visualizzazione di Progetti in Stage e Tirocini', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.PLUS.CRUSCOTTO', E'Cruscotto PLUS', E'Cruscotto PLUS', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.PLUS.MODPWD', E'Modifica Password', E'Modifica Password', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.POLATT.BACHECA', E'Bacheca Annunci', E'Bacheca Annunci', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.POLATT.GESTIONE', E'Gestione Annunci', E'Gestione Annunci', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.POLATT.MENU', E'Strumento che rappresenta il nodo di primo livello per BORSA LAVORO', E'Menu BORSA LAVORO', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.POLATT.RICERCA', E'Ricerca Personale', E'Ricerca Personale', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.POL.STAGE', E'Stage e tirocini', E'Stage e tirocini', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.POL.STAGE.INSCONV', E'Inserimento di una convenzione', E'Inserimento di una convenzione', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.POL.STAGE.RICCONV', E'Ricerca di convenzioni', E'Ricerca di convenzioni', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.REG.MENU', E'Voce Registrazione del menu orizzontale', E'Voce Registrazione del menu orizzontale', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.REG.MODPASSWORD', E'Modifica password', E'Modifica password', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.REG.REGAZIREG', E'registrazione dell''azienda ospite', E'registrazione  dell''azienda ospite', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.REG.REGDATLAV', E'Registrazione datore di lavoro', E'Registrazione datore di lavoro', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.REG.REGSEDEAZIREG', E'Registrazione delle sedi di lavoro per l''utente di tipo Azienda Registrata', E'Registrazione delle sedi di lavoro per l''utente di tipo Azienda Registrata', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.REG.REGSEDEDATLAV', E'Registrazione sede datore di lavoro', E'Registrazione sede datore di lavoro', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.AZI.SERVCOMP', E'Visualizzazione dati relativi al servizio competente dell''Azienda', E'Visualizzazione dati relativi al servizio competente dell''Azienda', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.LAV.DIS.SEZB', E'Disabili Sezione B', E'Disabili Sezione B', NULL, NULL, NULL, NULL, E'ICF', NOW()),
  (E'ST.LAV.DIS.SEZVC', E'Disabili Verbale Conclusivo', E'Disabili Verbale Conclusivo', NULL, NULL, NULL, NULL, E'ICF', NOW()),
  (E'ST.INT.IST', E'Strumento di gestione delle istanze interventi (ricerca, ricerca in visualizzazione, nuova istanza)', E'Gestione istanze interventi', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.INT.IST.AUP.MENU', E'menu gestione aule in presenza', E'menu gestione aule in presenza', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.INT.IST.SEM.MENU', E'Menu gestione seminari', E'Menu gestione seminari', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.INT.IST.TIR.MENU', E'Strumento che rappresenta il nodo di secondo livello GESTIONE TIROCINI', E'SottoMenu GESTIONE TIROCINI', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.INT.ISTVISRICTIR.USER.USER', E'Ricerca Tirocinio', E'Ricerca Tirocinio', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.INT.MENU', E'Strumento che rappresenta il nodo INTERVENTI', E'SottoMenu INTERVENTI', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.INT.STRINT.GSTSTRINT', E'Strumento per la gestione strutture intervento', E'Gestione strutture intervento', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.INT.STRINT.MENU', E'Strumento che rappresenta il nodo di secondo livello GESTIONE STRUTTURA INTERVENTI', E'SottoMenu GESTIONE STRUTTURA INTERVENTI', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.INT.STRINT.VISSTRINT', E'Strumento per la visualizzazione delle strutture intervento', E'Visualizza strutture intervento', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.JPLUS.INCR', E'Collegamento all''incrocio JPLUS', E'Collegamento all''incrocio JPLUS', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.JPLUS.ISCR', E'Collegamento Gestione Iscrizione JPLUS', E'Collegamento Gestione Iscrizione JPLUS', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.JPLUS.PAGAMENTI', E'Collegamento Gestione Dati Pagamenti JPLUS', E'Collegamento Gestione Dati Pagamenti JPLUS', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.JPLUS.STAT', E'Collegamento alle statistiche JPLUS', E'Collegamento alle statistiche JPLUS', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.LAV.ANNULLACANCLAV', E'Annulla cancellazione logica lavoratore', E'Annulla cancellazione logica lavoratore', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.LAV.CPI', E'CRITERIO RICERCA CPI', E'CRITERIO RICERCA CPI', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.LAV.CTXSAP', E'Lavoratore contesto', E'Lavoratore contesto', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.LAV.DID', E'Gestione Dichiarazione di Immediata Disponibilità', E'Gestione Dichiarazione di Immediata Disponibilità', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.LAV.DIS.COLLMIR', E'Collocamento Mirato', E'Collocamento Mirato', NULL, NULL, NULL, NULL, E'ICF', NOW()),
  (E'ST.LAV.DIS.SEZC', E'Disabili Sezione C', E'Disabili Sezione C', NULL, NULL, NULL, NULL, E'ICF', NOW()),
  (E'ST.LAV.DIS.SEZD', E'Disabili Sezione D', E'Disabili Sezione D', NULL, NULL, NULL, NULL, E'ICF', NOW()),
  (E'ST.LAV.DIS.SEZE', E'Disabili Sezione E', E'Disabili Sezione E', NULL, NULL, NULL, NULL, E'ICF', NOW()),
  (E'ST.LAV.DIS.SEZF', E'Disabili Sezione F', E'Disabili Sezione F', NULL, NULL, NULL, NULL, E'ICF', NOW()),
  (E'ST.LAV.DIS.SEZG', E'Disabili Sezione G', E'Disabili Sezione G', NULL, NULL, NULL, NULL, E'ICF', NOW()),
  (E'ST.LAV.DIS.SEZH', E'Disabili Sezione H', E'Disabili Sezione H', NULL, NULL, NULL, NULL, E'ICF', NOW()),
  (E'ST.LAV.DIS.SEZH1', E'Disabili Sezione H1', E'Disabili Sezione H1', NULL, NULL, NULL, NULL, E'ICF', NOW()),
  (E'ST.LAV.DIS.SEZH2', E'Disabili Sezione H2', E'Disabili Sezione H2', NULL, NULL, NULL, NULL, E'ICF', NOW()),
  (E'ST.LAV.DIS.SEZI', E'Disabili Sezione I', E'Disabili Sezione I', NULL, NULL, NULL, NULL, E'ICF', NOW()),
  (E'ST.LAV.DIS.SEZL', E'Disabili Sezione L', E'Disabili Sezione L', NULL, NULL, NULL, NULL, E'ICF', NOW()),
  (E'ST.LAV.DIS.SEZM', E'Disabili Sezione M', E'Disabili Sezione M', NULL, NULL, NULL, NULL, E'ICF', NOW()),
  (E'ST.LAV.DIS.SINTPROT', E'Sintesi Protocollo Lavoratore', E'Sintesi Protocollo Lavoratore', NULL, NULL, NULL, NULL, E'ICF', NOW()),
  (E'ST.LAV.ELILAV', E'Cancellazione fisica delle informazioni di un lavoratore (uso amministratore)', E'Cancellazione fisica delle informazioni di un lavoratore (uso amministratore)', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.LAV.ESPSTUDIO', E'Esperienze di studio del lavoratore', E'Esperienze di studio del lavoratore', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.LAV.GESPIANO', E'Strumento per la gestione di un piano individuale', E'Strumento per la gestione di un piano individuale', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.LAV.GESTENTECOMP', E'Gestione Ente di Competenza', E'Gestione Ente di Competenza', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.LAV.GESTENTECOMP.LSTENTI', E'Lista Enti di Competenza', E'Lista Enti di Competenza', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.LAV.GESTLAV', E'Gestione Lavoratore', E'Gestione Lavoratore', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.LAV.INSLAV', E'Inserimento Lavoratore (Registrazione)', E'Inserimento Lavoratore (Registrazione)', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.LAV.MENU', E'Strumento che rappresenta il nodo di primo livello per GESTIONE LAVORATORE', E'Menu Gestione Lavoratore', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.LAV.MOBILITA', E'mobilita', E'mobilita', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.LAV.MODSAP', E'Modifica della Scheda Anagrafico-Professionale di un lavoratore', E'Modifica della Scheda Anagrafico-Professionale di un lavoratore', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.LAV.MODSAP.USER', E'Modifica della Scheda Anagrafico-Professionale di un lavoratore per un profilo plus.user', E'Modifica della Scheda Anagrafico-Professionale di un lavoratore per un profilo plus.user', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.LAV.NAZ', E'CRITERIO RICERCA NAZIONE', E'CRITERIO RICERCA NAZIONE', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.LAV.OFFERTA.MENU', E'Menu offerta per il lavoratore', E'Menu offerta per il lavoratore', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.LAV.OFFERTA.RICLAV', E'Ricerca lavoratore', E'Ricerca lavoratore', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.LAV.OFFERTA.RICLAVEXTRAREG', E'Ricerca extra regionali', E'Ricerca extra regionali', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.LAV.PATTOSERV', E'Patti di Servizio', E'Patti di Servizio(Servizio da voce di menu)', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.LAV.PATTOSERV.LSTPATTI', E'Lista Patti di Servizio', E'Lista Patti di Servizio', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.LAV.PATTOSERV.PATTO', E'Gestione Patti di Servizio', E'Gestione Patti di Servizio', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.LAV.PATTOSERV.RIFIUTO', E'Gestione Rifiuti Patto di Servizio', E'Gestione Rifiuti Patto di Servizio', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.LAV.PERS', E'CRITERIO RICERCA PERSONALI', E'CRITERIO RICERCA PERSONALI', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.LAV.PROFILOSINTESI', E'Strumento Profilo di sintesi', E'strumento profilo di sintesi', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.LAV.PROV', E'CRITERIO RICERCA PROVINCIA', E'CRITERIO RICERCA PROVINCIA', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.LAV.REG', E'CRITERIO RICERCA REGIONE', E'CRITERIO RICERCA REGIONE', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.LAV.RICAVA.RDBAMBITI', E'CRITERIO RICERCA RadioButton', E'CRITERIO RICERCA RadioButton', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.LAV.RICFASCICOLOLAV', E'Ricerca fascicolo personale di un iscritto al progetto. Comprende anche i fuoriusciti dal bacino', E'Ricerca fascicolo personale di un iscritto al progetto. Comprende anche i fuoriusciti dal bacino', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.LAV.RICLAV', E'Ricerca Lavoratore', E'Ricerca Lavoratore', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.LAV.RICLAVA', E'Ricerca Avanzata Lavoratore', E'Ricerca Avanzata Lavoratore', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.LAV.RICLAVDIS', E'Comunica a Pegaso', E'Comunica a Pegaso', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.LAV.RICLAVEXTRAREG', E'Ricerca Lavoratori Extra-Regionali', E'Ricerca Lavoratori Extra-Regionali', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.LAV.RICLAV.USER', E'Ricerca Lavoratore', E'Ricerca Lavoratore', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.LAV.SCHEDA', E'SCHEDA AP', E'SCHEDA AP', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.LAV.SOSP', E'Strumento che rappresenta il nodo di secondo livello GESTIONE SOSPENSIONI', E'SottoMenu GESTIONE SOSPENSIONI', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.LAV.SOSP.GEST', E'Strumento per la gestione sospensione rapporto di lavoro attivo a TI', E'Gestisci sospensione', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.LAV.SOSP.INS', E'Strumento per l''inserimento sospensione rapporto di lavoro attivo a TI', E'Inserisci sospensione', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.LAV.TRALAV', E'Trasferimento Lavoratore tra CPI nell''ambito della stessa Regione', E'Trasferimento Lavoratore tra CPI nell''ambito della stessa Regione', NULL, NULL, NULL, NULL, E'SYSTEM', NOW()),
  (E'ST.LAV.UNI', E'CRITERIO RICERCA UNIVERSITA', E'CRITERIO RICERCA UNIVERSITA', NULL, NULL, NULL, NULL, E'SYSTEM', NOW());