/* Data for the 'plus_dizionari.dec_allegati' table  (Records 1 - 16) */

INSERT INTO plus_dizionari.dec_allegati ("cod_applicazione", "cod_allegato", "des_label", "des_formato", "cod_codicestrumento", "cod_funzione", "txt_note", "prg_istanza", "num_dimensione_max", "cod_obbligatorio", "dat_inizio", "dat_fine", "dtt_tmst")
VALUES 
  (E'PERCORSI', E'ACOD_FISC', E'Codice fiscale', E'PDF,JPEG,JPG', E'ST.AMM.GESALLEGATIMODULOPAGAMENTO', E'FN.AMM.GESALLEGATIMODULOPAGAMENTO', NULL, NULL, 500, E'U', '2015-11-20', NULL, NOW()),
  (E'PERCORSI', E'BDOC_IDEN', E'Documento di identità', E'PDF,JPEG,JPG', E'ST.AMM.GESALLEGATIMODULOPAGAMENTO', E'FN.AMM.GESALLEGATIMODULOPAGAMENTO', NULL, NULL, 500, E'U', '2015-11-20', NULL, NOW()),
  (E'PERCORSI', E'CDATI_PAG', E'Dati pagamento', E'PDF,JPEG,JPG', E'ST.AMM.GESALLEGATIMODULOPAGAMENTO', E'FN.AMM.GESALLEGATIMODULOPAGAMENTO', NULL, NULL, 500, E'U', '2015-11-20', NULL, NOW()),
  (E'PERCORSI', E'CONV', E'Convenzione', E'PDF,JPEG,JPG', E'ST.PA.CONV.GESALLEGATI', E'FN.PA.CONV.GESALLEGATI', NULL, NULL, 1024, E'S', '2015-11-20', NULL, NOW()),
  (E'PERCORSI', E'CV', E'Curriculum Vitae', E'PDF', E'ST.SIC.ISCRIZIONEPERSONA', E'FN.SIC.ISCRIZIONEPERSONA.ALLEGATI', NULL, NULL, 1024, E'S', '2015-11-20', NULL, NOW()),
  (E'PERCORSI', E'DDETR_REDD', E'Detrazione dal reddito', E'PDF,JPEG,JPG', E'ST.AMM.GESALLEGATIMODULOPAGAMENTO', E'FN.AMM.GESALLEGATIMODULOPAGAMENTO', NULL, NULL, 500, E'U', '2015-11-20', NULL, NOW()),
  (E'PERCORSI', E'DID', E'Autocertificazione o copia iscrizione CPI', E'PDF,JPEG,JPG', E'ST.SIC.ISCRIZIONEPERSONA', E'FN.SIC.ISCRIZIONEPERSONA.ALLEGATI', NULL, NULL, 500, E'S', '2015-11-20', NULL, NOW()),
  (E'PERCORSI', E'DOC_IDEN_I', E'Documento di identità o permesso di soggiorno', E'PDF,JPEG,JPG', E'ST.SIC.ISCRIZIONEPERSONA', E'FN.SIC.ISCRIZIONEPERSONA.ALLEGATI', NULL, NULL, 500, E'S', '2015-11-20', NULL, NOW()),
  (E'PERCORSI', E'EPROG_FORM', E'Progetto formativo', E'PDF,JPEG,JPG', E'ST.AMM.GESALLEGATIMODULOPAGAMENTO', E'FN.AMM.GESALLEGATIMODULOPAGAMENTO', NULL, NULL, 500, E'U', '2015-11-20', NULL, NOW()),
  (E'PERCORSI', E'FINAIL', E'INAIL', E'PDF,JPG,JPEG', E'ST.AMM.GESALLEGATIMODULOPAGAMENTO', E'FN.AMM.GESALLEGATIMODULOPAGAMENTO', NULL, NULL, 500, E'U', '2015-11-20', NULL, NOW()),
  (E'PERCORSI', E'GRCT', E'RCT', E'PDF,JPG,JPEG', E'ST.AMM.GESALLEGATIMODULOPAGAMENTO', E'FN.AMM.GESALLEGATIMODULOPAGAMENTO', NULL, NULL, 500, E'U', '2015-11-20', NULL, NOW()),
  (E'PERCORSI', E'HREG_PRES', E'Registro presenze', E'PDF,JPEG,JPG', E'ST.AMM.GESALLEGATIMODULOPAGAMENTO', E'FN.AMM.GESALLEGATIMODULOPAGAMENTO', NULL, NULL, 1024, E'S', '2015-11-20', NULL, NOW()),
  (E'PERCORSI', E'ICOM_OBB', E'Comunicazione obbligatoria di attivazione del tirocinio', E'PDF,JPG,JPEG', E'ST.AMM.GESALLEGATIMODULOPAGAMENTO', E'FN.AMM.GESALLEGATIMODULOPAGAMENTO', NULL, NULL, 1024, E'U', '2015-11-20', NULL, NOW()),
  (E'PERCORSI', E'LATT_SICUR', E'Attestato corso di formazione sicurezza o autocertificazione', E'PDF,JPG,JPEG', E'ST.AMM.GESALLEGATIMODULOPAGAMENTO', E'FN.AMM.GESALLEGATIMODULOPAGAMENTO', NULL, NULL, 500, E'U', '2015-11-20', NULL, NOW()),
  (E'PERCORSI', E'REG_PRES_T', E'Registro presenze', E'PDF,JPEG,JPG', E'ST.AMM.GESALLEGATIMODULOPAGAMENTO.TUTOR', E'FN.AMM.GESALLEGATIMODULOPAGAMENTO', NULL, NULL, 2048, E'S', '2015-11-20', NULL, NOW()),
  (E'PERCORSI', E'RIEP_ATT', E'Riepilogo attività', E'PDF,JPG,JPEG', E'ST.AMM.GESRICHIESTAPAGAMENTO', E'FN.AMM.GESRICHIESTAPAGAMENTO.ALLEGATI', NULL, NULL, 1024, E'S', '2015-11-20', NULL, NOW());