
Insert into SPC_DEC_TIPO_CODIFICA_REGOLA
   (COD_TIPO_CODIFICA_REGOLA, DES_TIPO_CODIFICA_REGOLA)
 Values
   ('SQL', 'Linguaggio SQL');
Insert into SPC_DEC_TIPO_CODIFICA_REGOLA
   (COD_TIPO_CODIFICA_REGOLA, DES_TIPO_CODIFICA_REGOLA)
 Values
   ('EL', 'Expression Language');

