/* Data for the 'spc_strumento' table  (Records 1 - 314) */

INSERT INTO spc_strumento ("cod_strumento", "des_nome", "des_url", "des_strumento", "cod_userins", "dtt_tmstins")
VALUES 
  (E'MNU.ADMIN', E'MENU DI AMMINISTRAZIONE', NULL, NULL, E'SYSTEM',NOW() ),
  (E'MNU.AMM.ANP.GESELENCHI', E'Gestione Elenchi', NULL, E'Voce di menu Gestione Elenchi', E'SYSTEM',NOW() ),
  (E'MNU.AMM.ANP.GESTIONE_PAGAMENTI', E'Richiesta anticipo Piano', NULL, E'Voce di menu Richiesta anticipo Piano', E'SYSTEM',NOW() ),
  (E'MNU.AMM.ANP.MODULO_PAGAMENTO', E'Richiesta anticipo Piano', NULL, E'Voce di menu Richiesta anticipo Piano', E'SYSTEM',NOW() ),
  (E'MNU.AMM.DATI_PAGAMENTO', E'Menu Gestione Dati di pagamento del lavoratore', NULL, NULL, E'SYSTEM',NOW() ),
  (E'MNU.AMM.GESTIONE_PAGAMENTI', E'DES STRUMENTO', NULL, NULL, E'SYSTEM',NOW() ),
  (E'MNU.AMM.GESTIONE_PAGAMENTITUT', E'Gestione Pagamenti Tutoraggio', NULL, NULL, E'SYSTEM',NOW() ),
  (E'MNU.AMM.MODULO_DETRAZIONI', E'MENU MODULO DETRAZIONI', NULL, NULL, E'SYSTEM',NOW() ),
  (E'MNU.AMM.MODULO_PAGAMENTO', E'DES STRUMENTO', NULL, NULL, E'SYSTEM',NOW() ),
  (E'MNU.AMM.MODULO_PAGAMENTOTUT', E'Richiesta di pagamento Tutor', NULL, NULL, E'SYSTEM',NOW() ),
  (E'MNU.AMM.PAI.GESELENCHI', E'Elenchi Piano Personalizzato', NULL, E'Elenchi Piano Personalizzato', E'SYSTEM',NOW() ),
  (E'MNU.AMM.PAI.GESTIONE_PAGAMENTI', E'Gestione Pagamenti Piano Personalizzato', NULL, E'Gestione Pagamenti Piano Personalizzato', E'SYSTEM',NOW() ),
  (E'MNU.AMM.RICHIESTA_PAGAMENTO', E'Richiesta di pagamento', NULL, E'Richiesta di pagamento', E'SYSTEM',NOW() ),
  (E'MNU.AMM.SAP.GESTIONE_FLUSSI', E'MENU flussi SAP', NULL, NULL, E'SYSTEM',NOW() ),
  (E'MNU.AMM.TIR.GESDDR', E'MENU DDR', NULL, NULL, E'SYSTEM',NOW() ),
  (E'MNU.AMM.TIR.SIGMA', E'MENU Generazione pacchetto SIGMA', NULL, NULL, E'SYSTEM',NOW() ),
  (E'MNU.AMM.TUT.GESELENCHI', E'Gestione Elenchi', NULL, E'Voce di menu Gestione Elenchi', E'SYSTEM',NOW() ),
  (E'MNU.FILE', E'MENU INDICATORI SU FILE', NULL, NULL, E'SYSTEM',NOW() ),
  (E'MNU.GESTIONE.REPORT', E'MENU GESTIONE REPORT', NULL, NULL, E'SYSTEM',NOW() ),
  (E'MNU.GESTIONE.REPORT.ADESIONI', E'Menu Gestione Report Adesioni', NULL, NULL, E'SYSTEM',NOW() ),
  (E'MNU.GESTIONE.REPORT.AZIENDE', E'Report Incentivi in erogazione', NULL, NULL, E'SYSTEM',NOW() ),
  (E'MNU.GESTIONE.REPORT.CONVENZIONI.FILE', E'MENU GESTIONE REPORT CONVENZIONI (FILE)', NULL, NULL, E'SYSTEM',NOW() ),
  (E'MNU.GESTIONE.REPORT.CONVENZIONI.NAZ', E'CONVENZIONI NAZIONALI', NULL, NULL, E'SYSTEM',NOW() ),
  (E'MNU.GESTIONE.REPORT.CONVENZIONI.PROV', E'CONVENZIONI PROVINCIALI', NULL, NULL, E'SYSTEM',NOW() ),
  (E'MNU.GESTIONE.REPORT.CONVENZIONI.REG', E'CONVENZIONI REGIONALI', NULL, NULL, E'SYSTEM',NOW() ),
  (E'MNU.GESTIONE.REPORT.CONVOCAZIONI.NAZ', E'Menu Gestione Report Convocazioni', NULL, NULL, E'SYSTEM',NOW() ),
  (E'MNU.GESTIONE.REPORT.DOMANDA.NAZ', E'Menu domanda', NULL, E'-', E'SYSTEM',NOW() ),
  (E'MNU.GESTIONE.REPORT.INCSUSS', E'Report Incentivi in erogazione', NULL, NULL, E'SYSTEM',NOW() ),
  (E'MNU.GESTIONE.REPORT.LAVORATORI', E'Menu Gestione Lavoratori', NULL, NULL, E'SYSTEM',NOW() ),
  (E'MNU.GESTIONE.REPORT.MONITORAGGIO', E'MENU GESTIONE REPORT MONITORAGGIO', NULL, NULL, E'SYSTEM',NOW() ),
  (E'MNU.GESTIONE.REPORT.MONITORAGGIO.REG', E'GESTIONE REPORT MONITORAGGIO', NULL, NULL, E'SYSTEM',NOW() ),
  (E'MNU.GESTIONE.REPORT.NAZ', E'Menu report nazionali', NULL, E'-', E'SYSTEM',NOW() ),
  (E'MNU.GESTIONE.REPORT.OFFERTA.NAZ', E'Menu offerta', NULL, E'-', E'SYSTEM',NOW() ),
  (E'MNU.GESTIONE.REPORT.ORIENTAMENTO', E'Report Incentivi in erogazione', NULL, NULL, E'SYSTEM',NOW() ),
  (E'MNU.GESTIONE.REPORT.PAGAMENTI.FILE', E'Menu estrazioni ufficio personale', E'-', E'-', E'SYSTEM',NOW() ),
  (E'MNU.GESTIONE.REPORT.PAI', E'Report Piani di Azione Individuale', NULL, NULL, E'SYSTEM',NOW() ),
  (E'MNU.GESTIONE.REPORT.PDS.NAZ', E'PATTI DI SERVIZIO', NULL, NULL, E'SYSTEM',NOW() ),
  (E'MNU.GESTIONE.REPORT.PROV', E'Menu report provinciali', NULL, E'-', E'SYSTEM',NOW() ),
  (E'MNU.GESTIONE.REPORT.REG', E'Menu report regionali', NULL, E'-', E'SYSTEM',NOW() ),
  (E'MNU.GESTIONE.REPORT.SUSSIDI.FILE', E'Menu Gestione Report Incentivi (FILE)', NULL, NULL, E'SYSTEM',NOW() ),
  (E'MNU.GESTIONE.REPORT.TIROCINI.FILE', E'Menu Gestione Report Tirocini (FILE)', NULL, NULL, E'SYSTEM',NOW() ),
  (E'MNU.GESTIONE.REPORT.TIROCINI.INT.NAZ', E'TIROCINI NAZIONALI PER INTERMEDIARIO', NULL, NULL, E'SYSTEM',NOW() ),
  (E'MNU.GESTIONE.REPORT.TIROCINI.NAZ', E'TIROCINI NAZIONALI', NULL, NULL, E'SYSTEM',NOW() ),
  (E'MNU.GESTIONE.REPORT.TIROCINI.PROV', E'TIROCINI PROVINCIALI', NULL, NULL, E'SYSTEM',NOW() ),
  (E'MNU.GESTIONE.REPORT.TIROCINI.REG', E'TIROCINI REGIONALI', NULL, NULL, E'SYSTEM',NOW() ),
  (E'MNU.PAGAMENTI', E'MENU PAGAMENTI', NULL, NULL, E'SYSTEM',NOW() ),
  (E'MNU.REPORT', E'MENU REPORT', NULL, NULL, E'SYSTEM',NOW() ),
  (E'MNU.SECURITY', E'MENU SECURITY', NULL, NULL, E'SYSTEM',NOW() ),
  (E'MNU.SIC.AZIENDE', E'Menu Registrazioni Aziende', NULL, E'-', E'SYSTEM',NOW() ),
  (E'MNU.SIC.ISCRIZ_AZIENDE', E'ISCRIZIONE AZIENDE', NULL, NULL, E'SYSTEM',NOW() ),
  (E'MNU.SIC.ISCRIZ_PERSONE', E'ISCRIZIONE PERSONE', NULL, NULL, E'SYSTEM',NOW() ),
  (E'MNU.SIC.ISCRIZ_PROGETTI', E'ISCRIZIONE PROGETTI', NULL, NULL, E'SYSTEM',NOW() ),
  (E'MNU.SIC.PERSONE', E'Registrazioni al progetto', NULL, E'-', E'SYSTEM',NOW() ),
  (E'MNU.SIC.VALIDAZ_ISCRIZ_AZIENDE', E'Validazione registrazioni', E'-', E'-', E'SYSTEM',NOW() ),
  (E'MNU.SIC.VALIDAZ_ISCRIZ_PROGETTI', E'VALIDAZIONE ISCRIZIONE PROGETTI', NULL, NULL, E'SYSTEM',NOW() ),
  (E'ST.AMM.AGGMODULODETRAZIONI', E'Aggiorna Modulo Detrazione', NULL, NULL, E'SYSTEM',NOW() ),
  (E'ST.AMM.ANP.INSELENCO', E'Creazione Elenco', NULL, E'Creazione Elenco', E'SYSTEM',NOW() ),
  (E'ST.AMM.ANP.LSTELENCHI', E'Lista Elenchi', NULL, E'Lista Elenchi', E'SYSTEM',NOW() ),
  (E'ST.AMM.ANP.RICELENCO', E'Ricerca Elenco', NULL, E'Ricerca Elenco', E'SYSTEM',NOW() ),
  (E'ST.AMM.ANP.RICMODULIPAGAMENTO', E'Ricerca anticipo Piano', NULL, E'Voce di menu ricerca anticipo Piano', E'SYSTEM',NOW() ),
  (E'ST.AMM.ANP.RICRICHIESTA', E'Ricerca Richieste', NULL, E'Ricerca Richieste', E'SYSTEM',NOW() ),
  (E'ST.AMM.ARCHIVIAMODULODETRAZIONI', E'ARCHIVIA MODULO DI DETRAZIONE', NULL, NULL, E'SYSTEM',NOW() ),
  (E'ST.AMM.GESELENCO', E'Gestisci Elenco', NULL, E'Gestisci Elenco Richieste Pagamento', E'SYSTEM',NOW() ),
  (E'ST.AMM.GESLAVDATIPAGAMENTO', E'Gestione DATI di PAGAMENTO', NULL, E'Gestione DATI di PAGAMENTO', E'SYSTEM',NOW() ),
  (E'ST.AMM.GESMODULODETRAZIONI', E'Gestisci Modulo Detrazione', NULL, NULL, E'SYSTEM',NOW() ),
  (E'ST.AMM.GESMODULOPAGAMENTOSTATO', E'Gestione Modulo Pagamento', NULL, NULL, E'SYSTEM',NOW() ),
  (E'ST.AMM.INSMODULIPAGAMENTO.TUTOR', E'Inserisci Modulo Pagamento Tutor', NULL, NULL, E'SYSTEM',NOW() ),
  (E'ST.AMM.INSMODULODETRAZIONI', E'Inserisci Modulo Detrazione', NULL, NULL, E'SYSTEM',NOW() ),
  (E'ST.AMM.INSMODULOPAGAMENTO', E'DES STRUMENTO', NULL, NULL, E'SYSTEM',NOW() ),
  (E'ST.AMM.LSTLAVDATIPAGAMENTO', E'Lista dati di pagamento', NULL, NULL, E'SYSTEM',NOW() ),
  (E'ST.AMM.LSTLAVDATIPAGAMENTO.MENU', E'Lista dati di pagamento (da menu)', NULL, NULL, E'SYSTEM',NOW() ),
  (E'ST.AMM.LSTMODULIDETRAZIONI', E'LISTA MODULO DETRAZIONI', NULL, NULL, E'SYSTEM',NOW() ),
  (E'ST.AMM.LSTMODULIDETRAZIONI.MENU', E'LISTA MODULO DETRAZIONI (da menu)', NULL, NULL, E'SYSTEM',NOW() ),
  (E'ST.AMM.LSTMODULIPAGAMENTO', E'DES STRUMENTO', NULL, NULL, E'SYSTEM',NOW() ),
  (E'ST.AMM.LSTMODULOINTERVENTOATTORI', E'LISTA INTERVENTI', NULL, NULL, E'SYSTEM',NOW() ),
  (E'ST.AMM.LSTRICHIESTEPAGAMENTO', E'Lista delle Richiesta di pagamento', NULL, E'Lista delle Richiesta di pagamento', E'SYSTEM',NOW() ),
  (E'ST.AMM.LSTSTATIRICPAGAGGNOTE', E'Aggiorna Note Richieste Pagamento', NULL, E'Aggiorna Note Richieste Pagamento', E'SYSTEM',NOW() ),
  (E'ST.AMM.LSTSTORICOLAVDATIPAGAMENTO', E'Lista dati di pagamento (storico)', NULL, NULL, E'SYSTEM',NOW() ),
  (E'ST.AMM.MODMODULOPAGAMENTO', E'MODIFICA MODULO PAGAMENTO', NULL, NULL, E'SYSTEM',NOW() ),
  (E'ST.AMM.PAI.INSELENCO', E'Crea Elenco', NULL, E'Crea Elenco di Richieste Pagamento', E'SYSTEM',NOW() ),
  (E'ST.AMM.PAI.LSTELENCHI', E'Lista Elenchi', NULL, E'Lista Elenchi Richieste Pagamento', E'SYSTEM',NOW() ),
  (E'ST.AMM.PAI.RICELENCO', E'Ricerca Elenchi', NULL, E'Ricerca Elenchi di Richieste Pagamento', E'SYSTEM',NOW() ),
  (E'ST.AMM.PAI.RICRICHIESTA', E'Ricerca Richieste', NULL, E'Ricerca Richieste Pagamento', E'SYSTEM',NOW() ),
  (E'ST.AMM.PAI.RICRICHIESTEPAGAMENTO', E'Ricerca delle Richiesta di pagamento', NULL, E'Ricerca delle Richiesta di pagamento', E'SYSTEM',NOW() ),
  (E'ST.AMM.RICLAVDATIPAGAMENTO', E'Ricerca dati di pagamento', NULL, NULL, E'SYSTEM',NOW() ),
  (E'ST.AMM.RICMODULIDETRAZIONI', E'RICERCA MODULO DETRAZIONI', NULL, NULL, E'SYSTEM',NOW() ),
  (E'ST.AMM.RICMODULIPAGAMENTO', E'DES STRUMENTO', NULL, NULL, E'SYSTEM',NOW() ),
  (E'ST.AMM.RICMODULIPAGAMENTO.ITRANCHE', E'Gestione pagamenti I Tranche', NULL, E'Gestione pagamenti I Tranche', E'SYSTEM',NOW() ),
  (E'ST.AMM.RICMODULIPAGAMENTO.RET', E'Ricerca delle Richieste di pagamento da rettificare', NULL, E'Ricerca delle Richieste di pagamento da rettificare', E'SYSTEM',NOW() ),
  (E'ST.AMM.RICMODULIPAGAMENTO.TUTOR', E'Ricerca Modulo Pagamento Tutor', NULL, NULL, E'SYSTEM',NOW() ),
  (E'ST.AMM.SAP.GESFLUSSOPAGAMENTI', E'Flusso Pagamenti', NULL, NULL, E'SYSTEM',NOW() ),
  (E'ST.AMM.SAP.GESFLUSSOSOSPESI', E'Flusso Sospesi', NULL, NULL, E'SYSTEM',NOW() ),
  (E'ST.AMM.SAP.INSCARELLONR', E'Genera Flusso Nuove Richieste', NULL, NULL, E'SYSTEM',NOW() ),
  (E'ST.AMM.SAP.INSCARELLORT', E'Genera Flusso Rettifiche', NULL, NULL, E'SYSTEM',NOW() ),
  (E'ST.AMM.SAP.INSCARRELLONR', E'Genera Flusso Nuove Richieste', NULL, NULL, E'SYSTEM',NOW() ),
  (E'ST.AMM.SAP.INSCARRELLORT', E'Genera Flusso Rettifiche', NULL, NULL, E'SYSTEM',NOW() ),
  (E'ST.AMM.SAP.LSTCARRELLI', E'Lista Carrelli', NULL, NULL, E'SYSTEM',NOW() ),
  (E'ST.AMM.SAP.LSTELENCHI', E'Nuova richiesta - lista elenchi', NULL, NULL, E'SYSTEM',NOW() ),
  (E'ST.AMM.SAP.LSTMOVIMENTI', E'Lista Movimenti SAP', NULL, NULL, E'SYSTEM',NOW() ),
  (E'ST.AMM.SAP.LSTRICHIESTE', E'Lista Richieste SAP', NULL, NULL, E'SYSTEM',NOW() ),
  (E'ST.AMM.SAP.RICCARRELLI', E'Ricerca Carrelli', NULL, NULL, E'SYSTEM',NOW() ),
  (E'ST.AMM.SAP.RICELENCHI', E'Nuova Richiesta', NULL, NULL, E'SYSTEM',NOW() ),
  (E'ST.AMM.SAP.RICFLUSSI', E'Ricerca Flussi', NULL, NULL, E'SYSTEM',NOW() ),
  (E'ST.AMM.SAP.RICMOVIMENTI', E'Movimenti SAP', NULL, NULL, E'SYSTEM',NOW() ),
  (E'ST.AMM.SAP.RICRICHIESTE', E'Ricerca Richieste SAP', NULL, NULL, E'SYSTEM',NOW() ),
  (E'ST.AMM.TIR.GESDDR', E'Gestione DDR', NULL, NULL, E'SYSTEM',NOW() ),
  (E'ST.AMM.TIR.INSDDR', E'Inserimento DDR', NULL, NULL, E'SYSTEM',NOW() ),
  (E'ST.AMM.TIR.LSTDDR', E'Lista DDR', NULL, NULL, E'SYSTEM',NOW() ),
  (E'ST.AMM.TIR.RICDDR', E'Ricerca DDR', NULL, NULL, E'SYSTEM',NOW() ),
  (E'ST.AMM.TIR.SIGMA.GEN', E'Generazione pacchetto SIGMA', NULL, NULL, E'SYSTEM',NOW() ),
  (E'ST.AMM.TUT.INSELENCO', E'Creazione Elenco', NULL, E'Creazione Elenco', E'SYSTEM',NOW() ),
  (E'ST.AMM.TUT.LSTELENCHI', E'Lista Elenchi', NULL, E'Lista Elenchi', E'SYSTEM',NOW() ),
  (E'ST.AMM.TUT.RICELENCO', E'Ricerca Elenco', NULL, E'Ricerca Elenco', E'SYSTEM',NOW() ),
  (E'ST.AMM.TUT.RICRICHIESTA', E'Ricerca elenchi tutoraggio', NULL, E'Voce di menu ricerca elenchi tutoraggio con parametri richieste pagamento', E'SYSTEM',NOW() ),
  (E'ST.ANA.GESAZIENDA', E'Gestione Anagrafica Azienda', E'/switch.do?page=/GesAzienda.do#prefix=/presentation/core/anagrafica/aziende#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.ANA.GESSEDEAZIENDA', E'Gestione Anagrafica Sede Azienda', E'/switch.do?page=/GesSedeAzienda.do#prefix=/presentation/core/anagrafica/aziende#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.ANA.INSAZIENDA', E'Inserimento Anagrafica Azienda', E'/switch.do?page=/InsAzienda.do#prefix=/presentation/core/anagrafica/aziende#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.ANA.INSSEDEAZIENDA', E'Inserimento Anagrafica Sede Azienda', E'/switch.do?page=/InsSedeAzienda.do#prefix=/presentation/core/anagrafica/aziende#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.ANA.LSTAZIENDE', E'Lista Aziende', E'/switch.do?page=/LstAziende.do#prefix=/presentation/core/anagrafica/aziende#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.ANA.LSTSEDIAZIENDE', E'Lista Sedi Aziende', E'/switch.do?page=/LstSediAziende.do#prefix=/presentation/core/anagrafica/aziende#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.ANA.RICAZIENDE', E'Ricerca Aziende', E'/switch.do?page=/RicAziende.do#prefix=/presentation/core/anagrafica/aziende#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.ANA.RICSEDIAZIENDE', E'Ricerca Sedi Aziende', E'/switch.do?page=/RicSediAziende.do#prefix=/presentation/core/anagrafica/aziende#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.ANP.GESPERSONA', E'Gestione Anagrafica Persona', E'/switch.do?page=/GesPersona.do#prefix=/presentation/core/anagrafica/persone#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.ANP.INSPERSONA', E'Inserimento Anagrafica Persona', E'/switch.do?page=/InsPersona.do#prefix=/presentation/core/anagrafica/persone#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.ANP.LSTPERSONE', E'Lista Persone', E'/switch.do?page=/LstPersone.do#prefix=/presentation/core/anagrafica/persone#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.ANP.RICPERSONE', E'Ricerca Persone', E'/switch.do?page=/RicPersone.do#prefix=/presentation/core/anagrafica/persone#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.DBG.SNOOP', E'Snoop', E'/switch.do?page=/Snoop.do#prefix=/presentation/core/debug#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.DIZ.GESPROFILO', E'Dizionario Banca Profili - Gestione Profilo', E'/switch.do?page=/GesProfilo.do#prefix=/dizionari/bancaprofili#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.DIZ.INSPROFILO', E'Dizionario Banca Profili - Inserimento Profilo', E'/switch.do?page=/InsProfilo.do#prefix=/dizionari/bancaprofili#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.DIZ.LSTPROFILI', E'Dizionario Banca Profili - Lista Profili', E'/switch.do?page=/LstProfili.do#prefix=/dizionari/bancaprofili#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.DIZ.RICOFILI', E'Dizionario Banca Profili - Ricerca Profili', E'/switch.do?page=/RicProfili.do#prefix=/dizionari/bancaprofili#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.FOR.AUTOINSPERFOR', E'Autoiscrizione Percorso Formativo', E'/switch.do?page=/AutoInsPercorsoFormativo.do#prefix=/presentation/formazione#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.FOR.SELOFFFORM', E'Selezione Offerta Formativa', E'/switch.do?page=/SelOffertaFormativa.do#prefix=/presentation/formazione#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.LKP.LOOKUPATECO', E'Lookup ATECO - ISTAT', E'/switch.do?page=/LookupAteco.do#prefix=/presentation/lookup#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.LKP.LOOKUPAZIENDE', E'Lookup Aziende', E'/switch.do?page=/LookupAziende.do#prefix=/presentation/lookup#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.LKP.LOOKUPCOMUNEDOMICILIO', E'Lookup Comuni Domicilio', E'/switch.do?page=/LookupComuni.do#prefix=/presentation/lookup#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.LKP.LOOKUPCOMUNERESIDENZA', E'Lookup Comuni Residenza', E'/switch.do?page=/LookupComuni.do#prefix=/presentation/lookup#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.LKP.LOOKUPCOMUNI', E'Lookup Comuni Italiani', E'/switch.do?page=/LookupComuni.do#prefix=/presentation/lookup#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.LKP.LOOKUPDATORELAVORO', E'Lookup Datore di Lavoro', E'/switch.do?page=/LookupDatoreLavoro.do#prefix=/presentation/lookup#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.LKP.LOOKUPDATORELAVOROAZIENDA', E'Lookup Datore di Lavoro', E'/switch.do?page=/LookupDatoreLavoro.do#prefix=/presentation/lookup#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.LKP.LOOKUPDESTINATARI', E'Lookup Destinatari su elenchi pagamenti', E'/switch.do?page=/LookupLocalita.do#prefix=/presentation/lookup#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.LKP.LOOKUPELENCODESTINATARI', E'Ricerca Destinatario Elenco', NULL, E'Ricerca Destinatario Elenco', E'SYSTEM',NOW() ),
  (E'ST.LKP.LOOKUPENTI', E'Ricerca Ente  destinatario', NULL, NULL, E'SYSTEM',NOW() ),
  (E'ST.LKP.LOOKUPINTERVENTIPAGAMENTI', E'Lookup Interventi su richieste pagamenti', E'/switch.do?page=/LookupLocalita.do#prefix=/presentation/lookup#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.LKP.LOOKUPLOCALITA', E'Lookup Comuni Italiani/Nazioni Estere', E'/switch.do?page=/LookupLocalita.do#prefix=/presentation/lookup#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.LKP.LOOKUPOLDTITOLISTUDIO', E'Lookup Vecchi Titoli di Studio', E'/switch.do?page=/LookupOldTitoliStudio.do#prefix=/presentation/lookup#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.LKP.LOOKUPQUALIFICHEPROFESSIONALI', E'Lookup Qualifiche Professionali', E'/switch.do?page=/LookupQualificheProfessionali.do#prefix=/presentation/lookup#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.LKP.LOOKUPSTRUMENTI', E'Lookup Strumenti', E'/switch.do?page=/LookupStrumenti.do#prefix=/presentation/lookup#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.LKP.LOOKUPTIPOLOGIESERVIZIO', E'Lista tipologie di servizio', E'/switch.do?page=/RicSemplicePersone.do#prefix=/presentation/ido/selezione#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.LKP.LOOKUPTITOLISTUDIO', E'Lista Titoli di Studio', E'-', E'-', E'SYSTEM',NOW() ),
  (E'ST.LOOKUP', E'Motore Lookup', E'/switch.do?page=/Lookup.do#prefix=/presentation/lookup#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.PUB.SIC.INSISCRIZIONEPERSONA', E'Iscrizione Persona Anonima', NULL, E'Iscrizione Persona Anonima', E'SYSTEM',NOW() ),
  (E'ST.REP.EXTDATIEXCEL', E'Estrazione Dati Excel', E'/switch.do?page=/ExtractDatiExcel.do#prefix=/presentation/report#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.REP.GESREPORT', E'Gestione Anagrafica Report', E'/switch.do?page=/GesReport.do#prefix=/presentation/report#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.REP.INSREPORT', E'Inserimento Anagrafica Report', E'/switch.do?page=/InsReport.do#prefix=/presentation/report#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.REP.LSTREPORT', E'Lista Report', E'/switch.do?page=/LstReport.do#prefix=/presentation/report#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.REP.REPORTADESMENS', E'Report Adesioni Mensili', E'/switch.do?page=/ReportAdesMens.do#prefix=/presentation/report#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.REP.REPORTADESMENSREG', E'Report Regionale Adesioni Mensili', E'/switch.do?page=/ReportAdesMensReg.do#prefix=/presentation/report#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.REP.REPORTANAGPAGFILE', E'Estrazioni anagrafica pagamenti', E'-', E'-', E'SYSTEM',NOW() ),
  (E'ST.REP.REPORTAZI001', E'Report Aziende 001', E'/switch.do?page=/ReportAziende001.do#prefix=/presentation/report#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.REP.REPORTAZI002', E'Report Aziende 002', E'/switch.do?page=/ReportAziende002.do#prefix=/presentation/report#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.REP.REPORTAZI003', E'Report Aziende 003', E'/switch.do?page=/ReportAziende003.do#prefix=/presentation/report#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.REP.REPORTAZILEGALE001', E'Report Aziende sede legale 001', E'/switch.do?page=/ReportAziendeLegale001.do#prefix=/presentation/report#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.REP.REPORTAZILEGALE002', E'Report Aziende sede legale 002', E'/switch.do?page=/ReportAziendeLegale002.do#prefix=/presentation/report#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.REP.REPORTAZILEGALE003', E'Report Aziende sede legale 003', E'/switch.do?page=/ReportAziendeLegale003.do#prefix=/presentation/report#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.REP.REPORTBIL001', E'Report Bilancio di ProssimitÃ  001', E'/switch.do?page=/ReportBilancio001.do#prefix=/presentation/report#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.REP.REPORTBIL002', E'Report Bilancio di ProssimitÃ  002', E'/switch.do?page=/ReportBilancio002.do#prefix=/presentation/report#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.REP.REPORTBIL003', E'Report Bilancio di ProssimitÃ  003', E'/switch.do?page=/ReportBilancio003.do#prefix=/presentation/report#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.REP.REPORTCOMP001', E'Report Portafoglio Competenze 001', E'/switch.do?page=/ReportCompetenze001.do#prefix=/presentation/report#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.REP.REPORTCOMP002', E'Report Portafoglio Competenze 002', E'/switch.do?page=/ReportCompetenze002.do#prefix=/presentation/report#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.REP.REPORTCOMP003', E'Report Portafoglio Competenze 003', E'/switch.do?page=/ReportCompetenze003.do#prefix=/presentation/report#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.REP.REPORTCONV001', E'CONVENZIONI ATTIVE', NULL, NULL, E'SYSTEM',NOW() ),
  (E'ST.REP.REPORTCONV002', E'CONVENZIONI ATTIVE', NULL, NULL, E'SYSTEM',NOW() ),
  (E'ST.REP.REPORTCONV003', E'CONVENZIONI ATTIVE (NAZIONALE)', NULL, NULL, E'SYSTEM',NOW() ),
  (E'ST.REP.REPORTCONVFILE', E'REPORT CONVENZIONI E TIROCINI ALLA DATA (FILE)', NULL, NULL, E'SYSTEM',NOW() ),
  (E'ST.REP.REPORTCONVOCAZIONI', E'Report Convocazioni per motivo ed esito', NULL, NULL, E'SYSTEM',NOW() ),
  (E'ST.REP.REPORTCONVSTIP001', E'CONVENZIONI STIPULATE', NULL, NULL, E'SYSTEM',NOW() ),
  (E'ST.REP.REPORTCONVSTIP002', E'CONVENZIONI STIPULATE', NULL, NULL, E'SYSTEM',NOW() ),
  (E'ST.REP.REPORTCONVSTIP003', E'CONVENZIONI STIPULATE (NAZIONALE)', NULL, NULL, E'SYSTEM',NOW() ),
  (E'ST.REP.REPORTCONVTIR001', E'CONVENZIONI E TIROCINI', NULL, NULL, E'SYSTEM',NOW() ),
  (E'ST.REP.REPORTCONVTIR002', E'CONVENZIONI E TIROCINI', NULL, NULL, E'SYSTEM',NOW() ),
  (E'ST.REP.REPORTCONVTIR003', E'CONVENZIONI E TIROCINI (NAZIONALE)', NULL, NULL, E'SYSTEM',NOW() ),
  (E'ST.REP.REPORTDETRPAGFILE', E'Estrazioni detrazioni', E'-', E'-', E'SYSTEM',NOW() ),
  (E'ST.REP.REPORTISCAZIENDESTATO', E'Report Iscrizioni aziende - stato di avanzamento', NULL, NULL, E'SYSTEM',NOW() ),
  (E'ST.REP.REPORTISCAZIENDESTATO.ESTRAI', E'Estrai dati Report Iscrizioni aziende', NULL, NULL, E'SYSTEM',NOW() ),
  (E'ST.REP.REPORTISCSTATO', E'Report Iscrizioni - stato di avanzamento', NULL, NULL, E'SYSTEM',NOW() ),
  (E'ST.REP.REPORTISCSTATO.ESTRAI', E'Estrai dati Report Iscrizioni persone', NULL, NULL, E'SYSTEM',NOW() ),
  (E'ST.REP.REPORTLAV001', E'Report Lavoratori 001', E'/switch.do?page=/ReportLav001.do#prefix=/presentation/report#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.REP.REPORTLAV002', E'Report Lavoratori 002', E'/switch.do?page=/ReportLav002.do#prefix=/presentation/report#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.REP.REPORTLAV003', E'Report Lavoratori 003', E'/switch.do?page=/ReportLav003.do#prefix=/presentation/report#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.REP.REPORTLAVCITT', E'Report Lavoratori in archivio per cittadinanza', NULL, NULL, E'SYSTEM',NOW() ),
  (E'ST.REP.REPORTLAVDOM', E'Report Lavoratori in archivio per domicilio', NULL, NULL, E'SYSTEM',NOW() ),
  (E'ST.REP.REPORTLAVENTECOMP', E'Report Lavoratori per servizio competente', NULL, NULL, E'SYSTEM',NOW() ),
  (E'ST.REP.REPORTLAVFUOR', E'Report Lavoratori fuoriusciti dal bacino', NULL, NULL, E'SYSTEM',NOW() ),
  (E'ST.REP.REPORTLAVRES', E'Report Lavoratori in archivio per residenza', NULL, NULL, E'SYSTEM',NOW() ),
  (E'ST.REP.REPORTLIVAMM001', E'Report Livello Ammortizzatori Sociali 001', E'/switch.do?page=/ReportLivelloAmmSoc001.do#prefix=/presentation/report#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.REP.REPORTLIVAMM002', E'Report Livello Ammortizzatori Sociali 002', E'/switch.do?page=/ReportLivelloAmmSoc002.do#prefix=/presentation/report#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.REP.REPORTLIVAMM003', E'Report Livello Ammortizzatori Sociali 003', E'/switch.do?page=/ReportLivelloAmmSoc003.do#prefix=/presentation/report#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.REP.REPORTLIVSTU001', E'Report Livello Studio 001', E'/switch.do?page=/ReportLivStu001.do#prefix=/presentation/report#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.REP.REPORTLIVSTU002', E'Report Livello Studio 002', E'/switch.do?page=/ReportLivStu002.do#prefix=/presentation/report#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.REP.REPORTLIVSTU003', E'Report Livello Studio 003', E'/switch.do?page=/ReportLivStu003.do#prefix=/presentation/report#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.REP.REPORTPAI001', E'Report PAI 001', E'/switch.do?page=/ReportPAI001.do#prefix=/presentation/report#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.REP.REPORTPAI002', E'Report PAI 002', E'/switch.do?page=/ReportPAI002.do#prefix=/presentation/report#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.REP.REPORTPAI003', E'Report PAI 003', E'/switch.do?page=/ReportPAI003.do#prefix=/presentation/report#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.REP.REPORTPAIATTDOM', E'Report PAI attivi per domicilio', NULL, NULL, E'SYSTEM',NOW() ),
  (E'ST.REP.REPORTPAIATTRES', E'Report PAI attivi per residenza', NULL, NULL, E'SYSTEM',NOW() ),
  (E'ST.REP.REPORTPAISTATODOM', E'Report PAI per stato di attivazione e domicilio', NULL, NULL, E'SYSTEM',NOW() ),
  (E'ST.REP.REPORTPAISTATORES', E'Report PAI per stato di attivazione e residenza', NULL, NULL, E'SYSTEM',NOW() ),
  (E'ST.REP.REPORTPDS003', E'Report PDS 003', E'/switch.do?page=/ReportPds003.do#prefix=/presentation/report#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.REP.REPORTPDSRIF002', E'Report PDS Rifiutati 002', E'/switch.do?page=/ReportPdsRif003.do#prefix=/presentation/report#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.REP.REPORTPDSRIF003', E'Report PDS Rifiutati 003', E'/switch.do?page=/ReportPdsRif003.do#prefix=/presentation/report#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.REP.REPORTPDSTIP002', E'Report PDS Tipologia 002', E'/switch.do?page=/ReportPdsTip003.do#prefix=/presentation/report#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.REP.REPORTPDSTIP003', E'Report PDS Tipologia 003', E'/switch.do?page=/ReportPdsTip003.do#prefix=/presentation/report#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.REP.REPORTPERCADES', E'Report Percentuali Adesioni', E'/switch.do?page=/ReportPercAdes.do#prefix=/presentation/report#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.REP.REPORTPERCADESNAZ', E'Perc adesioni', NULL, E'-', E'SYSTEM',NOW() ),
  (E'ST.REP.REPORTPERCADESREG', E'Report Regionale Percentuali Adesioni', E'/switch.do?page=/ReportPercAdesReg.do#prefix=/presentation/report#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.REP.REPORTPLSQL', E'Report PL/SQL', E'/switch.do?page=/ReportPlSql.do#prefix=/presentation/report#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.REP.REPORTSUSSIDI', E'Report Incentivi in erogazione', NULL, NULL, E'SYSTEM',NOW() ),
  (E'ST.REP.REPORTSUSSIDIFILE', E'Report Incentivi erogati (FILE)', NULL, NULL, E'SYSTEM',NOW() ),
  (E'ST.REP.REPORTTIPAMM001', E'Report Tipo Ammortizzatori Sociali 001', E'/switch.do?page=/ReportTipoAmmSoc001.do#prefix=/presentation/report#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.REP.REPORTTIPAMM002', E'Report Tipo Ammortizzatori Sociali 002', E'/switch.do?page=/ReportTipoAmmSoc002.do#prefix=/presentation/report#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.REP.REPORTTIPAMM003', E'Report Tipo Ammortizzatori Sociali 003', E'/switch.do?page=/ReportTipoAmmSoc003.do#prefix=/presentation/report#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.REP.REPORTTIR001', E'TIROCINI ATTIVI', NULL, NULL, E'SYSTEM',NOW() ),
  (E'ST.REP.REPORTTIR002', E'TIROCINI ATTIVI', NULL, NULL, E'SYSTEM',NOW() ),
  (E'ST.REP.REPORTTIR003', E'TIROCINI ATTIVI (NAZIONALE)', NULL, NULL, E'SYSTEM',NOW() ),
  (E'ST.REP.REPORTTIRCCCSETTORE', E'Report Tirocini conclusi con contratto per settore', NULL, NULL, E'SYSTEM',NOW() ),
  (E'ST.REP.REPORTTIRCCCSETTORE.ESTRAI', E'Estrai dati Report Tirocini conclusi con contratto', NULL, NULL, E'SYSTEM',NOW() ),
  (E'ST.REP.REPORTTIRCONCFILE', E'Report Tirocini Conclusi (FILE)', NULL, NULL, E'SYSTEM',NOW() ),
  (E'ST.REP.REPORTTIRCONCLUSI002', E'Report Tirocini Conclusi', NULL, NULL, E'SYSTEM',NOW() ),
  (E'ST.REP.REPORTTIRCONCLUSI003', E'Report Tirocini Conclusi', NULL, NULL, E'SYSTEM',NOW() ),
  (E'ST.REP.REPORTTIRCONCLUSICC', E'Report Tirocini conclusi con contratto', NULL, NULL, E'SYSTEM',NOW() ),
  (E'ST.REP.REPORTTIRCONCLUSIINT003', E'Report Tirocini Conclusi per intermediario (nazionale)', NULL, NULL, E'SYSTEM',NOW() ),
  (E'ST.REP.REPORTTIRCONT001', E'TIROCINI CONTRATTUALIZZATI', NULL, NULL, E'SYSTEM',NOW() ),
  (E'ST.REP.REPORTTIRCONT002', E'TIROCINI CONTRATTUALIZZATI', NULL, NULL, E'SYSTEM',NOW() ),
  (E'ST.REP.REPORTTIRCONT003', E'TIROCINI CONTRATTUALIZZATI (NAZIONALE)', NULL, NULL, E'SYSTEM',NOW() ),
  (E'ST.REP.REPORTTIRCONT003.ESTRAITIROCINI', E'Estrai tirocini Report Tirocini contrattualizzati', NULL, NULL, E'SYSTEM',NOW() ),
  (E'ST.REP.REPORTTIRCONT003.ESTRTIROCINANTI', E'Estrai tirocinanti Report Tirocini contrattualizzati', NULL, NULL, E'SYSTEM',NOW() ),
  (E'ST.REP.REPORTTIRCONTCITT', E'Report tirocini contrattualizzati per cittadinanza', NULL, NULL, E'SYSTEM',NOW() ),
  (E'ST.REP.REPORTTIRCONTETA001', E'TIROCINI CONTRATTUALIZZATI PER ETA'' E SESSO', NULL, NULL, E'SYSTEM',NOW() ),
  (E'ST.REP.REPORTTIRCONTETA002', E'TIROCINI CONTRATTUALIZZATI PER ETA'' E SESSO', NULL, NULL, E'SYSTEM',NOW() ),
  (E'ST.REP.REPORTTIRCONTETA003', E'TIROCINI CONTRATTUALIZZATI PER ETA'' E SESSO (NAZIONALE)', NULL, NULL, E'SYSTEM',NOW() ),
  (E'ST.REP.REPORTTIRCONTINT003', E'TIROCINI CONTRATTUALIZZATI PER INTERMEDIARIO (NAZIONALE)', NULL, NULL, E'SYSTEM',NOW() ),
  (E'ST.REP.REPORTTIRINIZIATI', E'Report Tirocini Iniziati', NULL, NULL, E'SYSTEM',NOW() ),
  (E'ST.REP.REPORTTIRINT003', E'TIROCINI ATTIVI PER INTERMEDIARIO (NAZIONALE)', NULL, NULL, E'SYSTEM',NOW() ),
  (E'ST.REP.RICREPORT', E'Ricerca Report', E'/switch.do?page=/RicReport.do#prefix=/presentation/report#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.SIC.CAMBIOPASSWORD', E'Cambio Password', E'/switch.do?page=/UpdPassword.do#prefix=/presentation/core/sicurezza#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.SIC.GESISCRIZIONEAZIENDA', E'Gestione Iscrizione Azienda', E'/switch.do?page=/GesIscrizioneAzienda.do#prefix=/presentation/sicurezza/iscrizioni#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.SIC.GESISCRIZIONEPERSONA', E'Gestione Iscrizione Persona', E'/switch.do?page=/GesIscrizionePersona.do#prefix=/presentation/sicurezza/iscrizioni#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.SIC.GESUTENTE', E'Gestione Utente', E'/switch.do?page=/GesUtente.do#prefix=/presentation/core/sicurezza#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.SIC.INSISCRIZIONEAZIENDA', E'Inserimento Iscrizione Azienda', E'/switch.do?page=/InsIscrizioneAzienda.do#prefix=/presentation/sicurezza/iscrizioni#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.SIC.INSISCRIZIONEPERSONA', E'Inserimento Iscrizione Persona', E'/switch.do?page=/InsIscrizionePersona.do#prefix=/presentation/sicurezza/iscrizioni#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.SIC.INSISCRIZIONEPERSONABATCH', E'Inserimento Iscrizione Persona Batch', E'/switch.do?page=/InsIscrizionePersonaBatch.do#prefix=/presentation/sicurezza/iscrizioni#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.SIC.INSUTENTE', E'Inserimento Utente', E'/switch.do?page=/InsUtente.do#prefix=/presentation/core/sicurezza#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.SIC.LOGIN', E'Login Applicazione', E'/switch.do?page=/Login.do#prefix=/presentation/core/sicurezza#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.SIC.LOGOUT', E'Logout Applicazione', E'/switch.do?page=/Logout.do#prefix=/presentation/core/sicurezza#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.SIC.LSTISCRIZIONEPERSONA', E'LST. ISCRIZIONE PERSONA', NULL, NULL, E'SYSTEM',NOW() ),
  (E'ST.SIC.LSTISCRIZIONIAZIENDA', E'Lista Iscrizioni Azienda', E'/switch.do?page=/LstIscrizioniAzienda.do#prefix=/presentation/sicurezza/iscrizioni#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.SIC.LSTISCRIZIONIAZIENDAI', E'Lista Iscrizioni Azienda', E'/switch.do?page=/LstIscrizioniAzienda.do#prefix=/presentation/sicurezza/iscrizioni#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.SIC.LSTISCRIZIONIAZIENDAR', E'Lista Aziende Respinte', E'/switch.do?page=/LstIscrizioniAzienda.do#prefix=/presentation/sicurezza/iscrizioni#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.SIC.LSTISCRIZIONIAZIENDAV', E'Lista Aziende Validate', E'/switch.do?page=/LstIscrizioniAzienda.do#prefix=/presentation/sicurezza/iscrizioni#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.SIC.LSTISCRIZIONIPERSONA', E'Lista Iscrizioni Persona', E'/switch.do?page=/LstIscrizioniPersona.do#modo_strumento=#prefix=/presentation/sicurezza/iscrizioni#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.SIC.LSTISCRIZIONIPERSONAD', E'Lista Persone Idoneee', NULL, E'-', E'SYSTEM',NOW() ),
  (E'ST.SIC.LSTISCRIZIONIPERSONAI', E'Lista Persone Iscritte', E'/switch.do?page=/LstIscrizioniPersona.do#modo_strumento=I#prefix=/presentation/sicurezza/iscrizioni#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.SIC.LSTISCRIZIONIPERSONAP', E'Lista Iscrizioni non completate', NULL, E'-', E'SYSTEM',NOW() ),
  (E'ST.SIC.LSTISCRIZIONIPERSONAR', E'Lista Persone Respinte', E'/switch.do?page=/LstIscrizioniPersona.do#modo_strumento=R#prefix=/presentation/sicurezza/iscrizioni#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.SIC.LSTISCRIZIONIPERSONAV', E'Lista Persone Validate', E'/switch.do?page=/LstIscrizioniPersona.do#modo_strumento=V#prefix=/presentation/sicurezza/iscrizioni#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.SIC.LSTUTENTI', E'Lista Utenti', E'/switch.do?page=/LstUtenti.do#prefix=/presentation/core/sicurezza#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.SIC.MODISCRIZIONEAZIENDA', E'Modifica Iscrizione Azienda', E'/switch.do?page=/ModIscrizioneAzienda.do#prefix=/presentation/sicurezza/iscrizioni#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.SIC.MODISCRIZIONEPERSONA', E'Modifica Iscrizione Persona', E'/switch.do?page=/ModIscrizionePersona.do#prefix=/presentation/sicurezza/iscrizioni#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.SIC.RICISCRIZIONIAZIENDA', E'Ricerca Iscrizioni Azienda', E'/switch.do?page=/RicIscrizioniAzienda.do#prefix=/presentation/sicurezza/iscrizioni#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.SIC.RICISCRIZIONIAZIENDAI', E'Ricerca iscrizioni da validare', E'-', E'-', E'SYSTEM',NOW() ),
  (E'ST.SIC.RICISCRIZIONIAZIENDAR', E'Ricerca iscrizioni respinte', E'-', E'-', E'SYSTEM',NOW() ),
  (E'ST.SIC.RICISCRIZIONIAZIENDAV', E'Ricerca iscrizioni ammesse', E'-', E'-', E'SYSTEM',NOW() ),
  (E'ST.SIC.RICISCRIZIONIPERSONA', E'Ricerca Iscrizioni Persona', E'/switch.do?page=/RicIscrizioniPersona.do#modo_strumento=#prefix=/presentation/sicurezza/iscrizioni#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.SIC.RICISCRIZIONIPERSONAI', E'Ricerca Persone Iscritte', E'/switch.do?page=/RicIscrizioniPersona.do#modo_strumento=I#prefix=/presentation/sicurezza/iscrizioni#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.SIC.RICISCRIZIONIPERSONAR', E'Ricerca Persone Respinta', E'/switch.do?page=/RicIscrizioniPersona.do#modo_strumento=I#prefix=/presentation/sicurezza/iscrizioni#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.SIC.RICISCRIZIONIPERSONAV', E'Ricerca Persone Validate', E'/switch.do?page=/RicIscrizioniPersona.do#modo_strumento=I#prefix=/presentation/sicurezza/iscrizioni#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.SIC.RICISCRIZIONIVALIDATEPERSONA', E'Ricerca Iscrizioni Validate Persona', E'-', E'-', E'SYSTEM',NOW() ),
  (E'ST.SIC.RICUTENTI', E'Ricerca Utenti', E'/switch.do?page=/RicUtenti.do#prefix=/presentation/core/sicurezza#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.SIC.VALISCRIZIONEPERSONA', E'Validazione Iscrizione Persona', E'/switch.do?page=/ValIscrizioniPersona.do#prefix=/presentation/sicurezza/iscrizioni#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.SIC.VISISCRIZIONEAZIENDA', E'Visualizzazione Iscrizione Azienda', E'/switch.do?page=/VisIscrizioneAzienda.do#prefix=/presentation/sicurezza/iscrizioni#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.SIC.VISISCRIZIONEPERSONA', E'Visualizzazione Iscrizione Persona', E'/switch.do?page=/VisIscrizionePersona.do#prefix=/presentation/sicurezza/iscrizioni#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.SPC.BUILDCONDIZXML', E'Costruzione Condizione Regola XML', E'/switch.do?page=/BuilderCondizioneRegolaEL.do#prefix=/presentation/core/regole#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.SPC.BUILDREGOLAXML', E'Costruzione Regola XML', E'/switch.do?page=/BuilderRegolaEL.do#prefix=/presentation/core/regole#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.SPC.GESAPPLICAZIONE', E'Gestione Applicazione', E'/switch.do?page=/GesApplicazione.do#prefix=/presentation/spc/applicazioni#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.SPC.GESPROFILO', E'Gestione Profilo', E'/switch.do?page=/GesProfilo.do#prefix=/presentation/spc/profili#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.SPC.GESREGOLASQL', E'Gestione Regola SQL', E'/switch.do?page=/GesRegola.do#prefix=/presentation/core/regole#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.SPC.GESREGOLAXML', E'Gestione Regola XML', E'/switch.do?page=/GesRegolaEL.do#prefix=/presentation/core/regole#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.SPC.GESSERVIZIOAPPLICAZIONE', E'Gestione Servizio Applicazione', E'/switch.do?page=/GesServizioApplicazione.do#prefix=/presentation/spc/applicazioni#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.SPC.GESSTRUMENTO', E'Gestione Strumento', E'/switch.do?page=/GesStrumento.do#prefix=/presentation/core/spc#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.SPC.INSALLSTRUMENTI', E'Caricamento Strumenti', E'/switch.do?page=/InsAllStrumenti.do#prefix=/presentation/core/spc#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.SPC.INSAPPLICAZIONE', E'Inserimento Applicazione', E'/switch.do?page=/InsApplicazione.do#prefix=/presentation/spc/applicazioni#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.SPC.INSNEWISTANZASERVIZIO', E'Inserimento Nuova Istanza di Servizio Applicazione', E'/switch.do?page=/InsNewIstanzaServizio.do#prefix=/presentation/spc/applicazioni#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.SPC.INSPROFILO', E'Inserimento Profilo', E'/switch.do?page=/InsProfilo.do#prefix=/presentation/spc/profili#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.SPC.INSREGOLASQL', E'Inserimento Regola SQL', E'/switch.do?page=/InsRegola.do#prefix=/presentation/core/regole#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.SPC.INSREGOLAXML', E'Inserimento Regola XML', E'/switch.do?page=/InsRegolaEL.do#prefix=/presentation/core/regole#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.SPC.INSSERVIZIOAPPLICAZIONE', E'Inserimento Servizio Applicazione', E'/switch.do?page=/InsServizioApplicazione.do#prefix=/presentation/spc/applicazioni#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.SPC.INSSTRUMENTO', E'Inserimento Strumento', E'/switch.do?page=/InsStrumento.do#prefix=/presentation/core/spc#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.SPC.LSTAPPLICAZIONI', E'Lista Applicazioni', E'/switch.do?page=/LstApplicazioni.do#prefix=/presentation/spc/applicazioni#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.SPC.LSTPROFILI', E'Lista Profili', E'/switch.do?page=/LstProfili.do#prefix=/presentation/spc/profili#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.SPC.LSTREGOLESQL', E'Lista Regole SQL', E'/switch.do?page=/LstRegole.do#prefix=/presentation/core/regole#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.SPC.LSTREGOLEXML', E'Lista Regole XML', E'/switch.do?page=/LstRegoleEL.do#prefix=/presentation/core/regole#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.SPC.LSTSTRUMENTI', E'Lista Strumenti', E'/switch.do?page=/LstStrumenti.do#prefix=/presentation/core/spc#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.SPC.RICAPPLICAZIONI', E'Ricerca Applicazioni', E'/switch.do?page=/RicApplicazioni.do#prefix=/presentation/spc/applicazioni#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.SPC.RICPROFILI', E'Ricerca Profili', E'/switch.do?page=/RicProfili.do#prefix=/presentation/spc/profili#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.SPC.RICREGOLESQL', E'Ricerca Regole SQL', E'/switch.do?page=/RicRegole.do#prefix=/presentation/core/regole#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.SPC.RICREGOLEXML', E'Ricerca Regole XML', E'/switch.do?page=/RicRegoleEL.do#prefix=/presentation/core/regole#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.SPC.RICSTRUMENTI', E'Ricerca Strumenti', E'/switch.do?page=/RicStrumenti.do#prefix=/presentation/core/spc#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.SPC.UPDMENUAPPLICAZIONE', E'Aggiornamento Menu Applicazione', E'/switch.do?page=/UpdMenuApplicazione.do#prefix=/presentation/spc/applicazioni#metodo=INIT', E'-', E'SYSTEM',NOW() ),
  (E'ST.STARTUP', E'RIAVVIO CONFIGURAZIONE APPLICAZIONE', NULL, NULL, E'SYSTEM',NOW() ),
  (E'SZ.AMM.DATIPAGAMENTO.RECAPITO', E'Dati per pagamento - sezione recapito', E'-', E'-', E'SYSTEM',NOW() ),
  (E'SZ.REP.DOM.LSTENTICOMPETENZA', E'Lista Enti di Competenza per statistiche Azienda', NULL, NULL, E'SYSTEM',NOW() ),
  (E'SZ.REP.OFF.LSTENTICOMPETENZA', E'Lista Enti di Competenza per statistiche Lavoratore', NULL, NULL, E'SYSTEM',NOW() ),
  (E'SZ.REP.REPORTTIRINT', E'Report Tirocini Attivi - sezione Ente', E'-', E'-', E'SYSTEM', NOW()  );