
Insert into DEC_SUSSIDI_ENTE_EROGATORE
   (COD_TIPO_SUSSIDIO, COD_ENTE_EROGATORE)
 Values
   ('RELAR2.001', 'INPS');
Insert into DEC_SUSSIDI_ENTE_EROGATORE
   (COD_TIPO_SUSSIDIO, COD_ENTE_EROGATORE)
 Values
   ('RELAR2.002', 'IL');
Insert into DEC_SUSSIDI_ENTE_EROGATORE
   (COD_TIPO_SUSSIDIO, COD_ENTE_EROGATORE)
 Values
   ('RELAR2.003', 'IL');

