

Insert into DEC_SUSSIDIO
   (COD_TIPO_SUSSIDIO, DES_TIPO_SUSSIDIO, DAT_INIZIO, COD_APPLICAZIONE)
 Values
   ('008', 'Ammortizzatore', TO_DATE('01/01/2001 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'BTG');

