
Insert into DEC_ESITO_CONVOCAZIONE
   (COD_ESITO_CONVOCAZIONE, DES_ESITO_CONVOCAZIONE, DAT_INIZIO, DTT_TMST)
 Values
   ('AI', 'ASSENTE INGIUSTIFICATO', TO_DATE('08/01/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW());
Insert into DEC_ESITO_CONVOCAZIONE
   (COD_ESITO_CONVOCAZIONE, DES_ESITO_CONVOCAZIONE, DAT_INIZIO, DTT_TMST)
 Values
   ('AG', 'ASSENTE GIUSTIFICATO', TO_DATE('08/01/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW());
Insert into DEC_ESITO_CONVOCAZIONE
   (COD_ESITO_CONVOCAZIONE, DES_ESITO_CONVOCAZIONE, DAT_INIZIO, DTT_TMST)
 Values
   ('P', 'PRESENTE', TO_DATE('08/01/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW());
INSERT INTO DEC_ESITO_CONVOCAZIONE (COD_ESITO_CONVOCAZIONE, DES_ESITO_CONVOCAZIONE, DAT_INIZIO, DTT_TMST)
  VALUES ('AN', 'ANNULLATA', TO_DATE('02/01/2016 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NOW());
