
Insert into DEC_TIPOLOGIA_COMPETENZA
   (COD_TIPOLOGIA_COMPETENZA, DES_TIPOLOGIA_COMPETENZA, COD_FONTE, COD_TIPO_FONTE, DTT_TMST, COD_USERAGG)
 Values
   (1, 'Di Base', 0, 'ITA', TO_DATE('11/15/2006 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'FAD');
Insert into DEC_TIPOLOGIA_COMPETENZA
   (COD_TIPOLOGIA_COMPETENZA, DES_TIPOLOGIA_COMPETENZA, COD_FONTE, COD_TIPO_FONTE, DTT_TMST, COD_USERAGG)
 Values
   (2, 'Trasversale', 0, 'ITA', TO_DATE('11/15/2006 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'FAD');
Insert into DEC_TIPOLOGIA_COMPETENZA
   (COD_TIPOLOGIA_COMPETENZA, DES_TIPOLOGIA_COMPETENZA, COD_FONTE, COD_TIPO_FONTE, DTT_TMST, COD_USERAGG)
 Values
   (3, 'Tecnico specialistica', 0, 'ITA', TO_DATE('11/15/2006 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'FAD');

