
Insert into DEC_ESITO_PROPOSTA
   (COD_ESITO_PROPOSTA, DES_ESITO_PROPOSTA, DTT_TMST)
 Values
   ('RCP', 'RIFIUTO CON PERDITA BENEFICI', TO_DATE('09/27/2012 16:25:13', 'MM/DD/YYYY HH24:MI:SS'));
Insert into DEC_ESITO_PROPOSTA
   (COD_ESITO_PROPOSTA, DES_ESITO_PROPOSTA, DTT_TMST)
 Values
   ('RSP', 'RIFIUTO SENZA PERDITA BENEFICI', TO_DATE('09/27/2012 16:25:13', 'MM/DD/YYYY HH24:MI:SS'));
Insert into DEC_ESITO_PROPOSTA
   (COD_ESITO_PROPOSTA, DES_ESITO_PROPOSTA, DTT_TMST)
 Values
   ('ACC', 'ACCETTATA', TO_DATE('09/27/2012 16:25:13', 'MM/DD/YYYY HH24:MI:SS'));

