
Insert into DEC_ENTE_EROGATORE
   (COD_ENTE_EROGATORE, DES_ENTE_EROGATORE, DAT_INIZIO)
 Values
   ('4', 'Comune', TO_DATE('01/01/1950 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into DEC_ENTE_EROGATORE
   (COD_ENTE_EROGATORE, DES_ENTE_EROGATORE, DAT_INIZIO)
 Values
   ('1', 'Provincia', TO_DATE('01/01/1950 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into DEC_ENTE_EROGATORE
   (COD_ENTE_EROGATORE, DES_ENTE_EROGATORE, DAT_INIZIO)
 Values
   ('2', 'Regione', TO_DATE('01/01/1950 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into DEC_ENTE_EROGATORE
   (COD_ENTE_EROGATORE, DES_ENTE_EROGATORE, DAT_INIZIO)
 Values
   ('3', 'Nazione', TO_DATE('01/01/1950 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into DEC_ENTE_EROGATORE
   (COD_ENTE_EROGATORE, DES_ENTE_EROGATORE, DAT_INIZIO)
 Values
   ('INPS', 'Inps', TO_DATE('01/01/1950 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into DEC_ENTE_EROGATORE
   (COD_ENTE_EROGATORE, DES_ENTE_EROGATORE, DAT_INIZIO)
 Values
   ('IL', 'IL', TO_DATE('01/01/1950 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into DEC_ENTE_EROGATORE
   (COD_ENTE_EROGATORE, DES_ENTE_EROGATORE, DAT_INIZIO)
 Values
   ('ALTRO', 'Altro', TO_DATE('01/01/1950 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));

