
Insert into DEC_STATO_PROCEDURA
   (COD_STATO_PROCEDURA, DES_STATO_PROCEDURA, DAT_INIZIO, DTT_TMST)
 Values
   ('RIC', 'Richiesto', TO_DATE('04/01/2010 10:12:15', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into DEC_STATO_PROCEDURA
   (COD_STATO_PROCEDURA, DES_STATO_PROCEDURA, DAT_INIZIO, DAT_FINE, DTT_TMST)
 Values
   ('ANN', 'Posizione annullata', TO_DATE('10/13/2010 11:47:31', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('10/13/2012 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into DEC_STATO_PROCEDURA
   (COD_STATO_PROCEDURA, DES_STATO_PROCEDURA, DAT_INIZIO, DTT_TMST)
 Values
   ('RET', 'Rettificato', TO_DATE('10/13/2010 11:47:31', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into DEC_STATO_PROCEDURA
   (COD_STATO_PROCEDURA, DES_STATO_PROCEDURA, DAT_INIZIO, DTT_TMST)
 Values
   ('RES', 'Posizione respinta', TO_DATE('10/13/2010 11:47:31', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into DEC_STATO_PROCEDURA
   (COD_STATO_PROCEDURA, DES_STATO_PROCEDURA, DAT_INIZIO, DTT_TMST)
 Values
   ('PNA', 'Sospeso o in revisione', TO_DATE('10/13/2010 11:47:31', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into DEC_STATO_PROCEDURA
   (COD_STATO_PROCEDURA, DES_STATO_PROCEDURA, DAT_INIZIO, DTT_TMST)
 Values
   ('PAG', 'Mandato di pagamento eseguito', TO_DATE('10/13/2010 11:47:31', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into DEC_STATO_PROCEDURA
   (COD_STATO_PROCEDURA, DES_STATO_PROCEDURA, DAT_INIZIO, DTT_TMST)
 Values
   ('NOP', 'Pagamento non eseguibile', TO_DATE('10/13/2010 11:47:31', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into DEC_STATO_PROCEDURA
   (COD_STATO_PROCEDURA, DES_STATO_PROCEDURA, DAT_INIZIO, DTT_TMST)
 Values
   ('FEX', 'Inviato ufficio pagamenti', TO_DATE('10/13/2010 11:47:31', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into DEC_STATO_PROCEDURA
   (COD_STATO_PROCEDURA, DES_STATO_PROCEDURA, DAT_INIZIO, DTT_TMST)
 Values
   ('APP', 'Verificato', TO_DATE('10/13/2010 11:47:31', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into DEC_STATO_PROCEDURA
   (COD_STATO_PROCEDURA, DES_STATO_PROCEDURA, DAT_INIZIO, DTT_TMST)
 Values
   ('NPG', 'Verificato. Non pagabile', TO_DATE('08/24/2012 11:47:31', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into DEC_STATO_PROCEDURA
   (COD_STATO_PROCEDURA, DES_STATO_PROCEDURA, DAT_INIZIO, DTT_TMST)
 Values
   ('EXP', 'Estratto per invio ufficio pagamenti', TO_DATE('07/01/2014 10:30:59', 'MM/DD/YYYY HH24:MI:SS'), now());
Insert into DEC_STATO_PROCEDURA
   (COD_STATO_PROCEDURA, DES_STATO_PROCEDURA, DAT_INIZIO, DTT_TMST)
 Values
   ('SIG', 'File SIGMA generati', TO_DATE('11/22/2013', 'MM/DD/YYYY'), now());
Insert into DEC_STATO_PROCEDURA
   (COD_STATO_PROCEDURA, DES_STATO_PROCEDURA, DAT_INIZIO, DTT_TMST)
 Values
   ('EXS', 'Richiesta generazione file SIGMA', TO_DATE('09/01/2017', 'MM/DD/YYYY'), now());   
   
   
