
Insert into DEC_LIV_TIPO_AMMORTIZZATORE
   (COD_LIVELLO_AMMORTIZZATORE, COD_TIPO_AMMORTIZZATORE)
 Values
   ('CIGS', '010');
Insert into DEC_LIV_TIPO_AMMORTIZZATORE
   (COD_LIVELLO_AMMORTIZZATORE, COD_TIPO_AMMORTIZZATORE)
 Values
   ('CIGS', '011');
Insert into DEC_LIV_TIPO_AMMORTIZZATORE
   (COD_LIVELLO_AMMORTIZZATORE, COD_TIPO_AMMORTIZZATORE)
 Values
   ('CIGO', '012');
Insert into DEC_LIV_TIPO_AMMORTIZZATORE
   (COD_LIVELLO_AMMORTIZZATORE, COD_TIPO_AMMORTIZZATORE)
 Values
   ('COSD', '013');
Insert into DEC_LIV_TIPO_AMMORTIZZATORE
   (COD_LIVELLO_AMMORTIZZATORE, COD_TIPO_AMMORTIZZATORE)
 Values
   ('COSD', '014');
Insert into DEC_LIV_TIPO_AMMORTIZZATORE
   (COD_LIVELLO_AMMORTIZZATORE, COD_TIPO_AMMORTIZZATORE)
 Values
   ('MOB', '015');
Insert into DEC_LIV_TIPO_AMMORTIZZATORE
   (COD_LIVELLO_AMMORTIZZATORE, COD_TIPO_AMMORTIZZATORE)
 Values
   ('MOB', '016');
Insert into DEC_LIV_TIPO_AMMORTIZZATORE
   (COD_LIVELLO_AMMORTIZZATORE, COD_TIPO_AMMORTIZZATORE)
 Values
   ('DIS', '017');
Insert into DEC_LIV_TIPO_AMMORTIZZATORE
   (COD_LIVELLO_AMMORTIZZATORE, COD_TIPO_AMMORTIZZATORE)
 Values
   ('DIS', '018');
Insert into DEC_LIV_TIPO_AMMORTIZZATORE
   (COD_LIVELLO_AMMORTIZZATORE, COD_TIPO_AMMORTIZZATORE)
 Values
   ('DIS', '019');
Insert into DEC_LIV_TIPO_AMMORTIZZATORE
   (COD_LIVELLO_AMMORTIZZATORE, COD_TIPO_AMMORTIZZATORE)
 Values
   ('DIS', '020');
Insert into DEC_LIV_TIPO_AMMORTIZZATORE
   (COD_LIVELLO_AMMORTIZZATORE, COD_TIPO_AMMORTIZZATORE)
 Values
   ('DIS', '021');
Insert into DEC_LIV_TIPO_AMMORTIZZATORE
   (COD_LIVELLO_AMMORTIZZATORE, COD_TIPO_AMMORTIZZATORE)
 Values
   ('DIS', '022');
Insert into DEC_LIV_TIPO_AMMORTIZZATORE
   (COD_LIVELLO_AMMORTIZZATORE, COD_TIPO_AMMORTIZZATORE)
 Values
   ('DIS', '023');
Insert into DEC_LIV_TIPO_AMMORTIZZATORE
   (COD_LIVELLO_AMMORTIZZATORE, COD_TIPO_AMMORTIZZATORE)
 Values
   ('DIS', '024');
Insert into DEC_LIV_TIPO_AMMORTIZZATORE
   (COD_LIVELLO_AMMORTIZZATORE, COD_TIPO_AMMORTIZZATORE)
 Values
   ('LSU', '025');

