
Insert into DEC_TIPO_REDDITO
   (COD_TIPO_REDDITO, DES_REDDITO, DAT_INIZIO)
 Values
   ('DIP', 'Lavoro dipendente', TO_DATE('01/01/1950 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into DEC_TIPO_REDDITO
   (COD_TIPO_REDDITO, DES_REDDITO, DAT_INIZIO)
 Values
   ('PEN', 'Pensione', TO_DATE('01/01/1950 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into DEC_TIPO_REDDITO
   (COD_TIPO_REDDITO, DES_REDDITO, DAT_INIZIO)
 Values
   ('AUT', 'Lavoro autonomo', TO_DATE('01/01/1950 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into DEC_TIPO_REDDITO
   (COD_TIPO_REDDITO, DES_REDDITO, DAT_INIZIO)
 Values
   ('ALT', 'Altro reddito', TO_DATE('01/01/1950 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));

