
Insert into DEC_TIPO_AMBITO_CRITERIO
   (COD_TIPO_AMBITO_CRITERIO, DES_TIPO_AMBITO_CRITERIO, DTT_TMST)
 Values
   ('UTE', 'PERSONALE', TO_DATE('07/11/2006 14:34:24', 'MM/DD/YYYY HH24:MI:SS'));
Insert into DEC_TIPO_AMBITO_CRITERIO
   (COD_TIPO_AMBITO_CRITERIO, DES_TIPO_AMBITO_CRITERIO, DTT_TMST)
 Values
   ('REG', 'REGIONALE', TO_DATE('07/11/2006 14:34:24', 'MM/DD/YYYY HH24:MI:SS'));
Insert into DEC_TIPO_AMBITO_CRITERIO
   (COD_TIPO_AMBITO_CRITERIO, DES_TIPO_AMBITO_CRITERIO, DTT_TMST)
 Values
   ('PRV', 'PROVINCIALE', TO_DATE('07/11/2006 14:34:24', 'MM/DD/YYYY HH24:MI:SS'));
Insert into DEC_TIPO_AMBITO_CRITERIO
   (COD_TIPO_AMBITO_CRITERIO, DES_TIPO_AMBITO_CRITERIO, DTT_TMST)
 Values
   ('CPI', 'CPI', TO_DATE('07/11/2006 14:34:24', 'MM/DD/YYYY HH24:MI:SS'));
Insert into DEC_TIPO_AMBITO_CRITERIO
   (COD_TIPO_AMBITO_CRITERIO, DES_TIPO_AMBITO_CRITERIO, DTT_TMST)
 Values
   ('NAZ', 'NAZIONALE', TO_DATE('11/21/2006 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));

