
Insert into TAB_UNITA_TEMPO
   (COD_UNITA_TEMPO, DES_UNITA_TEMPO, DTT_TMST)
 Values
   ('HH', 'ORE', TO_DATE('06/26/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into TAB_UNITA_TEMPO
   (COD_UNITA_TEMPO, DES_UNITA_TEMPO, DTT_TMST)
 Values
   ('GG', 'GIORNI', TO_DATE('06/26/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into TAB_UNITA_TEMPO
   (COD_UNITA_TEMPO, DES_UNITA_TEMPO, DTT_TMST)
 Values
   ('MM', 'MESI', TO_DATE('06/26/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into TAB_UNITA_TEMPO
   (COD_UNITA_TEMPO, DES_UNITA_TEMPO, DTT_TMST)
 Values
   ('AA', 'ANNI', TO_DATE('09/21/2004 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));

