
set search_path to plus_classificazione;


DROP TABLE TAB_ALBO_INTERMEDIARI;
DROP TABLE TAB_ALBI;
DROP TABLE TAB_ATECOLIV2;
DROP TABLE TAB_ESPERIENZELAV;
DROP TABLE TAB_ATECOLIV0;
DROP TABLE TAB_INFORMATICAGRADOCONOSC;
DROP TABLE TAB_INFORMATICACONOSC;
DROP TABLE TAB_FIGURAPROFESS;
DROP TABLE TAB_INTERMEDIARI;
DROP TABLE TAB_ATECOLIV4;
DROP TABLE TAB_ATECOLIV1;
DROP TABLE TABELLA_QUALPROF;
DROP TABLE TAB_INTERMEDIARI_FILIALI;
DROP TABLE TAB_ATECOLIV3;
DROP TABLE TAB_CATEGORIE181;
DROP TABLE TABELLA_ATECO;
DROP TABLE TAB_TIPOATTESTAZ;
DROP TABLE TAB_CATEGORIE_PROTETTE;
DROP TABLE TAB_CCNL;
DROP TABLE TAB_CITTADINANZE;
DROP TABLE TAB_COMUNE_INTERMEDIARI;
DROP TABLE TAB_COMUNI;
DROP TABLE TAB_CONDIZIONE_STATUS;
DROP TABLE TAB_STUDIOTITOLO;
DROP TABLE TAB_STATUS_STRANIERO;
DROP TABLE TAB_LINGUE;
DROP TABLE TAB_TIPOLOGIA_CONTR;
DROP TABLE TAB_TIPOAZIENDA;
DROP TABLE TAB_TIPOPATENTINI;
DROP TABLE TAB_TIPOPATENTIGUIDA;
DROP TABLE TAB_STUDIOLIVELLO;
DROP TABLE TAB_QUALPROFLIV1;
DROP TABLE TAB_STATUSOCCUPAZ;
DROP TABLE TAB_SESSO;
DROP TABLE TAB_REGIONI;
DROP TABLE TAB_RAPPORTILAVORO;
DROP TABLE TAB_QUALPROFLIV4;
DROP TABLE TAB_QUALPROFLIV3;
DROP TABLE TAB_QUALPROFLIV2;
DROP TABLE TAB_LISTESPECIALI;
DROP TABLE TAB_QUALPROFLIV0;
DROP TABLE TAB_PROVINCE;
DROP TABLE TAB_NAZIONI;
DROP TABLE TAB_MOTIVO_PERMESSO;
DROP TABLE TAB_MODALITALAV;
DROP TABLE TAB_LIVCONTRATTUALE;
DROP TABLE TAB_LINGUECONOSCENZA;
DROP TABLE TAB_TIPO_INTERMEDIARIO;
DROP TABLE TAB_AREAPROFESS;
DROP TABLE TAB_AMPIEZZA;
DROP TABLE TAB_ALBO_SEDI;

exit;

