
\echo 'executing script 1102_ddl.create.index.J.sql';

\c :dbName :userj

CREATE UNIQUE INDEX IDX_COD_PERSONA_ISCR_PERS ON ISCRIZIONE_PERSONA
(COD_PERSONA) ;


CREATE UNIQUE INDEX IDX_COD_FISCALE_ISCR_AZIEN ON ISCRIZIONE_AZIENDA
(COD_FISCALE_AZIENDA) ;


CREATE UNIQUE INDEX IDX_COD_USERID_ISCR_AZIEN ON ISCRIZIONE_AZIENDA
(COD_USERID) ;


CREATE UNIQUE INDEX IDX_COD_USERID_ISCR_PERS ON ISCRIZIONE_PERSONA
(COD_USERID) ;