
\echo 'executing script 1103_ddl.create.index.Sill.sql';

\c :dbName :usersill

CREATE UNIQUE INDEX IDX_COD_FISCALE ON DATORE_LAVORO
(COD_FISCALE_AZIENDA) ;



CREATE UNIQUE INDEX IDX_COD_FISCALE_LAVORATORE ON LAVORATORE
(COD_FISCALE_LAVORATORE) ;




CREATE INDEX IDX_DATORE_LAVORO_01 ON DATORE_LAVORO
(COD_FORMAGIURIDICA) ;



CREATE INDEX IDX_DATORE_LAVORO_02 ON DATORE_LAVORO
(DES_DENOMINAZIONE_AZIENDA) ;



CREATE INDEX IDX_DATORE_LAVORO_03 ON DATORE_LAVORO
(DES_COGNOME) ;



CREATE INDEX IDX_DATORE_LAVORO_04 ON DATORE_LAVORO
(DES_NOME) ;



CREATE INDEX IDX_DATORE_LAVORO_05 ON DATORE_LAVORO
(COD_ATECO) ;



CREATE INDEX IDX_DATORE_LAVORO_06 ON DATORE_LAVORO
(COD_INAIL) ;



CREATE INDEX IDX_DATORE_LAVORO_07 ON DATORE_LAVORO
(COD_MATRICOLA_INPS) ;



CREATE INDEX IDX_DAT_LAV_PRT_IVA ON DATORE_LAVORO
(COD_PARTITA_IVA) ;



CREATE INDEX IDX_DAT_NASCITA ON LAVORATORE
(DAT_NASCITA) ;



CREATE INDEX IDX_DES_COGNOME ON LAVORATORE
(DES_COGNOME) ;



CREATE INDEX IDX_DES_NOME ON LAVORATORE
(DES_NOME) ;



CREATE INDEX IDX_DL_SEDE_LEG_COM ON DL_SEDE_LEGALE
(COD_COMUNE, IDE_DATORE_LAVORO) ;



CREATE INDEX IDX_DL_SEDI_LAVORO_01 ON DL_SEDI_LAVORO
(DES_INDIRIZZO) ;



CREATE INDEX IDX_DL_SEDI_LAVORO_02 ON DL_SEDI_LAVORO
(COD_COMUNE) ;


CREATE UNIQUE INDEX IDX_MODULOPAGAMENTO ON ELENCO_MODULO_PAGAMENTO
(IDE_MODULO_PAGAMENTO   ASC) ;


CREATE UNIQUE INDEX IDX_IDE_RICHIESTA_PAGAMENTO ON ELENCO_RICHIESTA_PAGAMENTO
(IDE_RICHIESTA_PAGAMENTO   ASC) ;


CREATE UNIQUE INDEX IDX_ES_AZ_INT_IDE ON ESITO_AZIONE_INTERVENTO
(IDE_ESITO_AZIONE_INTERVENTO, IDE_INTERVENTO) ;



CREATE INDEX IDX_IDE_COD_COMUNE ON LAVORATORE
(COD_COMUNE_DOMICILIO, IDE_LAVORATORE) ;



CREATE UNIQUE INDEX IDX_LAVAZPAI_PAITEMPL ON LAV_AZIONI_PAI
(IDE_PAI, IDE_TEMPLATE_AZIONE_PAI) ;



CREATE INDEX IDX_LAV_AZIENDA_UTILIZZ_ATECO ON LAV_AZIENDA_UTILIZZATRICE
(COD_ATECO_UTIL) ;



CREATE INDEX IDX_LAV_AZIENDA_UTILIZZ_COMUNE ON LAV_AZIENDA_UTILIZZATRICE
(COD_COMUNE_UTIL) ;



CREATE INDEX IDX_LAV_AZIENDA_UTIL_NAZIONE ON LAV_AZIENDA_UTILIZZATRICE
(COD_NAZIONE_UTIL) ;



CREATE INDEX IDX_LAV_ESPERIENZE_PROFESS_01 ON LAV_ESPERIENZE_PROFESSIONALI
(IDE_LAVORATORE) ;





CREATE INDEX IDX_LAV_STATUS_01 ON LAV_STATUS
(IDE_LAVORATORE) ;

CREATE UNIQUE INDEX IDX_ALLEGATI ON ALLEGATI
 (des_path , des_nome_file );
 
 -- 20170802
 CREATE UNIQUE INDEX IDX_NUM_PROTOCOLLO ON DDR
(NUM_DDR   ASC);	

ALTER TABLE DDR_RICHIESTE_PAGAMENTO
ADD CONSTRAINT  IDX_RICHIESTA_PAGAMENTO UNIQUE (IDE_RICHIESTA_PAGAMENTO);
