
\echo 'executing script 1201_ddl.create.foreignkey.Profiler.sql';

\c :dbName :userprof



ALTER TABLE APPL_INT
	ADD CONSTRAINT FK_PRG_SIGMA_APPL_INT FOREIGN KEY (IDE_PRG_SIGMA) REFERENCES plus_dizionari.PRG_SIGMA (IDE_PRG_SIGMA) ;
	


ALTER TABLE FUNZIONE ADD
  CONSTRAINT FK_FUNZIONE_GRUPPO 
 FOREIGN KEY (DES_TIPO_GRUPPO) 
 REFERENCES TIPO_GRUPPO (DES_TIPO_GRUPPO);



ALTER TABLE FUNZIONE ADD
  CONSTRAINT FK_FUNZIONE_STRUMENTO 
 FOREIGN KEY (COD_CODICESTRUMENTO) 
 REFERENCES TAB_STRUMENTO (COD_CODICESTRUMENTO);



ALTER TABLE FUNZIONE_RUOLO_STRUMENTO ADD
  CONSTRAINT FK_FU_RU_ST_RU_ST 
 FOREIGN KEY (COD_CODICESTRUMENTO, COD_CODICERUOLO) 
 REFERENCES RUOLO_STRUMENTO (COD_CODICESTRUMENTO,COD_CODICERUOLO);



ALTER TABLE FUNZIONE_RUOLO_STRUMENTO ADD
  CONSTRAINT FK_FU_RU_ST_FUNZIONE 
 FOREIGN KEY (COD_CODICESTRUMENTO, COD_FUNZIONE) 
 REFERENCES FUNZIONE (COD_CODICESTRUMENTO,COD_FUNZIONE);



ALTER TABLE PROFILO_APPLICAZIONE ADD
  CONSTRAINT FK_PROF_SERV_APP_APPLICAZIONE 
 FOREIGN KEY (COD_APPLICAZIONE) 
 REFERENCES APPLICAZIONE (COD_APPLICAZIONE);



ALTER TABLE PROFILO_APP_RUOLO_STRUMENTO ADD
  CONSTRAINT FK_PR_AP_RU_ST_PR_SE_AP 
 FOREIGN KEY (COD_APPLICAZIONE, COD_CODICEPROFILO) 
 REFERENCES PROFILO_APPLICAZIONE (COD_APPLICAZIONE,COD_CODICEPROFILO);



ALTER TABLE PROFILO_APP_RUOLO_STRUMENTO ADD
  CONSTRAINT FK_PR_AP_RU_ST_RU_ST 
 FOREIGN KEY (COD_CODICESTRUMENTO, COD_CODICERUOLO) 
 REFERENCES RUOLO_STRUMENTO (COD_CODICESTRUMENTO,COD_CODICERUOLO);



ALTER TABLE PROFILO_APP_RUOLO_STRUMENTO ADD
  CONSTRAINT FK_PR_AP_RU_ST_SERVIZIO 
 FOREIGN KEY (COD_CODICESERVIZIO) 
 REFERENCES TAB_SERVIZIO (COD_CODICESERVIZIO);



ALTER TABLE PROFILO_APPLICAZIONE ADD
  CONSTRAINT FK_PR_SE_AP_PROFILO 
 FOREIGN KEY (COD_CODICEPROFILO) 
 REFERENCES TAB_PROFILO (COD_CODICEPROFILO);





ALTER TABLE REGOLA_APPLICAZIONE ADD
  CONSTRAINT E_SOGGETTA 
 FOREIGN KEY (COD_APPLICAZIONE) 
 REFERENCES APPLICAZIONE (COD_APPLICAZIONE);



ALTER TABLE APPL_INT ADD
  CONSTRAINT FK_APINPRRE_APPL 
 FOREIGN KEY (COD_APPLICAZIONE) 
 REFERENCES APPLICAZIONE (COD_APPLICAZIONE)
    ON DELETE CASCADE;



ALTER TABLE APPL_INT ADD
  CONSTRAINT FK_APINPRRE_INTER 
 FOREIGN KEY (COD_INTERMEDIARIO) 
 REFERENCES plus_classificazione.TAB_INTERMEDIARI (COD_INTERMEDIARIO)
    ON DELETE CASCADE;



ALTER TABLE REGOLA_APPLICAZIONE ADD
  CONSTRAINT FK_REGOLA_APPLICAZIONE_REGOLA 
 FOREIGN KEY (IDE_REGOLA) 
 REFERENCES REGOLA (IDE_REGOLA);



ALTER TABLE REGOLA_APPLICAZIONE_SERVIZIO ADD
  CONSTRAINT FK_SERVIZIO_REG_APP_SER 
 FOREIGN KEY (COD_CODICESERVIZIO) 
 REFERENCES TAB_SERVIZIO (COD_CODICESERVIZIO);



ALTER TABLE REGOLA_PROFILO_FUNZIONE ADD
  CONSTRAINT FK_RE_PR_FU_APPLICAZIONE 
 FOREIGN KEY (COD_APPLICAZIONE) 
 REFERENCES APPLICAZIONE (COD_APPLICAZIONE);




ALTER TABLE REGOLA_PROFILO_FUNZIONE ADD
  CONSTRAINT FK_RE_PR_FU_REGOLA 
 FOREIGN KEY (IDE_REGOLA) 
 REFERENCES REGOLA (IDE_REGOLA);



ALTER TABLE REGOLA ADD
  CONSTRAINT FK_TIPO_GRUPPO_REGOLA 
 FOREIGN KEY (DES_TIPO_GRUPPO) 
 REFERENCES TIPO_GRUPPO (DES_TIPO_GRUPPO)
    ON DELETE CASCADE;



ALTER TABLE REGOLA_PROFILO_FUNZIONE ADD
  CONSTRAINT FK_RE_PR_FU_SERVIZIO 
 FOREIGN KEY (COD_CODICESERVIZIO) 
 REFERENCES TAB_SERVIZIO (COD_CODICESERVIZIO);




ALTER TABLE REGOLA_APPLICAZIONE_SERVIZIO ADD
  CONSTRAINT FK_REG_APP_REG_APP_SER 
 FOREIGN KEY (COD_APPLICAZIONE, IDE_REGOLA) 
 REFERENCES REGOLA_APPLICAZIONE (COD_APPLICAZIONE,IDE_REGOLA);



ALTER TABLE TAB_SERVIZIO ADD
  CONSTRAINT FK_SERVIZIO_STRUMENTO 
 FOREIGN KEY (COD_CODICESTRUMENTO) 
 REFERENCES TAB_STRUMENTO (COD_CODICESTRUMENTO);



ALTER TABLE REGOLA_PROFILO_FUNZIONE ADD
  CONSTRAINT FK_RE_PR_FU_PROFILO 
 FOREIGN KEY (COD_CODICEPROFILO) 
 REFERENCES TAB_PROFILO (COD_CODICEPROFILO);



ALTER TABLE SOGGETTO_PROFILO_APPLICAZIONE ADD
  FOREIGN KEY (COD_APPLICAZIONE, COD_CODICEPROFILO) 
 REFERENCES PROFILO_APPLICAZIONE (COD_APPLICAZIONE,COD_CODICEPROFILO)
    ON DELETE SET NULL;



ALTER TABLE REGOLA_PROFILO_FUNZIONE ADD
  CONSTRAINT FK_RE_PR_FU_FUNZIONE 
 FOREIGN KEY (COD_CODICESTRUMENTO, COD_FUNZIONE) 
 REFERENCES FUNZIONE (COD_CODICESTRUMENTO,COD_FUNZIONE);



ALTER TABLE RUOLO_STRUMENTO ADD
  CONSTRAINT FK_RUOLO_STRUMENTO_STRUMENTO 
 FOREIGN KEY (COD_CODICESTRUMENTO) 
 REFERENCES TAB_STRUMENTO (COD_CODICESTRUMENTO);



ALTER TABLE CONDIZIONE ADD
  CONSTRAINT FK_REGOLA_CONDIZIONE 
 FOREIGN KEY (IDE_REGOLA) 
 REFERENCES REGOLA (IDE_REGOLA)
    ON DELETE CASCADE;
	
	
	---------------------------
	
ALTER TABLE PROFILO_APP_RUOLO_STRUMENTO ADD 
  CONSTRAINT FK_PR_AP_RU_ST_PROFILO
 FOREIGN KEY (COD_CODICEPROFILO) 
 REFERENCES TAB_PROFILO (COD_CODICEPROFILO);


----------------------


ALTER TABLE STRUMENTO_CATEGORIA ADD
  CONSTRAINT FK_ST_CAT_STRUMENTO 
 FOREIGN KEY (COD_CODICESTRUMENTO) 
 REFERENCES TAB_STRUMENTO (COD_CODICESTRUMENTO);
ALTER TABLE STRUMENTO_CATEGORIA ADD
  CONSTRAINT FK_ST_CA_CATEGORIA 
 FOREIGN KEY (IDE_CODICECATEGORIA) 
 REFERENCES TAB_CATEGORIA (IDE_CODICECATEGORIA);

-- 
-- Foreign Key Constraints for Table PROFILO_RUOLO_STRUMENTO 
-- 

ALTER TABLE PROFILO_RUOLO_STRUMENTO ADD
  CONSTRAINT FK_PR_RU_ST_PROFILO 
 FOREIGN KEY (COD_CODICEPROFILO) 
 REFERENCES TAB_PROFILO (COD_CODICEPROFILO);
 
 
--ALTER TABLE PROFILO_RUOLO_STRUMENTO ADD
--  CONSTRAINT FK_PR_RU_ST_RU_ST 
-- FOREIGN KEY (COD_CODICESTRUMENTO, COD_CODICERUOLO) 
-- REFERENCES RUOLO_STRUMENTO (COD_CODICESTRUMENTO,COD_CODICERUOLO) DISABLE;

