
\echo 'executing script 1202_ddl.create.foreignkey.J.sql';

\c :dbName :userj

ALTER TABLE ISCRIZIONE_AZIENDA ADD
  CONSTRAINT FK_ISCAZI_TABCOMN 
 FOREIGN KEY (COD_COMUNE_NASC_RAPP) 
 REFERENCES PLUS_CLASSIFICAZIONE.TAB_COMUNI (COD_COMUNE)
    ON DELETE CASCADE;



ALTER TABLE SPC_STRUMENTO_FUNZIONE ADD
  CONSTRAINT FK_STRFUN_GRPREG 
 FOREIGN KEY (COD_GRUPPO_REGOLA) 
 REFERENCES SPC_DEC_GRUPPO_REGOLA (COD_GRUPPO_REGOLA)
    ON DELETE CASCADE;



ALTER TABLE ISCRIZIONE_AZIENDA_STATO ADD
  CONSTRAINT FK_ISAZST_STAISC 
 FOREIGN KEY (COD_STATO) 
 REFERENCES plus_dizionari.DEC_STATO_ISCRIZIONE (COD_STATO)
    ON DELETE CASCADE;



ALTER TABLE ISCRIZIONE_PERSONA_ALTREINFO ADD
  CONSTRAINT FK_ISCRPERSALTTITSTU 
 FOREIGN KEY (COD_TITOLOSTUDIO) 
 REFERENCES plus_classificazione.TAB_STUDIOTITOLO (COD_TITOLOSTUDIO)
    ON DELETE CASCADE;



ALTER TABLE ISCRIZIONE_AZIENDA ADD
  CONSTRAINT FK_ISCAZI_TABCOM 
 FOREIGN KEY (COD_COMUNE_SEDELEG) 
 REFERENCES plus_classificazione.TAB_COMUNI (COD_COMUNE)
    ON DELETE CASCADE;



ALTER TABLE SPC_STRUMENTO_RUOLO ADD
  CONSTRAINT FK_STRRUO_STR 
 FOREIGN KEY (COD_STRUMENTO) 
 REFERENCES SPC_STRUMENTO (COD_STRUMENTO)
    ON DELETE CASCADE;




ALTER TABLE ISCRIZIONE_PERSONA_STATO ADD
  CONSTRAINT FK_ISC_PER_STA_ISC_PERS 
 FOREIGN KEY (IDE_ISCRIZIONE_PERSONA) 
 REFERENCES ISCRIZIONE_PERSONA (IDE_ISCRIZIONE_PERSONA)
    ON DELETE CASCADE;





ALTER TABLE ISCRIZIONE_PERSONA_TIPOSERV ADD
  CONSTRAINT FK_ICSRPERSTIPOSERV_ISCRPERS 
 FOREIGN KEY (IDE_ISCRIZIONE_PERSONA) 
 REFERENCES ISCRIZIONE_PERSONA (IDE_ISCRIZIONE_PERSONA)
    ON DELETE CASCADE;





ALTER TABLE ISCRIZIONE_PERSONA_ALTREINFO ADD
  CONSTRAINT FK_ISCRPERSALTLIVSTU 
 FOREIGN KEY (COD_LIVELLOSTUDIO) 
 REFERENCES plus_classificazione.TAB_STUDIOLIVELLO (COD_LIVELLOSTUDIO)
    ON DELETE CASCADE;



ALTER TABLE PERSONA ADD
  CONSTRAINT FK_PERSONASTATOCIVILE 
 FOREIGN KEY (COD_STATO_CIVILE) 
 REFERENCES plus_dizionari.TAB_STATOCIVILE (COD_STATOCIVILE)
    ON DELETE CASCADE;



ALTER TABLE UTENTE_ONLINE ADD
  CONSTRAINT FK_UTENTE_ONLINE_UTENTE 
 FOREIGN KEY (COD_USERID) 
 REFERENCES UTENTE (COD_USERID)
    ON DELETE CASCADE;



ALTER TABLE ISCRIZIONE_AZIENDA ADD
  CONSTRAINT FK_ISCAZI_TABNAZN 
 FOREIGN KEY (COD_NAZIONE_NASC_RAPP) 
 REFERENCES plus_classificazione.TAB_NAZIONI (COD_NAZIONE)
    ON DELETE CASCADE;



ALTER TABLE ISCRIZIONE_PERSONA_STATO ADD
  CONSTRAINT FK_ISCRPERSSTATO 
 FOREIGN KEY (COD_STATO_ISCRIZIONE) 
 REFERENCES plus_dizionari.DEC_STATO_ISCRIZIONE (COD_STATO)
    ON DELETE CASCADE;



ALTER TABLE UTENTE_APPLICAZIONE_PROFILO ADD
  CONSTRAINT FK_UTEAPPPRF_PROFILO 
 FOREIGN KEY (COD_APPLICAZIONE, COD_PROFILO) 
 REFERENCES SPC_APPLICAZIONE_PROFILO (COD_APPLICAZIONE,COD_PROFILO)
    ON DELETE CASCADE;



ALTER TABLE ISCRIZIONE_AZIENDA ADD
  CONSTRAINT FK_ISCRIZIONE_AZIENDA_FORMAGIU 
 FOREIGN KEY (COD_FORMAGIURIDICA) 
 REFERENCES plus_dizionari.TAB_FORMAGIURIDICA (COD_FORMAGIURIDICA);



ALTER TABLE ISCRIZIONE_PERSONA_ALTREINFO ADD
  CONSTRAINT FK_ISCRPERSALTSTATOESP 
 FOREIGN KEY (COD_STATOESPERIENZA) 
 REFERENCES plus_dizionari.TAB_STATOESPERIENZA (COD_STATOESPERIENZA)
    ON DELETE CASCADE;





ALTER TABLE ISCRIZIONE_PERSONA ADD
  CONSTRAINT FK_ISCRPERSCOMUNERES 
 FOREIGN KEY (COD_COMUNE_RESIDENZA) 
 REFERENCES plus_classificazione.TAB_COMUNI (COD_COMUNE)
    ON DELETE CASCADE;



ALTER TABLE ISCRIZIONE_AZIENDA_STATO ADD
  CONSTRAINT FK_ISAZST_ISCAZI 
 FOREIGN KEY (IDE_ISCRIZIONE_AZIENDA) 
 REFERENCES ISCRIZIONE_AZIENDA (IDE_ISCRIZIONE_AZIENDA)
    ON DELETE CASCADE;



ALTER TABLE ISCRIZIONE_PERSONA_ALLEGATI ADD
  CONSTRAINT FK_ISPEAL_ALLEG 
 FOREIGN KEY (IDE_ALLEGATO) 
 REFERENCES :usersill .ALLEGATI (IDE_ALLEGATO)
    ON DELETE CASCADE;



ALTER TABLE ISCRIZIONE_PERSONA ADD
  CONSTRAINT FK_ISCRPERSCOMUNENASC 
 FOREIGN KEY (COD_COMUNE_NASCITA) 
 REFERENCES plus_classificazione.TAB_COMUNI (COD_COMUNE)
    ON DELETE CASCADE;




ALTER TABLE ISCRIZIONE_PERSONA_ALTREINFO ADD
  CONSTRAINT FK_ISC_PER_ALT_ISC_PERS 
 FOREIGN KEY (IDE_ISCRIZIONE_PERSONA) 
 REFERENCES ISCRIZIONE_PERSONA (IDE_ISCRIZIONE_PERSONA)
    ON DELETE CASCADE;



ALTER TABLE SPC_STRUMENTO_RUOLO_FUNZIONE ADD
  CONSTRAINT FK_STRRUOFUN_STRFUN 
 FOREIGN KEY (COD_STRUMENTO, COD_FUNZIONE) 
 REFERENCES SPC_STRUMENTO_FUNZIONE (COD_STRUMENTO,COD_FUNZIONE)
    ON DELETE CASCADE;



ALTER TABLE ISCRIZIONE_PERSONA_ALTREINFO ADD
  CONSTRAINT FK_ISCRPERSALTTIPOFILE 
 FOREIGN KEY (COD_FORMATO_CV) 
 REFERENCES plus_dizionari.DEC_FORMATO_FILE (COD_FORMATO)
    ON DELETE CASCADE;





ALTER TABLE UTENTE ADD
  CONSTRAINT FK_UTE_SOG 
 FOREIGN KEY (IDE_SOGGETTO) 
 REFERENCES SOGGETTO (IDE_SOGGETTO)
    ON DELETE CASCADE;



ALTER TABLE SPC_AUTORIZZAZIONE_FUNZIONALE ADD
  CONSTRAINT FK_AUTHF_APPSERV 
 FOREIGN KEY (COD_APPLICAZIONE, COD_STRUMENTO, PRG_ISTANZA) 
 REFERENCES SPC_APPLICAZIONE_SERVIZIO (COD_APPLICAZIONE,COD_STRUMENTO,PRG_ISTANZA)
    ON DELETE CASCADE;



ALTER TABLE SPC_REGOLA ADD
  CONSTRAINT FK_REG_GRP 
 FOREIGN KEY (COD_GRUPPO_REGOLA) 
 REFERENCES SPC_DEC_GRUPPO_REGOLA (COD_GRUPPO_REGOLA)
    ON DELETE CASCADE;



ALTER TABLE SPC_AUTORIZZAZIONE_FUNZIONALE ADD
  CONSTRAINT FK_AUTHF_STRRUO 
 FOREIGN KEY (COD_STRUMENTO, COD_RUOLO_STRUMENTO) 
 REFERENCES SPC_STRUMENTO_RUOLO (COD_STRUMENTO,COD_RUOLO_STRUMENTO)
    ON DELETE CASCADE;



ALTER TABLE ISCRIZIONE_PERSONA_ALLEGATI ADD
  CONSTRAINT FK_ISPEAL_ISPEAI 
 FOREIGN KEY (IDE_ISCRIZIONE_PERSONA) 
 REFERENCES ISCRIZIONE_PERSONA_ALTREINFO (IDE_ISCRIZIONE_PERSONA)
    ON DELETE CASCADE;



ALTER TABLE ISCRIZIONE_PERSONA_ENTE ADD
  CONSTRAINT FK_ISPEEN_APPL 
 FOREIGN KEY (COD_APPLICAZIONE) 
 REFERENCES SPC_APPLICAZIONE (COD_APPLICAZIONE)
    ON DELETE CASCADE;



ALTER TABLE SPC_APPLICAZIONE_SERVIZIO ADD
  CONSTRAINT FK_APPSTR_APP 
 FOREIGN KEY (COD_APPLICAZIONE) 
 REFERENCES SPC_APPLICAZIONE (COD_APPLICAZIONE)
    ON DELETE CASCADE;



ALTER TABLE ISCRIZIONE_PERSONA_TIPOSERV ADD
  CONSTRAINT FK_ISCRPERSTIPOSERV 
 FOREIGN KEY (COD_TIPOLOGIA_SERVIZIO) 
 REFERENCES plus_dizionari.DEC_TIPOLOGIA_SERVIZIO (COD_TIPOLOGIA_SERVIZIO)
    ON DELETE CASCADE;



ALTER TABLE SPC_APPLICAZIONE_PROFILO ADD
  CONSTRAINT FK_APPPRF_APP 
 FOREIGN KEY (COD_APPLICAZIONE) 
 REFERENCES SPC_APPLICAZIONE (COD_APPLICAZIONE)
    ON DELETE CASCADE;



ALTER TABLE ISCRIZIONE_PERSONA ADD
  CONSTRAINT FK_ISCRPERSCOMUNEDOM 
 FOREIGN KEY (COD_COMUNE_DOMICILIO) 
 REFERENCES plus_classificazione.TAB_COMUNI (COD_COMUNE)
    ON DELETE CASCADE;



ALTER TABLE UTENTE ADD
  CONSTRAINT FK_UTE_REG 
 FOREIGN KEY (COD_REGIONE) 
 REFERENCES plus_classificazione.TAB_REGIONI (COD_REGIONE)
    ON DELETE CASCADE;



ALTER TABLE ISCRIZIONE_PERSONA ADD
  CONSTRAINT FK_ISCRPERSSTATOCIVILE 
 FOREIGN KEY (COD_STATO_CIVILE) 
 REFERENCES plus_dizionari.TAB_STATOCIVILE (COD_STATOCIVILE)
    ON DELETE CASCADE;



ALTER TABLE PERSONA ADD
  CONSTRAINT FK_PERSONACITTADINANZA 
 FOREIGN KEY (COD_CITTADINANZA) 
 REFERENCES plus_classificazione.TAB_CITTADINANZE (COD_CITTADINANZA)
    ON DELETE CASCADE;



ALTER TABLE SPC_STRUMENTO_RUOLO_FUNZIONE ADD
  CONSTRAINT FK_STRRUOFUN_STRRUO 
 FOREIGN KEY (COD_STRUMENTO, COD_RUOLO_STRUMENTO) 
 REFERENCES SPC_STRUMENTO_RUOLO (COD_STRUMENTO,COD_RUOLO_STRUMENTO)
    ON DELETE CASCADE;



ALTER TABLE ISCRIZIONE_PERSONA ADD
  CONSTRAINT FK_ISCRPERSCITTADINANZA 
 FOREIGN KEY (COD_CITTADINANZA) 
 REFERENCES plus_classificazione.TAB_CITTADINANZE (COD_CITTADINANZA)
    ON DELETE CASCADE;



ALTER TABLE ISCRIZIONE_AZIENDA ADD
  CONSTRAINT FK_ISCAZI_TABNAZ 
 FOREIGN KEY (COD_NAZIONE_ESTERA_SEDELEG) 
 REFERENCES plus_classificazione.TAB_NAZIONI (COD_NAZIONE)
    ON DELETE CASCADE;



ALTER TABLE PERSONA ADD
  CONSTRAINT FK_PERSONACOMUNENASC 
 FOREIGN KEY (COD_COMUNE_NASCITA) 
 REFERENCES plus_classificazione.TAB_COMUNI (COD_COMUNE)
    ON DELETE CASCADE;



ALTER TABLE ISCRIZIONE_PERSONA ADD
  CONSTRAINT FK_ISCRPERSSESSO 
 FOREIGN KEY (COD_SESSO) 
 REFERENCES plus_classificazione.TAB_SESSO (COD_SESSO)
    ON DELETE CASCADE;



ALTER TABLE ISCRIZIONE_AZIENDA ADD
  CONSTRAINT FK_ISCAZI_TABAMP 
 FOREIGN KEY (COD_AMPIEZZA) 
 REFERENCES plus_classificazione.TAB_AMPIEZZA (COD_AMPIEZZA)
    ON DELETE CASCADE;



ALTER TABLE SPC_APPLICAZIONE_SERVIZIO ADD
  CONSTRAINT FK_APPSTR_STR 
 FOREIGN KEY (COD_STRUMENTO) 
 REFERENCES SPC_STRUMENTO (COD_STRUMENTO)
    ON DELETE CASCADE;



ALTER TABLE ISCRIZIONE_PERSONA_ENTE ADD
  CONSTRAINT FK_ISPEEN_ISPE 
 FOREIGN KEY (IDE_ISCRIZIONE_PERSONA) 
 REFERENCES ISCRIZIONE_PERSONA (IDE_ISCRIZIONE_PERSONA)
    ON DELETE CASCADE;



ALTER TABLE SPC_AUTORIZZAZIONE_DATI ADD
  CONSTRAINT FK_AUTHD_REGOLAD 
 FOREIGN KEY (IDE_REGOLA_DATI) 
 REFERENCES SPC_REGOLA (IDE_REGOLA)
    ON DELETE CASCADE;


ALTER TABLE SPC_AUTORIZZAZIONE_DATI ADD
  CONSTRAINT FK_AUTHD_PROF 
 FOREIGN KEY (COD_APPLICAZIONE, COD_PROFILO) 
 REFERENCES  SPC_APPLICAZIONE_PROFILO (COD_APPLICAZIONE,COD_PROFILO)
    ON DELETE CASCADE;


ALTER TABLE ISCRIZIONE_AZIENDA ADD
  CONSTRAINT FK_ISCAZI_TABCCNL 
 FOREIGN KEY (COD_CCNL) 
 REFERENCES plus_classificazione.TAB_CCNL (COD_CCNL)
    ON DELETE CASCADE;



ALTER TABLE SPC_AUTORIZZAZIONE_DATI ADD
  CONSTRAINT FK_AUTHD_APP 
 FOREIGN KEY (COD_APPLICAZIONE) 
 REFERENCES SPC_APPLICAZIONE (COD_APPLICAZIONE)
    ON DELETE CASCADE;


ALTER TABLE SPC_REGOLA ADD
  CONSTRAINT FK_REG_TCF 
 FOREIGN KEY (COD_TIPO_CODIFICA_REGOLA) 
 REFERENCES SPC_DEC_TIPO_CODIFICA_REGOLA (COD_TIPO_CODIFICA_REGOLA)
    ON DELETE CASCADE;



ALTER TABLE SPC_STRUMENTO_FUNZIONE ADD
  CONSTRAINT FK_STRFUN_STR 
 FOREIGN KEY (COD_STRUMENTO) 
 REFERENCES SPC_STRUMENTO (COD_STRUMENTO)
    ON DELETE CASCADE;



ALTER TABLE SPC_AUTORIZZAZIONE_DATI ADD
  CONSTRAINT FK_AUTHD_STRFUN 
 FOREIGN KEY (COD_STRUMENTO, COD_FUNZIONE) 
 REFERENCES SPC_STRUMENTO_FUNZIONE (COD_STRUMENTO,COD_FUNZIONE)
    ON DELETE CASCADE;



ALTER TABLE ISCRIZIONE_PERSONA ADD
  CONSTRAINT FK_ISCRPERSNAZIONENASC 
 FOREIGN KEY (COD_NAZIONE_NASCITA) 
 REFERENCES plus_classificazione.TAB_NAZIONI (COD_NAZIONE)
    ON DELETE CASCADE;



ALTER TABLE PERSONA ADD
  CONSTRAINT FK_PERSONASOGG 
 FOREIGN KEY (IDE_SOGGETTO) 
 REFERENCES SOGGETTO (IDE_SOGGETTO)
    ON DELETE CASCADE;



ALTER TABLE SPC_AUTORIZZAZIONE_DATI ADD
  CONSTRAINT FK_AUTHD_UTENTE 
 FOREIGN KEY (COD_UTENTE) 
 REFERENCES UTENTE (COD_USERID)
    ON DELETE CASCADE;



ALTER TABLE UTENTE_APPLICAZIONE_PROFILO ADD
  CONSTRAINT FK_UTEAPPPRF_UTEAPP 
 FOREIGN KEY (COD_USERID, COD_APPLICAZIONE) 
 REFERENCES UTENTE_APPLICAZIONE (COD_USERID,COD_APPLICAZIONE)
    ON DELETE CASCADE;



ALTER TABLE ISCRIZIONE_AZIENDA ADD
  CONSTRAINT FK_ISCAZI_ATECO4 
 FOREIGN KEY (COD_ATECO) 
 REFERENCES plus_classificazione.TAB_ATECOLIV4 (COD_ATECOLIV4)
    ON DELETE CASCADE;



ALTER TABLE SPC_AUTORIZZAZIONE_FUNZIONALE ADD
  CONSTRAINT FK_AUTHF_REGOLA 
 FOREIGN KEY (IDE_REGOLA_BOOLEANA) 
 REFERENCES SPC_REGOLA (IDE_REGOLA)
    ON DELETE CASCADE;


ALTER TABLE SPC_AUTORIZZAZIONE_FUNZIONALE ADD
  CONSTRAINT FK_AUTHF_APPROF 
 FOREIGN KEY (COD_APPLICAZIONE,COD_PROFILO) 
 REFERENCES SPC_APPLICAZIONE_PROFILO (COD_APPLICAZIONE,COD_PROFILO)
    ON DELETE CASCADE;
	

ALTER TABLE UTENTE_APPLICAZIONE ADD
  CONSTRAINT FK_UTEAPP_APP 
 FOREIGN KEY (COD_APPLICAZIONE) 
 REFERENCES SPC_APPLICAZIONE (COD_APPLICAZIONE)
    ON DELETE CASCADE;



ALTER TABLE UTENTE ADD
  CONSTRAINT FK_UTE_PROV 
 FOREIGN KEY (COD_PROVINCIA) 
 REFERENCES plus_classificazione.TAB_PROVINCE (COD_PROVINCIA)
    ON DELETE CASCADE;



ALTER TABLE UTENTE_APPLICAZIONE ADD
  CONSTRAINT FK_UTEAPP_UTE 
 FOREIGN KEY (COD_USERID) 
 REFERENCES UTENTE (COD_USERID)
    ON DELETE CASCADE;



ALTER TABLE SPC_AUTORIZZAZIONE_FUNZIONALE ADD
  CONSTRAINT FK_AUTHF_UTENTE 
 FOREIGN KEY (COD_UTENTE) 
 REFERENCES UTENTE (COD_USERID)
    ON DELETE CASCADE;



ALTER TABLE ENTE ADD
  CONSTRAINT FK_ENTESOGG 
 FOREIGN KEY (IDE_SOGGETTO) 
 REFERENCES SOGGETTO (IDE_SOGGETTO)
    ON DELETE CASCADE;



ALTER TABLE ISCRIZIONE_PERSONA_ALTREINFO ADD
  CONSTRAINT FK_ISCRPERSALTSTATUS 
 FOREIGN KEY (COD_STATUSOCCUPAZ_DICHIARATO) 
 REFERENCES plus_classificazione.TAB_STATUSOCCUPAZ (COD_STATUSOCCUPAZ)
    ON DELETE CASCADE;



ALTER TABLE ENTE ADD
  CONSTRAINT FK_ENTE_DATLAV 
 FOREIGN KEY (IDE_DATORE_LAVORO) 
 REFERENCES :usersill .DATORE_LAVORO (IDE_DATORE_LAVORO)
    ON DELETE CASCADE;



ALTER TABLE PERSONA ADD
  CONSTRAINT FK_PERSONANAZIONENASC 
 FOREIGN KEY (COD_NAZIONE_NASCITA) 
 REFERENCES plus_classificazione.TAB_NAZIONI (COD_NAZIONE)
    ON DELETE CASCADE;



ALTER TABLE ENTE ADD
  CONSTRAINT FK_ENTE_ISCAZI 
 FOREIGN KEY (IDE_ISCRIZIONE_AZIENDA) 
 REFERENCES ISCRIZIONE_AZIENDA (IDE_ISCRIZIONE_AZIENDA)
    ON DELETE CASCADE;




ALTER TABLE PERSONA ADD
  CONSTRAINT FK_PERSONASESSO 
 FOREIGN KEY (COD_SESSO) 
 REFERENCES plus_classificazione.TAB_SESSO (COD_SESSO)
    ON DELETE CASCADE;



ALTER TABLE ISCRIZIONE_AZIENDA_ALTREINFO ADD
  CONSTRAINT FK_ISAZAL_ISCAZI 
 FOREIGN KEY (IDE_ISCRIZIONE_AZIENDA) 
 REFERENCES ISCRIZIONE_AZIENDA (IDE_ISCRIZIONE_AZIENDA)
    ON DELETE CASCADE;
-----------------------------------------
