
\echo 'executing script 1203_ddl.create.foreignkey.Sill.sql';

\c :dbName :usersill



ALTER TABLE RICHIESTA_PAG_STATO_PROCEDURA
	ADD CONSTRAINT FK_RICPAGSTATOPROC_RICPAG FOREIGN KEY (IDE_RICHIESTA_PAGAMENTO) REFERENCES RICHIESTA_PAGAMENTO (IDE_RICHIESTA_PAGAMENTO) ON DELETE CASCADE;

ALTER TABLE LAV_AZIONI_ESITO_PROPOSTA
	ADD CONSTRAINT FK_AZES_DECES FOREIGN KEY (COD_ESITO_PROPOSTA) REFERENCES plus_dizionari.DEC_ESITO_PROPOSTA (COD_ESITO_PROPOSTA) ON DELETE CASCADE;
	
ALTER TABLE RICHIESTA_PAG_STATO_PROCEDURA
	ADD CONSTRAINT FK_DECSTATO_RICPAGSTATOPROC FOREIGN KEY (COD_STATO_PROCEDURA) REFERENCES plus_dizionari.DEC_STATO_PROCEDURA (COD_STATO_PROCEDURA);

ALTER TABLE RICHIESTA_PAGAMENTO
	ADD CONSTRAINT FK_TIPOINCENTIVO_RICPAG FOREIGN KEY (COD_TIPO_INCENTIVO) REFERENCES plus_dizionari.DEC_TIPO_INCENTIVO (COD_TIPO_INCENTIVO);

ALTER TABLE RICHIESTA_PAGAMENTO
	ADD CONSTRAINT FK_INTERMEDIARI_RICPAG FOREIGN KEY (COD_INTERMEDIARIO) REFERENCES plus_classificazione.TAB_INTERMEDIARI (COD_INTERMEDIARIO);

ALTER TABLE RICHIESTA_PAGAMENTO_ALLEGATI
	ADD CONSTRAINT FK_RICPAGALL_RICPAG FOREIGN KEY (IDE_RICHIESTA_PAGAMENTO) REFERENCES RICHIESTA_PAGAMENTO (IDE_RICHIESTA_PAGAMENTO) ON DELETE CASCADE;

ALTER TABLE RICHIESTA_PAGAMENTO_ALLEGATI
	ADD CONSTRAINT FK_ALLEGATI_RICPAGALLEGATI FOREIGN KEY (IDE_ALLEGATO) REFERENCES ALLEGATI (IDE_ALLEGATO) ON DELETE CASCADE;

ALTER TABLE RICHIESTA_PAGAMENTO_PAI
	ADD CONSTRAINT FK_RICPAG_RICPAGPAI FOREIGN KEY (IDE_RICHIESTA_PAGAMENTO) REFERENCES RICHIESTA_PAGAMENTO (IDE_RICHIESTA_PAGAMENTO) ON DELETE CASCADE;

ALTER TABLE RICHIESTA_PAGAMENTO_PAI
	ADD CONSTRAINT FKPAI_RICPAGPAI FOREIGN KEY (IDE_PAI) REFERENCES LAV_PAI (IDE_PAI);

ALTER TABLE RICHIESTA_PAGAMENTO_STATO
	ADD CONSTRAINT FK_RICPAGSTATO_RICPAG FOREIGN KEY (IDE_RICHIESTA_PAGAMENTO) REFERENCES RICHIESTA_PAGAMENTO (IDE_RICHIESTA_PAGAMENTO) ON DELETE CASCADE;

ALTER TABLE RICHIESTA_PAGAMENTO_STATO
	ADD CONSTRAINT FK_DECSTATO_RICPAGSTATO FOREIGN KEY (COD_STATO_DOCUMENTO) REFERENCES plus_dizionari.DEC_STATO_DOCUMENTO (COD_STATO_DOCUMENTO);

ALTER TABLE ELENCO_RICHIESTA_PAGAMENTO
	ADD CONSTRAINT FK_RICPAG_ELENCORICPAG FOREIGN KEY (IDE_RICHIESTA_PAGAMENTO) REFERENCES RICHIESTA_PAGAMENTO (IDE_RICHIESTA_PAGAMENTO);

ALTER TABLE ELENCO_RICHIESTA_PAGAMENTO
	ADD CONSTRAINT FK_ELENCO_ELENCORICPAG FOREIGN KEY (IDE_ELENCO) REFERENCES ELENCO (IDE_ELENCO) ON DELETE CASCADE;

ALTER TABLE TEMPLATE_PAI
	ADD CONSTRAINT FK_TMPPIANO_TIPOPIANO FOREIGN KEY (COD_TIPO_COSTO_PIANO) REFERENCES plus_dizionari.DEC_TIPO_COSTO_PIANO (COD_TIPO_COSTO_PIANO) ON DELETE CASCADE;
	


ALTER TABLE LAV_CATEGORIA181 ADD
  FOREIGN KEY (COD_CATEGORIA181) 
 REFERENCES plus_classificazione.TAB_CATEGORIE181 (COD_CATEGORIA181);



ALTER TABLE LAV_CATEGORIE_PARTICOLARI ADD
  FOREIGN KEY (COD_CATEGORIA) 
 REFERENCES plus_classificazione.TAB_CATEGORIE_PROTETTE (COD_CATEGORIA);



ALTER TABLE LAV_CONOSCENZE_INFORMATICHE ADD
  FOREIGN KEY (COD_GRADOCONOSC) 
 REFERENCES plus_classificazione.TAB_INFORMATICAGRADOCONOSC (COD_GRADOCONOSC);



ALTER TABLE INTERVENTO_SEDE ADD
  CONSTRAINT FK_INTERVENTO_SEDE__INTERVENTO 
 FOREIGN KEY (IDE_INTERVENTO) 
 REFERENCES INTERVENTO (IDE_INTERVENTO)
    ON DELETE CASCADE;


ALTER TABLE LAV_LINGUE_CONOSCIUTE ADD
  FOREIGN KEY (COD_CONOSCENZA_SCRITTA) 
 REFERENCES plus_classificazione.TAB_LINGUECONOSCENZA (COD_CONOSCENZA);



ALTER TABLE LAV_LINGUE_CONOSCIUTE ADD
  FOREIGN KEY (COD_CONOSCENZA_LETTA) 
 REFERENCES plus_classificazione.TAB_LINGUECONOSCENZA (COD_CONOSCENZA);



ALTER TABLE LAV_ESPERIENZE_PROFESSIONALI ADD
  CONSTRAINT FK_LAV_ESP_PROFESS_COMUNI 
 FOREIGN KEY (COD_COMUNE_ESPERIENZA) 
 REFERENCES plus_classificazione.TAB_COMUNI (COD_COMUNE);



ALTER TABLE LAV_STATUS ADD
  FOREIGN KEY (COD_STATUSOCCUPAZ) 
 REFERENCES plus_classificazione.TAB_STATUSOCCUPAZ (COD_STATUSOCCUPAZ);



ALTER TABLE DL_FABBISOGNI_OCCUPAZIONALI ADD
  CONSTRAINT FK_DLFABBOCC_QUALPROFLIV4 
 FOREIGN KEY (COD_QUALPROFLIV4) 
 REFERENCES plus_classificazione.TAB_QUALPROFLIV4 (COD_QUALPROFLIV4)
    ON DELETE SET NULL;



ALTER TABLE LAV_ESPERIENZE_PROFESSIONALI ADD
  CONSTRAINT FK_LAV_ESP_PROFESS_DL_COMUNI 
 FOREIGN KEY (COD_COMUNE_DL) 
 REFERENCES plus_classificazione.TAB_COMUNI (COD_COMUNE)
    ON DELETE SET NULL;



ALTER TABLE LAV_ESPERIENZE_PROFESSIONALI ADD
  CONSTRAINT FK_LAV_ESP_PROFESS_ATECOLIV4 
 FOREIGN KEY (COD_SETTORE_AZIENDA) 
 REFERENCES plus_classificazione.TAB_ATECOLIV4 (COD_ATECOLIV4);




ALTER TABLE LAV_PATTO_SERVIZIO ADD
  CONSTRAINT FK_LAVPATTO_TIPOPATTO 
 FOREIGN KEY (COD_TIPO_PATTO, COD_APPLICAZIONE) 
 REFERENCES plus_dizionari.DEC_TIPO_PATTO (COD_TIPO_PATTO,COD_APPLICAZIONE);



ALTER TABLE ESITO_AZIONE_INTERVENTO ADD
  CONSTRAINT FK_ESAZ_DESAZ 
 FOREIGN KEY (COD_ESITO_AZIONE_PAI) 
 REFERENCES :userdiz.DEC_ESITO_AZIONE_PAI (COD_ESITO_AZIONE_PAI)
    ON DELETE SET NULL;



ALTER TABLE FONDO ADD
  CONSTRAINT FK_FONDO_TIPFON 
 FOREIGN KEY (COD_TIPOLOGIA_FONDO) 
 REFERENCES plus_dizionari.DEC_TIPOLOGIA_FONDO (COD_TIPOLOGIA_FONDO)
    ON DELETE SET NULL;



ALTER TABLE DATORE_LAVORO ADD
  FOREIGN KEY (COD_ATECO) 
 REFERENCES plus_classificazione.TAB_ATECOLIV4 (COD_ATECOLIV4);


ALTER TABLE DL_FABB_COMPETENZE ADD
  FOREIGN KEY (COD_COMPETENZA) 
 REFERENCES plus_dizionari.DEC_COMPETENZE (COD_COMPETENZA)
    ON DELETE SET NULL;




ALTER TABLE LAV_ELEMENTI ADD
  FOREIGN KEY (IDE_LAVORATORE) 
 REFERENCES LAVORATORE (IDE_LAVORATORE)
    ON DELETE CASCADE;



ALTER TABLE LAV_ESPERIENZE_FORMAZIONE ADD
  FOREIGN KEY (IDE_LAVORATORE) 
 REFERENCES LAVORATORE (IDE_LAVORATORE)
    ON DELETE CASCADE;



ALTER TABLE LAV_ESPERIENZE_STUDIO ADD
  FOREIGN KEY (IDE_LAVORATORE) 
 REFERENCES LAVORATORE (IDE_LAVORATORE)
    ON DELETE CASCADE;



ALTER TABLE LAV_ESPERIENZE_FORMAZIONE ADD
  FOREIGN KEY (COD_STATOESPERIENZA) 
 REFERENCES plus_dizionari.TAB_STATOESPERIENZA (COD_STATOESPERIENZA);



ALTER TABLE STRINT_TIPO_TIPOSERV ADD
  CONSTRAINT FK_TITISE_TIPSERV 
 FOREIGN KEY (COD_TIPOLOGIA_SERVIZIO) 
 REFERENCES plus_dizionari.DEC_TIPOLOGIA_SERVIZIO (COD_TIPOLOGIA_SERVIZIO)
    ON DELETE CASCADE;



ALTER TABLE DL_FABB_DISP_MOBILITAGEOG ADD
  FOREIGN KEY (COD_MOBILITAGEOG) 
 REFERENCES plus_dizionari.TAB_MOBILITAGEOG (COD_MOBILITAGEOG)
    ON DELETE SET NULL;



ALTER TABLE LAV_RECAPITI ADD
  FOREIGN KEY (IDE_LAVORATORE) 
 REFERENCES LAVORATORE (IDE_LAVORATORE)
    ON DELETE CASCADE;


ALTER TABLE LAV_REDDITO_DICHIARATO ADD
  FOREIGN KEY (IDE_LAVORATORE) 
 REFERENCES LAVORATORE (IDE_LAVORATORE)
    ON DELETE CASCADE;



ALTER TABLE LAV_STATUS ADD
  FOREIGN KEY (IDE_LAVORATORE) 
 REFERENCES LAVORATORE (IDE_LAVORATORE)
    ON DELETE CASCADE;






ALTER TABLE STRINT_PAGAMENTO ADD
  CONSTRAINT FK_STRPAG_INCENTIVO 
 FOREIGN KEY (COD_TIPO_INCENTIVO) 
 REFERENCES plus_dizionari.DEC_TIPO_INCENTIVO (COD_TIPO_INCENTIVO);





ALTER TABLE STRINT_ATTORE ADD
  FOREIGN KEY (IDE_TIPO_INTERVENTO) 
 REFERENCES STRINT_TIPO (IDE_TIPO_INTERVENTO)
    ON DELETE CASCADE;



ALTER TABLE LAV_ESPERIENZE_FORMAZIONE ADD
  FOREIGN KEY (COD_NAZIONE_ENTE) 
 REFERENCES plus_classificazione.TAB_NAZIONI (COD_NAZIONE);





ALTER TABLE DL_FABB_TITOLO_STUDIO ADD
  FOREIGN KEY (COD_UNITA_TEMPO) 
 REFERENCES plus_dizionari.TAB_UNITA_TEMPO (COD_UNITA_TEMPO)
    ON DELETE SET NULL;



ALTER TABLE DL_FABB_DOMICILIO ADD
  FOREIGN KEY (COD_RIPTERRITORIALE) 
 REFERENCES plus_dizionari.TAB_RIPTERRITORIALE (COD_RIPTERRITORIALE)
    ON DELETE SET NULL;



ALTER TABLE DL_FABB_CONOSC_INFORMATICHE ADD
  FOREIGN KEY (COD_CONOSCENZA) 
 REFERENCES plus_classificazione.TAB_INFORMATICACONOSC (COD_CONOSCENZA)
    ON DELETE SET NULL;



ALTER TABLE DL_FABB_CONOSC_INFORMATICHE ADD
  FOREIGN KEY (COD_GRADOCONOSC) 
 REFERENCES plus_classificazione.TAB_INFORMATICAGRADOCONOSC (COD_GRADOCONOSC)
    ON DELETE SET NULL;



ALTER TABLE MODULO_INTERVENTO_ATTORE ADD
  CONSTRAINT FK_MODINTATT_LAVPAI 
 FOREIGN KEY (IDE_PAI) 
 REFERENCES LAV_PAI (IDE_PAI)
    ON DELETE CASCADE;



ALTER TABLE ELENCO_MODULO_PAGAMENTO ADD
  CONSTRAINT FK_MODPAG_ELENCO_MODPAG 
 FOREIGN KEY (IDE_MODULO_PAGAMENTO) 
 REFERENCES MODULO_PAGAMENTO (IDE_MODULO_PAGAMENTO)
    ON DELETE CASCADE;



ALTER TABLE MODULO_INTATT_ALLEGATI ADD
  CONSTRAINT FK_MOINAL_ALLEGA 
 FOREIGN KEY (IDE_ALLEGATO) 
 REFERENCES ALLEGATI (IDE_ALLEGATO)
    ON DELETE CASCADE;



ALTER TABLE MODULO_INTATT_ALLEGATI ADD
  CONSTRAINT FK_MOINAL_MOINAT 
 FOREIGN KEY (IDE_MODULO_INTERVENTO_ATTORE) 
 REFERENCES MODULO_INTERVENTO_ATTORE (IDE_MODULO_INTERVENTO_ATTORE)
    ON DELETE CASCADE;



ALTER TABLE MODULO_INTERVENTO_ATTORE ADD
  CONSTRAINT FK_MOINAT_DATLAV 
 FOREIGN KEY (IDE_DATORE_LAVORO) 
 REFERENCES DATORE_LAVORO (IDE_DATORE_LAVORO)
    ON DELETE CASCADE;



ALTER TABLE LAV_STATUS_DICH ADD
  CONSTRAINT FK_LASTDI_LAVOR 
 FOREIGN KEY (IDE_LAVORATORE) 
 REFERENCES LAVORATORE (IDE_LAVORATORE)
    ON DELETE CASCADE;



ALTER TABLE LAV_AZIONI_PAI_CONSUNTIVO ADD
  CONSTRAINT FK_LAVAZCOSTO_FONDO 
 FOREIGN KEY (IDE_FONDO) 
 REFERENCES FONDO (IDE_FONDO)
    ON DELETE SET NULL;


alter table LAV_AZIONI_PAI_CONSUNTIVO
  add constraint FK_COMUNI_AZPAICONS foreign key (COD_COMUNE_DOC)
  references plus_classificazione.TAB_COMUNI (COD_COMUNE);
alter table LAV_AZIONI_PAI_CONSUNTIVO
  add constraint FK_NAZIONI_AZPAICONS foreign key (COD_NAZIONE_DOC)
  references plus_classificazione.TAB_NAZIONI (COD_NAZIONE);
alter table LAV_AZIONI_PAI_CONSUNTIVO
  add constraint FK_SESSO_AZPAICONS foreign key (COD_SESSO_DOC)
  references plus_classificazione.TAB_SESSO (COD_SESSO);

ALTER TABLE LAV_RICHIESTA_BONUS ADD
  CONSTRAINT FK_TARGET_RICHBONUS 
 FOREIGN KEY (COD_APPLICAZIONE, COD_TARGET) 
 REFERENCES plus_dizionari.DEC_TARGET (COD_APPLICAZIONE,COD_TARGET)
    ON DELETE SET NULL;



ALTER TABLE LAV_NUCLEO_FAMILIARE ADD
  FOREIGN KEY (IDE_LAVORATORE) 
 REFERENCES LAVORATORE (IDE_LAVORATORE)
    ON DELETE CASCADE;



ALTER TABLE LAV_OBBLIGO_FORMATIVO ADD
  FOREIGN KEY (IDE_LAVORATORE) 
 REFERENCES LAVORATORE (IDE_LAVORATORE)
    ON DELETE CASCADE;



ALTER TABLE LAV_PATENTE ADD
  FOREIGN KEY (IDE_LAVORATORE) 
 REFERENCES LAVORATORE (IDE_LAVORATORE)
    ON DELETE CASCADE;



ALTER TABLE LAV_PATENTINO ADD
  FOREIGN KEY (IDE_LAVORATORE) 
 REFERENCES LAVORATORE (IDE_LAVORATORE)
    ON DELETE CASCADE;



ALTER TABLE LAV_PAI_STATO ADD
  CONSTRAINT FK_LAVPAISTATO_STATODOC 
 FOREIGN KEY (COD_STATO_DOCUMENTO) 
 REFERENCES plus_dizionari.DEC_STATO_DOCUMENTO (COD_STATO_DOCUMENTO);



ALTER TABLE LAV_PATTO_SERVIZIO_STATO ADD
  CONSTRAINT FK_LAVPATST_DECSTATO 
 FOREIGN KEY (COD_STATO_DOCUMENTO) 
 REFERENCES plus_dizionari.DEC_STATO_DOCUMENTO (COD_STATO_DOCUMENTO);



ALTER TABLE MODULO_PAG_STATO_PROCEDURA ADD
  CONSTRAINT FK_MOPASTPR_STAPRO 
 FOREIGN KEY (COD_STATO_PROCEDURA) 
 REFERENCES plus_dizionari.DEC_STATO_PROCEDURA (COD_STATO_PROCEDURA)
    ON DELETE SET NULL;



ALTER TABLE ALLEGATI ADD
  CONSTRAINT FK_ALLEG_DECALL 
 FOREIGN KEY (COD_APPLICAZIONE, COD_ALLEGATO) 
 REFERENCES plus_dizionari.DEC_ALLEGATI (COD_APPLICAZIONE,COD_ALLEGATO)
    ON DELETE CASCADE;



ALTER TABLE APPL_INT_TIPOSERV ADD
  CONSTRAINT FK_APINTS_TIPSERV 
 FOREIGN KEY (COD_TIPOLOGIA_SERVIZIO) 
 REFERENCES plus_dizionari.DEC_TIPOLOGIA_SERVIZIO (COD_TIPOLOGIA_SERVIZIO)
    ON DELETE CASCADE;



ALTER TABLE MODULO_PAGAMENTO ADD
  CONSTRAINT FK_MODPAG_INCENTIVO 
 FOREIGN KEY (COD_TIPO_INCENTIVO) 
 REFERENCES plus_dizionari.DEC_TIPO_INCENTIVO (COD_TIPO_INCENTIVO);



ALTER TABLE LAV_ESPERIENZE_STUDIO ADD
  FOREIGN KEY (COD_STATOESPERIENZA) 
 REFERENCES plus_dizionari.TAB_STATOESPERIENZA (COD_STATOESPERIENZA);



ALTER TABLE DL_FABB_CONOSC_INFORMATICHE ADD
  FOREIGN KEY (IDE_FABB_OCCUPAZIONALI) 
 REFERENCES DL_FABBISOGNI_OCCUPAZIONALI (IDE_FABB_OCCUPAZIONALI)
    ON DELETE CASCADE;



ALTER TABLE DL_FABB_CONOSC_LINGUE ADD
  FOREIGN KEY (IDE_FABB_OCCUPAZIONALI) 
 REFERENCES DL_FABBISOGNI_OCCUPAZIONALI (IDE_FABB_OCCUPAZIONALI)
    ON DELETE CASCADE;



ALTER TABLE DL_FABB_DISP_MOBILITAGEOG ADD
  FOREIGN KEY (IDE_FABB_OCCUPAZIONALI) 
 REFERENCES DL_FABBISOGNI_OCCUPAZIONALI (IDE_FABB_OCCUPAZIONALI)
    ON DELETE CASCADE;



ALTER TABLE DL_FABB_DISP_MODALITALAV ADD
  FOREIGN KEY (IDE_FABB_OCCUPAZIONALI) 
 REFERENCES DL_FABBISOGNI_OCCUPAZIONALI (IDE_FABB_OCCUPAZIONALI)
    ON DELETE CASCADE;



ALTER TABLE DL_FABB_DISP_TIPOCONTRATTO ADD
  FOREIGN KEY (IDE_FABB_OCCUPAZIONALI) 
 REFERENCES DL_FABBISOGNI_OCCUPAZIONALI (IDE_FABB_OCCUPAZIONALI)
    ON DELETE CASCADE;



ALTER TABLE DL_FABB_DOMICILIO ADD
  FOREIGN KEY (IDE_FABB_OCCUPAZIONALI) 
 REFERENCES DL_FABBISOGNI_OCCUPAZIONALI (IDE_FABB_OCCUPAZIONALI)
    ON DELETE CASCADE;



ALTER TABLE DL_FABB_CONOSCENZE_AREE ADD
  FOREIGN KEY (COD_AREA_RIF) 
 REFERENCES plus_dizionari.DEC_AREA_RIFERIMENTO (COD_AREA_RIF)
    ON DELETE SET NULL;



ALTER TABLE STRINT_ATTRIBUTO ADD
  FOREIGN KEY (COD_TIPO_ATTRIBUTO) 
 REFERENCES plus_dizionari.DEC_TIPO_ATTRIBUTO (COD_TIPO_ATTRIBUTO);



ALTER TABLE ELENCO_DESTINATARIO ADD
  CONSTRAINT FK_ELENCO_ELEDEST 
 FOREIGN KEY (IDE_ELENCO) 
 REFERENCES ELENCO (IDE_ELENCO)
    ON DELETE CASCADE;
	

ALTER TABLE ELENCO_DESTINATARIO
	ADD CONSTRAINT FK_COMUNICAP_ELEDEST FOREIGN KEY (COD_COMUNE_SL, COD_CAP_SL) REFERENCES plus_dizionari.TAB_COMUNI_CAP (COD_COMUNE, COD_CAP);


ALTER TABLE ELENCO_DESTINATARIO
	ADD CONSTRAINT FK_SESSO_ELEDEST FOREIGN KEY (COD_SESSO_RAPP) REFERENCES plus_classificazione.TAB_SESSO (COD_SESSO);


ALTER TABLE ELENCO_DESTINATARIO
	ADD CONSTRAINT FK_NAZ_ELEDEST_SL FOREIGN KEY (COD_NAZIONE_SL) REFERENCES plus_classificazione.TAB_NAZIONI (COD_NAZIONE);


ALTER TABLE ELENCO_DESTINATARIO
	ADD CONSTRAINT FK_NAZ_ELEDEST_RAPP FOREIGN KEY (COD_NAZIONE_NASCITA_RAPP) REFERENCES plus_classificazione.TAB_NAZIONI (COD_NAZIONE);


ALTER TABLE ELENCO_DESTINATARIO
	ADD CONSTRAINT FK_COMUNE_ELEDEST FOREIGN KEY (COD_COMUNE_NASCITA_RAPP) REFERENCES plus_classificazione.TAB_COMUNI (COD_COMUNE);
		

ALTER TABLE DL_DISPONIBILITA_INTERVENTI ADD
  FOREIGN KEY (COD_UNITA_TEMPO) 
 REFERENCES plus_dizionari.TAB_UNITA_TEMPO (COD_UNITA_TEMPO)
    ON DELETE SET NULL;



ALTER TABLE LAV_AZIONI_PAI ADD
  CONSTRAINT FK_AZIONIPAI_TEMPAZIONIPAI 
 FOREIGN KEY (IDE_TEMPLATE_AZIONE_PAI) 
 REFERENCES TEMPLATE_AZIONI_PAI (IDE_TEMPLATE_AZIONE_PAI)
    ON DELETE SET NULL;




ALTER TABLE TEMPLATE_AZIONI_PAI_COSTO ADD
  CONSTRAINT FK_TEMPCOSTO_TIPOCOSTO 
 FOREIGN KEY (COD_TIPO_COSTO) 
 REFERENCES plus_dizionari.DEC_TIPO_COSTO (COD_TIPO_COSTO)
    ON DELETE SET NULL;



ALTER TABLE INTERVENTO_PAI ADD
  CONSTRAINT FK_INTPAI_INT 
 FOREIGN KEY (IDE_INTERVENTO) 
 REFERENCES INTERVENTO (IDE_INTERVENTO)
    ON DELETE CASCADE;



ALTER TABLE INTERVENTO_PAI ADD
  CONSTRAINT FK_INTPAI_LAZPAI 
 FOREIGN KEY (IDE_AZIONE_PAI) 
 REFERENCES LAV_AZIONI_PAI (IDE_AZIONE_PAI)
    ON DELETE CASCADE;



ALTER TABLE LAV_DETRAZIONI ADD
  CONSTRAINT FK_LAVDET_LAV 
 FOREIGN KEY (IDE_LAVORATORE) 
 REFERENCES LAVORATORE (IDE_LAVORATORE)
    ON DELETE CASCADE;



ALTER TABLE LAV_ENTE ADD
  CONSTRAINT FK_LAVENT_LAV 
 FOREIGN KEY (IDE_LAVORATORE) 
 REFERENCES LAVORATORE (IDE_LAVORATORE)
    ON DELETE CASCADE;



ALTER TABLE ESITO_AZIONE_INTERVENTO ADD
  CONSTRAINT FK_ESI_AZI_INT_LAV_ESP_PROF 
 FOREIGN KEY (PRG_ESPERIENZA_PROF, IDE_LAVORATORE) 
 REFERENCES LAV_ESPERIENZE_PROFESSIONALI (PRG_ESPERIENZA_PROF,IDE_LAVORATORE)
    ON DELETE SET NULL;



ALTER TABLE DL_ENTE ADD
  CONSTRAINT FK_DLAVENT_TABINT 
 FOREIGN KEY (COD_INTERMEDIARIO) 
 REFERENCES plus_classificazione.TAB_INTERMEDIARI (COD_INTERMEDIARIO)
    ON DELETE CASCADE;



ALTER TABLE LAV_DETRAZIONI_DETTAGLIO ADD
  CONSTRAINT FK_LADEDE_LAVDET 
 FOREIGN KEY (IDE_LAVORATORE, DAT_INIZIO_DETRAZIONE) 
 REFERENCES LAV_DETRAZIONI (IDE_LAVORATORE,DAT_INIZIO_DETRAZIONE)
    ON DELETE CASCADE;



ALTER TABLE LAV_DETRAZIONI_STATO ADD
  CONSTRAINT FK_LADEST_LAVDET 
 FOREIGN KEY (IDE_LAVORATORE, DAT_INIZIO_DETRAZIONE) 
 REFERENCES LAV_DETRAZIONI (IDE_LAVORATORE,DAT_INIZIO_DETRAZIONE)
    ON DELETE CASCADE;



ALTER TABLE STRINT_PAGAMENTO ADD
  CONSTRAINT FK_STPAG_DETIPA 
 FOREIGN KEY (COD_APPLICAZIONE, COD_TIPO_PAGAMENTO) 
 REFERENCES plus_dizionari.DEC_TIPO_PAGAMENTO (COD_APPLICAZIONE,COD_TIPO_PAGAMENTO);



ALTER TABLE TEMPLATE_AZIONI_PAI_COSTO ADD
  CONSTRAINT FK_TMPCOSTO_DESTINATARIO 
 FOREIGN KEY (COD_DESTINATARIO) 
 REFERENCES plus_dizionari.DEC_DESTINATARIO (COD_DESTINATARIO)
    ON DELETE SET NULL;



ALTER TABLE LAV_ELEMENTI ADD
  FOREIGN KEY (COD_ELEMENTO) 
 REFERENCES plus_dizionari.DEC_ELEMENTI (COD_ELEMENTO);



ALTER TABLE STRINT_ATTORE ADD
  FOREIGN KEY (COD_CODICEPROFILO) 
 REFERENCES :userprof.TAB_PROFILO (COD_CODICEPROFILO)
    ON DELETE SET NULL;



ALTER TABLE LAV_AZIONI_PAI_CONSUNTIVO ADD
  CONSTRAINT FK_AZICONSUNTIVO_AZPAI 
 FOREIGN KEY (IDE_AZIONE_PAI) 
 REFERENCES LAV_AZIONI_PAI (IDE_AZIONE_PAI)
    ON DELETE CASCADE;



ALTER TABLE LAV_STATUS_DICH ADD
  CONSTRAINT FK_LASTDI_TSTAOC 
 FOREIGN KEY (COD_STATUSOCCUPAZ) 
 REFERENCES plus_classificazione.TAB_STATUSOCCUPAZ (COD_STATUSOCCUPAZ);



ALTER TABLE DL_SEDE_LEGALE ADD
  CONSTRAINT FK_SEDELEG_NAZIONI 
 FOREIGN KEY (COD_NAZIONE_ESTERA) 
 REFERENCES plus_classificazione.TAB_NAZIONI (COD_NAZIONE);



ALTER TABLE DL_FABB_TITOLO_STUDIO ADD
  FOREIGN KEY (COD_TITOLOSTUDIO) 
 REFERENCES plus_classificazione.TAB_STUDIOTITOLO (COD_TITOLOSTUDIO)
    ON DELETE SET NULL;



ALTER TABLE DL_FABB_TITOLO_STUDIO ADD
  FOREIGN KEY (COD_LIVELLOSTUDIO) 
 REFERENCES plus_classificazione.TAB_STUDIOLIVELLO (COD_LIVELLOSTUDIO)
    ON DELETE SET NULL;



ALTER TABLE LAV_DATI_PAGAMENTO ADD
  CONSTRAINT FK_DATPAG_LAV 
 FOREIGN KEY (IDE_LAVORATORE) 
 REFERENCES LAVORATORE (IDE_LAVORATORE)
    ON DELETE CASCADE;



ALTER TABLE INTERVENTO_PROROGA_SOSPENSIONE ADD
  FOREIGN KEY (COD_EVENTO) 
 REFERENCES plus_dizionari.DEC_EVENTI_INTERVENTO (COD_EVENTO);



ALTER TABLE STRINT_MACROSTRUMENTO_STRUM ADD
  FOREIGN KEY (COD_MACROSTRUMENTO) 
 REFERENCES plus_dizionari.DEC_STRINT_MACROSTRUMENTO (COD_MACROSTRUMENTO);



ALTER TABLE STRINT_TIPO_MACROSTRUMENTO ADD
  FOREIGN KEY (COD_MACROSTRUMENTO) 
 REFERENCES plus_dizionari.DEC_STRINT_MACROSTRUMENTO (COD_MACROSTRUMENTO);



ALTER TABLE DL_DISPONIBILITA_INTERVENTI ADD
  FOREIGN KEY (IDE_DATORE_LAVORO, COD_SEDE_LAVORO) 
 REFERENCES DL_SEDI_LAVORO (IDE_DATORE_LAVORO,COD_SEDE_LAVORO)
    ON DELETE CASCADE;



ALTER TABLE DL_DISPONIBILITA_INTERVENTI ADD
  FOREIGN KEY (IDE_DATORE_LAVORO) 
 REFERENCES DATORE_LAVORO (IDE_DATORE_LAVORO)
    ON DELETE CASCADE;



ALTER TABLE DL_FABB_ANAG ADD
  FOREIGN KEY (IDE_FABB_OCCUPAZIONALI) 
 REFERENCES DL_FABBISOGNI_OCCUPAZIONALI (IDE_FABB_OCCUPAZIONALI)
    ON DELETE CASCADE;



ALTER TABLE DL_FABB_COMPETENZE ADD
  FOREIGN KEY (IDE_FABB_OCCUPAZIONALI) 
 REFERENCES DL_FABBISOGNI_OCCUPAZIONALI (IDE_FABB_OCCUPAZIONALI)
    ON DELETE CASCADE;



ALTER TABLE DL_FABB_CONOSCENZE_AREE ADD
  FOREIGN KEY (IDE_FABB_OCCUPAZIONALI) 
 REFERENCES DL_FABBISOGNI_OCCUPAZIONALI (IDE_FABB_OCCUPAZIONALI)
    ON DELETE CASCADE;



ALTER TABLE LAV_ANALISI_PROFILI ADD
  FOREIGN KEY (COD_PROFILO) 
 REFERENCES plus_dizionari.DEC_PROFILI (COD_PROFILO);



ALTER TABLE LAV_PAI_STATO ADD
  CONSTRAINT FK_LAVPAISTATO_LAVPAI 
 FOREIGN KEY (IDE_PAI) 
 REFERENCES LAV_PAI (IDE_PAI)
    ON DELETE CASCADE;



ALTER TABLE LAV_PAI ADD
  CONSTRAINT FK_LAVPAI_LAVORATORE 
 FOREIGN KEY (IDE_LAVORATORE) 
 REFERENCES LAVORATORE (IDE_LAVORATORE)
    ON DELETE CASCADE;



ALTER TABLE LAV_PAI ADD
  CONSTRAINT FK_LAVPAI_TEMPLATEPAI 
 FOREIGN KEY (IDE_TEMPLATE_PAI) 
 REFERENCES TEMPLATE_PAI (IDE_TEMPLATE_PAI)
    ON DELETE CASCADE;



ALTER TABLE LAV_PATTO_SERVIZIO_CHIUSURA ADD
  CONSTRAINT FK_LAVPATCH_LAVPATTO 
 FOREIGN KEY (IDE_PATTO_SERVIZIO) 
 REFERENCES LAV_PATTO_SERVIZIO (IDE_PATTO_SERVIZIO)
    ON DELETE CASCADE;

	


ALTER TABLE CONVENZIONE_STATO ADD
  CONSTRAINT FK_CONVST_STADOC 
 FOREIGN KEY (COD_STATO_DOCUMENTO) 
 REFERENCES plus_dizionari.DEC_STATO_DOCUMENTO (COD_STATO_DOCUMENTO)
    ON DELETE CASCADE;




ALTER TABLE TEMPLATE_PAI_STATO ADD
  CONSTRAINT FK_TEMPPAISTATO_STATODOC 
 FOREIGN KEY (COD_STATO_DOCUMENTO) 
 REFERENCES plus_dizionari.DEC_STATO_DOCUMENTO (COD_STATO_DOCUMENTO);



ALTER TABLE LAV_OBBLIGO_FORMATIVO ADD
  FOREIGN KEY (COD_OBBLIGOFORMATIVO) 
 REFERENCES plus_dizionari.TAB_OBBLIGOFORMATIVO (COD_OBBLIGOFORMATIVO);



ALTER TABLE LAV_PATENTE ADD
  FOREIGN KEY (COD_TIPO_PATENTEGUIDA) 
 REFERENCES plus_classificazione.TAB_TIPOPATENTIGUIDA (COD_TIPO_PATENTEGUIDA);



ALTER TABLE LAV_PATENTINO ADD
  FOREIGN KEY (COD_TIPO_PATENTINO) 
 REFERENCES plus_classificazione.TAB_TIPOPATENTINI (COD_TIPO_PATENTINO);



ALTER TABLE LAV_ESPERIENZE_PROFESSIONALI ADD
  CONSTRAINT FK_LAV_ESP_PROF_MODALITALAV 
 FOREIGN KEY (COD_MODALITALAV) 
 REFERENCES plus_classificazione.TAB_MODALITALAV (COD_MODALITALAV);




ALTER TABLE CONVENZIONE_STATO ADD
  CONSTRAINT FK_CONVST_CONV 
 FOREIGN KEY (PRG_CONVENZIONE) 
 REFERENCES CONVENZIONE (PRG_CONVENZIONE)
    ON DELETE CASCADE;



ALTER TABLE DL_FABB_ESPERIENZA_SETTORE ADD
  FOREIGN KEY (COD_UNITA_TEMPO) 
 REFERENCES plus_dizionari.TAB_UNITA_TEMPO (COD_UNITA_TEMPO)
    ON DELETE SET NULL;



ALTER TABLE LAV_STATUS ADD
  FOREIGN KEY (COD_CRITERIO_SC) 
 REFERENCES plus_dizionari.DEC_CRITERIO_SOSP_CONS (COD_CRITERIO_SC);



ALTER TABLE DL_FABB_RESIDENZA ADD
  FOREIGN KEY (COD_PROVINCIA) 
 REFERENCES plus_classificazione.TAB_PROVINCE (COD_PROVINCIA)
    ON DELETE SET NULL;



ALTER TABLE DL_FABB_RESIDENZA ADD
  FOREIGN KEY (COD_COMUNE) 
 REFERENCES plus_classificazione.TAB_COMUNI (COD_COMUNE)
    ON DELETE SET NULL;




ALTER TABLE INTERVENTO_DATI_TIROCINIO ADD
  CONSTRAINT FK_INDATI_INTERV 
 FOREIGN KEY (IDE_INTERVENTO) 
 REFERENCES INTERVENTO (IDE_INTERVENTO)
    ON DELETE CASCADE;



ALTER TABLE ELENCO ADD
  CONSTRAINT FK_INCENTIVI_ELENCHI 
 FOREIGN KEY (COD_TIPO_INCENTIVO) 
 REFERENCES plus_dizionari.DEC_TIPO_INCENTIVO (COD_TIPO_INCENTIVO);



ALTER TABLE INTERVENTO_TIROCINIO_COND ADD
  CONSTRAINT FK_INTTIR_DECOTI 
 FOREIGN KEY (COD_CONDIZIONE_TIROCINIO) 
 REFERENCES plus_dizionari.DEC_CONDIZIONE_TIROCINIO (COD_CONDIZIONE_TIROCINIO);



ALTER TABLE LAV_LINGUE_CONOSCIUTE ADD
  FOREIGN KEY (COD_LINGUA) 
 REFERENCES plus_classificazione.TAB_LINGUE (COD_LINGUA);



ALTER TABLE LAV_LISTE_SPECIALI ADD
  FOREIGN KEY (COD_LISTESPEC) 
 REFERENCES plus_classificazione.TAB_LISTESPECIALI (COD_LISTESPEC);




ALTER TABLE LAV_STATUS_DICH ADD
  CONSTRAINT FK_LASTDI_DCRSOCO 
 FOREIGN KEY (COD_CRITERIO_SC) 
 REFERENCES plus_dizionari.DEC_CRITERIO_SOSP_CONS (COD_CRITERIO_SC);



ALTER TABLE LAV_STATUS_DICH ADD
  CONSTRAINT FK_LASTDI_DECORIN 
 FOREIGN KEY (COD_ORIGINE_INFO) 
 REFERENCES plus_dizionari.DEC_ORIGINE_INFO (COD_ORIGINE_INFO);



ALTER TABLE LAV_LISTE_SPECIALI ADD
  FOREIGN KEY (COD_PROVINCIA_LISTA) 
 REFERENCES plus_classificazione.TAB_PROVINCE (COD_PROVINCIA);




ALTER TABLE LAV_AZIONI_PAI_CONSUNTIVO ADD
  CONSTRAINT FK_LAVAZCONSTO_DESTINATARIO 
 FOREIGN KEY (COD_DESTINATARIO) 
 REFERENCES plus_dizionari.DEC_DESTINATARIO (COD_DESTINATARIO);



ALTER TABLE LAV_CONVOCAZIONI ADD
  CONSTRAINT FK_LAVCONV_MOTCONV 
 FOREIGN KEY (COD_APPLICAZIONE, COD_MOTIVO_CONVOCAZIONE) 
 REFERENCES plus_dizionari.DEC_MOTIVO_CONVOCAZIONE (COD_APPLICAZIONE,COD_MOTIVO_CONVOCAZIONE);



ALTER TABLE LAV_ESPERIENZE_STUDIO ADD
  FOREIGN KEY (COD_TITOLOSTUDIO) 
 REFERENCES plus_classificazione.TAB_STUDIOTITOLO (COD_TITOLOSTUDIO);



ALTER TABLE LAV_ESPERIENZE_STUDIO ADD
  FOREIGN KEY (COD_LIVELLOSTUDIO) 
 REFERENCES plus_classificazione.TAB_STUDIOLIVELLO (COD_LIVELLOSTUDIO);



ALTER TABLE CONVENZIONE ADD
  CONSTRAINT FK_CONV_TIPCON 
 FOREIGN KEY (COD_APPLICAZIONE, COD_TIPO_CONVENZIONE) 
 REFERENCES plus_dizionari.DEC_TIPO_CONVENZIONE (COD_APPLICAZIONE,COD_TIPO_CONVENZIONE);



ALTER TABLE DATORE_LAVORO ADD
  CONSTRAINT FK_DATORE_LAVORO_FORMAGIURIDCA 
 FOREIGN KEY (COD_FORMAGIURIDICA) 
 REFERENCES plus_dizionari.TAB_FORMAGIURIDICA (COD_FORMAGIURIDICA);



ALTER TABLE LAVORATORE ADD
  FOREIGN KEY (COD_NAZIONE_NASCITA) 
 REFERENCES plus_classificazione.TAB_NAZIONI (COD_NAZIONE);



ALTER TABLE LAVORATORE ADD
  FOREIGN KEY (COD_SESSO) 
 REFERENCES plus_classificazione.TAB_SESSO (COD_SESSO);



ALTER TABLE STRINT_ATTRIBUTO ADD
  FOREIGN KEY (IDE_TIPO_INTERVENTO) 
 REFERENCES STRINT_TIPO (IDE_TIPO_INTERVENTO)
    ON DELETE CASCADE;



ALTER TABLE STRINT_TIPO_MACROSTRUMENTO ADD
  FOREIGN KEY (IDE_TIPO_INTERVENTO) 
 REFERENCES STRINT_TIPO (IDE_TIPO_INTERVENTO)
    ON DELETE CASCADE;


ALTER TABLE CONVENZIONE ADD
  FOREIGN KEY (IDE_DATORE_LAVORO) 
 REFERENCES DATORE_LAVORO (IDE_DATORE_LAVORO)
    ON DELETE CASCADE;



ALTER TABLE DL_DISPONIBILITA_INTERVENTI ADD
  FOREIGN KEY (IDE_TIPO_INTERVENTO) 
 REFERENCES STRINT_TIPO (IDE_TIPO_INTERVENTO)
    ON DELETE CASCADE;



ALTER TABLE ESITO_AZIONE_INTERVENTO ADD
  CONSTRAINT FK_ESAZ_IN 
 FOREIGN KEY (IDE_INTERVENTO) 
 REFERENCES INTERVENTO (IDE_INTERVENTO)
    ON DELETE CASCADE;



ALTER TABLE ESITO_AZIONE_INTERVENTO ADD
  CONSTRAINT FK_ESITOAZINT_LAVAZPAI 
 FOREIGN KEY (IDE_AZIONE_PAI) 
 REFERENCES LAV_AZIONI_PAI (IDE_AZIONE_PAI)
    ON DELETE CASCADE;



ALTER TABLE MODULO_PAGAMENTO ADD
  CONSTRAINT FK_MODPAG_INT 
 FOREIGN KEY (COD_INTERMEDIARIO) 
 REFERENCES plus_classificazione.TAB_INTERMEDIARI (COD_INTERMEDIARIO)
    ON DELETE CASCADE;






ALTER TABLE DL_FABB_DOMICILIO ADD
  FOREIGN KEY (COD_REGIONE) 
 REFERENCES plus_classificazione.TAB_REGIONI (COD_REGIONE)
    ON DELETE SET NULL;



ALTER TABLE DL_FABB_DOMICILIO ADD
  FOREIGN KEY (COD_PROVINCIA) 
 REFERENCES plus_classificazione.TAB_PROVINCE (COD_PROVINCIA)
    ON DELETE SET NULL;



ALTER TABLE DL_FABB_DISP_MODALITALAV ADD
  FOREIGN KEY (COD_MODALITALAV) 
 REFERENCES plus_classificazione.TAB_MODALITALAV (COD_MODALITALAV)
    ON DELETE SET NULL;



ALTER TABLE DL_FABB_DISP_TIPOCONTRATTO ADD
  FOREIGN KEY (COD_TIPOLOGIACONTR) 
 REFERENCES plus_classificazione.TAB_TIPOLOGIA_CONTR (COD_TIPOLOGIACONTR)
    ON DELETE SET NULL;



ALTER TABLE DL_FABB_ESPERIENZA_MANSIONI ADD
  FOREIGN KEY (COD_UNITA_TEMPO) 
 REFERENCES plus_dizionari.TAB_UNITA_TEMPO (COD_UNITA_TEMPO)
    ON DELETE SET NULL;



ALTER TABLE DL_ENTE ADD
  CONSTRAINT FK_DLAVENT_DLAV 
 FOREIGN KEY (IDE_DATORE_LAVORO) 
 REFERENCES DATORE_LAVORO (IDE_DATORE_LAVORO)
    ON DELETE CASCADE;



ALTER TABLE ELENCO_MODULO_PAGAMENTO ADD
  CONSTRAINT FK_ELENCHI_MODPAG 
 FOREIGN KEY (IDE_ELENCO) 
 REFERENCES ELENCO (IDE_ELENCO)
    ON DELETE CASCADE;



ALTER TABLE TEMPLATE_AZIONI_PAI_COSTO ADD
  CONSTRAINT FK_TEMPCOSTO_VOCECOSTO 
 FOREIGN KEY (COD_VOCE_COSTO) 
 REFERENCES plus_dizionari.DEC_VOCE_COSTO (COD_VOCE_COSTO)
    ON DELETE SET NULL;



ALTER TABLE LAV_LINGUE_CONOSCIUTE ADD
  FOREIGN KEY (COD_CONOSCENZA_PARLATA) 
 REFERENCES plus_classificazione.TAB_LINGUECONOSCENZA (COD_CONOSCENZA);



ALTER TABLE DL_SEDE_LEGALE ADD
  FOREIGN KEY (COD_COMUNE) 
 REFERENCES plus_classificazione.TAB_COMUNI (COD_COMUNE);



ALTER TABLE DL_SEDI_LAVORO ADD
  FOREIGN KEY (COD_COMUNE) 
 REFERENCES plus_classificazione.TAB_COMUNI (COD_COMUNE);



ALTER TABLE DL_FABB_DOMICILIO ADD
  FOREIGN KEY (COD_COMUNE) 
 REFERENCES plus_classificazione.TAB_COMUNI (COD_COMUNE)
    ON DELETE SET NULL;



ALTER TABLE DL_FABB_RESIDENZA ADD
  FOREIGN KEY (COD_REGIONE) 
 REFERENCES plus_classificazione.TAB_REGIONI (COD_REGIONE)
    ON DELETE SET NULL;



ALTER TABLE LAV_ESPERIENZE_PROFESSIONALI ADD
  CONSTRAINT FK_LAV_ESP_PROFESS_ORIG_INFO 
 FOREIGN KEY (COD_ORIGINE_INFO) 
 REFERENCES plus_dizionari.DEC_ORIGINE_INFO (COD_ORIGINE_INFO);



ALTER TABLE LAV_LINGUE_CONOSCIUTE ADD
  CONSTRAINT FK_LAV_LINGUE_CONOSCIUTE_CEF 
 FOREIGN KEY (COD_CONOSCENZA_CEF) 
 REFERENCES plus_dizionari.DEC_LINGUECONOSCENZACEF (COD_CONOSCENZA_CEF);



ALTER TABLE LAV_ESPERIENZE_PROFESSIONALI ADD
  CONSTRAINT FK_LAV_ESP_PROFESS_DL_NAZIONI 
 FOREIGN KEY (COD_NAZIONE_DL) 
 REFERENCES plus_classificazione.TAB_NAZIONI (COD_NAZIONE)
    ON DELETE SET NULL;



ALTER TABLE DL_FABB_CONOSC_LINGUE ADD
  FOREIGN KEY (COD_CONOSCENZA_LETTA) 
 REFERENCES plus_classificazione.TAB_LINGUECONOSCENZA (COD_CONOSCENZA)
    ON DELETE SET NULL;



ALTER TABLE DL_FABB_CONOSC_LINGUE ADD
  FOREIGN KEY (COD_CONOSCENZA_PARLATA) 
 REFERENCES plus_classificazione.TAB_LINGUECONOSCENZA (COD_CONOSCENZA)
    ON DELETE SET NULL;





ALTER TABLE LAV_ESPERIENZE_PROFESSIONALI ADD
  CONSTRAINT FK_LAV_ESP_PROFESS_FIGPROF 
 FOREIGN KEY (COD_FIGURAPROFESS) 
 REFERENCES plus_classificazione.TAB_FIGURAPROFESS (COD_FIGURAPROFESS);



ALTER TABLE DL_FABB_CONOSC_LINGUE ADD
  FOREIGN KEY (COD_CONOSCENZA_SCRITTA) 
 REFERENCES plus_classificazione.TAB_LINGUECONOSCENZA (COD_CONOSCENZA)
    ON DELETE SET NULL;



ALTER TABLE DL_FABB_CONOSC_LINGUE ADD
  FOREIGN KEY (COD_LINGUA) 
 REFERENCES plus_classificazione.TAB_LINGUE (COD_LINGUA)
    ON DELETE SET NULL;




ALTER TABLE STRINT_PAGAMENTO ADD
  CONSTRAINT FK_STRPAG_STRTIP 
 FOREIGN KEY (IDE_TIPO_INTERVENTO) 
 REFERENCES STRINT_TIPO (IDE_TIPO_INTERVENTO)
    ON DELETE CASCADE;



ALTER TABLE TEMPLATE_AZIONI_PAI_COSTO ADD
  CONSTRAINT FK_TEMPAZOCOSTO_FONDO 
 FOREIGN KEY (IDE_FONDO) 
 REFERENCES FONDO (IDE_FONDO)
    ON DELETE SET NULL;



ALTER TABLE DATORE_LAVORO ADD
  FOREIGN KEY (COD_TIPOAZIENDA) 
 REFERENCES plus_classificazione.TAB_TIPOAZIENDA (COD_TIPOAZIENDA);



ALTER TABLE DL_FABB_ANAG ADD
  FOREIGN KEY (COD_SESSO) 
 REFERENCES plus_classificazione.TAB_SESSO (COD_SESSO)
    ON DELETE SET NULL;



ALTER TABLE STRINT_TIPO ADD
  FOREIGN KEY (COD_AREA_INTERVENTO) 
 REFERENCES plus_dizionari.DEC_STRINT_AREA (COD_AREA_INTERVENTO);



ALTER TABLE LAV_BILANCIO ADD
  FOREIGN KEY (COD_PROFILO) 
 REFERENCES plus_dizionari.DEC_PROFILI (COD_PROFILO);



ALTER TABLE INTERVENTO_TIROCINIO_COND ADD
  CONSTRAINT FK_INTTIR_INTERV 
 FOREIGN KEY (IDE_INTERVENTO) 
 REFERENCES INTERVENTO (IDE_INTERVENTO)
    ON DELETE CASCADE;



ALTER TABLE LAV_ESPERIENZE_FORMAZIONE ADD
  FOREIGN KEY (COD_UNITA_TEMPO) 
 REFERENCES plus_dizionari.TAB_UNITA_TEMPO (COD_UNITA_TEMPO);



ALTER TABLE DL_FABB_RESIDENZA ADD
  FOREIGN KEY (COD_RIPTERRITORIALE) 
 REFERENCES plus_dizionari.TAB_RIPTERRITORIALE (COD_RIPTERRITORIALE)
    ON DELETE SET NULL;



ALTER TABLE CONVENZIONE_ALLEGATI ADD
  CONSTRAINT FK_CONALL_ALLEGA 
 FOREIGN KEY (IDE_ALLEGATO) 
 REFERENCES ALLEGATI (IDE_ALLEGATO)
    ON DELETE CASCADE;



ALTER TABLE REGOLA_AMBITO_RICERCA ADD
  FOREIGN KEY (COD_TIPO_AMBITO_CRITERIO) 
 REFERENCES plus_dizionari.DEC_TIPO_AMBITO_CRITERIO (COD_TIPO_AMBITO_CRITERIO);



ALTER TABLE INTERVENTO_PROROGA_SOSPENSIONE ADD
  FOREIGN KEY (IDE_INTERVENTO) 
 REFERENCES INTERVENTO (IDE_INTERVENTO)
    ON DELETE CASCADE;



ALTER TABLE LAV_ALBO ADD
  FOREIGN KEY (IDE_LAVORATORE) 
 REFERENCES LAVORATORE (IDE_LAVORATORE)
    ON DELETE CASCADE;



ALTER TABLE LAV_ANALISI_PROFILI ADD
  FOREIGN KEY (IDE_LAVORATORE) 
 REFERENCES LAVORATORE (IDE_LAVORATORE)
    ON DELETE CASCADE;



ALTER TABLE LAV_ANZIANITA_DISOCCUPAZIONE ADD
  FOREIGN KEY (DAT_INIZIO_DID, IDE_LAVORATORE) 
 REFERENCES LAV_DID (DAT_INIZIO_DID,IDE_LAVORATORE)
    ON DELETE CASCADE;



ALTER TABLE LAV_BILANCIO ADD
  FOREIGN KEY (IDE_LAVORATORE) 
 REFERENCES LAVORATORE (IDE_LAVORATORE)
    ON DELETE CASCADE;





ALTER TABLE LAV_ESPERIENZE_FORMAZIONE ADD
  FOREIGN KEY (COD_COMUNE_ENTE) 
 REFERENCES plus_classificazione.TAB_COMUNI (COD_COMUNE);



ALTER TABLE LAV_ESPERIENZE_STUDIO ADD
  FOREIGN KEY (COD_NAZIONE_STUDIO) 
 REFERENCES plus_classificazione.TAB_NAZIONI (COD_NAZIONE);



ALTER TABLE LAV_STRANIERO ADD
  CONSTRAINT FK_LAV_STRANIERO_STATUS 
 FOREIGN KEY (COD_STATUS_STRANIERO) 
 REFERENCES plus_classificazione.TAB_STATUS_STRANIERO (COD_STATUS_STRANIERO);





ALTER TABLE LAVORATORE ADD
  FOREIGN KEY (COD_CITTADINANZA) 
 REFERENCES plus_classificazione.TAB_CITTADINANZE (COD_CITTADINANZA);



ALTER TABLE LAVORATORE ADD
  FOREIGN KEY (COD_COMUNE_RESIDENZA) 
 REFERENCES plus_classificazione.TAB_COMUNI (COD_COMUNE);



ALTER TABLE LAV_PATTO_SERVIZIO ADD
  CONSTRAINT FK_LAVPATTO_COMUNE 
 FOREIGN KEY (COD_COMUNE_ENTE) 
 REFERENCES plus_classificazione.TAB_COMUNI (COD_COMUNE);



ALTER TABLE TEMPLATE_AZIONI_PAI ADD
  CONSTRAINT FK_TMPAZPAI_TIPOAZIONE 
 FOREIGN KEY (COD_APPLICAZIONE, COD_TIPOLOGIA_AZIONE) 
 REFERENCES plus_dizionari.DEC_TIPOLOGIA_AZIONE (COD_APPLICAZIONE,COD_TIPOLOGIA_AZIONE)
    ON DELETE SET NULL;



ALTER TABLE LAV_DID ADD
  FOREIGN KEY (COD_CAUSA_FINE_DID) 
 REFERENCES plus_dizionari.DEC_CAUSA_FINE_DID (COD_CAUSA_FINE_DID);



ALTER TABLE DATORE_LAVORO ADD
  CONSTRAINT FK_DATLAV_TABCOM 
 FOREIGN KEY (COD_COMUNE_NASC_RAPP) 
 REFERENCES plus_classificazione.TAB_COMUNI (COD_COMUNE)
    ON DELETE CASCADE;
	

ALTER TABLE CONV_SOGGETTO_PROMOTORE ADD
  CONSTRAINT FK_COSOGPRO_NAZIONI 
 FOREIGN KEY (COD_NAZIONE_NAS_RAPPR) 
 REFERENCES plus_classificazione.TAB_NAZIONI (COD_NAZIONE)
    ON DELETE CASCADE;



ALTER TABLE LAV_TIPOSERV ADD
  CONSTRAINT FK_TIPOSERV_DECTS 
 FOREIGN KEY (COD_TIPOLOGIA_SERVIZIO) 
 REFERENCES plus_dizionari.DEC_TIPOLOGIA_SERVIZIO (COD_TIPOLOGIA_SERVIZIO)
    ON DELETE CASCADE;



ALTER TABLE LAV_CONVOCAZIONI ADD
  FOREIGN KEY (COD_MODALITA_CONVOCAZIONE) 
 REFERENCES plus_dizionari.DEC_MODALITA_CONVOCAZIONE (COD_MODALITA_CONVOCAZIONE);



ALTER TABLE LAVORATORE ADD
  FOREIGN KEY (COD_COMUNE_DOMICILIO) 
 REFERENCES plus_classificazione.TAB_COMUNI (COD_COMUNE);



ALTER TABLE LAVORATORE ADD
  FOREIGN KEY (COD_COMUNE_NASCITA) 
 REFERENCES plus_classificazione.TAB_COMUNI (COD_COMUNE);



ALTER TABLE LAV_DETRAZIONI ADD
  CONSTRAINT FK_LAVDET_TABCOMC 
 FOREIGN KEY (COD_COMUNE_RES_ANNOCOR) 
 REFERENCES plus_classificazione.TAB_COMUNI (COD_COMUNE)
    ON DELETE SET NULL;



ALTER TABLE STRINT_PAGAMENTO ADD
  CONSTRAINT FK_STRPAG_PERPAG 
 FOREIGN KEY (COD_APPLICAZIONE, COD_PERIODO_PAGAMENTO) 
 REFERENCES plus_dizionari.DEC_PERIODO_PAGAMENTO (COD_APPLICAZIONE,COD_PERIODO_PAGAMENTO);



ALTER TABLE LAV_CONVOCAZIONI ADD
  FOREIGN KEY (COD_ESITO_CONVOCAZIONE) 
 REFERENCES plus_dizionari.DEC_ESITO_CONVOCAZIONE (COD_ESITO_CONVOCAZIONE);



ALTER TABLE DATORE_LAVORO ADD
  CONSTRAINT FK_DATLAV_TABNAZ 
 FOREIGN KEY (COD_NAZIONE_NASC_RAPP) 
 REFERENCES plus_classificazione.TAB_NAZIONI (COD_NAZIONE)
    ON DELETE CASCADE;



ALTER TABLE INTERVENTO ADD
  FOREIGN KEY (COD_APPLICAZIONE) 
 REFERENCES :userprof .APPLICAZIONE (COD_APPLICAZIONE);



ALTER TABLE LAV_ESPERIENZE_FORMAZIONE ADD
  FOREIGN KEY (COD_TIPO_CORSO) 
 REFERENCES plus_dizionari.TAB_CORSOTIPO (COD_CORSOTIPO);



ALTER TABLE REGOLA_AMBITO_RICERCA ADD
  FOREIGN KEY (IDE_REGOLA) 
 REFERENCES :userprof .REGOLA (IDE_REGOLA);



ALTER TABLE DL_SEDI_LAVORO ADD
  CONSTRAINT FK_SEDILAV_NAZIONI 
 FOREIGN KEY (COD_NAZIONE_ESTERA) 
 REFERENCES plus_classificazione.TAB_NAZIONI (COD_NAZIONE);



ALTER TABLE DL_DISPONIBILITA_INTERVENTI ADD
  FOREIGN KEY (COD_APPLICAZIONE) 
 REFERENCES :userprof .APPLICAZIONE (COD_APPLICAZIONE)
    ON DELETE CASCADE;



ALTER TABLE LAV_DETRAZIONI ADD
  CONSTRAINT FK_LAVDET_TABCOMP 
 FOREIGN KEY (COD_COMUNE_RES_ANNOPREC) 
 REFERENCES plus_classificazione.TAB_COMUNI (COD_COMUNE)
    ON DELETE SET NULL;



ALTER TABLE LAV_AZIONI_PAI ADD
  CONSTRAINT FK_AZPAI_INTER 
 FOREIGN KEY (COD_INTERMEDIARIO) 
 REFERENCES plus_classificazione.TAB_INTERMEDIARI (COD_INTERMEDIARIO)
    ON DELETE SET NULL;



ALTER TABLE LAV_COMPETENZE ADD
  FOREIGN KEY (COD_COMPETENZA) 
 REFERENCES plus_dizionari.DEC_COMPETENZE (COD_COMPETENZA);



ALTER TABLE INTERVENTO_SEDE ADD
  CONSTRAINT FK_INTERVENTO_SEDE__NAZIONE 
 FOREIGN KEY (COD_SEDE_NAZIONE) 
 REFERENCES plus_classificazione.TAB_NAZIONI (COD_NAZIONE);



ALTER TABLE INTERVENTO_SEDE ADD
  CONSTRAINT FK_INTERVENTO_SEDE__COMUNI 
 FOREIGN KEY (COD_COMUNE) 
 REFERENCES plus_classificazione.TAB_COMUNI (COD_COMUNE);



ALTER TABLE CONV_SOGGETTO_PROMOTORE ADD
  CONSTRAINT FK_COSOGPRO_INTERMED 
 FOREIGN KEY (COD_INTERMEDIARIO) 
 REFERENCES plus_classificazione.TAB_INTERMEDIARI (COD_INTERMEDIARIO)
    ON DELETE CASCADE;




ALTER TABLE ELENCO ADD
  CONSTRAINT FK_INTER_ELENCHI 
 FOREIGN KEY (COD_INTERMEDIARIO) 
 REFERENCES plus_classificazione.TAB_INTERMEDIARI (COD_INTERMEDIARIO);



ALTER TABLE LAV_PAI ADD
  CONSTRAINT FK_LAVPAI_APPL_INT 
 FOREIGN KEY (IDE_APPL_INT) 
 REFERENCES :userprof .APPL_INT (IDE_APPL_INT)
    ON DELETE SET NULL;



ALTER TABLE STRINT_PAGAMENTO ADD
  CONSTRAINT FK_STRPAG_SOGASS 
 FOREIGN KEY (COD_SOGG_ASSICURA) 
 REFERENCES plus_dizionari.DEC_SOGG_ASSICURA (COD_SOGG_ASSICURA);



ALTER TABLE APPL_INT_TIPOSERV ADD
  CONSTRAINT FK_APINTS_APPINT 
 FOREIGN KEY (IDE_APPL_INT) 
 REFERENCES :userprof .APPL_INT (IDE_APPL_INT)
    ON DELETE CASCADE;



ALTER TABLE LAV_DETRAZIONI_DETTAGLIO ADD
  CONSTRAINT FK_LADEDE_TABCOM 
 FOREIGN KEY (COD_COMUNE_NASCITA) 
 REFERENCES plus_classificazione.TAB_COMUNI (COD_COMUNE)
    ON DELETE CASCADE;





ALTER TABLE LAV_PATTO_SERVIZIO ADD
  CONSTRAINT FK_LAVPATTO_INT 
 FOREIGN KEY (COD_INTERMEDIARIO) 
 REFERENCES plus_classificazione.TAB_INTERMEDIARI (COD_INTERMEDIARIO);




ALTER TABLE LAV_DETRAZIONI ADD
  CONSTRAINT FK_LAVDET_TABNAZP 
 FOREIGN KEY (COD_NAZIONE_RES_ANNOPREC) 
 REFERENCES plus_classificazione.TAB_NAZIONI (COD_NAZIONE)
    ON DELETE SET NULL;



ALTER TABLE STRINT_MACROSTRUMENTO_STRUM ADD
  FOREIGN KEY (COD_CODICESTRUMENTO) 
 REFERENCES :userprof .TAB_STRUMENTO (COD_CODICESTRUMENTO);



ALTER TABLE TEMPLATE_PAI ADD
  CONSTRAINT FK_TMPPAI_APPLICAZIONE 
 FOREIGN KEY (COD_APPLICAZIONE) 
 REFERENCES :userprof .APPLICAZIONE (COD_APPLICAZIONE)
    ON DELETE SET NULL;



ALTER TABLE LAV_DETRAZIONI_DETTAGLIO ADD
  CONSTRAINT FK_LADEDE_TABNAZ 
 FOREIGN KEY (COD_NAZIONE_NASCITA) 
 REFERENCES plus_classificazione.TAB_NAZIONI (COD_NAZIONE)
    ON DELETE CASCADE;



ALTER TABLE CONV_SOGGETTO_PROMOTORE ADD
  CONSTRAINT FK_COSOGPRO_COMUNI 
 FOREIGN KEY (COD_COMUNE_SEDE) 
 REFERENCES plus_classificazione.TAB_COMUNI (COD_COMUNE)
    ON DELETE CASCADE;



ALTER TABLE LAV_ENTE ADD
  CONSTRAINT FK_LAVENT_APP_INT 
 FOREIGN KEY (IDE_APPL_INT) 
 REFERENCES :userprof .APPL_INT (IDE_APPL_INT)
    ON DELETE CASCADE;




ALTER TABLE LAV_ESPERIENZE_FORMAZIONE ADD
  FOREIGN KEY (COD_AMBITO_DISCIPLINARE) 
 REFERENCES plus_dizionari.TAB_AMBITI_DISCIPLINARI (COD_AMBITO_DISCIPLINARE);



ALTER TABLE LAV_ALBO ADD
  FOREIGN KEY (COD_ALBO) 
 REFERENCES plus_classificazione.TAB_ALBI (COD_ALBO);


ALTER TABLE LAV_CONOSCENZE_INFORMATICHE ADD
  FOREIGN KEY (COD_CONOSCENZA) 
 REFERENCES plus_classificazione.TAB_INFORMATICACONOSC (COD_CONOSCENZA);



ALTER TABLE LAV_DID ADD
  FOREIGN KEY (COD_INTERMEDIARIO) 
 REFERENCES plus_classificazione.TAB_INTERMEDIARI (COD_INTERMEDIARIO);





ALTER TABLE LAV_CATEGORIA181 ADD
  FOREIGN KEY (IDE_LAVORATORE) 
 REFERENCES LAVORATORE (IDE_LAVORATORE)
    ON DELETE CASCADE;



ALTER TABLE LAV_CATEGORIE_PARTICOLARI ADD
  FOREIGN KEY (IDE_LAVORATORE) 
 REFERENCES LAVORATORE (IDE_LAVORATORE)
    ON DELETE CASCADE;



ALTER TABLE LAV_COMPETENZE ADD
  FOREIGN KEY (IDE_LAVORATORE) 
 REFERENCES LAVORATORE (IDE_LAVORATORE)
    ON DELETE CASCADE;



ALTER TABLE LAV_CONOSCENZE_INFORMATICHE ADD
  FOREIGN KEY (IDE_LAVORATORE) 
 REFERENCES LAVORATORE (IDE_LAVORATORE)
    ON DELETE CASCADE;



ALTER TABLE LAV_CONVOCAZIONI ADD
  FOREIGN KEY (IDE_LAVORATORE) 
 REFERENCES LAVORATORE (IDE_LAVORATORE)
    ON DELETE CASCADE;



ALTER TABLE LAV_DID ADD
  FOREIGN KEY (IDE_LAVORATORE) 
 REFERENCES LAVORATORE (IDE_LAVORATORE)
    ON DELETE CASCADE;




ALTER TABLE LAV_LINGUE_CONOSCIUTE ADD
  FOREIGN KEY (IDE_LAVORATORE) 
 REFERENCES LAVORATORE (IDE_LAVORATORE)
    ON DELETE CASCADE;



ALTER TABLE LAV_LISTE_SPECIALI ADD
  FOREIGN KEY (IDE_LAVORATORE) 
 REFERENCES LAVORATORE (IDE_LAVORATORE)
    ON DELETE CASCADE;




ALTER TABLE LAVORATORE ADD
  FOREIGN KEY (COD_STATOCIVILE) 
 REFERENCES plus_dizionari.TAB_STATOCIVILE (COD_STATOCIVILE);



ALTER TABLE DL_FABB_ESPERIENZA_MANSIONI ADD
  FOREIGN KEY (IDE_FABB_OCCUPAZIONALI) 
 REFERENCES DL_FABBISOGNI_OCCUPAZIONALI (IDE_FABB_OCCUPAZIONALI)
    ON DELETE CASCADE;



ALTER TABLE DL_FABB_ESPERIENZA_SETTORE ADD
  FOREIGN KEY (IDE_FABB_OCCUPAZIONALI) 
 REFERENCES DL_FABBISOGNI_OCCUPAZIONALI (IDE_FABB_OCCUPAZIONALI)
    ON DELETE CASCADE;



ALTER TABLE DL_FABBISOGNI_OCCUPAZIONALI ADD
  FOREIGN KEY (IDE_DISPONIBILITA_INTERVENTI) 
 REFERENCES DL_DISPONIBILITA_INTERVENTI (IDE_DISPONIBILITA_INTERVENTI)
    ON DELETE CASCADE;



ALTER TABLE DL_FABBISOGNI_OCCUPAZIONALI ADD
  FOREIGN KEY (IDE_DATORE_LAVORO, COD_SEDE_LAVORO) 
 REFERENCES DL_SEDI_LAVORO (IDE_DATORE_LAVORO,COD_SEDE_LAVORO)
    ON DELETE CASCADE;



ALTER TABLE DL_FABBISOGNI_OCCUPAZIONALI ADD
  FOREIGN KEY (IDE_DATORE_LAVORO) 
 REFERENCES DATORE_LAVORO (IDE_DATORE_LAVORO)
    ON DELETE CASCADE;



ALTER TABLE DL_FABB_RESIDENZA ADD
  FOREIGN KEY (IDE_FABB_OCCUPAZIONALI) 
 REFERENCES DL_FABBISOGNI_OCCUPAZIONALI (IDE_FABB_OCCUPAZIONALI)
    ON DELETE CASCADE;



ALTER TABLE INTERVENTO_ATTORE ADD
  FOREIGN KEY (IDE_INTERVENTO) 
 REFERENCES INTERVENTO (IDE_INTERVENTO)
    ON DELETE CASCADE;



ALTER TABLE INTERVENTO_ATTRIBUTO ADD
  FOREIGN KEY (IDE_INTERVENTO) 
 REFERENCES INTERVENTO (IDE_INTERVENTO)
    ON DELETE CASCADE;



ALTER TABLE LAV_PATTO_SERVIZIO ADD
  CONSTRAINT FK_LAVPATTO_LAVCONV 
 FOREIGN KEY (PRG_CONVOCAZIONE, IDE_LAVORATORE) 
 REFERENCES LAV_CONVOCAZIONI (PRG_CONVOCAZIONE,IDE_LAVORATORE)
    ON DELETE CASCADE;



ALTER TABLE LAV_PATTO_SERVIZIO ADD
  CONSTRAINT FK_LAVPATTO_LAVORATORE 
 FOREIGN KEY (IDE_LAVORATORE) 
 REFERENCES LAVORATORE (IDE_LAVORATORE)
    ON DELETE CASCADE;



ALTER TABLE LAV_ESPERIENZE_PROFESSIONALI ADD
  CONSTRAINT FK_LAV_ESP_PROFESS_DATLAV 
 FOREIGN KEY (IDE_DATORE_LAVORO) 
 REFERENCES DATORE_LAVORO (IDE_DATORE_LAVORO);



ALTER TABLE LAV_ESPERIENZE_PROFESSIONALI ADD
  CONSTRAINT FK_LAV_ESP_PROFESS_LAV 
 FOREIGN KEY (IDE_LAVORATORE) 
 REFERENCES LAVORATORE (IDE_LAVORATORE)
    ON DELETE CASCADE;



ALTER TABLE LAV_STRANIERO ADD
  CONSTRAINT FK_LAV_STRANIERO_LAV 
 FOREIGN KEY (IDE_LAVORATORE) 
 REFERENCES LAVORATORE (IDE_LAVORATORE)
    ON DELETE CASCADE;



ALTER TABLE LAV_AZIONI_PAI ADD
  CONSTRAINT FK_LAZPAI_LAVPAI 
 FOREIGN KEY (IDE_PAI) 
 REFERENCES LAV_PAI (IDE_PAI)
    ON DELETE CASCADE;




ALTER TABLE LAV_ESPERIENZE_PROFESSIONALI ADD
  CONSTRAINT FK_LAV_ESP_PROFESS_LIVCONTR 
 FOREIGN KEY (COD_LIVCONTRATTUALE) 
 REFERENCES plus_classificazione.TAB_LIVCONTRATTUALE (COD_LIVCONTRATTUALE);



ALTER TABLE LAV_DATI_PAGAMENTO ADD
  CONSTRAINT FK_DATPAG_TIPPAG 
 FOREIGN KEY (COD_APPLICAZIONE, COD_TIPO_PAGAMENTO) 
 REFERENCES plus_dizionari.DEC_TIPO_PAGAMENTO (COD_APPLICAZIONE,COD_TIPO_PAGAMENTO)
    ON DELETE SET NULL;




ALTER TABLE MODULO_INTERVENTO_ATTORE ADD
  CONSTRAINT FK_MOINAT_MODPAG 
 FOREIGN KEY (IDE_MODULO_PAGAMENTO) 
 REFERENCES MODULO_PAGAMENTO (IDE_MODULO_PAGAMENTO)
    ON DELETE CASCADE;



ALTER TABLE MODULO_INTATT_DETT_RATA ADD
  CONSTRAINT FK_MOINDR_MOINAT 
 FOREIGN KEY (IDE_MODULO_INTERVENTO_ATTORE) 
 REFERENCES MODULO_INTERVENTO_ATTORE (IDE_MODULO_INTERVENTO_ATTORE)
    ON DELETE CASCADE;



ALTER TABLE MODULO_PAG_STATO_PROCEDURA ADD
  CONSTRAINT FK_MOPASTPR_MODPAG 
 FOREIGN KEY (IDE_MODULO_PAGAMENTO) 
 REFERENCES MODULO_PAGAMENTO (IDE_MODULO_PAGAMENTO)
    ON DELETE CASCADE;



ALTER TABLE MODULO_PAGAMENTO_STATO ADD
  CONSTRAINT FK_MOPAST_MODPAG 
 FOREIGN KEY (IDE_MODULO_PAGAMENTO) 
 REFERENCES MODULO_PAGAMENTO (IDE_MODULO_PAGAMENTO)
    ON DELETE CASCADE;



ALTER TABLE MODULO_PAGAMENTO_STATO ADD
  CONSTRAINT FK_MOPAST_STADOC 
 FOREIGN KEY (COD_STATO_DOCUMENTO) 
 REFERENCES plus_dizionari.DEC_STATO_DOCUMENTO (COD_STATO_DOCUMENTO)
    ON DELETE CASCADE;



ALTER TABLE DL_FABB_TITOLO_STUDIO ADD
  FOREIGN KEY (IDE_FABB_OCCUPAZIONALI) 
 REFERENCES DL_FABBISOGNI_OCCUPAZIONALI (IDE_FABB_OCCUPAZIONALI)
    ON DELETE CASCADE;



ALTER TABLE DL_SEDE_LEGALE ADD
  FOREIGN KEY (IDE_DATORE_LAVORO) 
 REFERENCES DATORE_LAVORO (IDE_DATORE_LAVORO)
    ON DELETE CASCADE;



ALTER TABLE DL_SEDI_LAVORO ADD
  FOREIGN KEY (IDE_DATORE_LAVORO) 
 REFERENCES DATORE_LAVORO (IDE_DATORE_LAVORO)
    ON DELETE CASCADE;



ALTER TABLE INTERVENTO ADD
  FOREIGN KEY (IDE_TIPO_INTERVENTO) 
 REFERENCES STRINT_TIPO (IDE_TIPO_INTERVENTO)
    ON DELETE CASCADE;



ALTER TABLE INTERVENTO_ASSICURAZIONE ADD
  FOREIGN KEY (IDE_INTERVENTO) 
 REFERENCES INTERVENTO (IDE_INTERVENTO)
    ON DELETE CASCADE;



ALTER TABLE INTERVENTO_ATTORE ADD
  FOREIGN KEY (IDE_TIPO_INTERVENTO, COD_CODICEPROFILO) 
 REFERENCES STRINT_ATTORE (IDE_TIPO_INTERVENTO,COD_CODICEPROFILO)
    ON DELETE SET NULL;



ALTER TABLE CONVENZIONE_ALLEGATI ADD
  CONSTRAINT FK_CONALL_CONVEN 
 FOREIGN KEY (PRG_CONVENZIONE) 
 REFERENCES CONVENZIONE (PRG_CONVENZIONE)
    ON DELETE CASCADE;



ALTER TABLE INTERVENTO_CONVENZIONE ADD
  FOREIGN KEY (PRG_CONVENZIONE) 
 REFERENCES CONVENZIONE (PRG_CONVENZIONE);



ALTER TABLE INTERVENTO_CONVENZIONE ADD
  FOREIGN KEY (IDE_INTERVENTO) 
 REFERENCES INTERVENTO (IDE_INTERVENTO)
    ON DELETE CASCADE;



ALTER TABLE INTERVENTO_OBIETTIVI ADD
  FOREIGN KEY (IDE_INTERVENTO) 
 REFERENCES INTERVENTO (IDE_INTERVENTO)
    ON DELETE CASCADE;



ALTER TABLE TEMPLATE_AZIONI_PAI ADD
  CONSTRAINT FK_TEMPAZPAI_TEMPPAI 
 FOREIGN KEY (IDE_TEMPLATE_PAI) 
 REFERENCES TEMPLATE_PAI (IDE_TEMPLATE_PAI)
    ON DELETE CASCADE;


ALTER TABLE TEMPLATE_AZIONI_PAI ADD
  CONSTRAINT FK_TIPODOCENZA_TMPAZPAI 
 FOREIGN KEY (COD_TIPO_DOCENZA) 
 REFERENCES plus_dizionari.DEC_TIPO_DOCENZA (COD_TIPO_DOCENZA);


ALTER TABLE TEMPLATE_PAI_STATO ADD
  CONSTRAINT FK_TEMPPAISTATO_TEMPPAI 
 FOREIGN KEY (IDE_TEMPLATE_PAI) 
 REFERENCES TEMPLATE_PAI (IDE_TEMPLATE_PAI)
    ON DELETE CASCADE;



ALTER TABLE LAV_TIPOSERV ADD
  CONSTRAINT FK_TIPOSERV_LAV 
 FOREIGN KEY (IDE_LAVORATORE) 
 REFERENCES LAVORATORE (IDE_LAVORATORE)
    ON DELETE CASCADE;



ALTER TABLE STRINT_TIPO_TIPOSERV ADD
  CONSTRAINT FK_TITISE_STRTIP 
 FOREIGN KEY (IDE_TIPO_INTERVENTO) 
 REFERENCES STRINT_TIPO (IDE_TIPO_INTERVENTO)
    ON DELETE CASCADE;



ALTER TABLE TEMPLATE_AZIONI_PAI_COSTO ADD
  CONSTRAINT FK_TMPCOSTO_TMPAZIONI 
 FOREIGN KEY (IDE_TEMPLATE_AZIONE_PAI) 
 REFERENCES TEMPLATE_AZIONI_PAI (IDE_TEMPLATE_AZIONE_PAI)
    ON DELETE CASCADE;



ALTER TABLE LAV_RECAPITI ADD
  FOREIGN KEY (COD_TIPO_RECAPITO) 
 REFERENCES plus_dizionari.TAB_TIPORECAPITO (COD_TIPORECAPITO);



ALTER TABLE LAV_PATTO_SERVIZIO_STATO ADD
  CONSTRAINT FK_LAVPATST_LAVPATTO 
 FOREIGN KEY (IDE_PATTO_SERVIZIO) 
 REFERENCES LAV_PATTO_SERVIZIO (IDE_PATTO_SERVIZIO)
    ON DELETE CASCADE;



ALTER TABLE CONV_SOGGETTO_PROMOTORE ADD
  CONSTRAINT FK_COMUNI_NASRAPPR 
 FOREIGN KEY (COD_COMUNE_NAS_RAPPR) 
 REFERENCES plus_classificazione.TAB_COMUNI (COD_COMUNE)
    ON DELETE CASCADE;



ALTER TABLE LAV_ESPERIENZE_PROFESSIONALI ADD
  CONSTRAINT FK_LAV_ESP_PROFESS_NAZIONI 
 FOREIGN KEY (COD_NAZIONE_LAVORO) 
 REFERENCES plus_classificazione.TAB_NAZIONI (COD_NAZIONE);



ALTER TABLE LAV_DETRAZIONI_DETTAGLIO ADD
  CONSTRAINT FK_LADEDE_TABSES 
 FOREIGN KEY (COD_SESSO) 
 REFERENCES plus_classificazione.TAB_SESSO (COD_SESSO)
    ON DELETE CASCADE;


ALTER TABLE DL_ENTE ADD
  CONSTRAINT FK_DLAVENT_APPL 
 FOREIGN KEY (COD_APPLICAZIONE) 
 REFERENCES :userprof .APPLICAZIONE (COD_APPLICAZIONE)
    ON DELETE CASCADE;




ALTER TABLE LAV_ESPERIENZE_PROFESSIONALI ADD
  CONSTRAINT FK_LAV_ESP_PROFESS_ESPLAVA 
 FOREIGN KEY (COD_ESPERIENZELAV) 
 REFERENCES plus_classificazione.TAB_ESPERIENZELAV (COD_ESPERIENZELAV);
 
----------------------------------------------
 ALTER TABLE DATORE_LAVORO ADD 
  CONSTRAINT FK_DATLAV_TABAMP 
 FOREIGN KEY (COD_AMPIEZZA) 
 REFERENCES plus_classificazione.TAB_AMPIEZZA (COD_AMPIEZZA)
    ON DELETE CASCADE;
ALTER TABLE DATORE_LAVORO ADD 
  CONSTRAINT FK_DATLAV_TABCCNL
 FOREIGN KEY (COD_CCNL) 
 REFERENCES plus_classificazione.TAB_CCNL (COD_CCNL)
    ON DELETE CASCADE;
ALTER TABLE DL_FABBISOGNI_OCCUPAZIONALI ADD 
  CONSTRAINT FK_DLFABBOCC_APPL 
 FOREIGN KEY (COD_APPLICAZIONE) 
 REFERENCES :userprof .APPLICAZIONE (COD_APPLICAZIONE);
 

ALTER TABLE LAV_REDDITI ADD
  FOREIGN KEY (IDE_LAVORATORE) 
 REFERENCES LAVORATORE (IDE_LAVORATORE)
    ON DELETE CASCADE;

-- Foreign Key Constraints for Table LAV_SUSSIDIO 
-- 

ALTER TABLE LAV_SUSSIDIO ADD
  FOREIGN KEY (IDE_LAVORATORE) 
 REFERENCES LAVORATORE (IDE_LAVORATORE)
    ON DELETE CASCADE;

ALTER TABLE LAV_SUSSIDIO ADD
  FOREIGN KEY (COD_ENTE_EROGATORE) 
 REFERENCES plus_dizionari.DEC_ENTE_EROGATORE (COD_ENTE_EROGATORE)
    ON DELETE CASCADE;

ALTER TABLE LAV_SUSSIDIO ADD
  FOREIGN KEY (COD_TIPO_SUSSIDIO) 
 REFERENCES plus_dizionari.DEC_SUSSIDIO (COD_TIPO_SUSSIDIO)
    ON DELETE CASCADE;

-- 
-- Foreign Key Constraints for Table LAV_ISTITUTO 
-- 

ALTER TABLE LAV_ISTITUTO ADD
  CONSTRAINT LAVO 
 FOREIGN KEY (IDE_LAVORATORE) 
 REFERENCES LAVORATORE (IDE_LAVORATORE)
    ON DELETE CASCADE;
	
ALTER TABLE LAV_ISTITUTO ADD
  FOREIGN KEY (COD_CCNL) 
 REFERENCES plus_classificazione.TAB_CCNL (COD_CCNL);

 ALTER TABLE LAV_ISTITUTO ADD
  FOREIGN KEY (COD_DETTAGLIOISTITUTO, COD_TIPOISTITUTO) 
 REFERENCES plus_dizionari.DEC_DETTAGLIOISTITUTO (COD_DETTAGLIOISTITUTO,COD_TIPOISTITUTO)
    ON DELETE CASCADE;
	
ALTER TABLE LAV_ISTITUTO ADD
  FOREIGN KEY (IDE_LAV_SUSSIDIO) 
 REFERENCES LAV_SUSSIDIO (IDE_LAV_SUSSIDIO);


-- Foreign Key Constraints for Table LAV_SUSSIDIO_STATO_PAG 
-- 

ALTER TABLE LAV_SUSSIDIO_STATO_PAG ADD
  CONSTRAINT FK_LSSTPA_LAVSUS 
 FOREIGN KEY (IDE_LAV_SUSSIDIO) 
 REFERENCES LAV_SUSSIDIO (IDE_LAV_SUSSIDIO)
    ON DELETE CASCADE;
	
ALTER TABLE LAV_SUSSIDIO_STATO_PAG ADD
  CONSTRAINT FK_LSSTPA_STADOC 
 FOREIGN KEY (COD_STATO_PROCEDURA) 
 REFERENCES plus_dizionari.DEC_STATO_PROCEDURA (COD_STATO_PROCEDURA)
    ON DELETE SET NULL;

-- 
-- Foreign Key Constraints for Table LAV_ISTITUTO_EVENTI 
-- 

ALTER TABLE LAV_ISTITUTO_EVENTI ADD
  FOREIGN KEY (IDE_LAV_ISTITUTO) 
 REFERENCES LAV_ISTITUTO (IDE_LAV_ISTITUTO)
    ON DELETE CASCADE;

-- 
-- Foreign Key Constraints for Table LOG_WSC 
-- 

ALTER TABLE LOG_WSC ADD
  CONSTRAINT FK_LOGWSC_DECWSC 
 FOREIGN KEY (COD_APPLICAZIONE, COD_WSC) 
 REFERENCES plus_dizionari.DEC_WSC (COD_APPLICAZIONE,COD_WSC);

-- 
-- Foreign Key Constraints for Table LAV_AZIENDA_UTILIZZATRICE 
-- 

ALTER TABLE LAV_AZIENDA_UTILIZZATRICE ADD
  CONSTRAINT FK_LAV_AZIENDA_UTIL_ATECO 
 FOREIGN KEY (COD_ATECO_UTIL) 
 REFERENCES plus_classificazione.TAB_ATECOLIV4 (COD_ATECOLIV4)
    ON DELETE SET NULL;
	
ALTER TABLE LAV_AZIENDA_UTILIZZATRICE ADD
  CONSTRAINT FK_LAV_AZIENDA_UTIL_COMUN 
 FOREIGN KEY (COD_COMUNE_UTIL) 
 REFERENCES plus_classificazione.TAB_COMUNI (COD_COMUNE)
    ON DELETE SET NULL;
	
ALTER TABLE LAV_AZIENDA_UTILIZZATRICE ADD
  CONSTRAINT FK_LAV_AZIENDA_UTIL_NAZ 
 FOREIGN KEY (COD_NAZIONE_UTIL) 
 REFERENCES plus_classificazione.TAB_NAZIONI (COD_NAZIONE)
    ON DELETE SET NULL;

-- 
-- Foreign Key Constraints for Table LAV_ESPERIENZA_INTERMEDIATA 
-- 

ALTER TABLE LAV_ESPERIENZA_INTERMEDIATA ADD
  CONSTRAINT FK_ESP_ESPEINTERMEDIATA 
 FOREIGN KEY (PRG_ESPERIENZA_PROF, IDE_LAVORATORE) 
 REFERENCES LAV_ESPERIENZE_PROFESSIONALI (PRG_ESPERIENZA_PROF,IDE_LAVORATORE)
    ON DELETE CASCADE;

ALTER TABLE LAV_ESPERIENZA_INTERMEDIATA ADD	
  CONSTRAINT FK_INTERMEDIARI_LAV_ESP_INTERM 
 FOREIGN KEY (COD_INTERMEDIARIO) 
 REFERENCES plus_classificazione.TAB_INTERMEDIARI (COD_INTERMEDIARIO)
    ON DELETE SET NULL;

ALTER TABLE LAV_ESPERIENZA_INTERMEDIATA ADD	
  CONSTRAINT FK_INTER_FILIALI_LAV_ESP_INTER 
 FOREIGN KEY (COD_INTERMEDIARIO, COD_FILIALE) 
 REFERENCES plus_classificazione.TAB_INTERMEDIARI_FILIALI (COD_INTERMEDIARIO,COD_FILIALE)
    ON DELETE SET NULL;

-- 
-- Foreign Key Constraints for Table LAV_RICHIESTA_BONUS 
-- 

ALTER TABLE LAV_RICHIESTA_BONUS ADD
  CONSTRAINT FK_ESP_INTERM_RICHBONUS 
 FOREIGN KEY (IDE_ESPERIENZA_INTERM) 
 REFERENCES LAV_ESPERIENZA_INTERMEDIATA (IDE_ESPERIENZA_INTERM)
    ON DELETE CASCADE;
	

ALTER TABLE LAV_RICHIESTA_BONUS ADD
  CONSTRAINT FK_RICHBONUS_SUSSIDIO 
 FOREIGN KEY (IDE_LAV_SUSSIDIO) 
 REFERENCES LAV_SUSSIDIO (IDE_LAV_SUSSIDIO)
    ON DELETE SET NULL;

ALTER TABLE LAV_RICHIESTA_BONUS ADD
  CONSTRAINT FK_TIPOPAG_RICHBONUS 
 FOREIGN KEY (COD_APPLICAZIONE, COD_TIPO_PAGAMENTO) 
 REFERENCES plus_dizionari.DEC_TIPO_PAGAMENTO (COD_APPLICAZIONE,COD_TIPO_PAGAMENTO)
    ON DELETE SET NULL;

-- 
-- Foreign Key Constraints for Table LAV_ISTITUTOCERT 
-- 

ALTER TABLE LAV_ISTITUTOCERT ADD
  FOREIGN KEY (COD_CERTIFICATORI) 
 REFERENCES plus_dizionari.DEC_CERTIFICATORI (COD_CERTIFICATORI)
    ON DELETE CASCADE;

ALTER TABLE LAV_ISTITUTOCERT ADD
  FOREIGN KEY (IDE_LAV_ISTITUTO) 
 REFERENCES LAV_ISTITUTO (IDE_LAV_ISTITUTO)
    ON DELETE CASCADE;

-- 
-- Foreign Key Constraints for Table LAV_ESITO_AZINT_COSTO 
-- 

ALTER TABLE LAV_ESITO_AZINT_COSTO ADD
  CONSTRAINT FK_ESAZCO_DESTINAT 
 FOREIGN KEY (COD_DESTINATARIO) 
 REFERENCES plus_dizionari.DEC_DESTINATARIO (COD_DESTINATARIO)
    ON DELETE SET NULL;

ALTER TABLE LAV_ESITO_AZINT_COSTO ADD
  CONSTRAINT FK_ESAZCO_ESAZIN 
 FOREIGN KEY (IDE_ESITO_AZIONE_INTERVENTO) 
 REFERENCES ESITO_AZIONE_INTERVENTO (IDE_ESITO_AZIONE_INTERVENTO)
    ON DELETE CASCADE;

ALTER TABLE LAV_ESITO_AZINT_COSTO ADD
  CONSTRAINT FK_ESAZCO_FONDO 
 FOREIGN KEY (IDE_FONDO) 
 REFERENCES FONDO (IDE_FONDO)
    ON DELETE CASCADE;

ALTER TABLE LAV_ESITO_AZINT_COSTO ADD
  CONSTRAINT FK_ESAZCO_TIPOPAG 
 FOREIGN KEY (COD_APPLICAZIONE, COD_TIPO_PAGAMENTO) 
 REFERENCES plus_dizionari.DEC_TIPO_PAGAMENTO (COD_APPLICAZIONE,COD_TIPO_PAGAMENTO)
    ON DELETE SET NULL;

ALTER TABLE LAV_ESITO_AZINT_COSTO ADD
  CONSTRAINT FK_ESAZCO_VOCCOST 
 FOREIGN KEY (COD_VOCE_COSTO) 
 REFERENCES plus_dizionari.DEC_VOCE_COSTO (COD_VOCE_COSTO)
    ON DELETE SET NULL;

-- 
-- Foreign Key Constraints for Table LAV_RICHIESTA_BONUS_STATO 
-- 

ALTER TABLE LAV_RICHIESTA_BONUS_STATO ADD
  CONSTRAINT FK_RICHBONUS_STATO 
 FOREIGN KEY (IDE_RICHIESTA_BONUS) 
 REFERENCES LAV_RICHIESTA_BONUS (IDE_RICHIESTA_BONUS)
    ON DELETE CASCADE;
	
ALTER TABLE LAV_RICHIESTA_BONUS_STATO ADD
  CONSTRAINT FK_STATO_RICHIBONUS_STATO 
 FOREIGN KEY (COD_STATO_DOCUMENTO) 
 REFERENCES plus_dizionari.DEC_STATO_DOCUMENTO (COD_STATO_DOCUMENTO)
    ON DELETE CASCADE;

-- 
-- Foreign Key Constraints for Table LAV_CANDIDATURE 
-- 

ALTER TABLE LAV_CANDIDATURE ADD
  FOREIGN KEY (COD_SETTORE) 
 REFERENCES plus_classificazione.TAB_ATECOLIV4 (COD_ATECOLIV4);
 
ALTER TABLE LAV_CANDIDATURE ADD
  FOREIGN KEY (COD_MOBILITAGEOG) 
 REFERENCES plus_dizionari.TAB_MOBILITAGEOG (COD_MOBILITAGEOG);
 
ALTER TABLE LAV_CANDIDATURE ADD
  FOREIGN KEY (COD_MODALITALAV) 
 REFERENCES plus_classificazione.TAB_MODALITALAV (COD_MODALITALAV);
 
ALTER TABLE LAV_CANDIDATURE ADD
  FOREIGN KEY (COD_TIPOLOGIACONTR) 
 REFERENCES plus_classificazione.TAB_TIPOLOGIA_CONTR (COD_TIPOLOGIACONTR);
 
ALTER TABLE LAV_CANDIDATURE ADD
  FOREIGN KEY (COD_AREAPROFESS) 
 REFERENCES plus_classificazione.TAB_AREAPROFESS (COD_AREAPROFESS);
 
ALTER TABLE LAV_CANDIDATURE ADD
  FOREIGN KEY (COD_FIGURAPROFESS) 
 REFERENCES plus_classificazione.TAB_FIGURAPROFESS (COD_FIGURAPROFESS);
 
ALTER TABLE LAV_CANDIDATURE ADD
  FOREIGN KEY (IDE_LAVORATORE) 
 REFERENCES LAVORATORE (IDE_LAVORATORE)
    ON DELETE CASCADE;

-- 
-- Foreign Key Constraints for Table LAV_CANDIDATURE_MEZZITRASP 
-- 

ALTER TABLE LAV_CANDIDATURE_MEZZITRASP ADD
  FOREIGN KEY (IDE_LAVORATORE, PRG_CANDIDATURA) 
 REFERENCES LAV_CANDIDATURE (IDE_LAVORATORE,PRG_CANDIDATURA)
    ON DELETE CASCADE;
	
ALTER TABLE LAV_CANDIDATURE_MEZZITRASP ADD
  FOREIGN KEY (COD_MEZZITRASP) 
 REFERENCES plus_dizionari.TAB_MEZZITRASP (COD_MEZZITRASP);


-- 
-- Foreign Key Constraints for Table RAPPORTO_LAVORO 
-- 

ALTER TABLE RAPPORTO_LAVORO ADD
  FOREIGN KEY (COD_CCNL) 
 REFERENCES plus_classificazione.TAB_CCNL (COD_CCNL);
 
ALTER TABLE RAPPORTO_LAVORO ADD
  FOREIGN KEY (COD_FIGURAPROFESS) 
 REFERENCES plus_classificazione.TAB_FIGURAPROFESS (COD_FIGURAPROFESS);
 
ALTER TABLE RAPPORTO_LAVORO ADD
  FOREIGN KEY (IDE_LAVORATORE) 
 REFERENCES LAVORATORE (IDE_LAVORATORE)
    ON DELETE CASCADE;
 
ALTER TABLE RAPPORTO_LAVORO ADD
    FOREIGN KEY (IDE_DATORE_LAVORO, COD_SEDE_LAVORO) 
 REFERENCES DL_SEDI_LAVORO (IDE_DATORE_LAVORO,COD_SEDE_LAVORO);
 
ALTER TABLE RAPPORTO_LAVORO ADD
  FOREIGN KEY (COD_FIGURAPROFESS_CONS) 
 REFERENCES plus_classificazione.TAB_FIGURAPROFESS (COD_FIGURAPROFESS);
 
ALTER TABLE RAPPORTO_LAVORO ADD
  FOREIGN KEY (COD_TIPOLOGIACONTR) 
 REFERENCES plus_classificazione.TAB_RAPPORTILAVORO (COD_TIPOLOGIACONTR);
 
ALTER TABLE RAPPORTO_LAVORO ADD
  FOREIGN KEY (COD_LIVCONTRATTUALE) 
 REFERENCES plus_classificazione.TAB_LIVCONTRATTUALE (COD_LIVCONTRATTUALE);


-- 
-- Foreign Key Constraints for Table RAPPORTO_LAVORO_BATCH 
-- 

ALTER TABLE RAPPORTO_LAVORO_BATCH ADD
  FOREIGN KEY (IDE_RAPPORTO_LAVORO, DTT_INIZIO_VAL_REC) 
 REFERENCES RAPPORTO_LAVORO (IDE_RAPPORTO_LAVORO,DTT_INIZIO_VAL_REC)
    ON DELETE CASCADE;

ALTER TABLE LAV_AZIONI_PAI_ALLEGATI
	ADD CONSTRAINT FK_AZPAI_AZALLEGATI FOREIGN KEY (IDE_AZIONE_PAI) REFERENCES LAV_AZIONI_PAI (IDE_AZIONE_PAI) ON DELETE CASCADE;

ALTER TABLE LAV_AZIONI_PAI_ALLEGATI
	ADD CONSTRAINT FK_ALLEGATI_AZ_ALLEGATI FOREIGN KEY (IDE_ALLEGATO) REFERENCES ALLEGATI (IDE_ALLEGATO) ON DELETE CASCADE;

ALTER TABLE TEMPLATE_AZIONI_ALLEGATI
	ADD CONSTRAINT FK_TMPAZ_TMPAZALL FOREIGN KEY (IDE_TEMPLATE_AZIONE_PAI) REFERENCES TEMPLATE_AZIONI_PAI (IDE_TEMPLATE_AZIONE_PAI) ON DELETE CASCADE;

ALTER TABLE TEMPLATE_AZIONI_ALLEGATI
	ADD CONSTRAINT FK_DECALL_TMPAZALL FOREIGN KEY (COD_APPLICAZIONE, COD_ALLEGATO) REFERENCES PLUS_DIZIONARI.DEC_ALLEGATI (COD_APPLICAZIONE, COD_ALLEGATO);

ALTER TABLE LAV_AZIONI_PAI_PROFILING
	ADD CONSTRAINT FK_AZPAI_AZPROILING FOREIGN KEY (IDE_AZIONE_PAI) REFERENCES LAV_AZIONI_PAI (IDE_AZIONE_PAI) ON DELETE CASCADE;

ALTER TABLE LAV_AZIONI_PAI_PROFILING
	ADD CONSTRAINT FK_PROFILING_AZPROFILING FOREIGN KEY (COD_PROFILING) REFERENCES TAB_PROFILING (COD_PROFILING);

ALTER TABLE REGISTRO
	ADD CONSTRAINT FK_AZPAI_REGISTRO FOREIGN KEY (IDE_AZIONE_PAI) REFERENCES LAV_AZIONI_PAI (IDE_AZIONE_PAI) ON DELETE CASCADE;

ALTER TABLE TEMPLATE_AZIONI_PAI
	ADD CONSTRAINT FK_CALCORE_TEMPAZPAI FOREIGN KEY (COD_CALCOLO_ORE) REFERENCES plus_dizionari.DEC_CALCOLO_ORE (COD_CALCOLO_ORE);  

	
-- 20160919
ALTER TABLE TEMPLATE_AZIONI_PAI_ESITI 
	ADD CONSTRAINT FK_TMPAZESITO_TMPAZ FOREIGN KEY (IDE_TEMPLATE_AZIONE_PAI) REFERENCES TEMPLATE_AZIONI_PAI (IDE_TEMPLATE_AZIONE_PAI) ON DELETE CASCADE;

ALTER TABLE TEMPLATE_AZIONI_PAI_ESITI 
	ADD CONSTRAINT FK_DEC_ESITO_TMPAZESITO FOREIGN KEY (COD_ESITO_AZIONE_PAI) REFERENCES :userdiz.DEC_ESITO_AZIONE_PAI (COD_ESITO_AZIONE_PAI);
	
-- 20170213
ALTER TABLE TEMPLATE_AZIONI_COSTO_ATTR
	ADD CONSTRAINT FK_TMP_AZIONE_TMP_ATTR FOREIGN KEY (IDE_TEMPLATE_AZIONE_PAI) REFERENCES TEMPLATE_AZIONI_PAI_COSTO (IDE_TEMPLATE_AZIONE_PAI) ON DELETE CASCADE;

ALTER TABLE TEMPLATE_AZIONI_COSTO_ATTR
	ADD CONSTRAINT FK_ATTRIBUTO_TMP_ATTRIBUTO FOREIGN KEY (COD_ATTRIBUTO) REFERENCES plus_dizionari.DEC_ATTRIBUTI_COSTO (COD_ATTRIBUTO);

ALTER TABLE TEMPLATE_AZIONI_MATR_CONS
	ADD CONSTRAINT FK_TMP_AZIONE_TMP_MATR_CONS FOREIGN KEY (IDE_TEMPLATE_AZIONE_PAI) REFERENCES TEMPLATE_AZIONI_PAI_COSTO (IDE_TEMPLATE_AZIONE_PAI) ON DELETE CASCADE;

ALTER TABLE TEMPLATE_AZIONI_ATTR_MATRICE
	ADD CONSTRAINT FK_TMP_ATTR_TMP_MATRICE FOREIGN KEY (IDE_TEMPLATE_AZIONE_PAI, COD_ATTRIBUTO) REFERENCES TEMPLATE_AZIONI_COSTO_ATTR (IDE_TEMPLATE_AZIONE_PAI, COD_ATTRIBUTO) ON DELETE CASCADE;

ALTER TABLE TEMPLATE_AZIONI_ATTR_MATRICE
	ADD CONSTRAINT FK_TMP_MATR_CONS_ATTR_MATR FOREIGN KEY (IDE_TEMPLATE_AZIONE_PAI, IDE_MATRICE) REFERENCES TEMPLATE_AZIONI_MATR_CONS (IDE_TEMPLATE_AZIONE_PAI, IDE_MATRICE) ON DELETE CASCADE;
	
ALTER TABLE template_azioni_pai_esplav
  ADD CONSTRAINT tmp_az_pai_tmp_esp_lav FOREIGN KEY (ide_template_azione_pai)
    REFERENCES template_azioni_pai(ide_template_azione_pai)
    ON DELETE CASCADE;
	

ALTER TABLE TEMPLATE_AZIONI_PAI_ESPLAV
	ADD CONSTRAINT TAB_ESPLV_TMP_AZ_PAI FOREIGN KEY (COD_ESPERIENZELAV) REFERENCES plus_classificazione.TAB_ESPERIENZELAV (COD_ESPERIENZELAV);
	
-- 20170223
ALTER TABLE TEMPLATE_PAI_MISURE
	ADD CONSTRAINT FK_MISURE_TMPPAI FOREIGN KEY (COD_MISURA, COD_APPLICAZIONE) REFERENCES plus_dizionari.DEC_MISURE (COD_MISURA, COD_APPLICAZIONE);

ALTER TABLE TEMPLATE_PAI_MISURE
	ADD CONSTRAINT FK_TMPPAI_MISURE FOREIGN KEY (IDE_TEMPLATE_PAI) REFERENCES TEMPLATE_PAI (IDE_TEMPLATE_PAI) ON DELETE CASCADE;

-- 20170323
ALTER TABLE ELENCO
	ADD CONSTRAINT FK_MISURE_ELENCO FOREIGN KEY (COD_MISURA, COD_APPLICAZIONE) REFERENCES plus_dizionari.DEC_MISURE(COD_MISURA, COD_APPLICAZIONE) ON DELETE RESTRICT;
	
-- 20170802
ALTER TABLE DDR
	ADD CONSTRAINT FK_DEC_TIPO_INCENTIVO FOREIGN KEY (COD_TIPO_INCENTIVO) REFERENCES PLUS_DIZIONARI.DEC_TIPO_INCENTIVO (COD_TIPO_INCENTIVO) ON DELETE SET NULL;

ALTER TABLE DDR_PAI
	ADD CONSTRAINT FK_DDR_DDRPAI FOREIGN KEY (IDE_DDR) REFERENCES DDR (IDE_DDR) ON DELETE CASCADE;

ALTER TABLE DDR_PAI
	ADD CONSTRAINT FK_DEC_MISURE_DDRPAI FOREIGN KEY (COD_MISURA, COD_APPLICAZIONE) REFERENCES PLUS_DIZIONARI.DEC_MISURE (COD_MISURA, COD_APPLICAZIONE);

ALTER TABLE DDR_PAI
	ADD CONSTRAINT FK_DDRPAI_ENTE_EROGATORE FOREIGN KEY (COD_ENTE_EROGATORE) REFERENCES PLUS_DIZIONARI.DEC_ENTE_EROGATORE (COD_ENTE_EROGATORE);

ALTER TABLE RICHIESTA_PAG_INFO_PAGAMENTO
	ADD CONSTRAINT FK_RICPAG_RICPAGINFOPAG FOREIGN KEY (IDE_RICHIESTA_PAGAMENTO) REFERENCES RICHIESTA_PAGAMENTO (IDE_RICHIESTA_PAGAMENTO) ON DELETE CASCADE;

ALTER TABLE DDR_RICHIESTE_PAGAMENTO
	ADD CONSTRAINT FK_DDR_DDRRICPAG FOREIGN KEY (IDE_DDR) REFERENCES DDR (IDE_DDR) ON DELETE CASCADE;

ALTER TABLE DDR_RICHIESTE_PAGAMENTO
	ADD CONSTRAINT FK_DDRRICPAG_RICPAG FOREIGN KEY (IDE_RICHIESTA_PAGAMENTO) REFERENCES RICHIESTA_PAGAMENTO (IDE_RICHIESTA_PAGAMENTO);	
 	
-- 20171011
ALTER TABLE TEMPLATE_AZIONI_PAI_ESITI_UCS
	ADD CONSTRAINT FK_TEMPPAI_UCS_ESITI FOREIGN KEY (IDE_TEMPLATE_AZIONE_PAI, COD_ESITO_AZIONE_PAI) REFERENCES TEMPLATE_AZIONI_PAI_ESITI (IDE_TEMPLATE_AZIONE_PAI, COD_ESITO_AZIONE_PAI) ON DELETE CASCADE;

ALTER TABLE TEMPLATE_AZIONI_PAI_ESITI_UCS
	ADD CONSTRAINT FK_TEMPPAI_UCS_PROF FOREIGN KEY (COD_PROFILING) REFERENCES PLUS_CLASSIFICAZIONE.TAB_PROFILING (COD_PROFILING) ON DELETE SET NULL;

	
ALTER TABLE ESTRAZIONE_SIGMA_RICHIESTA_PAG
	ADD CONSTRAINT FK_RICPAG_SIGMA FOREIGN KEY (IDE_RICHIESTA_PAGAMENTO) REFERENCES RICHIESTA_PAGAMENTO (IDE_RICHIESTA_PAGAMENTO) ON DELETE CASCADE;

	
ALTER TABLE ESTRAZIONE_SIGMA_RICHIESTA_PAG
	ADD CONSTRAINT FK_ESTRAZIONE_SIGMA_PAG FOREIGN KEY (IDE_ESTRAZIONE_SIGMA) REFERENCES ESTRAZIONE_SIGMA (IDE_ESTRAZIONE_SIGMA) ON DELETE CASCADE;	

-- 20190516

ALTER TABLE ELENCO_STATO
	ADD CONSTRAINT FK_ELENCO_ELESTATO FOREIGN KEY (IDE_ELENCO) REFERENCES ELENCO (IDE_ELENCO) ON DELETE CASCADE;

ALTER TABLE ELENCO_STATO
	ADD CONSTRAINT FK_DECSTAELE_ELENCO FOREIGN KEY (COD_STATO_ELENCO) REFERENCES plus_dizionari.DEC_STATO_ELENCO (COD_STATO_ELENCO);

 ALTER TABLE ELENCO_DESTINATARIO
    ADD CONSTRAINT FK_DATORE_LAVORO_PAG FOREIGN KEY (IDE_DATORE_LAVORO_PAG) REFERENCES DATORE_LAVORO (IDE_DATORE_LAVORO),
	ADD CONSTRAINT FK_INTERMEDIARIO_PAG FOREIGN KEY (COD_INTERMEDIARIO_PAG) REFERENCES plus_classificazione.TAB_INTERMEDIARI (COD_INTERMEDIARIO);	

/* 
-- 20190911

ALTER TABLE MODULO_PAG_INFO_PAGAMENTO ADD
  CONSTRAINT FK_MODPAG_MODPAGINFOPAG 
 FOREIGN KEY (IDE_MODULO_PAGAMENTO) 
 REFERENCES MODULO_PAGAMENTO (IDE_MODULO_PAGAMENTO)
    ON DELETE CASCADE;

*/	