
\echo 'executing script 401_ddl.create.tables.Profiler.sql';

\c :dbName :userprof

CREATE TABLE REGOLA_PROFILO_FUNZIONE
(
  COD_APPLICAZIONE     VARCHAR(20)        NOT NULL,
  COD_CODICESERVIZIO   VARCHAR(40)        NOT NULL,
  COD_CODICESTRUMENTO  VARCHAR(40)        NOT NULL,
  COD_FUNZIONE         VARCHAR(40)        NOT NULL,
  COD_CODICEPROFILO    VARCHAR(30)        NOT NULL,
  IDE_REGOLA           INTEGER            NOT NULL,
  COD_USERAGG          VARCHAR(40)        NOT NULL,
  DTT_TMST             TIMESTAMP(6)       NOT NULL
);




CREATE TABLE TIPO_GRUPPO
(
  DES_TIPO_GRUPPO     VARCHAR(30)         NOT NULL,
  DES_DESCRIZIONE     VARCHAR(255)        NOT NULL,
  DES_TABELLA_TARGET  VARCHAR(30)             NULL,
  COD_USERAGG         VARCHAR(40)         NOT NULL,
  DTT_TMST            TIMESTAMP(6)        NOT NULL
);




CREATE TABLE CONDIZIONE
(
  IDE_REGOLA      INTEGER                 NOT NULL,
  DES_ENTITA      VARCHAR(30)             NOT NULL,
  DES_CONDIZIONE  VARCHAR(4000)               NULL,
  COD_USERAGG     VARCHAR(40)                 NULL,
  DTT_TMST        TIMESTAMP(6)                NULL
);




CREATE TABLE APPLICAZIONE
(
  COD_APPLICAZIONE  VARCHAR(20)           NOT NULL,
  DES_ACRONIMO      VARCHAR(20)           NOT NULL,
  DES_DESCRIZIONE   VARCHAR(255)              NULL,
  DES_TITOLO        VARCHAR(60)               NULL,
  COD_USERAGG       VARCHAR(40)           NOT NULL,
  DTT_TMST          TIMESTAMP(6)          NOT NULL
);





CREATE TABLE APPL_INT
(
  IDE_APPL_INT       INTEGER,
  COD_APPLICAZIONE   VARCHAR(20)          NOT NULL,
  COD_INTERMEDIARIO  VARCHAR(11)          NOT NULL,
  IDE_PRG_SIGMA	     NUMERIC			 	  NULL,
  COD_USERAGG        VARCHAR(50)          NOT NULL,
  DTT_TMSTAGG        TIMESTAMP(6)         NOT NULL
);

COMMENT ON COLUMN APPL_INT.IDE_APPL_INT IS 'Identificativo univoco della tabella';

COMMENT ON COLUMN APPL_INT.COD_APPLICAZIONE IS 'Codice applicazione';

COMMENT ON COLUMN APPL_INT.COD_INTERMEDIARIO IS 'Codice intermediario (ente)';

COMMENT ON COLUMN APPL_INT.IDE_PRG_SIGMA IS 'Identificativo della riga da associare all''intermediario';




CREATE TABLE RUOLO_STRUMENTO
(
  COD_CODICESTRUMENTO  VARCHAR(40)        NOT NULL,
  COD_CODICERUOLO      VARCHAR(30)        NOT NULL,
  DES_NOME             VARCHAR(30)        NOT NULL,
  DES_DESCRIZIONE      VARCHAR(255)       NOT NULL,
  COD_USERAGG          VARCHAR(40)        NOT NULL,
  DTT_TMST             TIMESTAMP(6)           NULL
);






CREATE TABLE TAB_STRUMENTO
(
  COD_CODICESTRUMENTO  VARCHAR(40)        NOT NULL,
  DES_DESCRIZIONE      VARCHAR(255)       NOT NULL,
  DES_NOME             VARCHAR(255)       NOT NULL,
  IMG_LOGO             BYTEA                  NULL,
  DES_NOME_LOGO        VARCHAR(50)            NULL,
  DES_TIPO_LOGO        VARCHAR(50)            NULL,
  DES_URL              VARCHAR(500)           NULL,
  COD_USERAGG          VARCHAR(40)        NOT NULL,
  DTT_TMST             TIMESTAMP(6)           NULL
);




CREATE TABLE TAB_PROFILO
(
  COD_CODICEPROFILO  VARCHAR(30)          NOT NULL,
  DES_DESCRIZIONE    VARCHAR(255)         NOT NULL,
  DES_NOME           VARCHAR(30)          NOT NULL,
  COD_USERAGG        VARCHAR(40)              NULL,
  DTT_TMST           TIMESTAMP(6)             NULL
);




CREATE TABLE FUNZIONE
(
  COD_CODICESTRUMENTO  VARCHAR(40)        NOT NULL,
  COD_FUNZIONE         VARCHAR(40)        NOT NULL,
  DES_NOME             VARCHAR(255)       NOT NULL,
  DES_DESCRIZIONE      VARCHAR(255)       NOT NULL,
  DES_TIPO_GRUPPO      VARCHAR(30)            NULL,  
  COD_USERAGG          VARCHAR(40)        NOT NULL,
  DTT_TMST             TIMESTAMP(6)       NOT NULL
);





CREATE TABLE PROFILO_APPLICAZIONE
(
  COD_APPLICAZIONE   VARCHAR(20)          NOT NULL,
  COD_CODICEPROFILO  VARCHAR(30)          NOT NULL,
  COD_USERAGG        VARCHAR(40)          NOT NULL,
  DTT_TMST           TIMESTAMP(6)         NOT NULL
);




CREATE TABLE PROFILO_APP_RUOLO_STRUMENTO
(
  COD_APPLICAZIONE     VARCHAR(20)        NOT NULL,
  COD_CODICEPROFILO    VARCHAR(30)        NOT NULL,
  COD_CODICESERVIZIO   VARCHAR(40)        NOT NULL,
  COD_CODICESTRUMENTO  VARCHAR(40)        NOT NULL,
  COD_CODICERUOLO      VARCHAR(30)        NOT NULL,
  COD_USERAGG          VARCHAR(40)            NULL,
  DTT_TMST             TIMESTAMP(6)           NULL
);




CREATE TABLE SOGGETTO_PROFILO_APPLICAZIONE
(
  IDE_SOGG_PROF_APP    INTEGER,
  COD_TIPO_ANAGRAFICA  VARCHAR(60)            NULL,
  IDE_SOGGETTO         NUMERIC            NOT NULL,
  COD_CODICEPROFILO    VARCHAR(30)            NULL,
  COD_APPLICAZIONE     VARCHAR(20)            NULL,  
  COD_USERAGG          VARCHAR(40)        NOT NULL,
  DTT_TMST             TIMESTAMP(6)       NOT NULL
);




CREATE TABLE REGOLA_APPLICAZIONE
(
  COD_APPLICAZIONE  VARCHAR(20)           NOT NULL,
  IDE_REGOLA        INTEGER               NOT NULL,
  COD_USERAGG       VARCHAR(40)           NOT NULL,
  DTT_TMST          TIMESTAMP(6)          NOT NULL
);




CREATE TABLE FUNZIONE_RUOLO_STRUMENTO
(
  COD_CODICESTRUMENTO  VARCHAR(40)        NOT NULL,
  COD_CODICERUOLO      VARCHAR(30)        NOT NULL,
  COD_FUNZIONE         VARCHAR(40)        NOT NULL,
  COD_USERAGG          VARCHAR(40)        NOT NULL,
  DTT_TMST             TIMESTAMP(6)       NOT NULL
);




CREATE TABLE REGOLA_APPLICAZIONE_SERVIZIO
(
  COD_APPLICAZIONE    VARCHAR(20)         NOT NULL,
  IDE_REGOLA          INTEGER             NOT NULL,
  COD_CODICESERVIZIO  VARCHAR(40)         NOT NULL,
  COD_USERAGG         VARCHAR(40)         NOT NULL,
  DTT_TMST            TIMESTAMP(6)        NOT NULL
);




CREATE TABLE REGOLA
(
  IDE_REGOLA            INTEGER,
  DES_NOME              VARCHAR(30)       NOT NULL,
  DES_TIPO_GRUPPO       VARCHAR(30)       NOT NULL,
  DES_DESCRIZIONE       VARCHAR(255)          NULL,
  DES_REGOLA            VARCHAR(4000)         NULL,  
  DES_STATEMENT_REGOLA  VARCHAR(4000)         NULL,
  COD_USERAGG           VARCHAR(40)           NULL,
  DTT_TMST              TIMESTAMP(6)          NULL
);




CREATE TABLE TAB_SERVIZIO
(
  COD_CODICESERVIZIO   VARCHAR(40)        NOT NULL,
  DES_DESCRIZIONE      VARCHAR(255)       NOT NULL,
  DES_NOME             VARCHAR(255)       NOT NULL,
  COD_CODICESTRUMENTO  VARCHAR(40)        NOT NULL,
  IMG_LOGO             BYTEA                  NULL,
  DES_NOME_LOGO        VARCHAR(50)            NULL,
  DES_TIPO_LOGO        VARCHAR(50)            NULL,  
  DES_URL              VARCHAR(500)           NULL,
  COD_USERAGG          VARCHAR(40)            NULL,
  DTT_TMST             TIMESTAMP(6)           NULL
);
----------------------

--
-- TAB_CATEGORIA  (Table) 
--
CREATE TABLE TAB_CATEGORIA
(
  IDE_CODICECATEGORIA  INTEGER            NOT NULL,
  DES_NOME             VARCHAR(30)        NOT NULL,
  DES_DESCRIZIONE      VARCHAR(255)       NOT NULL,
  DTT_TMST             TIMESTAMP(6)           NULL
);



--
-- STRUMENTO_CATEGORIA  (Table) 
--
CREATE TABLE STRUMENTO_CATEGORIA
(
  COD_CODICESTRUMENTO  VARCHAR(40)        NOT NULL,
  IDE_CODICECATEGORIA  INTEGER            NOT NULL,
  COD_USERAGG          VARCHAR(40)        NOT NULL,
  DTT_TMST             TIMESTAMP(6)           NULL
);



--
-- PROFILO_RUOLO_STRUMENTO  (Table) 
--
CREATE TABLE PROFILO_RUOLO_STRUMENTO
(
  COD_CODICESTRUMENTO  VARCHAR(40)        NOT NULL,
  COD_CODICEPROFILO    VARCHAR(30)        NOT NULL,
  COD_CODICERUOLO      VARCHAR(30)        NOT NULL,
  COD_CODICESERVIZIO   VARCHAR(40)        NOT NULL,
  COD_USERAGG          VARCHAR(40)        NOT NULL,
  DTT_TMST             TIMESTAMP(6)       NOT NULL
);



--
-- MONITORAGGIO  (Table) 
--
CREATE TABLE MONITORAGGIO
(
  COD_APPLICAZIONE    VARCHAR(20)         NOT NULL,
  COD_CODICESERVIZIO  VARCHAR(40)             NULL,
  COD_FUNZIONE        VARCHAR(40)             NULL,
  COD_USERAGG         VARCHAR(40)         NOT NULL,
  DTT_TMST            TIMESTAMP(6)        NOT NULL
);




