
\echo 'executing script 601_ddl.create.primarykey.Profiler.sql';

\c :dbName :userprof


ALTER TABLE REGOLA_APPLICAZIONE ADD 
  CONSTRAINT PK_REGOLA_APPLICAZIONE
 PRIMARY KEY
 (COD_APPLICAZIONE, IDE_REGOLA) ;



ALTER TABLE REGOLA ADD 
  CONSTRAINT PK_REGOLA
 PRIMARY KEY
 (IDE_REGOLA) ;



ALTER TABLE REGOLA_PROFILO_FUNZIONE ADD 
  CONSTRAINT PK_REGOLA_PROFILO_FUNZIONE
 PRIMARY KEY
 (COD_APPLICAZIONE, COD_CODICESERVIZIO, COD_CODICESTRUMENTO, COD_FUNZIONE, COD_CODICEPROFILO, IDE_REGOLA) ;



ALTER TABLE SOGGETTO_PROFILO_APPLICAZIONE ADD 
  CONSTRAINT PK_SOGG_PROF_APP
 PRIMARY KEY
 (IDE_SOGG_PROF_APP, IDE_SOGGETTO, COD_TIPO_ANAGRAFICA) ;



ALTER TABLE FUNZIONE_RUOLO_STRUMENTO ADD 
  CONSTRAINT PK_FUNZIONE_RUOLO_STRUMENTO
 PRIMARY KEY
 (COD_CODICESTRUMENTO, COD_CODICERUOLO, COD_FUNZIONE) ;



ALTER TABLE FUNZIONE ADD 
  CONSTRAINT PK_FUNZIONE
 PRIMARY KEY
 (COD_CODICESTRUMENTO, COD_FUNZIONE) ;



ALTER TABLE TAB_PROFILO ADD 
  CONSTRAINT PK_TAB_PROFILO
 PRIMARY KEY
 (COD_CODICEPROFILO) ;



ALTER TABLE TAB_SERVIZIO ADD 
  CONSTRAINT PK_TAB_SERVIZIO
 PRIMARY KEY
 (COD_CODICESERVIZIO) ;



ALTER TABLE PROFILO_APPLICAZIONE ADD 
  CONSTRAINT PK_PROFILO_APPLICAZIONE
 PRIMARY KEY
 (COD_APPLICAZIONE, COD_CODICEPROFILO) ;



ALTER TABLE TAB_STRUMENTO ADD 
  CONSTRAINT PK_TAB_STRUMENTO
 PRIMARY KEY
 (COD_CODICESTRUMENTO) ;



ALTER TABLE RUOLO_STRUMENTO ADD 
  CONSTRAINT PK_RUOLO_STRUMENTO
 PRIMARY KEY
 (COD_CODICESTRUMENTO, COD_CODICERUOLO) ;



ALTER TABLE TIPO_GRUPPO ADD 
  CONSTRAINT PK_TIPO_GRUPPO
 PRIMARY KEY
 (DES_TIPO_GRUPPO) ;



ALTER TABLE APPL_INT ADD 
  CONSTRAINT PK_APPL_INT
 PRIMARY KEY
 (IDE_APPL_INT) ;




ALTER TABLE CONDIZIONE ADD 
  CONSTRAINT PK_CONDIZIONE
 PRIMARY KEY
 (IDE_REGOLA, DES_ENTITA) ;



ALTER TABLE REGOLA_APPLICAZIONE_SERVIZIO ADD 
  CONSTRAINT PK_REGOLA_APP_SERVIZIO
 PRIMARY KEY
 (COD_APPLICAZIONE, IDE_REGOLA, COD_CODICESERVIZIO) ;



ALTER TABLE APPLICAZIONE ADD 
  CONSTRAINT PK_APPLICAZIONE
 PRIMARY KEY
 (COD_APPLICAZIONE) ;



ALTER TABLE PROFILO_APP_RUOLO_STRUMENTO ADD 
  CONSTRAINT PK_PROFILO_APP_RUOLO_STRUMENTO
 PRIMARY KEY
 (COD_APPLICAZIONE, COD_CODICEPROFILO, COD_CODICESERVIZIO, COD_CODICESTRUMENTO, COD_CODICERUOLO) ;

----------

ALTER TABLE TAB_CATEGORIA ADD 
  CONSTRAINT PK_TAB_CATEGORIA
 PRIMARY KEY
 (IDE_CODICECATEGORIA);

-- 
-- Non Foreign Key Constraints for Table STRUMENTO_CATEGORIA 
-- 

ALTER TABLE STRUMENTO_CATEGORIA ADD 
  CONSTRAINT PK_STRUMENTO_CATEGORIA
 PRIMARY KEY
 (COD_CODICESTRUMENTO, IDE_CODICECATEGORIA);

-- 
-- Non Foreign Key Constraints for Table PROFILO_RUOLO_STRUMENTO 
-- 

ALTER TABLE PROFILO_RUOLO_STRUMENTO ADD 
  CONSTRAINT PK_PROFILO_RUOLO_STRUMENTO
 PRIMARY KEY
 (COD_CODICESTRUMENTO, COD_CODICEPROFILO, COD_CODICERUOLO, COD_CODICESERVIZIO);

-- 
