
\echo 'executing script 602_ddl.create.primarykey.J.sql';

\c :dbName :userj



ALTER TABLE UTENTE ADD 
  CONSTRAINT PK_UTENTE
 PRIMARY KEY
 (COD_USERID) ;



ALTER TABLE SPC_STRUMENTO_RUOLO ADD 
  CONSTRAINT PK_STRRUOLO
 PRIMARY KEY
 (COD_STRUMENTO, COD_RUOLO_STRUMENTO) ;



ALTER TABLE PERSONA ADD 
  CONSTRAINT PK_PERSONA
 PRIMARY KEY
 (IDE_SOGGETTO) ;



ALTER TABLE SPC_STRUMENTO_RUOLO_FUNZIONE ADD 
  CONSTRAINT PK_STRRUOLOFUNZ
 PRIMARY KEY
 (COD_STRUMENTO, COD_RUOLO_STRUMENTO, COD_FUNZIONE) ;



ALTER TABLE SPC_STRUMENTO ADD 
  CONSTRAINT PK_STRUMENTO
 PRIMARY KEY
 (COD_STRUMENTO) ;



ALTER TABLE SPC_DEC_TIPO_CODIFICA_REGOLA ADD 
  CONSTRAINT PK_TIPOCODREGOLA
 PRIMARY KEY
 (COD_TIPO_CODIFICA_REGOLA) ;



ALTER TABLE SPC_REGOLA ADD
  CONSTRAINT PK_REGOLA
 PRIMARY KEY
 (IDE_REGOLA) ;



ALTER TABLE SPC_AUTORIZZAZIONE_DATI ADD
  CONSTRAINT PK_SPC_AUTORIZZAZIONE_DATI
 PRIMARY KEY
 (COD_STRUMENTO, COD_PROFILO, COD_FUNZIONE, IDE_REGOLA_DATI) ;



ALTER TABLE UTENTE_APPLICAZIONE_PROFILO ADD
  CONSTRAINT PK_UTEAPPPROFILO
 PRIMARY KEY
 (COD_USERID, COD_APPLICAZIONE, COD_PROFILO) ;



ALTER TABLE UTENTE_ONLINE ADD
  CONSTRAINT PK_UTENTE_ONLINE
 PRIMARY KEY
 (COD_USERID) ;



ALTER TABLE SPC_AUTORIZZAZIONE_FUNZIONALE ADD
  CONSTRAINT PK_SPC_AUTORIZZAZIONE_FUNZIONA
 PRIMARY KEY
 (COD_STRUMENTO, COD_PROFILO) ;



ALTER TABLE SOGGETTO ADD
  CONSTRAINT PK_SOGGETTO
 PRIMARY KEY
 (IDE_SOGGETTO) ;




ALTER TABLE UTENTE_APPLICAZIONE ADD
  CONSTRAINT PK_UTEAPP
 PRIMARY KEY
 (COD_USERID, COD_APPLICAZIONE) ;




ALTER TABLE ISCRIZIONE_PERSONA_ALTREINFO ADD
  CONSTRAINT PK_ISCRIZIONE_PERS_ALTREINFO
 PRIMARY KEY
 (IDE_ISCRIZIONE_PERSONA) ;





ALTER TABLE ISCRIZIONE_AZIENDA_STATO ADD
  CONSTRAINT PK_ISCR_AZIENDA_STATO
 PRIMARY KEY
 (IDE_ISCRIZIONE_AZIENDA, COD_STATO, DTT_INI) ;





ALTER TABLE SPC_STRUMENTO_FUNZIONE ADD
  CONSTRAINT PK_STRUMENTOFUNZ
 PRIMARY KEY
 (COD_STRUMENTO, COD_FUNZIONE) ;



ALTER TABLE ISCRIZIONE_PERSONA_ALLEGATI ADD
  CONSTRAINT PK_ISCR_PERS_ALLEGATI
 PRIMARY KEY
 (IDE_ISCRIZIONE_PERSONA, IDE_ALLEGATO) ;



ALTER TABLE ISCRIZIONE_AZIENDA_ALTREINFO ADD
  CONSTRAINT PK_ISCR_AZIENDA_ALTREINFO
 PRIMARY KEY
 (IDE_ISCRIZIONE_AZIENDA) ;



ALTER TABLE SPC_APPLICAZIONE ADD
  CONSTRAINT PK_APPLICAZIONE
 PRIMARY KEY
 (COD_APPLICAZIONE) ;





ALTER TABLE SPC_APPLICAZIONE_PROFILO ADD
  CONSTRAINT PK_APPLICAZIONE_PROFILO
 PRIMARY KEY
 (COD_APPLICAZIONE, COD_PROFILO) ;





ALTER TABLE SPC_APPLICAZIONE_SERVIZIO ADD
  CONSTRAINT PK_APPLICAZIONE_SERVIZIO
 PRIMARY KEY
 (COD_APPLICAZIONE, COD_STRUMENTO, PRG_ISTANZA) ;




ALTER TABLE ENTE ADD
  CONSTRAINT PK_ENTE
 PRIMARY KEY
 (IDE_SOGGETTO) ;



ALTER TABLE SPC_DEC_GRUPPO_REGOLA ADD
  CONSTRAINT PK_GRUPPOREGOLA
 PRIMARY KEY
 (COD_GRUPPO_REGOLA) ;



ALTER TABLE ISCRIZIONE_AZIENDA ADD
  CONSTRAINT PK_ISCRIZIONE_AZIENDA
 PRIMARY KEY
 (IDE_ISCRIZIONE_AZIENDA) ;






ALTER TABLE ISCRIZIONE_PERSONA ADD
  CONSTRAINT PK_ISCRIZIONE_PERS
 PRIMARY KEY
 (IDE_ISCRIZIONE_PERSONA) ;



ALTER TABLE ISCRIZIONE_PERSONA_ENTE ADD
  CONSTRAINT PK_ISCRIZIONE_PERSONA_ENTE
 PRIMARY KEY
 (IDE_ISCRIZIONE_PERSONA, COD_APPLICAZIONE, COD_INTERMEDIARIO) ;



ALTER TABLE ISCRIZIONE_PERSONA_TIPOSERV ADD
  CONSTRAINT PK_ISCRIZIONE_PERSONA_TIPOSERV
 PRIMARY KEY
 (IDE_ISCRIZIONE_PERSONA, COD_TIPOLOGIA_SERVIZIO) ;
 

ALTER TABLE ISCRIZIONE_PERSONA_STATO    ADD
  CONSTRAINT  PK_ISCRPERSTATO 
 PRIMARY KEY 
 (IDE_ISCRIZIONE_PERSONA,COD_STATO_ISCRIZIONE,DTT_INI) ;
 
 --------------------------------
