
\echo 'executing script 603_ddl.create.primarykey.Sill.sql';

\c :dbName :usersill



ALTER TABLE RICHIESTA_PAG_STATO_PROCEDURA
	ADD CONSTRAINT  PK_RICHIESTA_PAG_STATO_PROCEDU PRIMARY KEY (COD_STATO_PROCEDURA,DTT_INI,IDE_RICHIESTA_PAGAMENTO) ;


ALTER TABLE LAV_AZIONI_ESITO_PROPOSTA
	ADD CONSTRAINT  PK_LAV_AZIONI_ESITO_PROPOSTA PRIMARY KEY (PRG_AZIONI_ESITO_PROPOSTA, IDE_PAI, PRG_AZIONE) ;


ALTER TABLE RICHIESTA_PAGAMENTO
	ADD CONSTRAINT  PK_RICHIESTA_PAGAMENTO PRIMARY KEY (IDE_RICHIESTA_PAGAMENTO) ;


ALTER TABLE RICHIESTA_PAGAMENTO_ALLEGATI
	ADD CONSTRAINT  PK_RICHIESTA_PAGAMENTO_ALLEGAT PRIMARY KEY (IDE_ALLEGATO,IDE_RICHIESTA_PAGAMENTO) ;


ALTER TABLE RICHIESTA_PAGAMENTO_PAI
	ADD CONSTRAINT  PK_RICHIESTA_PAGAMENTO_PAI PRIMARY KEY (IDE_PAI,IDE_RICHIESTA_PAGAMENTO) ;


ALTER TABLE RICHIESTA_PAGAMENTO_STATO
	ADD CONSTRAINT  PK_RICHIESTA_PAGAMENTO_STATO PRIMARY KEY (COD_STATO_DOCUMENTO,IDE_RICHIESTA_PAGAMENTO) ;	


ALTER TABLE ELENCO_RICHIESTA_PAGAMENTO
	ADD CONSTRAINT  PK_ELENCO_RICHIESTA_PAGAMENTO PRIMARY KEY (IDE_ELENCO,IDE_RICHIESTA_PAGAMENTO) ;	
	

ALTER TABLE DL_FABB_ESPERIENZA_MANSIONI ADD
  CONSTRAINT PK_DL_FABB_ESPERIENZA_MANSIONI
 PRIMARY KEY
 (PRG_FABB_ESPERIENZA_MANSIONI, IDE_FABB_OCCUPAZIONALI) ;



ALTER TABLE DL_FABB_ESPERIENZA_SETTORE ADD
  CONSTRAINT PK_DL_FABB_ESPERIENZA_SETTORE
 PRIMARY KEY
 (PRG_FABB_ESPERIENZA_SETTORE, IDE_FABB_OCCUPAZIONALI) ;



ALTER TABLE DL_FABB_RESIDENZA ADD
  CONSTRAINT PK_DL_FABB_RESIDENZA
 PRIMARY KEY
 (PRG_FABB_RESIDENZA, IDE_FABB_OCCUPAZIONALI) ;



ALTER TABLE DL_FABB_TITOLO_STUDIO ADD
  CONSTRAINT PK_DL_FABB_TITOLO_STUDIO
 PRIMARY KEY
 (PRG_FABB_TITOLO_STUDIO, IDE_FABB_OCCUPAZIONALI) ;



ALTER TABLE ELENCO ADD
  CONSTRAINT PK_ELENCHI
 PRIMARY KEY
 (IDE_ELENCO) ;



ALTER TABLE ELENCO_DESTINATARIO ADD
  CONSTRAINT PK_ELENCO_DESTINATARIO
 PRIMARY KEY
 (IDE_ELENCO) ;



ALTER TABLE ELENCO_MODULO_PAGAMENTO ADD
  CONSTRAINT PK_ELENCO_MODULO_PAGAMENTO
 PRIMARY KEY
 (IDE_ELENCO, IDE_MODULO_PAGAMENTO) ;




ALTER TABLE LAV_LINGUE_CONOSCIUTE ADD
  PRIMARY KEY
 (COD_LINGUA, IDE_LAVORATORE) ;



ALTER TABLE LAV_LISTE_SPECIALI ADD
  PRIMARY KEY
 (DAT_INIZIO_ISCRIZIONE, IDE_LAVORATORE, COD_LISTESPEC) ;




ALTER TABLE LAV_NUCLEO_FAMILIARE ADD
  PRIMARY KEY
 (IDE_LAVORATORE) ;



ALTER TABLE LAV_OBBLIGO_FORMATIVO ADD
  PRIMARY KEY
 (IDE_LAVORATORE) ;



ALTER TABLE LAVORATORE ADD
  PRIMARY KEY
 (IDE_LAVORATORE) ;



ALTER TABLE LAV_PATENTE ADD
  PRIMARY KEY
 (COD_TIPO_PATENTEGUIDA, IDE_LAVORATORE) ;



ALTER TABLE LAV_PATENTINO ADD
  PRIMARY KEY
 (IDE_LAVORATORE, COD_TIPO_PATENTINO) ;



ALTER TABLE LAV_RECAPITI ADD
  PRIMARY KEY
 (IDE_LAVORATORE, PRG_RECAPITO) ;




ALTER TABLE CONVENZIONE_STATO ADD
  CONSTRAINT PK_CONVENZIONE_STATO
 PRIMARY KEY
 (PRG_CONVENZIONE, COD_STATO_DOCUMENTO) ;



ALTER TABLE CONV_SOGGETTO_PROMOTORE ADD
  CONSTRAINT PK_CONV_SOGGETTO_PROMOTORE
 PRIMARY KEY
 (IDE_SOGGETTO_PROMOTORE) ;



ALTER TABLE DL_DISPONIBILITA_INTERVENTI ADD
  CONSTRAINT PK_DL_DISPONIBILITA_INTERVENTI
 PRIMARY KEY
 (IDE_DISPONIBILITA_INTERVENTI) ;



ALTER TABLE DL_ENTE ADD
  CONSTRAINT PK_DL_ENTE
 PRIMARY KEY
 (IDE_DL_ENTE) ;



ALTER TABLE DL_FABBISOGNI_OCCUPAZIONALI ADD
  CONSTRAINT PK_DL_FABBISOGNI_OCCUPAZIONALI
 PRIMARY KEY
 (IDE_FABB_OCCUPAZIONALI) ;



ALTER TABLE DL_FABB_ANAG ADD
  CONSTRAINT PK_DL_FABB_ANAG
 PRIMARY KEY
 (IDE_FABB_OCCUPAZIONALI) ;



ALTER TABLE DL_FABB_COMPETENZE ADD
  CONSTRAINT PK_DL_FABB_COMPETENZE
 PRIMARY KEY
 (PRG_FABB_COMPETENZE, IDE_FABB_OCCUPAZIONALI) ;



ALTER TABLE DL_FABBISOGNI_OCCUPAZIONALI ADD
  CHECK (DES_DIFF_REPERIMENTO IN ('ALTO', 'BASSO', 'MEDIO'));



ALTER TABLE DL_FABBISOGNI_OCCUPAZIONALI ADD
  CHECK (DES_LIV_CRITICITA IN ('ALTO', 'BASSO', 'MEDIO'));



ALTER TABLE DL_FABBISOGNI_OCCUPAZIONALI ADD
  CHECK (FLG_TIPO_FABB_DISP IN ('DISP', 'FABB'));



ALTER TABLE DL_FABBISOGNI_OCCUPAZIONALI ADD
  CHECK (DES_DIFF_REPERIMENTO IN ('ALTO', 'BASSO', 'MEDIO'));



ALTER TABLE DL_FABBISOGNI_OCCUPAZIONALI ADD
  CHECK (DES_LIV_CRITICITA IN ('ALTO', 'BASSO', 'MEDIO'));



ALTER TABLE DL_FABBISOGNI_OCCUPAZIONALI ADD
  CHECK (FLG_TIPO_FABB_DISP IN ('DISP', 'FABB'));



ALTER TABLE LAV_AZIONI_PAI_CONSUNTIVO ADD
  CONSTRAINT PK_LAV_AZIONI_PAI_CONSUNTIVO
 PRIMARY KEY
 (IDE_AZIONE_PAI) ;



ALTER TABLE LAV_DATI_PAGAMENTO ADD
  CONSTRAINT PK_LAV_DATI_PAGAMENTO
 PRIMARY KEY
 (IDE_LAVORATORE, DTT_INIZIO_VAL_REC) ;



ALTER TABLE LAV_DETRAZIONI ADD
  CONSTRAINT PK_LAV_DETRAZIONI
 PRIMARY KEY
 (IDE_LAVORATORE, DAT_INIZIO_DETRAZIONE) ;



ALTER TABLE LAV_DETRAZIONI_DETTAGLIO ADD
  CONSTRAINT PK_LAV_DETRAZIONI_DETTAGLIO
 PRIMARY KEY
 (IDE_DETRAZIONI_DETTAGLIO) ;



ALTER TABLE LAV_DETRAZIONI_STATO ADD
  CONSTRAINT PK_LAV_DETRAZIONI_STATO
 PRIMARY KEY
 (IDE_LAVORATORE, DAT_INIZIO_DETRAZIONE, COD_STATO_DOCUMENTO) ;



ALTER TABLE LAV_ENTE ADD
  CONSTRAINT PK_LAV_ENTE
 PRIMARY KEY
 (IDE_LAV_ENTE) ;





ALTER TABLE LAV_DID ADD
  PRIMARY KEY
 (DAT_INIZIO_DID, IDE_LAVORATORE) ;




ALTER TABLE LAV_ELEMENTI ADD
  PRIMARY KEY
 (COD_ELEMENTO, IDE_LAVORATORE) ;



ALTER TABLE DATORE_LAVORO ADD
  PRIMARY KEY
 (IDE_DATORE_LAVORO) ;



ALTER TABLE DL_SEDE_LEGALE ADD
  PRIMARY KEY
 (IDE_DATORE_LAVORO) ;



ALTER TABLE DL_SEDI_LAVORO ADD
  PRIMARY KEY
 (IDE_DATORE_LAVORO, COD_SEDE_LAVORO) ;



ALTER TABLE INTERVENTO ADD
  PRIMARY KEY
 (IDE_INTERVENTO) ;



ALTER TABLE LAV_ALBO ADD
  PRIMARY KEY
 (COD_ALBO, DAT_ISCRIZIONE, IDE_LAVORATORE) ;



ALTER TABLE LAV_ANALISI_PROFILI ADD
  PRIMARY KEY
 (IDE_LAVORATORE, COD_PROFILO) ;



ALTER TABLE LAV_ANZIANITA_DISOCCUPAZIONE ADD
  PRIMARY KEY
 (DAT_INIZIO_DID, IDE_LAVORATORE) ;



ALTER TABLE LAV_BILANCIO ADD
  PRIMARY KEY
 (IDE_LAVORATORE, COD_PROFILO, DTT_TMST) ;




ALTER TABLE ALLEGATI ADD
  CONSTRAINT PK_ALLEGATI
 PRIMARY KEY
 (IDE_ALLEGATO) ;



ALTER TABLE APPL_INT_TIPOSERV ADD
  CONSTRAINT PK_APPL_INT_TIPOSERV
 PRIMARY KEY
 (IDE_APPL_INT, COD_TIPOLOGIA_SERVIZIO) ;



ALTER TABLE CONVENZIONE_ALLEGATI ADD
  CONSTRAINT PK_CONVENZIONE_ALLEGATI
 PRIMARY KEY
 (PRG_CONVENZIONE, IDE_ALLEGATO) ;



ALTER TABLE DL_FABB_CONOSCENZE_AREE ADD
  CONSTRAINT PK_DL_FABB_CONOSCENZE_AREE
 PRIMARY KEY
 (IDE_FABB_OCCUPAZIONALI, PRG_FABB_CONOSCENZE_AREE) ;



ALTER TABLE LAV_ESPERIENZE_FORMAZIONE ADD
  PRIMARY KEY
 (PRG_ESPERIENZA_FORMAZIONE, IDE_LAVORATORE) ;



ALTER TABLE LAV_ESPERIENZE_PROFESSIONALI ADD
  PRIMARY KEY
 (PRG_ESPERIENZA_PROF, IDE_LAVORATORE) ;



ALTER TABLE LAV_ESPERIENZE_STUDIO ADD
  PRIMARY KEY
 (IDE_LAVORATORE, PRG_ESPERIENZA_STUDIO) ;



ALTER TABLE DL_FABB_DISP_MODALITALAV ADD
  CONSTRAINT PK_DL_FABB_DISP_MODALITALAV
 PRIMARY KEY
 (IDE_FABB_OCCUPAZIONALI, PRG_FABB_DISP_MODALITALAV) ;



ALTER TABLE DL_FABB_DISP_TIPOCONTRATTO ADD
  CONSTRAINT PK_DL_FABB_DISP_TIPOCONTRATTO
 PRIMARY KEY
 (PRG_FABB_DISP_TIPOCONTRATTO, IDE_FABB_OCCUPAZIONALI) ;



ALTER TABLE DL_FABB_DOMICILIO ADD
  CONSTRAINT PK_DL_FABB_DOMICILIO
 PRIMARY KEY
 (PRG_FABB_DOMICILIO, IDE_FABB_OCCUPAZIONALI) ;



ALTER TABLE LAV_STATUS_DICH ADD
  CONSTRAINT PK_LAV_STATUS_DICH
 PRIMARY KEY
 (IDE_LAVORATORE) ;



ALTER TABLE LAV_STRANIERO ADD
  CONSTRAINT PK_LAV_STRANIERO_LAV
 PRIMARY KEY
 (IDE_LAVORATORE) ;



ALTER TABLE LAV_TIPOSERV ADD
  CONSTRAINT PK_LAV_TIPOSERV
 PRIMARY KEY
 (IDE_LAVORATORE, COD_TIPOLOGIA_SERVIZIO) ;




ALTER TABLE MODULO_INTATT_ALLEGATI ADD
  CONSTRAINT PK_MODULO_INTATT_ALLEGATI
 PRIMARY KEY
 (IDE_MODULO_INTERVENTO_ATTORE, IDE_ALLEGATO) ;



ALTER TABLE MODULO_INTATT_DETT_RATA ADD
  CONSTRAINT PK_MODULO_INTATT_DETT_RATA
 PRIMARY KEY
 (IDE_MODULO_INTERVENTO_ATTORE, DAT_INI_RIFERIMENTO) ;



ALTER TABLE LAV_CATEGORIA181 ADD
  PRIMARY KEY
 (IDE_LAVORATORE) ;



ALTER TABLE LAV_CATEGORIE_PARTICOLARI ADD
  PRIMARY KEY
 (IDE_LAVORATORE) ;



ALTER TABLE LAV_COMPETENZE ADD
  PRIMARY KEY
 (COD_COMPETENZA, IDE_LAVORATORE) ;



ALTER TABLE LAV_CONOSCENZE_INFORMATICHE ADD
  PRIMARY KEY
 (COD_CONOSCENZA, IDE_LAVORATORE) ;



ALTER TABLE LAV_CONVOCAZIONI ADD
  PRIMARY KEY
 (PRG_CONVOCAZIONE, IDE_LAVORATORE) ;



ALTER TABLE ESITO_AZIONE_INTERVENTO ADD
  CONSTRAINT PK_ESITO_AZIONE_INTERVENTO
 PRIMARY KEY
 (IDE_ESITO_AZIONE_INTERVENTO) ;



ALTER TABLE FONDO ADD
  CONSTRAINT PK_FONDO
 PRIMARY KEY
 (IDE_FONDO) ;



ALTER TABLE INTERVENTO_ASSICURAZIONE ADD
  CONSTRAINT PK_INTERVENTO_ASSICURAZIONE
 PRIMARY KEY
 (IDE_INTERVENTO, PRG_ASSICURAZIONE) ;



ALTER TABLE INTERVENTO_ATTORE ADD
  CONSTRAINT PK_INTERVENTO_ATTORE
 PRIMARY KEY
 (PRG_INTERVENTO_ATTORE) ;



ALTER TABLE INTERVENTO_ATTRIBUTO ADD
  CONSTRAINT PK_INTERVENTO_ATTRIBUTO
 PRIMARY KEY
 (IDE_INTERVENTO_ATTRIBUTO, IDE_INTERVENTO) ;



ALTER TABLE INTERVENTO_CONVENZIONE ADD
  CONSTRAINT PK_INTERVENTO_CONVENZIONE
 PRIMARY KEY
 (IDE_INTERVENTO, PRG_CONVENZIONE) ;



ALTER TABLE INTERVENTO_DATI_TIROCINIO ADD
  CONSTRAINT PK_INTERVENTO_DATI_TIROCINIO
 PRIMARY KEY
 (IDE_INTERVENTO) ;



ALTER TABLE INTERVENTO_OBIETTIVI ADD
  CONSTRAINT PK_INTERVENTO_OBIETTIVI
 PRIMARY KEY
 (PRG_INTERVENTO_OBIETTIVO, IDE_INTERVENTO) ;



ALTER TABLE LAV_REDDITO_DICHIARATO ADD
  PRIMARY KEY
 (IDE_LAVORATORE) ;



ALTER TABLE LAV_STATUS ADD
  PRIMARY KEY
 (DTT_INIZIO, IDE_LAVORATORE, COD_STATUSOCCUPAZ) ;



ALTER TABLE LAV_STATUS_STORICO ADD
  PRIMARY KEY
 (DTT_STORICO, IDE_LAVORATORE, DTT_INIZIO, COD_STATUSOCCUPAZ) ;




ALTER TABLE REGOLA_AMBITO_RICERCA ADD
  PRIMARY KEY
 (IDE_REGOLA) ;



ALTER TABLE STRINT_MACROSTRUMENTO_STRUM ADD
  CONSTRAINT PK_STRINT_MACROSTRUMENTO_STRUM
 PRIMARY KEY
 (COD_MACROSTRUMENTO, COD_CODICESTRUMENTO) ;



ALTER TABLE STRINT_PAGAMENTO ADD
  CONSTRAINT PK_STRINT_PAGAMENTO
 PRIMARY KEY
 (IDE_TIPO_INTERVENTO, COD_TIPO_INCENTIVO) ;



ALTER TABLE STRINT_TIPO ADD
  CONSTRAINT PK_STRINT_TIPO
 PRIMARY KEY
 (IDE_TIPO_INTERVENTO) ;



ALTER TABLE STRINT_TIPO_MACROSTRUMENTO ADD
  CONSTRAINT PK_STRINT_TIPO_MACROSTRUMENTO
 PRIMARY KEY
 (IDE_TIPO_INTERVENTO, COD_MACROSTRUMENTO) ;



ALTER TABLE STRINT_TIPO_TIPOSERV ADD
  CONSTRAINT PK_STRINT_TIPO_TIPOSERV
 PRIMARY KEY
 (IDE_TIPO_INTERVENTO, COD_TIPOLOGIA_SERVIZIO) ;



ALTER TABLE TEMPLATE_AZIONI_PAI ADD
  CONSTRAINT PK_TEMPLATE_AZIONI_PAI
 PRIMARY KEY
 (IDE_TEMPLATE_AZIONE_PAI) ;



ALTER TABLE TEMPLATE_AZIONI_PAI_COSTO ADD
  CONSTRAINT PK_TEMPLATE_AZIONI_PAI_COSTO
 PRIMARY KEY
 (IDE_TEMPLATE_AZIONE_PAI) ;



ALTER TABLE TEMPLATE_PAI ADD
  CONSTRAINT PK_TEMPLATE_PAI
 PRIMARY KEY
 (IDE_TEMPLATE_PAI) ;



ALTER TABLE TEMPLATE_PAI_STATO ADD
  CONSTRAINT PK_TEMPLATE_PAI_STATO
 PRIMARY KEY
 (IDE_TEMPLATE_PAI, COD_STATO_DOCUMENTO) ;



ALTER TABLE CONVENZIONE ADD
  PRIMARY KEY
 (PRG_CONVENZIONE) ;



ALTER TABLE LAV_PAI ADD
  CONSTRAINT PK_LAV_PAI
 PRIMARY KEY
 (IDE_PAI) ;



ALTER TABLE LAV_PAI_STATO ADD
  CONSTRAINT PK_LAV_PAI_STATO
 PRIMARY KEY
 (IDE_PAI, COD_STATO_DOCUMENTO) ;



ALTER TABLE LAV_PATTO_SERVIZIO ADD
  CONSTRAINT PK_LAV_PATTO_SERVIZIO
 PRIMARY KEY
 (IDE_PATTO_SERVIZIO) ;



ALTER TABLE LAV_PATTO_SERVIZIO_CHIUSURA ADD
  CONSTRAINT PK_LAV_PATTO_SERVIZIO_CHIUSURA
 PRIMARY KEY
 (IDE_PATTO_SERVIZIO) ;



ALTER TABLE LAV_PATTO_SERVIZIO_STATO ADD
  CONSTRAINT PK_LAV_PATTO_SERVIZIO_STATO
 PRIMARY KEY
 (IDE_PATTO_SERVIZIO, COD_STATO_DOCUMENTO) ;




ALTER TABLE MODULO_INTERVENTO_ATTORE ADD
  CONSTRAINT PK_MODULO_INTERVENTO_ATTORE
 PRIMARY KEY
 (IDE_MODULO_INTERVENTO_ATTORE) ;



ALTER TABLE MODULO_PAGAMENTO ADD
  CONSTRAINT PK_MODULO_PAGAMENTO
 PRIMARY KEY
 (IDE_MODULO_PAGAMENTO) ;



ALTER TABLE MODULO_PAGAMENTO_STATO ADD
  CONSTRAINT PK_MODULO_PAGAMENTO_STATO
 PRIMARY KEY
 (IDE_MODULO_PAGAMENTO, COD_STATO_DOCUMENTO) ;



ALTER TABLE MODULO_PAG_STATO_PROCEDURA ADD
  CONSTRAINT PK_MODULO_PAG_STATO_PROCEDURA
 PRIMARY KEY
 (IDE_MODULO_PAGAMENTO, COD_STATO_PROCEDURA, DTT_INI) ;



ALTER TABLE STRINT_ATTORE ADD
  CONSTRAINT PK_STRINT_ATTORE
 PRIMARY KEY
 (IDE_TIPO_INTERVENTO, COD_CODICEPROFILO) ;



ALTER TABLE DL_FABB_CONOSC_INFORMATICHE ADD
  CONSTRAINT PK_DL_FABB_CONOSC_INFORMATICHE
 PRIMARY KEY
 (PRG_FABB_CONOSCENZE_INFORMATIC, IDE_FABB_OCCUPAZIONALI) ;



ALTER TABLE DL_FABB_CONOSC_LINGUE ADD
  CONSTRAINT PK_DL_FABB_CONOSC_LINGUE
 PRIMARY KEY
 (PRG_FABB_CONOSCENZE_LINGUE, IDE_FABB_OCCUPAZIONALI) ;



ALTER TABLE DL_FABB_DISP_MOBILITAGEOG ADD
  CONSTRAINT PK_DL_FABB_DISP_MOBILITAGEOG
 PRIMARY KEY
 (IDE_FABB_OCCUPAZIONALI, PRG_FABB_DISP_MOBILITAGEOG) ;



ALTER TABLE INTERVENTO_PAI ADD
  CONSTRAINT PK_INTERVENTO_PAI
 PRIMARY KEY
 (IDE_INTERVENTO) ;



ALTER TABLE INTERVENTO_PROROGA_SOSPENSIONE ADD
  CONSTRAINT PK_INTERVENTO_PROROGA_SOSP
 PRIMARY KEY
 (PRG_PROG_SOSP) ;



ALTER TABLE INTERVENTO_TIROCINIO_COND ADD
  CONSTRAINT PK_INTERVENTO_TIROCINIO_COND
 PRIMARY KEY
 (IDE_INTERVENTO, COD_CONDIZIONE_TIROCINIO) ;



ALTER TABLE INTERVENTO_SEDE ADD
  CONSTRAINT PK_INT_SEDE
 PRIMARY KEY
 (IDE_INTERVENTO, PRG_SEDE) ;



ALTER TABLE LAV_AZIENDA_UTILIZZATRICE ADD
  CONSTRAINT PK_LAV_AZIENDA_UTILIZZATRICE
 PRIMARY KEY
 (IDE_AZIENDA_UTILIZZATRICE) ;



ALTER TABLE LAV_AZIONI_PAI ADD
  CONSTRAINT PK_LAV_AZIONI_PAI
 PRIMARY KEY
 (IDE_AZIONE_PAI) ;

 -----------------------------------------------
 
-- 
-- Non Foreign Key Constraints for Table LAV_REDDITI 
-- 

ALTER TABLE LAV_REDDITI ADD
  PRIMARY KEY
 (IDE_LAVORATORE, COD_TIPO_REDDITO, ANN_RIF) ;


-- Non Foreign Key Constraints for Table LAV_SUSSIDIO 
-- 

ALTER TABLE LAV_SUSSIDIO ADD
  PRIMARY KEY
 (IDE_LAV_SUSSIDIO) ;

-- 
-- Non Foreign Key Constraints for Table LAV_ISTITUTO 
-- 

ALTER TABLE LAV_ISTITUTO ADD
  PRIMARY KEY
 (IDE_LAV_ISTITUTO) ;

-- 
-- Non Foreign Key Constraints for Table LAV_SUSSIDIO_STATO_PAG 
-- 

ALTER TABLE LAV_SUSSIDIO_STATO_PAG ADD
  CONSTRAINT PK_LAV_SUSSIDIO_STATO_PAG
 PRIMARY KEY
 (IDE_LAV_SUSSIDIO, COD_STATO_PROCEDURA, DTT_INI) ;

-- 
-- Non Foreign Key Constraints for Table LAV_ISTITUTO_EVENTI 
-- 

ALTER TABLE LAV_ISTITUTO_EVENTI ADD
  PRIMARY KEY
 (IDE_LAV_ISTITUTO_EVENTI) ;

-- 
-- Non Foreign Key Constraints for Table LOG_WSC 
-- 

ALTER TABLE LOG_WSC ADD
  CONSTRAINT PK_LOG_WSC
 PRIMARY KEY
 (COD_APPLICAZIONE, COD_WSC, DTT_TMST) ;

-- 
-- Non Foreign Key Constraints for Table LAV_ESPERIENZA_INTERMEDIATA 
-- 

ALTER TABLE LAV_ESPERIENZA_INTERMEDIATA ADD
  CONSTRAINT PK_LAV_ESPERIENZA_INTERMEDIATA
 PRIMARY KEY
 (IDE_ESPERIENZA_INTERM) ;

-- 
-- Non Foreign Key Constraints for Table LAV_RICHIESTA_BONUS 
-- 

ALTER TABLE LAV_RICHIESTA_BONUS ADD
  CONSTRAINT PK_LAV_RICHIESTA_BONUS
 PRIMARY KEY
 (IDE_RICHIESTA_BONUS) ;

-- 
-- Non Foreign Key Constraints for Table LAV_ISTITUTOCERT 
-- 

ALTER TABLE LAV_ISTITUTOCERT ADD
  PRIMARY KEY
 (IDE_LAV_ISTITUTOCERT) ;

-- 
-- Non Foreign Key Constraints for Table LAV_ESITO_AZINT_COSTO 
-- 

ALTER TABLE LAV_ESITO_AZINT_COSTO ADD
  CONSTRAINT PK_LAV_ESITO_AZINT_COSTO
 PRIMARY KEY
 (IDE_ESITO_AZIONE_INTERVENTO, PRG_COSTO) ;

 
	
-- 
-- Non Foreign Key Constraints for Table LAV_RICHIESTA_BONUS_STATO 
-- 

ALTER TABLE LAV_RICHIESTA_BONUS_STATO ADD
  CONSTRAINT PK_LAV_RICHIESTA_BONUS_STATO
 PRIMARY KEY
 (IDE_RICHIESTA_BONUS, COD_STATO_DOCUMENTO) ;

-- 
-- Non Foreign Key Constraints for Table ORIGINE_COMUNICAZIONE 
-- 

ALTER TABLE ORIGINE_COMUNICAZIONE ADD
  PRIMARY KEY
 (COD_ORIGINE_CO) ;

-- 
-- Non Foreign Key Constraints for Table LAV_CANDIDATURE 
-- 

ALTER TABLE LAV_CANDIDATURE ADD
  PRIMARY KEY
 (IDE_LAVORATORE, PRG_CANDIDATURA) ;

-- 
-- Non Foreign Key Constraints for Table LAV_CANDIDATURE_MEZZITRASP 
-- 

ALTER TABLE LAV_CANDIDATURE_MEZZITRASP ADD
  PRIMARY KEY
 (IDE_LAVORATORE, PRG_CANDIDATURA, COD_MEZZITRASP) ;



-- Non Foreign Key Constraints for Table RAPPORTO_LAVORO 
-- 

ALTER TABLE RAPPORTO_LAVORO ADD
  PRIMARY KEY
 (IDE_RAPPORTO_LAVORO, DTT_INIZIO_VAL_REC) ;


-- Non Foreign Key Constraints for Table RAPPORTO_LAVORO_BATCH 
-- 

ALTER TABLE RAPPORTO_LAVORO_BATCH ADD
  PRIMARY KEY
 (IDE_BATCH, DTT_INIZIO_VAL_REC, IDE_RAPPORTO_LAVORO) ;

ALTER TABLE LAV_AZIONI_PAI_ALLEGATI
	ADD CONSTRAINT  PK_LAV_AZIONI_PAI_ALLEGATI PRIMARY KEY (IDE_AZIONE_PAI,IDE_ALLEGATO) ;
	
ALTER TABLE TEMPLATE_AZIONI_ALLEGATI
	ADD CONSTRAINT  PK_TEMPLATE_AZIONI_ALLEGATI PRIMARY KEY (IDE_TEMPLATE_AZIONE_PAI,COD_APPLICAZIONE,COD_ALLEGATO) ;

ALTER TABLE LAV_AZIONI_PAI_PROFILING
	ADD CONSTRAINT  PK_LAV_AZIONI_PAI_PROFILING PRIMARY KEY (IDE_AZIONE_PAI) ;

ALTER TABLE REGISTRO
	ADD CONSTRAINT  PK_REGISTRO PRIMARY KEY (IDE_REGISTRO);

	
-- 20160302
alter table utente_info
add constraint pk_utente_info primary key (ide_utente_nsec);	

-- 20160919

ALTER TABLE TEMPLATE_AZIONI_PAI_ESITI 
ADD CONSTRAINT  PK_TEMPLATE_AZIONI_PAI_ESITI 
PRIMARY KEY (IDE_TEMPLATE_AZIONE_PAI,COD_ESITO_AZIONE_PAI);

-- 20170213
ALTER TABLE TEMPLATE_AZIONI_COSTO_ATTR
	ADD CONSTRAINT  PK_TEMPLATE_AZIONI_COSTO_ATTR PRIMARY KEY (IDE_TEMPLATE_AZIONE_PAI,COD_ATTRIBUTO);
ALTER TABLE TEMPLATE_AZIONI_MATR_CONS
	ADD CONSTRAINT  PK_TEMPLATE_AZIONI_MATR_CONS PRIMARY KEY (IDE_TEMPLATE_AZIONE_PAI,IDE_MATRICE);
ALTER TABLE TEMPLATE_AZIONI_ATTR_MATRICE
	ADD CONSTRAINT  PK_TEMPLATE_AZIONI_ATTR_MATRIC PRIMARY KEY (IDE_TEMPLATE_AZIONE_PAI,COD_ATTRIBUTO,IDE_MATRICE);
ALTER TABLE TEMPLATE_AZIONI_PAI_ESPLAV
	ADD CONSTRAINT  PK_TEMPLATE_AZIONI_PAI_ESPLAV PRIMARY KEY (IDE_TEMPLATE_AZIONE_PAI,COD_ESPERIENZELAV);
	
-- 20170223
ALTER TABLE TEMPLATE_PAI_MISURE
	ADD CONSTRAINT  PK_TEMPLATE_PAI_MISURE PRIMARY KEY (COD_MISURA,COD_APPLICAZIONE,IDE_TEMPLATE_PAI);

-- 20170802
 ALTER TABLE DDR
	ADD CONSTRAINT  PK_DDR PRIMARY KEY (IDE_DDR);

ALTER TABLE DDR_PAI
	ADD CONSTRAINT  PK_DDR_PAI PRIMARY KEY (IDE_DDR);

ALTER TABLE RICHIESTA_PAG_INFO_PAGAMENTO
	ADD CONSTRAINT  PK_RICHIESTA_PAG_INFO_PAGAMENT PRIMARY KEY (IDE_RICHIESTA_PAGAMENTO);

ALTER TABLE DDR_RICHIESTE_PAGAMENTO
	ADD CONSTRAINT  PK_DDR_RICHIESTE_PAGAMENTO PRIMARY KEY (IDE_DDR,IDE_RICHIESTA_PAGAMENTO);	
	
-- 20171011

ALTER TABLE TEMPLATE_AZIONI_PAI_ESITI_UCS
	ADD CONSTRAINT  PK_TEMPLATE_AZIONI_PAI_ESITI_U PRIMARY KEY (IDE_TEMPLATE_AZIONE_PAI,COD_UCS, COD_ESITO_AZIONE_PAI);
  	
ALTER TABLE ESTRAZIONE_SIGMA
	ADD CONSTRAINT  PK_ESTRAZIONE_SIGMA PRIMARY KEY (IDE_ESTRAZIONE_SIGMA);
	
ALTER TABLE ESTRAZIONE_SIGMA_RICHIESTA_PAG
	ADD CONSTRAINT  PK_ESTRAZIONE_SIGMA_RICPAG PRIMARY KEY (IDE_RICHIESTA_PAGAMENTO,IDE_ESTRAZIONE_SIGMA);	
	
-- 20190516

ALTER TABLE ELENCO_STATO
	ADD CONSTRAINT PK_ELENCO_STATO PRIMARY KEY (IDE_ELENCO,COD_STATO_ELENCO,DTT_INI);
	
/*
-- 20190911

ALTER TABLE MODULO_PAG_INFO_PAGAMENTO ADD
  CONSTRAINT PK_MODULO_PAG_INFO_PAGAMENTO
 PRIMARY KEY
 (IDE_MODULO_PAGAMENTO) ;

*/	