
\echo 'executing script 30_Tabelle_Cla.sql';
\c :dbName plus_classificazione;




CREATE TABLE TAB_ALBI
(
  COD_ALBO    VARCHAR(10) NOT NULL,
  DES_ALBO    VARCHAR(200) NOT NULL,
  DAT_INIZIO  DATE NOT NULL,
  DAT_FINE    DATE,
  DTT_TMST    TIMESTAMP(6) NOT NULL
);



CREATE TABLE TAB_ALBO_SEDI
(
  IDE_ALBO_SEDI          NUMERIC NOT NULL,
  COD_ALBO_INTERMEDIARI  VARCHAR(16),
  COD_TIPOLSEDE          VARCHAR(10),
  COD_COMUNE             VARCHAR(10),
  DAT_INIZIO             DATE NOT NULL,
  DAT_FINE               DATE,
  DES_INDIRIZZO          VARCHAR(250),
  COD_CAP                VARCHAR(5),
  DES_TELEFONO           VARCHAR(40),
  DES_FAX                VARCHAR(40),
  DES_EMAIL              VARCHAR(100),
  COD_NAZIONE_ESTERA     VARCHAR(10),
  COD_INTERMEDIARIO      VARCHAR(11),
  COD_FILIALE            VARCHAR(4),
  FLG_CANCELLAZIONE      CHAR(1)   NOT NULL DEFAULT 'N',
  COD_USERAGG            VARCHAR(40) NOT NULL,
  DTT_TMST               TIMESTAMP(6) NOT NULL
);

CREATE TABLE TAB_ALBO_INTERMEDIARI
(
  COD_ALBO_INTERMEDIARI  VARCHAR(16) NOT NULL,
  DES_ALBO_INTERMEDIARI  VARCHAR(200) NOT NULL,
  COD_INTERMEDIARIO      VARCHAR(11),  
  COD_INAIL              VARCHAR(11),
  COD_MATRICOLA_INPS     VARCHAR(16),
  COD_PARTITA_IVA        VARCHAR(11),
  COD_CCNL_PREVALENTE    VARCHAR(10),
  NUM_ISCRIZIONE_ALBO    VARCHAR(100),
  COD_SETTORE            VARCHAR(10),
  FLG_CANCELLAZIONE      CHAR(1)  NOT NULL DEFAULT 'N',
  DAT_INIZIO             DATE NOT NULL,
  DAT_FINE               DATE,
  COD_USERAGG            VARCHAR(40) NOT NULL,
  DTT_TMST               TIMESTAMP(6) NOT NULL
);

COMMENT ON COLUMN TAB_ALBO_INTERMEDIARI.COD_SETTORE IS 'ex COD_ATECOLIV4';



CREATE TABLE TAB_ATECOLIV0
(
  COD_ATECOLIV0  VARCHAR(10) NOT NULL,
  DES_ATECOLIV0  VARCHAR(400) NOT NULL,
  DAT_INIZIO     DATE NOT NULL,
  DAT_FINE       DATE,
  DTT_TMST       TIMESTAMP(6) NOT NULL
);

CREATE TABLE TAB_ATECOLIV1
(
  COD_ATECOLIV1  VARCHAR(10) NOT NULL,
  COD_ATECOLIV0  VARCHAR(10) NOT NULL,
  DES_ATECOLIV1  VARCHAR(400),
  DAT_INIZIO     DATE NOT NULL,
  DAT_FINE       DATE,
  DTT_TMST       TIMESTAMP(6) NOT NULL
);
CREATE TABLE TAB_ATECOLIV2
(
  COD_ATECOLIV2  VARCHAR(10) NOT NULL,
  COD_ATECOLIV1  VARCHAR(10) NOT NULL,
  DES_ATECOLIV2  VARCHAR(400) NOT NULL,
  DAT_INIZIO     DATE NOT NULL,
  DAT_FINE       DATE,
  DTT_TMST       TIMESTAMP(6) NOT NULL
);

CREATE TABLE TAB_ATECOLIV3
(
  COD_ATECOLIV3  VARCHAR(10) NOT NULL,
  COD_ATECOLIV2  VARCHAR(10) NOT NULL,
  DES_ATECOLIV3  VARCHAR(400),
  DAT_INIZIO     DATE NOT NULL,
  DAT_FINE       DATE,
  DTT_TMST       TIMESTAMP(6) NOT NULL
);


CREATE TABLE TAB_ATECOLIV4
(
  COD_ATECOLIV4  VARCHAR(10) NOT NULL,
  COD_ATECOLIV3  VARCHAR(10) NOT NULL,
  DES_ATECOLIV4  VARCHAR(400) NOT NULL,
  DAT_INIZIO     DATE NOT NULL,
  DAT_FINE       DATE,
  DTT_TMST       TIMESTAMP(6) NOT NULL
);

CREATE TABLE TABELLA_ATECO
(
  SEZIONE       VARCHAR(1) NOT NULL,
  SOTTOSEZIONE  VARCHAR(1),
  DIVISIONE     VARCHAR(2),
  GRUPPO        VARCHAR(1),
  CLASSE        VARCHAR(1),
  CATEGORIA     VARCHAR(1),
  DESCRIZIONE   VARCHAR(250),
  DETTAGLIO     VARCHAR(870),
  COD_ATECO     VARCHAR(20) NOT NULL,
  DAT_INIZIO    DATE NOT NULL,
  DAT_FINE      DATE,
  DTT_TMST      TIMESTAMP(6) NOT NULL
);




CREATE TABLE TAB_ESPERIENZELAV
(
  COD_ESPERIENZELAV  VARCHAR(10) NOT NULL,
  DES_ESPERIENZELAV  VARCHAR(200) NOT NULL,
  DAT_INIZIO         DATE NOT NULL,
  DAT_FINE           DATE,
  DTT_TMST           TIMESTAMP(6) NOT NULL
);


CREATE TABLE TAB_INFORMATICAGRADOCONOSC
(
  COD_GRADOCONOSC  VARCHAR(10) NOT NULL,
  DES_GRADOCONOSC  VARCHAR(200) NOT NULL,
  DAT_INIZIO       DATE NOT NULL,
  DAT_FINE         DATE,
  DTT_TMST         TIMESTAMP(6) NOT NULL
);




CREATE TABLE TAB_INFORMATICACONOSC
(
  COD_CONOSCENZA  VARCHAR(10) NOT NULL,
  DES_CONOSCENZA  VARCHAR(200) NOT NULL,
  DAT_INIZIO      DATE NOT NULL,
  DAT_FINE        DATE,
  DTT_TMST        TIMESTAMP(6) NOT NULL
);




CREATE TABLE TAB_FIGURAPROFESS
(
  COD_FIGURAPROFESS  VARCHAR(12) NOT NULL,
  COD_AREAPROFESS    VARCHAR(10) NOT NULL,
  DES_FIGURAPROFESS  VARCHAR(350) NOT NULL,
  TXT_TESTO          VARCHAR(100),
  TXT_TESTOBREVE     VARCHAR(50),
  DAT_INIZIO         DATE NOT NULL,
  DAT_FINE           DATE,
  DTT_TMST           TIMESTAMP(6) NOT NULL
);




CREATE TABLE TAB_TIPO_INTERMEDIARIO
(
  COD_TIPO_INTERMEDIARIO  VARCHAR(20) NOT NULL,
  DES_TIPO_INTERMEDIARIO  VARCHAR(200) NOT NULL,
  FLG_PUBBLICO            VARCHAR(1) NOT NULL,
  DAT_INIZIO              DATE NOT NULL,
  DAT_FINE                DATE,
  DTT_TMST                TIMESTAMP(6) NOT NULL
);

CREATE TABLE TAB_INTERMEDIARI
(
  COD_INTERMEDIARIO             VARCHAR(11)   NOT NULL,
  COD_TIPO_INTERMEDIARIO        VARCHAR(20)   NOT NULL,
  DES_INTERMEDIARIO             VARCHAR(200)  NOT NULL,
  COD_FISCALE                   VARCHAR(16)   NULL,
  DES_INDIRIZZO_RECAPITO        VARCHAR(250)  NULL,
  COD_CAP_RECAPITO              VARCHAR(5)    NULL,
  COD_COMUNE_RECAPITO           VARCHAR(10)   NULL,
  DES_EMAIL                     VARCHAR(50)   NULL,  
  COD_PADRE						VARCHAR(11)   NULL,
  COD_RAGGRUPPAMENTO            VARCHAR(11)   NULL,
  FLG_CLASSIFICAZIONE_STANDARD  CHAR(1)   	  NOT NULL,
  DAT_INIZIO                    DATE 	  	  NOT NULL,
  DAT_FINE                      DATE          NULL ,
  COD_UNI_IPA        	        VARCHAR(10)   NULL ,
  FLG_PUBBLICO         			CHAR(1) 	  NULL ,
  COD_FORMAGIURIDICA   			VARCHAR(10)   NULL ,
  COD_ENTE_EROGATORE   			VARCHAR(10)   NULL ,
  COD_ATECO 				    VARCHAR(10)   NULL,
  COD_IMPRESA_PROD 				VARCHAR(10)   NULL ,
  IMP_MASSIMALE 			    NUMERIC(9,2)  NULL  ,
  COD_CUP  					    VARCHAR(3)    NULL ,   
  TXT_NOTE     		  			VARCHAR(2500) NULL ,
  DTT_TMST                      TIMESTAMP(6)  NOT NULL
);

COMMENT ON COLUMN TAB_INTERMEDIARI.FLG_CLASSIFICAZIONE_STANDARD IS '''S'' classificazione standard, ''N'' dati inseriti da Italia lavoro';

COMMENT ON COLUMN TAB_INTERMEDIARI.DES_INDIRIZZO_RECAPITO IS 'Indirizzo di recapito dell''intermediario';

COMMENT ON COLUMN TAB_INTERMEDIARI.COD_CAP_RECAPITO IS 'CAP di recapito dell''intermediario';

COMMENT ON COLUMN TAB_INTERMEDIARI.COD_COMUNE_RECAPITO IS 'Comune di recapito dell''intermediario';

CREATE TABLE TAB_INTERMEDIARI_FILIALI
(
  COD_INTERMEDIARIO  VARCHAR(11) NOT NULL,
  COD_FILIALE        VARCHAR(4) NOT NULL,
  DES_FILIALE        VARCHAR(200) NOT NULL,
  COD_COMUNE         VARCHAR(10) NOT NULL,
  DES_INDIRIZZO      VARCHAR(250),
  COD_CAP            VARCHAR(5),
  DES_EMAIL          VARCHAR(100),
  DAT_INIZIO         DATE NOT NULL,
  DAT_FINE           DATE,
  DTT_TMST           TIMESTAMP(6) NOT NULL
);

COMMENT ON COLUMN TAB_INTERMEDIARI_FILIALI.COD_FILIALE IS 'Codice Filiale';

COMMENT ON COLUMN TAB_INTERMEDIARI_FILIALI.DES_FILIALE IS 'Descrizione filiale';

COMMENT ON COLUMN TAB_INTERMEDIARI_FILIALI.DES_INDIRIZZO IS 'Indirizzo filiale';




CREATE TABLE TAB_COMUNE_INTERMEDIARI
(
  COD_INTERMEDIARIO  VARCHAR(11) NOT NULL,
  COD_COMUNE         VARCHAR(10) NOT NULL,
  DAT_INIZIO         DATE NOT NULL,
  DAT_FINE           DATE,
  DTT_TMST           TIMESTAMP(6) NOT NULL
);

CREATE TABLE TAB_CATEGORIE181
(
  COD_CATEGORIA181  VARCHAR(10) NOT NULL,
  DES_CATEGORIA181  VARCHAR(200) NOT NULL,
  DAT_INIZIO        DATE NOT NULL,
  DAT_FINE          DATE,
  DTT_TMST          TIMESTAMP(6) NOT NULL
);


CREATE TABLE TAB_TIPOATTESTAZ
(
  COD_TIPOATTESTAZ  VARCHAR(10) NOT NULL,
  DES_TIPOATTESTAZ  VARCHAR(200) NOT NULL,
  DAT_INIZIO        DATE NOT NULL,
  DAT_FINE          DATE,
  DTT_TMST          TIMESTAMP(6) NOT NULL
);




CREATE TABLE TAB_CATEGORIE_PROTETTE
(
  COD_CATEGORIA  VARCHAR(10) NOT NULL,
  DES_CATEGORIA  VARCHAR(200) NOT NULL,
  DAT_INIZIO     DATE NOT NULL,
  DAT_FINE       DATE,
  DTT_TMST       TIMESTAMP(6) NOT NULL
);




CREATE TABLE TAB_CCNL
(
  COD_CCNL     VARCHAR(10) NOT NULL,
  DES_CCNL     VARCHAR(250) NOT NULL,
  DES_SETTORE  VARCHAR(250) NOT NULL,
  TXT_CCNL     VARCHAR(2500) NOT NULL,
  DAT_INIZIO   DATE NOT NULL,
  DAT_FINE     DATE,
  DTT_TMST     TIMESTAMP(6) NOT NULL  
);


CREATE TABLE TAB_CONDIZIONE_STATUS
(
  COD_CONDIZIONE_STATUS  VARCHAR(10) NOT NULL,
  DES_CONDIZIONE_STATUS  VARCHAR(200) NOT NULL,
  DAT_INIZIO             DATE NOT NULL,
  DAT_FINE               DATE,
  DTT_TMST               TIMESTAMP(6) NOT NULL
);




CREATE TABLE TAB_STUDIOTITOLO
(
  COD_TITOLOSTUDIO      VARCHAR(11) NOT NULL,
  DES_TITOLOSTUDIO      VARCHAR(300) NOT NULL,
  COD_LIVELLOSTUDIO     VARCHAR(10) NOT NULL,
  TIPO_LIVELLO          VARCHAR(10) NOT NULL,
  COD_TITOLOSTUDIOLIV2  VARCHAR(10) NOT NULL,
  DES_TITOLOSTUDIOLIV2  VARCHAR(300) NOT NULL,
  COD_TITOLOSTUDIOLIV3  VARCHAR(10),
  DES_TITOLOSTUDIOLIV3  VARCHAR(300),
  COD_TITOLOSTUDIOLIV4  VARCHAR(11),
  DES_TITOLOSTUDIOLIV4  VARCHAR(300),
  COD_TITOLOSTUDIO_SIGMA VARCHAR(2) NOT NULL,  
  DAT_INIZIO            DATE NOT NULL,
  DAT_FINE              DATE,
  DTT_TMST              TIMESTAMP(6) NOT NULL
);




CREATE TABLE TAB_STATUS_STRANIERO
(
  COD_STATUS_STRANIERO  VARCHAR(10) NOT NULL,
  DES_STATUS_STRANIERO  VARCHAR(250) NOT NULL,
  DAT_INIZIO            DATE NOT NULL,
  DAT_FINE              DATE,
  DTT_TMST              TIMESTAMP(6) NOT NULL
);




CREATE TABLE TAB_LINGUE
(
  COD_LINGUA  VARCHAR(10) NOT NULL,
  DES_LINGUA  VARCHAR(200) NOT NULL,
  DAT_INIZIO  DATE NOT NULL,
  DAT_FINE    DATE,
  DTT_TMST    TIMESTAMP(6) NOT NULL
);




CREATE TABLE TAB_TIPOLOGIA_CONTR
(
  COD_TIPOLOGIACONTR  VARCHAR(10) NOT NULL,
  DES_TIPOLOGIACONTR  VARCHAR(250) NOT NULL,
  DAT_INIZIO          DATE NOT NULL,
  DAT_FINE            DATE,
  DTT_TMST            TIMESTAMP(6) NOT NULL
);




CREATE TABLE TAB_TIPOAZIENDA
(
  COD_TIPOAZIENDA  VARCHAR(10) NOT NULL,
  DES_TIPOAZIENDA  VARCHAR(200) NOT NULL,
  DAT_INIZIO       DATE NOT NULL,
  DAT_FINE         DATE,
  DTT_TMST         TIMESTAMP(6) NOT NULL
);




CREATE TABLE TAB_TIPOPATENTINI
(
  COD_TIPO_PATENTINO  VARCHAR(10) NOT NULL,
  DES_TIPO_PATENTINO  VARCHAR(250) NOT NULL,
  DAT_INIZIO          DATE NOT NULL,
  DAT_FINE            DATE,
  DTT_TMST            TIMESTAMP(6) NOT NULL
);




CREATE TABLE TAB_TIPOPATENTIGUIDA
(
  COD_TIPO_PATENTEGUIDA  VARCHAR(10) NOT NULL,
  DES_TIPO_PATENTEGUIDA  VARCHAR(200) NOT NULL,
  DAT_INIZIO             DATE NOT NULL,
  DAT_FINE               DATE,
  DTT_TMST               TIMESTAMP(6) NOT NULL
);




CREATE TABLE TAB_STUDIOLIVELLO
(
  COD_LIVELLOSTUDIO  VARCHAR(10) NOT NULL,
  DES_LIVELLOSTUDIO  VARCHAR(200) NOT NULL,
  COD_STUDIO         VARCHAR(10) NOT NULL,
  DAT_INIZIO         DATE NOT NULL,
  DAT_FINE           DATE,
  DTT_TMST           TIMESTAMP(6) NOT NULL
);




CREATE TABLE TAB_QUALPROFLIV0
(
  COD_QUALPROFLIV0  VARCHAR(10) NOT NULL,
  DES_QUALPROFLIV0  VARCHAR(300),
  DAT_INIZIO        DATE NOT NULL,
  DAT_FINE          DATE,
  DTT_TMST          TIMESTAMP(6) NOT NULL  
);

CREATE TABLE TAB_QUALPROFLIV1
(
  COD_QUALPROFLIV1  VARCHAR(10) NOT NULL,
  COD_QUALPROFLIV0  VARCHAR(10),
  DES_QUALPROFLIV1  VARCHAR(300),
  DAT_INIZIO        DATE NOT NULL,
  DAT_FINE          DATE,
  DTT_TMST          TIMESTAMP(6) NOT NULL  
);


CREATE TABLE TAB_QUALPROFLIV2
(
  COD_QUALPROFLIV2  VARCHAR(10) NOT NULL,
  DES_QUALPROFLIV2  VARCHAR(300),
  COD_QUALPROFLIV1  VARCHAR(10),
  DAT_INIZIO        DATE NOT NULL,
  DAT_FINE          DATE,
  DTT_TMST          TIMESTAMP(6) NOT NULL
);

CREATE TABLE TAB_QUALPROFLIV3
(
  COD_QUALPROFLIV3  VARCHAR(10) NOT NULL,
  COD_QUALPROFLIV2  VARCHAR(10),
  DES_QUALPROFLIV3  VARCHAR(350),
  DAT_INIZIO        DATE NOT NULL,  
  DAT_FINE          DATE,  
  DTT_TMST          TIMESTAMP(6) NOT NULL
);

CREATE TABLE TAB_QUALPROFLIV4
(
  COD_QUALPROFLIV4  VARCHAR(12) NOT NULL,
  COD_QUALPROFLIV3  VARCHAR(10),
  DES_QUALPROFLIV4  VARCHAR(400),
  COD_MANSIONE      VARCHAR(10),
  DAT_INIZIO        DATE NOT NULL,  
  DAT_FINE          DATE ,  
  DTT_TMST          TIMESTAMP(6) NOT NULL
);

CREATE TABLE TABELLA_QUALPROF
(
  COD_QUALPROF  VARCHAR(16) NOT NULL,
  DES_QUALPROF  VARCHAR(350),
  DAT_INIZIO    DATE NOT NULL,
  DAT_FINE      DATE,
  DTT_TMST      TIMESTAMP(6) NOT NULL
);




CREATE TABLE TAB_STATUSOCCUPAZ
(
  COD_STATUSOCCUPAZ  VARCHAR(10) NOT NULL,
  DES_STATUSOCCUPAZ  VARCHAR(200) NOT NULL,
  DAT_INIZIO         DATE NOT NULL,
  DAT_FINE           DATE,
  DTT_TMST           TIMESTAMP(6) NOT NULL
);




CREATE TABLE TAB_SESSO
(
  COD_SESSO  VARCHAR(1) NOT NULL,
  DES_SESSO  VARCHAR(200) NOT NULL,
  DTT_TMST   TIMESTAMP(6) NOT NULL
);




CREATE TABLE TAB_COMUNI
(
  COD_COMUNE     VARCHAR(10) NOT NULL,
  COD_PROVINCIA  VARCHAR(10) NOT NULL,
  DES_COMUNE     VARCHAR(200) NOT NULL,
  COD_ISTAT      VARCHAR(10),
  COD_INPS       VARCHAR(10),
  COD_CAP        VARCHAR(10),
  COD_PREFISSO   VARCHAR(10),
  COD_COMUNE_SIGMA VARCHAR(9) ,
  DAT_INIZIO     DATE NOT NULL,
  DAT_FINE       DATE,
  DTT_TMST       TIMESTAMP(6) NOT NULL
);

CREATE TABLE TAB_PROVINCE
(
  COD_PROVINCIA  VARCHAR(10) NOT NULL,
  DES_PROVINCIA  VARCHAR(200) NOT NULL,
  COD_REGIONE    VARCHAR(10) NOT NULL,
  COD_ML_REG     VARCHAR(10) NOT NULL,
  DAT_INIZIO     DATE NOT NULL,
  DAT_FINE       DATE,
  DES_TARGA      VARCHAR(2),
  DTT_TMST       TIMESTAMP(6) NOT NULL
);

COMMENT ON COLUMN TAB_PROVINCE.COD_ML_REG IS 'Codice Ministero del Lavoro (20081117)';

CREATE TABLE TAB_REGIONI
(
  COD_REGIONE          VARCHAR(10) NOT NULL,
  DES_REGIONE          VARCHAR(200) NOT NULL,
  COD_RIPTERRITORIALE  VARCHAR(10) NOT NULL,
  COD_MOBILITAGEOG     VARCHAR(10),
  COD_ILUP             VARCHAR(10),
  COD_ML               VARCHAR(10),
  DAT_INIZIO           DATE NOT NULL,
  DAT_FINE             DATE,
  DTT_TMST             TIMESTAMP(6) NOT NULL
);

COMMENT ON COLUMN TAB_REGIONI.COD_ILUP IS 'Codice Italia Lavoro Ufficio Pagamenti (20081117)';

COMMENT ON COLUMN TAB_REGIONI.COD_ML IS 'Codice Ministero del Lavoro (20081117)';

CREATE TABLE TAB_NAZIONI
(
  COD_NAZIONE  VARCHAR(10) NOT NULL,
  DES_NAZIONE  VARCHAR(200) NOT NULL,
  FLG_UE       VARCHAR(1),
  DAT_INIZIO   DATE NOT NULL,
  DAT_FINE     DATE,
  DTT_TMST     TIMESTAMP(6) NOT NULL
);

CREATE TABLE TAB_CITTADINANZE
(
  COD_CITTADINANZA  VARCHAR(10) NOT NULL,
  COD_MF            VARCHAR(4),
  DES_CITTADINANZA  VARCHAR(200) NOT NULL,
  DES_NAZIONALITA   VARCHAR(250),
  FLG_UE            VARCHAR(1),
  DAT_INIZIO        DATE NOT NULL,
  DAT_FINE          DATE,
  DTT_TMST          TIMESTAMP(6) NOT NULL
);




CREATE TABLE TAB_RAPPORTILAVORO
(
  COD_TIPOLOGIACONTR  VARCHAR(10) NOT NULL,
  DES_TIPOLOGIACONTR  VARCHAR(200) NOT NULL,
  DAT_INIZIO          DATE NOT NULL,
  DAT_FINE            DATE,
  DTT_TMST            TIMESTAMP(6) NOT NULL
);




CREATE TABLE TAB_LISTESPECIALI
(
  COD_LISTESPEC  VARCHAR(10) NOT NULL,
  DES_LISTESPEC  VARCHAR(200) NOT NULL,
  DAT_INIZIO     DATE NOT NULL,
  DAT_FINE       DATE,
  DTT_TMST       TIMESTAMP(6) NOT NULL
);



CREATE TABLE TAB_MOTIVO_PERMESSO
(
  COD_MOTIVO  VARCHAR(10) NOT NULL,
  DES_MOTIVO  VARCHAR(200) NOT NULL,
  DAT_INIZIO  DATE NOT NULL,
  DAT_FINE    DATE,
  DTT_TMST    TIMESTAMP(6) NOT NULL
);

CREATE TABLE TAB_MODALITALAV
(
  COD_MODALITALAV   VARCHAR(10) NOT NULL,
  DES_MODALITA_LAV  VARCHAR(200) NOT NULL,
  DAT_INIZIO        DATE NOT NULL,
  DAT_FINE          DATE,
  DTT_TMST          TIMESTAMP(6) NOT NULL
);



CREATE TABLE TAB_LIVCONTRATTUALE
(
  COD_LIVCONTRATTUALE  VARCHAR(10) NOT NULL,
  DES_LIVCONTRATTUALE  VARCHAR(200) NOT NULL,
  DAT_INIZIO           DATE NOT NULL,
  DAT_FINE             DATE,
  DTT_TMST             TIMESTAMP(6) NOT NULL
);



CREATE TABLE TAB_LINGUECONOSCENZA
(
  COD_CONOSCENZA  VARCHAR(10) NOT NULL,
  DES_CONOSCENZA  VARCHAR(200) NOT NULL,
  DAT_INIZIO      DATE NOT NULL,
  DAT_FINE        DATE,
  DTT_TMST        TIMESTAMP(6) NOT NULL
);


CREATE TABLE TAB_AREAPROFESS
(
  COD_AREAPROFESS  VARCHAR(10) NOT NULL,
  DES_AREAPROFESS  VARCHAR(250) NOT NULL,
  DAT_INIZIO       DATE NOT NULL,
  DAT_FINE         DATE,
  DTT_TMST         TIMESTAMP(6) NOT NULL
);


CREATE TABLE TAB_AMPIEZZA
(
  COD_AMPIEZZA  VARCHAR(10) NOT NULL,
  DES_AMPIEZZA  VARCHAR(200) NOT NULL,
  DAT_INIZIO    DATE NOT NULL,
  DAT_FINE      DATE,
  DTT_TMST      TIMESTAMP(6) NOT NULL
);


CREATE TABLE TAB_PROFILING
(
	COD_PROFILING        NUMERIC(1) NOT NULL ,
	DES_PROFILING        VARCHAR(50) NOT NULL ,
	DAT_INIZIO           DATE NOT NULL ,
	DAT_FINE             DATE NULL ,
	DTT_TMST             TIMESTAMP(6) NOT NULL 
);

COMMENT ON TABLE TAB_PROFILING IS 'La tabella contiene gli indici di profiling validi per la Garanzia Giovani';



ALTER TABLE TAB_ALBI OWNER TO plus_classificazione;
ALTER TABLE TAB_ALBO_INTERMEDIARI OWNER TO plus_classificazione;
ALTER TABLE TAB_ALBO_SEDI OWNER TO plus_classificazione;
ALTER TABLE TAB_AMPIEZZA OWNER TO plus_classificazione;
ALTER TABLE TAB_AREAPROFESS OWNER TO plus_classificazione;
ALTER TABLE TAB_ATECOLIV0 OWNER TO plus_classificazione;
ALTER TABLE TAB_ATECOLIV1 OWNER TO plus_classificazione;
ALTER TABLE TAB_ATECOLIV2 OWNER TO plus_classificazione;
ALTER TABLE TAB_ATECOLIV3 OWNER TO plus_classificazione;
ALTER TABLE TAB_ATECOLIV4 OWNER TO plus_classificazione;
ALTER TABLE TAB_CATEGORIE_PROTETTE OWNER TO plus_classificazione;
ALTER TABLE TAB_CATEGORIE181 OWNER TO plus_classificazione;
ALTER TABLE TAB_CCNL OWNER TO plus_classificazione;
ALTER TABLE TAB_CITTADINANZE OWNER TO plus_classificazione;
ALTER TABLE TAB_COMUNE_INTERMEDIARI OWNER TO plus_classificazione;
ALTER TABLE TAB_COMUNI OWNER TO plus_classificazione;
ALTER TABLE TAB_CONDIZIONE_STATUS OWNER TO plus_classificazione;
ALTER TABLE TAB_ESPERIENZELAV OWNER TO plus_classificazione;
ALTER TABLE TAB_FIGURAPROFESS OWNER TO plus_classificazione;
ALTER TABLE TAB_INFORMATICACONOSC OWNER TO plus_classificazione;
ALTER TABLE TAB_INFORMATICAGRADOCONOSC OWNER TO plus_classificazione;
ALTER TABLE TAB_INTERMEDIARI OWNER TO plus_classificazione;
ALTER TABLE TAB_INTERMEDIARI_FILIALI OWNER TO plus_classificazione;
ALTER TABLE TAB_LINGUE OWNER TO plus_classificazione;
ALTER TABLE TAB_LINGUECONOSCENZA OWNER TO plus_classificazione;
ALTER TABLE TAB_LISTESPECIALI OWNER TO plus_classificazione;
ALTER TABLE TAB_LIVCONTRATTUALE OWNER TO plus_classificazione;
ALTER TABLE TAB_MODALITALAV OWNER TO plus_classificazione;
ALTER TABLE TAB_MOTIVO_PERMESSO OWNER TO plus_classificazione;
ALTER TABLE TAB_NAZIONI OWNER TO plus_classificazione;
ALTER TABLE TAB_PROVINCE OWNER TO plus_classificazione;
ALTER TABLE TAB_PROFILING OWNER TO plus_classificazione;
ALTER TABLE TAB_QUALPROFLIV0 OWNER TO plus_classificazione;
ALTER TABLE TAB_QUALPROFLIV1 OWNER TO plus_classificazione;
ALTER TABLE TAB_QUALPROFLIV2 OWNER TO plus_classificazione;
ALTER TABLE TAB_QUALPROFLIV3 OWNER TO plus_classificazione;
ALTER TABLE TAB_QUALPROFLIV4 OWNER TO plus_classificazione;
ALTER TABLE TAB_RAPPORTILAVORO OWNER TO plus_classificazione;
ALTER TABLE TAB_REGIONI OWNER TO plus_classificazione;
ALTER TABLE TAB_SESSO OWNER TO plus_classificazione;
ALTER TABLE TAB_STATUS_STRANIERO OWNER TO plus_classificazione;
ALTER TABLE TAB_STATUSOCCUPAZ OWNER TO plus_classificazione;
ALTER TABLE TAB_STUDIOLIVELLO OWNER TO plus_classificazione;
ALTER TABLE TAB_STUDIOTITOLO OWNER TO plus_classificazione;
ALTER TABLE TAB_TIPO_INTERMEDIARIO OWNER TO plus_classificazione;
ALTER TABLE TAB_TIPOATTESTAZ OWNER TO plus_classificazione;
ALTER TABLE TAB_TIPOAZIENDA OWNER TO plus_classificazione;
ALTER TABLE TAB_TIPOLOGIA_CONTR OWNER TO plus_classificazione;
ALTER TABLE TAB_TIPOPATENTIGUIDA OWNER TO plus_classificazione;
ALTER TABLE TAB_TIPOPATENTINI OWNER TO plus_classificazione;
ALTER TABLE TABELLA_ATECO OWNER TO plus_classificazione;
ALTER TABLE TABELLA_QUALPROF OWNER TO plus_classificazione;